### ISSUE TITLE
MAVEN HOUSE : Redefining virtual experiences by providing a platform for artists and creators to create, manage, and host live-stream events.

### ISSUE THREAD

**Issue by MavenFoundation** [livepeer/Grant-Program#100]
**Give a 3 sentence description for your proposal.**
[Maven Foundation](https://maven.foundation/) is building Web 3.0 protocols, tools, and applications for the Creator Economy.

We are building MAVEN HOUSE to make it as simple as possible for creators to host live or physical events, as well as ticketed experiences, for their die-hard fans globally.

It removes obstacles for the audience while giving artists total control over their performance and profit.  The platform is capable to handle online traffic for an event of any size, from anywhere in the world.

**Describe the problem you are solving.** 

> Current Video Streaming Platforms are owned by Centralised Organisations like YouTube, Facebook(Meta), Twitch, etc. and the creators themselves have no ownership of their content.

> Creators need a platform where they can live stream their content, and earn revenue from their die-hard fans by selling physical or virtual event tickets in form of NFTs, merchandise, and a lot more. 
 
**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

> Livepeer will serve as Maven House's skeleton because it may not be able to stream live events without it.

**Describe why you are the right team with the capability to build this.**

Sachin Rana (Founder & Product Design) 
LinkedIn: https://www.linkedin.com/in/sachin-rana/
Twitter : https://twitter.com/iamsachinrana

Kalika Prasad Mishra ( Product Lead)
LinkedIn: https://www.linkedin.com/in/kalika-prasad-mishra-036b27103/

Rajiv Ranjan: (Senior Developer)
Twitter : https://twitter.com/okranjan
Github : https://github.com/iamrajivranjan

Aviral Gupta: (Full Stack Developer) 
LinkedIn: https://www.linkedin.com/in/aviral10x//
Github: https://github.com/aviral10x
Twitter: https://twitter.com/aviral10x

Yashwant Choudhary: (Project Manager)
LinkedIn: https://www.linkedin.com/in/yashwanteth/
Twitter : https://twitter.com/Yashwant_eth

Mizan Mohammed: (Project Analyst)
LinkedIn: https://www.linkedin.com/in/mizanmohammed/
Twitter: https://twitter.com/Mizan_eth

Bibek Jha: (Junior Developer)
LinkedIn: https://www.linkedin.com/in/bibek-jha-3396b4218/
Twitter: https://twitter.com/zhabibek4u

**Describe the scope of the project including a 3-month timeline and milestones.** 

The project is split into three milestones and tied to a successful outcome that would benefit the Livepeer ecosystem.

**Milestone 1 - $15k USDC ( Nov 20th - Dec 31st, 2022)**

- Ideate, design, prototype, test, and refine the user interface/web flow.
- Coding the Website design of MAVEN HOUSE.
- Integrate Magic.link for Onboarding new users with email or social login or existing crypto-natives with self-custody wallets.
- Integrate to Livepeer network for live streaming.
- Integrate Livepeer Token Gated Stream.
- Release of Maven House alpha to public test-net, and allow all users to test MAVEN HOUSE without any gas.

**Milestone 2 - $10k USDC ( 1st Jan - 20th Jan 2023)**

- Cyberconnect to verify alpha users and create their universal Social Graph profile.
- Deploying all major Cyberconnect Features on MAVEN HOUSE
- Profile - Display your user's decentralized identities.
- Messaging - Enable users to stay connected with content creators.
- Notification - Keep followers updated.
- Search - Explore new content creators.

**Milestone 3 - $10k USDC (21st Jan - 20th Feb 2023)**

- Minting of MAVEN tokens on Ethereum network.
- Release main-net P2P Streaming platform with all in-built features like NFTS, overlays, face-mask, and audio.
- Official Launch of MAVEN HOUSE with Web application.
- Partnering with verified content creators worldwide.

**Please estimate hours spent on project based on the above and how much funding you will need.** 

1. Magic Link for Onboarding user: 20 -30 Hours Total.
2. Livepeer network for live streaming: 50-80 Hours Total.
3. Livepeer Token Gated Stream: 20-30 Hours Total.
4. Cyberconnect as a social graph: 40-50 Hours Total.
6. Smart contract : 10 hours total
7. React-native Web application + UX/UI designs: 400-500 hours total

Amount of USDC Grant we are looking
MAVEN is looking to obtain a grant amount of  35K USDC separated into 3 phases with an initial deposit of  15K USDC to kick start the project.

**Comment by shann7** [comment]
Thank you so much for this proposal! We've reviewed and would love to fund $10,000 USDC for the following 3 milestones to be delivered over 3 months with a $3000 USDC initial deposit: 

- Milestone 1: Live streaming integration

- Milestone 2: Video on demand 

- Milestone 3: Token gating

With a success metric bonus (5k) for hitting 20k streams as a 4th milestone 

How does this sound to you? Happy to have a call to discuss!

**Comment by MavenFoundation** [comment]
As 1,2 & 3  milestone will be finished within in two weeks as we would be launching the app in 15 days . i am ready with you proposal love to connect with you over a call .
