### ISSUE TITLE
Cryptic OTT: Decentralized Crypto focused Edutainment OTT

### ISSUE THREAD

**Issue by crypticentertainments** [livepeer/Grant-Program#102]
**Give a 3 sentence description for your proposal.**

We are a Crypto Edutainment content production house. We've produced the docu-series "Crypto Revolution: India" that'll release on OTT platforms soon. Catering to only crypto and web3 ecosystem, we have produced documentaries, web series, music videos, short films, reels etc. in collaboration with projects like Polygon, Filecoin, ICP, Tellor, EPNS and many more. 

We are now building a OTT for hosting the entire content. We are looking to produce 12 web series plus short films to educate through entertainment as a medium. 

Website: https://platform.crypticentertainments.com/

Content: https://linktr.ee/crypticentertainments

Web Series: https://www.imdb.com/title/tt22325134/?ref_=fn_al_tt_1

**Describe the problem you are solving.** 
Education for masses is still not solved in the crypto and blockchain space. Through the edutainment content we are looking to educate the masses. 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
We will be developing a decentralized OTT which will host the edutainment content aimed at creating awareness about crypto/blockchain. Through the content we will educate and aware about the technology and importance of decentralization using entertainment as a medium. The content hosted on the OTT will draw masses due to the mass appeal and entertaining nature of the content.

**Describe why you are the right team with the capability to build this.**
We are the only creators, who are producing high quality content (for OTTs) in the crypto edutainment sector. Our expertise of combining crypto education and entertainment makes us a unique in this landscape. 

- Litesh Gumber, Founder of Cryptic Entertainments
Litesh Gumber is an Educationist and a team player who always believed that in order to introduce the "Early Majority" to the crypto and blockchain sector, we have to make learning fun. For this, he brought together 20+ industry experts from the entertainment and crypto ecosystem under one roof, to create meaningful art that'll act as a catalyst for the present crypto revolution.

- Pratham Verma, Head Video Department
Pratham is an experienced Veteran of Punjabi Film industry, specializing in cinematography, editing and post production processes

**Describe the scope of the project including a 3 month timeline and milestones.** 

Phase 1

- Launching Video Streaming platform as NFT gated club for early adopters
- Blockchain identification with login as a wallet option
- Early Access on the platform before YT/OTT release
- Decentralized video streaming using Livepeer

Phase2:

- Secondary trading NFT marketplace of platform NFT's
- Launching NFT's for each series for early access and AMA's with creators and Stars

**Please estimate hours spent on project based on the above and how much funding you will need.** 
We will be giving 80-100 hours in technical development and similar timeframe on content side on weekly basis. We are requesting $8,000 for building this.

**Comment by shann7** [comment]
Thank you for this proposal! We are reviewing and will get back to you asap

**Comment by crypticentertainments** [comment]
Thank you @shann7 , please let me know if you need any additional information or details.

**Comment by crypticentertainments** [comment]
Hi @shann7 , please let me know if there's any update regarding our application.

**Comment by hansy** [comment]
Hey @crypticentertainments! Apologies for the delay; we've been overhauling our grants system. 

With the new changes, we think this application my be a good target for a microgrant, to which we award up to $2000. Microgrants are tightly-scoped applications typically built around a specific Livepeer feature, in this case Livepeer’s VOD functionality.

If you're still interested in pursuing this grant, please feel free to reach out to me on Discord (hansy#9576)! We can schedule a scoping call there.

**Comment by crypticentertainments** [comment]
Hi @hansy I have sent you a friend request on discord. Please check so that we can connect further. My username is litesh#9318

**Comment by hansy** [comment]
@crypticentertainments, to confirm this grant, please paste the address of your arbitrum wallet here. We'll pay 25% upfront ($500 in LPT), then after 30 days, we'll review your milestone and release the rest ($1500 in LPT) if everything looks good.

**Comment by hansy** [comment]
Real quickly @crypticentertainments, while reviewing your project repo (https://github.com/cryptic-entertainments/video-platform), I notice that there hasn't been commit activity since August. Additionally, I don't see very many mints for any of the NFT passes on rarible. Can you explain the 5 month inactivity?

While we do want to see more Livepeer apps in the web3 ecosystem, we want to be judicious about giving funds to applications we think can thrive. I guess my question is, how will the Livepeer integration increase your application's user activity?

**Comment by crypticentertainments** [comment]
> @crypticentertainments, to confirm this grant, please paste the address of your arbitrum wallet here. We'll pay 25% upfront ($500 in LPT), then after 30 days, we'll review your milestone and release the rest ($1500 in LPT) if everything looks good.

Please use the following address @hansy 0xB7d04eC2BeeEe0a287Ce2f7bE469929Ff5D5C9bE

**Comment by crypticentertainments** [comment]
> Real quickly @crypticentertainments, while reviewing your project repo (https://github.com/cryptic-entertainments/video-platform), I notice that there hasn't been commit activity since August. Additionally, I don't see very many mints for any of the NFT passes on rarible. Can you explain the 5 month inactivity?
> 
> While we do want to see more Livepeer apps in the web3 ecosystem, we want to be judicious about giving funds to applications we think can thrive. I guess my question is, how will the Livepeer integration increase your application's user activity?

Hansy we push new code as and when we have the stable version available. Our tech team is working on improving the security aspect along with streaming player on the application. We have now pushed the code so that you can check the next set of features development in the GitHub repo. 

Apart from the tech development we are also completing a short film along with multiple web series to exclusively stream on the OTT. Right now we are constantly working on community building. You can check our YT where we post regular content. 

Regarding the Rarible NFTs, we are currently in the closed beta with our community members and they are testing it. We have our short film ready which will be exclusive to our OTT and then we will launch to the public. Apart from the short film, we have completed a documentary on the Indian crypto ecosystem which will further boost the platform reach. These activities will ensure great reach to our platform.

We are looking to have a better streaming solution for our viewers so that's why we are looking to integrate Livepeer. By providing a smooth experience we are looking to increase the platform engagement along with enhanced user experience.

**Comment by hansy** [comment]
@crypticentertainments Thank you so much for the clarification. I'll let my team know you are ready for the microgrant and will ping you when the transaction is pending! You may start whenever you like (or after you get the transaction confirmation)! Let me know if you do start; I'll then set a follow-up in a month's time on your milestone update.

**Comment by crypticentertainments** [comment]
Thank you @hansy we would like to wait till the payment confirmation for setting up the timelines. Please let us know as and when the transaction is initiated by the team. Although our tech team will start the initial work in the meantime for the integration.

Looking forward to contribute in the growth of Livepeer ecosystem.

**Comment by hansy** [comment]
Hey @crypticentertainments. Wanted to update you with the status of your upfront milestone payment. We're shooting to get it to your team by the end of the week. Thank you for your patience!

**Comment by crypticentertainments** [comment]
Thank you for the update.

**Comment by crypticentertainments** [comment]
Hi @hansy just wanted to check whether the payment was released last week?

**Comment by hansy** [comment]
@crypticentertainments Upfront payment just went out (https://arbiscan.io/tx/0xd55f4685a2eb0f5a7b0ab0604ea910e28263a7ce92f6a9705ad87408b68771bb). The upfront payment is 20%, so upon completion of your milestone, we'll unlock the rest! We'll set your start and end dates to Feb. 24, 2023 to Mar. 24, 2023.

**Comment by crypticentertainments** [comment]
Thank you, will post the updates here shortly.

**Comment by crypticentertainments** [comment]
Hi @hansy we have completed all the three grant deliverables. Please use the following link to check:

https://platform.crypticentertainments.com/

We have integrated Livepeer and now all the videos are getting streamed through Livepeer on our platform.

**Comment by crypticentertainments** [comment]
Hi @hansy is there any update or development regarding the review of our milestone completion?

**Comment by hansy** [comment]
Sorry for the delay on this @crypticentertainments. We're in the midst of our quarterly review, but we will get back to you soon!

**Comment by hansy** [comment]
@crypticentertainments This is cool! A few questions:

1.) Is there a way I can get a temp NFT/pass to view videos. Would love to see how everything works.
2.) Looking through your Github repo, I couldn't find where you used Livepeer. Can you point me to some implementation examples?

**Comment by hansy** [comment]
Also Livepeer just released a token-gating feature (https://docs.livepeer.org/guides/developing/access-control-vod) that might interest you!

**Comment by crypticentertainments** [comment]
> @crypticentertainments This is cool! A few questions:
> 
> 1.) Is there a way I can get a temp NFT/pass to view videos. Would love to see how everything works. 2.) Looking through your Github repo, I couldn't find where you used Livepeer. Can you point me to some implementation examples?

@hansy please share your address for sending the NFT pass. 

2. Please refer to the following GitHub link: https://github.com/cryptic-entertainments/admin . You can check that all the videos are on Livepeer. Moreover we have an admin that we use to upload videos on Livepeer.

**Comment by crypticentertainments** [comment]
> Also Livepeer just released a token-gating feature (https://docs.livepeer.org/guides/developing/access-control-vod) that might interest you!

Sure @hansy we will surely look into this.

**Comment by hansy** [comment]
0x957Fc1013591552a5f8B499265C9E351e672d3F6

Thank you!

**Comment by crypticentertainments** [comment]
Please visit https://platform.crypticentertainments.com/ to test the platform. The NFT is transferred. Thank you. @hansy

**Comment by hansy** [comment]
I tried watching a few videos; I got a message saying I wasn't authenticated. Is there something extra I need to do?

**Comment by crypticentertainments** [comment]
Hi @hansy , I hope you have checked the working of the platform. Please let me know if you need any additional detail.

**Comment by hansy** [comment]
Hmm still no luck. See attached screenshot. What chain are you issuing the NFT on?

![image](https://user-images.githubusercontent.com/775807/232608372-a549d7aa-3ba5-4055-832f-3b762c402ff3.png)

**Comment by crypticentertainments** [comment]
Hi @hansy it shouldn't happen ideally. Can you please check your discord for resolving this issue? 
Also the NFTs are on Polygon.

**Comment by hansy** [comment]
Hi @crypticentertainments. Your last milestone payment has been confirmed! https://arbiscan.io/tx/0x57574fd559289839b6431c4476c94aa6de118099c290ff050885d717f50aa1da
