### ISSUE TITLE
Your Song

### ISSUE THREAD

**Issue by JasonMarkWomack** [livepeer/Grant-Program#104]
**Give a 3 sentence description for your proposal.**
'Your Song' a music video royalty sharing platform built on Liverpeer.
Simply  put, 'Your Song'  as a commodity.
'Your Song' is taking on major record labels, Spotify, and Youtube in the heart of Music City(Nashville).

**Describe the problem you are solving.** 
Musicians who release music videos are not compensate accordingly.
We flip the paradigm, it is 'Your Song' . You get paid when they click play.
We are a profit sharing app. Every user who wants to use the 'Your Song' app pays 5 USD a month. The royalties are dispersed according to video traffic and general popularity. With our decentralized tech, it is impossible to gamify the system.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

By leveraging mobile first decentralized tech, we empower creators to create and get paid . Everyone involved in creating a music video  on 'Your Song' , is grouped/ compensated accordingly. It is contingent on the amount of views a video receives. We are the one stop shop for dispersing royalty pay and to the consumption of music videos.

**Describe why you are the right team with the capability to build this.**

I built my first dapp in 2017. I own and lead software engineering at hackerhotel.xyz. I am more than qualified / capable to build this application.

I have experience building live streaming applications, including, www.akc.tv, while contracting at www.blive.nyc
Linkedin : https://www.linkedin.com/in/jasonmwomack/
Twitter : https://twitter.com/devjwo
**Describe the scope of the project including a 3 month timeline and milestones.** 

UI Design - 1 Week 
Jan 1 to Jan 7

Architecture - 1 Week
Jan 7 to Jan 14

Coding - 2 Months
Jan 14 to March 14

QA Pen Testing - 2 Weeks 
March 14 to March 31st

**Please estimate hours spent on project based on the above and how much funding you will need.** 

45 Hours per week X 12 weeks @  50 an hour ==== $ 27,000 USD

**Comment by hansy** [comment]
Hey @JasonMarkWomack! Apologies for the delay; we've been overhauling our grants system. 

With the new changes, we think this application my be a good target for a microgrant, to which we award up to $2000. Microgrants are used when we're interested in funding a particular component of a project, in this case, it'd be around the music video NFTs and your solution to prevent others from gamifying royalty view payouts.

If you're still interested in pursuing this grant, please feel free to reach out to me on Discord (hansy#9576)! We can schedule a scoping call there.

**Comment by JasonMarkWomack** [comment]
@hansy Should we communicate here instead of our Discord DMs?

**Comment by hansy** [comment]
Hi @JasonMarkWomack. As per our Discord convo, Livepeer is interested in your project's aspect of preventing gamified views. I said this could be a good target for a microgrant via (1) some type of public writeup about your implementation and (2) an open-source demo showcasing your approach. The demo doesn't need to be your full application; it can just be a minimal implementation using Livepeer that compliments the writeup.

However, you mentioned in our conversation that part of your approach is to ensure "...video views are authentically coming from real wallet addresses". Are you looking to address the [Sybil attack](https://en.wikipedia.org/wiki/Sybil_attack) problem?

**Comment by JasonMarkWomack** [comment]
Yes, addressing the Sybil attach problem is in the scope of my work.

**Comment by hansy** [comment]
@JasonMarkWomack if you're truly addressing Sybil then the scope of grant might be much larger. With that being said, my advice would be to post your thoughts and approach on the [Livepeer Forum](https://forum.livepeer.org/) and get feedback from the community. If they think you're on to something, we can revisit this under the larger Video Disruptors grant.
