### ISSUE TITLE
Alphaday community dashboard

### ISSUE THREAD

**Issue by Mikael337** [livepeer/Grant-Program#109]
**Give a 3 sentence description for your proposal.**
We’d like to build a Livepeer community dashboard on Alphaday that aggregates Livepeer news, on-chain data, social media, dev resources and much more into one customizable UI.

**Describe the problem you are solving.** 
Crypto has exploded in popularity over the last 4-5 years and there is so much going on that it’s almost impossible to keep up with everything. Our user research showed that users are overwhelmed with information and spend a lot of time jumping from one news source to another, from one social site to another, and usually have dozens of tabs open to stay up to date with everything happening in a community. 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
Having all this information in one place allows Livepeer stakeholders (ie. users, developers, investors) to easily stay up to date on Livepeer ecosystem updates, see the latest news and developments, do research and stay engaged. In general users who can track their favourite projects more easily stay more engaged with the project which in turn supports user retention. 

Additional Info:
Basically our Livepeer Alphaday dashboard will provide a single end-point from which users can consume all the information on Livepeer. Specifically, the Livepeer Community Dashboard will aggregate all the discussions, talking points, narratives, events, metrics, official announcements and much much more into one single dashboard. With one glance at this dashboard community members would have a top-down view of what is happening across the entire Livepeer ecosystem. From this view they could then jump deeper into their areas of interest (ie. devs to dev documentation, LPT holders to twitter and reddit discussions, investors to on-chain metrics across both Livepeer’s own pages and to third-party data providers).

**Describe why you are the right team with the capability to build this.**
I’ve been involved in the Ethereum space since early 2016 and joined Kyber Network in 2017 as Head of Ecosystem Growth before quitting to start Alphaday full-time in 2021. Previously I worked at Thomson Reuters for a decade building financial products that rivaled the Bloomberg Terminal. I am currently also a Venture Partner at IOSG.VC.

My co-founder Felipe has also been involved in Ethereum since 2016 and was a Developer Advocate at Pegasys and Consensys before quitting to work full time on Alphaday.

Alphaday’s third co-founder is DeFiDude who used to be a community manager at both Aave and Kyber Network before co-founding Alphaday.

https://www.linkedin.com/in/denizomer/ 
https://www.linkedin.com/in/faraggi/ 
https://twitter.com/defidude 

**Describe the scope of the project including a 3 month timeline and milestones.** 
We would like to create a Livepeer ecosystem dashboard that aggregates the following information into a single community dashboard:

- The latest Livepeer official announcements and blog post content.
- A feed of all news mentions of Livepeer from coindesk, cointelegraph and 20+ other news sources aggregated from across the internet.
- A calendar containing all Livepeer events including Livepeer meetups, hackathons with Livepeer bounties, AMAs.
- Podcast feed containing the latest appearances and interviews given by Livepeer team members.
- Youtube stream containing educational Livepeer content.
- Livepeer Documentation directory.
- Integration with Livepeer Forum to show the latest and trending discussion topics.
- Reddit, Twitter, Discord, & Telegram Integration to show a feed of latest discussions.
- FAQ, Whitepaper, LPT tokenomics information.
- Livepeer Jobs integration to show the latest open jobs listed on Livepeer.
- Livepeer & LPT metrics including on-chain volume, number of buys on DEX’s, and other metrics pulled in from Dune Analytics.

If we get a grant we will start working on the board immediately and we should have it ready within 2 months. Once we’ve launched the board, we will do user interviews and feedback sessions to tune the dashboard. We will continue this process of iterating, deploying, and collecting feedback continuously to build a dashboard that Livepeer stakeholders truly love to use.

**Please estimate hours spent on project based on the above and how much funding you will need.** 
1,200 USDC upfront costs for development including integrating the discussion forums, blog post, social feed, jobs listing, and on-chain metrics.

100 USDC per month for 12 months for maintenance including having an Alphaday content analyst quality-checking the dashboard every day and ensuring the Calendar widget is up-to-date with latest Livepeer events, all news mentions across the internet are captured by the dashboard, any updates not automatically captured by the Alphaday aggregator engine is manually added to the board, and other maintenance tasks.

Total Budget: 2,400 USD

**Comment by hansy** [comment]
Hi, @Mikael337, thanks for applying and apologies for the delay! We've been overhauling our grants system.

With the new changes, we think this application my be a good target for a microgrant, to which we award up to $2000. Microgrants are tightly-scoped applications with a clear deliverable. A Livepeer dashboard seems to be a perfect candidate!

Question: are these dashboards public? That is, once created, can they be shared and viewed by anyone with the URL?

**Comment by Mikael337** [comment]
Hi, @hansy, thank you for your reply.

A $2000 microgrant is sufficient for us to build the Livepeer dashboard, and we'd be happy to accept it as our budget.

Regarding your question, all our dashboard urls can be used as links to share with the public and are freely accessible by all users. For instance, for Livepeer the url would be https://app.alphaday.com/b/livepeer/ and would direct a user straight to Livepeer's dashboard.

**Comment by hansy** [comment]
@Mikael337 Awesome. Thanks for the info. Real quickly, though, who are your typical users? That is to say, who builds, views dashboards made through your platform. We're trying to determine the exact benefit Livepeer gets from having a dashboard created.

**Comment by Mikael337** [comment]
@hansy Currently our typical users are web3 enthusiasts, developers, founders and people who've been involved in this space for 1+ years (ie. people who understand or are involved with smart contract platforms like Ethereum and other L1s or L2s). These users have pretty involved daily workflows (ie. wake up, check the latest DAO discussions, listen to podcasts, track prices, follow twitter, check TVL and other onchain, track bounties etc etc). These users are typically pretty involved in the communities they are passionate about so having all the social discussions and relevant data about their projects under one roof is very convenient and time-saving for them (ie. check out this Arbitrum dashboard for an example: https://app.alphaday.com/b/arbitrum/)

Having said that, our userbase is growing rapidly (from 500 MAU when we launched our beta in August to 10k MAU today) so we're constalty seeing new user cohorts making use of our dashboards (ie. complete beginners, NFT enthusiasts, etc)

For the Livepeer dashboard we envision a wide range of ecosystem members from video miners to developers to regular LPT holders to use the dashboard to keep up with all the latest discussions, events, podcast appearances, AMAs to pretty much anything and everything Livepeer-related

**Comment by Mikael337** [comment]
Hello @hansy, hope you are well.
Could you please update us on the current status of our proposal?
Are there any more questions, or should we provide you with any more information?
Alternatively, we could schedule a call with one of our founders for a briefing on what we can offer and how we could customize it for you.

Thanks in advance,
Mike

**Comment by hansy** [comment]
@Mikael337 Thanks for your patience on this. After conferring with the rest of the grants committee, we've decided not to offer a grant at this time. Our primary reasoning is it's unclear how the Livepeer dashboard would increase demand on the Livepeer network or provide wider utility to the web3 video ecosystem. However, there might be benefits to (new and existing) node operators. My recommendation would be to post this application in the Livepeer Discord's [`#community-grants`](https://discord.com/channels/423160867534929930/680142091174543362) channel seeking feedback from orchestrators. If there appears to be interest in the dashboard from them, happy to revisit this grant.
