### ISSUE TITLE
Xilinx U30 based transcoding integration

### ISSUE THREAD

**Issue by ndujar** [livepeer/Grant-Program#110]
**Give a 3 sentence description for your proposal.**

At the moment, Livepeer transcoding nodes rely mostly on CPU and GPU computing power. 
For the sake of diversity, it would be great if Xilinx's U30 family of cards would be added to the family.
This is a proposal for the development of an Transcoder node definition integrating Xilinx's Video SDK for U30 instances.

**Describe the problem you are solving.** 

Currently, Livepeer transcoding nodes rely on CPU and GPU power. In the case of GPUs, one can even take advantage of the dual ethash mining / transcoding abilities to squeeze their income even further.
Unfortunately, in the case of NVIDIA GPUs, some instances have their users restricted from utilizing their own hardware to its full capacity, limiting the number of concurrent sessions they can provide to 3.

This basically means some transcoders are directly out of the game that actually matters to Livepeer, as their maintenance costs do not scale well with the potential revenue they can make.

If they want to play bigger, they have the choice of either purchasing higher end hardware, or relying on cloud providers at very narrow margins.

On the other hand, using the example of Amazon's EC2 VT1 offer, based on Xilinx's U30 cards:  

```
They can deliver up to 30% lower cost per stream compared to Amazon EC2 G4dn GPU-based instances and up to 60% lower cost per stream compared to Amazon EC2 C5 CPU-based instances for transcoding live video streams.

VT1 instances provided by AWS can support streams up to 4K UHD resolution at 60fps and can transcode up to 64 simultaneous 1080p60 streams in real time. They are powered by up to 8 Xilinx® Alveo™ U30 media accelerator cards and support up to 96 vCPUs, 192GB of memory, 25 Gbps of enhanced networking, and 19 Gbps of EBS bandwidth. They are optimized for workloads such as live broadcast, video conferencing, and just-in-time transcoding. 
```
Either for the choice of purchasing higher end hardware, or resourcing to cloud solutions, Xilinx U30 machines have a very competitive edge.

However, in their current state, the Livepeer protocol and the LPMS do not support the specifics of this kind of accelerators.

Our proposal aims at bridging that gap and making Livepeer compatible with this kind of hardware.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

In our proposal, we plan to integrate [Xilinx's Video SDK](https://xilinx.github.io/video-sdk/v1.5/getting_started_on_prem.html) for either on-prem as well as for cloud (AWS EC2 VT1).

This would enrich Livepeer's ecosystem with yet another form of technology that might attract new orchestrators and different business models.

Also, with the potential of using this as a cloud service with high efficiency, it increases the reach of the network to new places, expanding the geographical diversity and reducing latency.

**Describe why you are the right team with the capability to build this.**

I can apply my past expertise in benchmarking Xilinx technologies for production environments.

I have some experience with Livepeer as one of the contributors of the [transcoding verifier](https://github.com/livepeer/verification-classifier). 

I am also currently developing the [NDVD grant](https://github.com/livepeer/Grant-Program/issues/92) for near duplicate video detection and the expertise needed there regarding transcoder/orchestrator operation shows very good alignment and synergies with this project.

**Describe the scope of the project including a 3 month timeline and milestones.** 

Milestone 1: Research latest versions of Xilinx's Video SDK for the U30 and compare performance against GPU: 50h

* Define experimental benchmarks (10h)
* Run experiments (20h)
* Document, illustrate and publish results in Livepeer channels for feedback collection (20h)

Milestone 2: LPMS integration (FFmpeg + LPMS projects): 200h
* Integrate LPMS' FFmpeg with Xilinx's FFmpeg (40h)
* Adapt Livepeer docker image (50h)
* Integrate autoscaling (50h)
* Deploy and test (40h)
* Document, illustrate and publish results in Livepeer channels for feedback collection (20h)

Milestone 3: Test AWS transcoder node performance: 50h 
* Prepare cloud deployment (10h)
* Run experimental benchmarks (20h)
* Update Getting Started documentation, illustrate and publish results in Livepeer channels for feedback collection (20h)

**Please estimate hours spent on project based on the above and how much funding you will need.**

Assuming researchers work part time (4 hours per day) the research, development and divulging content creation should be completed within 15 weeks (300h in total). 

Researcher Hourly Wage: $55/hr USD* Up for discussion
Cloud computing costs: $300
Funding needed: USD16500 + Cloud costs

**Comment by hansy** [comment]
Hi @ndujar. Good to see you here again! I'm curious, have you proposed this to the wider orchestrator community? I'd be curious to hear their thoughts on this!

**Comment by Titan-Node** [comment]
This is very interesting. I'll have to do some research of the Xilinx cards. I see the U30 sell for about $800 on ebay. Would be very curious about the benchmark results with one U30. 
Would have to get 30-40+ streams in order for it to compete with Nvidia in my opinion.

On the other hand it would be good to diversify the chips that run Livepeer. Right now we pretty much completely rely on the third party patch to override the max concurrent sessions put on Nvidia retails cards. I wonder if they would ever block us from patching it, this would require a possible change to new hardware.

My 2 cents is to complete milestone one and see if any Orchs want to use Xilinx cards. Otherwise a similar fate will occur as the NETINT cards, they kind of suck and nobody uses them :/

**Comment by AuthorityNull** [comment]
While I think adding support for more GPU's is always a good thing, I would like to see NETINT become fully supported first since we're already half way there.

**Comment by Wisermerill** [comment]
> This is very interesting. I'll have to do some research of the Xilinx cards. I see the U30 sell for about $800 on ebay. Would be very curious about the benchmark results with one U30. Would have to get 30-40+ streams in order for it to compete with Nvidia in my opinion.
> 
> On the other hand it would be good to diversify the chips that run Livepeer. Right now we pretty much completely rely on the third party patch to override the max concurrent sessions put on Nvidia retails cards. I wonder if they would ever block us from patching it, this would require a possible change to new hardware.
> 
> My 2 cents is to complete milestone one and see if any Orchs want to use Xilinx cards. Otherwise a similar fate will occur as the NETINT cards, they kind of suck and nobody uses them :/

on the data sheat we can read and "encoding up to eight 1080p60 streams" that match with the memory capacity of the card. But i agree that will be great to have some feedback about benchmark of this product.

**Comment by ndujar** [comment]
I have made a quick table based on "official" specs to compare NETINT, on-premises U30 and AWS' VT1 in financial terms:

| Tech | Power  |  Price  | Capacity (4K60FPS)  |  Capacity (1080p30FPS)  |
| - | - | - | - | - |
| Netint T408 (30x) + server (3x) | 800W | $21k | 30x | 240x |
| Xilinx U30 (8x @1600$) + server (1x) | 200W | $22k | 16x | 128x |
| Xilinx U30 (8x @800$) + server (1x) | 200W | $15.6k  | 16x | 128x |
| AWS vt1.3xlarge (1 year reserve) | - | $0.39 / h + egress | 2x | 16x |
| AWS vt1.6xlarge (1 year reserve) | - | $0.78 / h + egress | 4x | 32x |
| AWS vt1.24xlarge (1 year reserve) | - | $3.12 / h + egress | 16x | 128x |

This table assumes three scenarios:
- One invests in 3 whole Netint ridges ($7000) based the offer provided [here](https://easyaccess.netint.com/t408_video_transcoder)
- One invests in a [Xilinx compliant server](https://www.xilinx.com/products/boards-and-kits/alveo/qualified-servers.html) with capacity for 8x U30s ($9200). There is a row for brand new U30s price ($1600), next row ebay prices ($800)
- One rents AWS's VT1 [cloud machines](https://aws.amazon.com/ec2/instance-types/vt1/), and egress costs fit those of the table below:

![image](https://user-images.githubusercontent.com/18640304/217218784-1b02f3b2-d592-4105-b09e-2f4505f0a436.png)


With such costs of egress, I have calculated egress costs of one hour on a VT1.3xlarge (with capacity for 16x 1080p30FPS streams), once spent the initial monthly 100GB for free:

> 16 streams x 4Mbps x 3600s = 230400 Mbits
> 230400Mbits x 0.000125 GB/Mb = 28.8 GBytes
> 28.8GBytes x $0.09 /GB =  $2.592 / h **egress**

Summing up, using this vt1.3xlarge, one needs to evaluate the total cost (compute + egress)

> TOTAL = $2.592 (egress) + $0.39 (transcode) = $2.982 for 16 streams, 1h

**Per stream, this boils down to $0.186375.**

In terms of current price per pixel (rough check on top orchestrators from explorer.livepeer.org gives me 1200 wei/pixel), and recent ETH/USD exchange of about $1500/ETH:

> (30fps x 1080p x 1920p x 3600s x 1200wei/pixel x 1500ETH/$ ) / (1000000000000000000 wei/ETH) = $0.403/stream-h

Which means there is still about 216% ($0.2167) margin at current pixel prices.

I leave below the [current Amazon prices](https://aws.amazon.com/ivs/pricing/) for consideration, though:
![image](https://user-images.githubusercontent.com/18640304/217264451-66d53e46-05a2-48ad-97e7-4d2d08fc3cf2.png)

I hope this helps to assess further whether or not the investments is too risky (as compared to NETINT).

**Comment by Titan-Node** [comment]
@ndujar this is my calculation of Nvidia 3050s, maybe a bit more than $6k but that's just the cards ($500 each). Not sure about the mobo and server cost.
Just for fun comparison. Just some napkin numbers :)
<html>
<body>


Tech | Power | Price | Capacity (4K60FPS) | Capacity (1080p30FPS)
-- | -- | -- | -- | --
Netint T408 (30x) + server (3x) | 800W | $21k | 30x | 240x
Xilinx U30 (8x @1600$) + server (1x) | 200W | $22k | 16x | 128x
Xilinx U30 (8x @800$) + server (1x) | 200W | $15.6k | 16x | 128x
AWS vt1.3xlarge (1 year reserve) | - | $0.39 / h + egress | 2x | 16x
AWS vt1.6xlarge (1 year reserve) | - | $0.78 / h + egress | 4x | 32x
AWS vt1.24xlarge (1 year reserve) | - | $3.12 / h + egress | 16x | 128x
Nvidia 3050 (x12) | 960W | $6k | |240x


</body>
</html>

**Comment by ndujar** [comment]
> @ndujar this is my calculation of Nvidia 3050s, maybe a bit more than $6k but that's just the cards ($500 each). Not sure about the mobo and server cost. Just for fun comparison. Just some napkin numbers :)
> 
> Tech	Power	Price	Capacity (4K60FPS)	Capacity (1080p30FPS)
> Netint T408 (30x) + server (3x)	800W	$21k	30x	240x
> Xilinx U30 (8x @1600$) + server (1x)	200W	$22k	16x	128x
> Xilinx U30 (8x @800$) + server (1x)	200W	$15.6k	16x	128x
> AWS vt1.3xlarge (1 year reserve)	-	$0.39 / h + egress	2x	16x
> AWS vt1.6xlarge (1 year reserve)	-	$0.78 / h + egress	4x	32x
> AWS vt1.24xlarge (1 year reserve)	-	$3.12 / h + egress	16x	128x
> Nvidia 3050 (x12)	960W	$6k		240x

Thank you very much @Titan-Node 
With these numbers, and assuming a $800 price for the U30s, (leaving server cost aside), the 3050 appears to have roughly twice the capacity for the same amount of dollars.
Still, there is the question of the patching, that IMO makes this kind of investment quite risky.
The only Nvidia product without nvenc session restrictions that I have found with similar price is the Tesla T4. According to [this thread](https://forums.developer.nvidia.com/t/max-nvenc-parallel-sessions-supported-by-tesla-t4/214903), 20 streams is a reasonable amount.
Then there is the issue of image quality, but that is another beast..

**Comment by AuthorityNull** [comment]
With the key lace patch, you can override the session limit. All O's use this. With a 1070 we get about 20 streams per card.
