### ISSUE TITLE
HumanQR dApp

### ISSUE THREAD

**Issue by legut2** [livepeer/Grant-Program#111]
**Give a 3 sentence description for your proposal.**
Decentralized QR Code hosting service that allows people to market and grow communities for their projects more effectively. This decentralized QR code service would be open source under the Apache 2.0 license. There would be an included way to make people's faces into QR codes but this last feature will not be open sourced.

**Describe the problem you are solving.** 
QR codes are extremely boring but a brilliant marketing tool. I want to make them more engaging and it more accessible to make really good looking ones for web3.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
I want to make a simple QR code hosting service that allows for tracking simple metrics of scans and allowing to put a creator's face into the QR code. This will benefit the Livepeer developer ecosystem by allowing them to market their projects more effectively. Thumbnails can literally have a QR code on them of the creator's face. Merch can have a QR code of the creator's face. This is a really effective tool for marketing.

**Describe why you are the right team with the capability to build this.**
I am a  Software Engineer with over 5 years of professional experience. I can write code, design mockups, and host infrastructure. You can see a demo over here where you can [upload a 400x400px profile picture and watch it turn into a QR code 30 seconds later.](https://jsbin.com/dalukamobi/edit?html,output)

You can also see an example where I made a QR code video on the [following page](https://qrtoad.com/pricing.html).

**Describe the scope of the project including a 3 month timeline and milestones.** 
Milestone 1 - Rust Rewrite of Face to QR code Code to allow for compiling down to web assembly
Milestone 2 - Link Shortener
Milestone 3 -  Decentralized Filehosting
Milestone 4 - Frontend Design

**Please estimate hours spent on project based on the above and how much funding you will need.** 
200+ hours, $5,000

**Comment by legut2** [comment]
@nelsorya let me know if you have any questions. I have a couple YouTubers I have in mind making merch for, but livepeer can be the proving grounds and I see cross over. Let me know your thoughts.

**Comment by hansy** [comment]
Hi @legut2, thanks for applying! Apologies for the delay on this; we've been overhauling our grants system.

With the new changes, we think this application my be a good target for a microgrant, to which we award up to $2000. Microgrants are tightly-scoped applications typically built around a specific Livepeer feature.

What would be the specific Livepeer integration/workflow you have in mind here?

**Comment by legut2** [comment]
@hansy I just want to clarify, am I to understand that the grant process has changed since I have applied?

One of my beliefs is that the QR code technology that I have worked on is great for marketing and advertising. I believe that it does really well for digital mediums and digital signage. So having a way for someone who is streaming to be able to have a QR code of their face show-up on screen would be useful for the content creators themselves. For example, here is one of your profile picture: 
![Screen Shot 2023-02-14 at 4 42 25 AM](https://user-images.githubusercontent.com/18754749/218718574-01a79e17-b07a-4d72-809a-af8c62a48394.png)
And here is a QR video example of Rick Astley dancing: 
https://user-images.githubusercontent.com/18754749/218719455-7ca77ff2-9b46-48ad-9a9e-c00e28139744.mp4

I am certain there is enough benefit to the end streamers, content creators, and consumers of the videos that there is a livepeer integration/workflow here. I am uncertain whether or not I could properly scope one down to a $2,000 grant. Could you please point me towards previous microgrant integrations/workflows?

**Comment by hansy** [comment]
@legut2 The grant requirements have recently changed (see https://github.com/livepeer/Grant-Program). Here are a few projects currently being scoped with microgrants:

- https://github.com/livepeer/Grant-Program/issues/107
- https://github.com/livepeer/Grant-Program/issues/118
- https://github.com/livepeer/Grant-Program/issues/126

We're definitely trying to put more emphasis on applications that drive demand through the network as well as foster more video-related research.

While your project is novel, it's still unclear to me how it is directly beneficial to the wider video ecosystem. The marketing angle is certainly there, but it may not be a direct enough value-add for us to fund via a grant.

**Comment by legut2** [comment]
@hansy are there any gaps you see with the category of `Educational guides/tutorials/videos targeted at a specific audience teaching them how to build with Livepeer.`? Otherwise I think I may just say this isn't a good fit and retract my application and close this thread.

**Comment by hansy** [comment]
@legut2 It's hard to say off the bat what gaps exist, but generally speaking, we're always looking for better developer resources when it comes to educational content. On the network/orchestrator side, better tooling/documentation is always welcome to make spinning up a node easier or even just running one.
