### ISSUE TITLE
Sponsorship for CRYPTO STAKING CONFERENCE

### ISSUE THREAD

**Issue by fcc2022** [livepeer/Grant-Program#112]
**Give a 3 sentence description for your proposal.**
I am inspired by crypto Conferences I saw in our discord and in twitter but for long time since crypto started no event happen here in Tacloban city. With livepeer sponsorship, Crypto staking conference will happen and people here can know more about crypto warn about fraud understand deeper about staking or validators /orchestrators.  In exchange the event will promote livepeer, lpt, staking and whole crypto adoption.

**Describe the problem you are solving.** 
Crypto adoption, educate people about proof of staking, build cooperation with government and concern agencies about crypto.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
Crypto Staking conference will make a big impact in adoption, and in education. Philippines is among the top countries in crypto adoption but mostly is into play to earn, trading, many is become victim also of rug pulls, With this event we can educate them more about  Staking, validators or becoming orchestrator for them to become long term crypto believer not just speculative and gain driven. Philippines Government is crypto friendly and with this event it will strengthen beliefs of concern agencies to support, adopt  crypto/blockchain projects.

**Describe why you are the right team with the capability to build this.**
I started learning about crypto in 2016 and started in livepeer as community admin in 2019 it is my long time dream to set up an event like this. Nov. 14 to 17 2023 I and my wife attended [Philippine web3 festival](https://www.phweb3festival.com/partners.html) in Manila a week event about web 3, nft and crypto. I was inspired again and it fuels me to start working on Crypto Staking Conference. With my connection to projects like livepeer and other, and with my team Fcc academy a crypto education dedicated small community we form and our connection to government agencies We can easily get speaker and deliver the event. 

**Describe the scope of the project including a 3 month timeline and milestones.** 
Preparation Start in January 2023. 
*Set up a team assign for each work- 1st week
*Website creation - 1st week
*Application for sponsorship- 1st week
*Getting list for speakers -1st week
*Programme set up -2nd week
*Venue reservation, - 2nd week
*Materials and equipment needed - 3rd & 4rt week

February 2023: 
Finalizing and implementing any adjustments

March 2023:
Double check any adjustments - 1st and 2nd week
Event date - 3rd week

**Please estimate hours spent on project based on the above and how much funding you will need.** 
A minimum of 64 hours to work for the whole projects, it also include a team of 5 people. 
A minimum of 300$ for booth in activity area and conference venue, up to a 2000$ grant.

event website: https://cryptostakingconference.fccnft.info/

**Comment by hansy** [comment]
Hi @fcc2022, thank you for applying to the grants program, but this application does not meet our requirements for receiving a grant. While grant funds are used for event sponsorships, we don't fund the creation of the event itself. If you do go ahead and decide to launch the event and need a sponsor afterward, please feel free to reach out again. However, keep in mind this is not a guarantee of sponsorship.

**Comment by hansy** [comment]
Hey @fcc2022, apologize for closing the issue earlier. I did not realize you were already in conversation with @dob and @shann7 for sponsorship. Ignore my earlier comment; again apologies for the confusion.

**Comment by fcc2022** [comment]
Yes. We are already talkingOn Feb 7, 2023 11:11 AM, Hans Yadav ***@***.***> wrote:
Hey @fcc2022, apologize for closing the issue earlier. I did not realize you were already in conversation with @dob and @shann7 for sponsorship. Ignore my earlier comment; again apologies for the confusion.
