### ISSUE TITLE
Xeenon Builds on Livepeer

### ISSUE THREAD

**Issue by transmental** [livepeer/Grant-Program#113]
**Give a 3 sentence description for your proposal.**
Xeenon is a creator first live streaming application that leverages the Livepeer network for it's low cost and open sourced real time transcoding solution. It's creator payment rails are built entirely on top of the Arbitrum blockchain to facilitate instant and transparent payments to creators. The platform has the power to not only bring in new users of the Livepeer network, but also to quickly onboard new Web3 users. Xeenon provides another valuable tool in the shed for creators to monetize their content, and provide value to their existing communities. 

**Describe the problem you are solving.** 
Livepeer as a transcoding network is a wonderful solution for live streaming, but the lack of documentation around building quality platforms on top of Catalyst is concerning. Catalyst offers more freedom for builders than the Livepeer Studio option does, and without documentation around how to actually use it Xeenon has had to spend a ton of time reverse engineering the code base to get to where it is today. From the many conversations with Livepeer team and  developers over the past few months, it is clear that even most of the core Livepeer team is not entirely aware of the intricacies involved in building with Livepeer Catalyst.  While there are a ton of aspects of Catalyst that are undocumented (or severely lacking in detail), the two areas that stand out the most are load balancing and serving VOD recordings via Catalyst / Mist server.  

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
For the past 9 months or so, Xeenon has been hammering away at the Livepeer Catalyst code base and asking the core Livepeer team tough questions that have undoubtedly shed light on the areas where documentation has holes. All the while, building easy to use tools for creators on top of the Livepeer Network. Our platform https://xeenon.xyz is currently up and running using Livepeer Catalyst, in which we have successfully implemented pay walled streams, NFT gated streams, a mobile broadcasting application, and an advanced blockchain native payment processing service.

**Describe why you are the right team with the capability to build this.**
Xeenon is being built in an iterative fashion by Graviton, a team of passionate and talented engineers and managers that have years of experience building blockchain protocols (such as Universe XYZ and Barnbridge) and products (NFT Embed, NFT display, Metaversian Republic, and Smart Yield). Not only do they build protocols and products, the team at Graviton are daily web3 enjoyers that truly understand the technology and culture of blockchain. 

Since launch, Xeenon has moved quickly with new features and bug fixes. With more runway to execute on the big picture, Xeenon will be on it's way to becoming a legitimate Twitch competitor that feeds back into the Livepeer ecosystem and benefits Web3 as a whole.   

Xeenon also runs it's own Livepeer Orchestrator that currently pays out 95% of it's inflationary LPT rewards to it's delegators, and keeps only 5% of it's ETH reward cut.

https://explorer.livepeer.org/accounts/0x76a65814b6e0fa5a3598ef6503fa1d990ec0e61a/orchestrating 

**Describe the scope of the project including a 3 month timeline and milestones.** 
Xeenon has built on top of Livepeer from the ground up. Choosing to build with Catalyst instead of the easy to use, plug and play Livepeer Studio was not an easy decision. From the start, Graviton wanted to build this with unlimited flexibility and futureproofing in mind.  

So far, the Xeenon team has already done a ton to aid in troubleshooting and enhancing the documentation around building with Catalyst. With a massive road map ahead, Xeenon will continue to uncover holes in the documentation and find critical issues while they build out the platforms feature set. 

Some upcoming features for Xeenon include: 
- VODs (uploaded / published past streams + paywalled / NFT gated)
- Continued mobile broadcasting app development 
- Iterative creator feature request support
- Social interactions (following, liking, and further interactions between creators, media, and viewers)
- Frictionless non web3 user onboarding

**Please estimate hours spent on project based on the above and how much funding you will need.** 
Xeenon is asking for a retroactive grant of 30k USD based on 300+ hours of planning, troubleshooting, and developing using Livepeer Catalyst. 

cc: @zcoon @dannydesert of https://graviton.xyz

**Comment by hansy** [comment]
Hi @transmental, I'd like to update you on the status of your retroactive grant. As per committee decision, we can't offer the full $30k amount, but still want to recognize the work you've done by offering $5k. Let me know if this works for you; if so feel free to add your arbitrum wallet address here and I can begin the payment process.

**Comment by DannyDesert** [comment]
@hansy, that's fantastic news! I just wanted to express my sincere gratitude to you and the team for working with us to build an incredible future together. It's been an absolute pleasure collaborating with you all, and I'm excited for what's to come!

the best address to send it to is: 0x76A65814b6e0fa5a3598Ef6503FA1D990ec0E61A

**Comment by transmental** [comment]
@hansy Thanks for getting back to us on this! We are grateful for the consideration and look forward to continuing to build on such a wonderful protocol. 

Verifying that 0x76A65814b6e0fa5a3598Ef6503FA1D990ec0E61A is the best address to send funds to.

**Comment by hansy** [comment]
Great to hear! I'll let the committee know and we'll begin the process. I'll let you know when the transaction has been made!

**Comment by hansy** [comment]
@transmental @DannyDesert Payment has been sent! Here's the transaction hash: https://arbiscan.io/tx/0x99b70a0f1f065336515f9b21506f76c04726545168a89b7b0357df1486475898. Closing this application now. Great work and let me know if you have any additional questions!
