### ISSUE TITLE
Proposal: nftstv.xyz

### ISSUE THREAD

**Issue by pabloVoorvaart** [livepeer/Grant-Program#115]
[[nftstv.xyz](http://nftstv.xyz/)](http://nftstv.xyz) allows content creators to become their own broadcasting platform by providing them with the tools and infrastructure necessary to easily distributive and monetize their video content through the usage of livestreaming NFTs.

## The problems

1. Currently content creators are forced to choose one streaming platform because: 
    - They rely on monetization tools provided by the platform
    - They rely on discoverability mechanism provided by the platforms.
    - They have custom non compete agreements.
    - They rely on the content creator tools provided by the platform.
2. Content creator platforms hold monopolies because:
    - Live video distribution at scale is really expensive.
    - Video storage at scale is really expensive.
    - Recommendation algorithms rely on getting better the more data a platform has.
    - Community perception.
    
![image](https://user-images.githubusercontent.com/38107177/213164621-a7a5cdac-d0f3-4c16-b97f-d4d6b4d95ec9.png)

## The solution

- We have extended the NFT concept and created the LiveNFT. With LiveNFTs, users can directly show a stream of video inside the NFT. We have also implemented new functionality into the NFT contract to enable all monetization features available in tradition streaming platforms:
    - Subscription model.
    - Donations.
    - Pay per view.
    - Interaction on donation.
- We have created an application that content creators can use to create, manage and stream to their LiveNFTs. This LiveNFTs serve as their new livestreaming channel.
- User can consume the content creators livestream on any platform that natively display nfts such as Opensea, Zora, Twitter or even the users mobile wallets such as Zerion wallet.
- Using liveNFTs, anyone can build a niche streaming platform for a certain topic. Using already existing developer sdk, they can implement all the functionality that the LiveNFT provides with 0 inhouse development time. LiveNFTs rely on decentralized protocols to handle distribution, storage and indexing of video content, reducing infrastructure cost of running such a platform by a factor of x10.

## How does it work

![image](https://user-images.githubusercontent.com/38107177/213164767-3ac82f60-a3d2-4abc-861e-00ec51a11c65.png)

High level overview of the [nftstv.xyz](http://nftstv.xyz) application

### The LiveNFT technology:

A non fungible token (NFT) is an inmutable piece of software that represents a digital asset (video, images, video game items)  and defines a clear way to interact with such asset. Lately, nfts use cases have revolved around the idea of attaching ownership to this digital goods creating interesting and diverse business models such as decentralized IP protection, token gated communities and digital collection games in which the user owns in games assets.

NFTs are ethereum tokens that follow the erc-721 token standard, which precisely defines how this token should be implemented by developers, but more importantly, which functions and attributes internet users and applications are able to expect when interacting with such tokens. The erc-721 token standard was created to support the ownership use case for digital assets on ethereum. 

![image](https://user-images.githubusercontent.com/38107177/213164904-0084debe-a958-430b-ad2b-5b34ab3b39e0.png)

The nft contracts tell internet applications how to interact with the digital asset

LiveNFT tokens inherit all functionality from the erc721 token standard and extend it with new functionality to support new use cases around live video digital assets. By introducing this new token standard, we intend to: 

1. Keep backwards compatibility with platforms that use erc721 nfts: in the last few years, a large application ecosystem has been built around nfts. We aim to keep LiveNFTs compatible with all of these applications to enable ease of adoption by users.
2. Standardize new functionality around live video digital assets. We believe there is a whole monetization vertical that is not supported by the erc721 standard and that is native to current video streaming applications: subscriptions to content, direct donations to content creators, pay per view models, monetized real time interactions and more. All of this functionality is easily supported by etherum contracts, and does not require custom inhouse software development to be adopted by existing video applications. 

## The NFTsTv application:

The NFTsTv application is composed of a simple client interface and a few backend services. The goal of the application is to allow content creators to: 

- Create and manage LiveNFTs
- Manage income generated by the LiveNFT and adjust monetization settings
- Manage the video streaming being sent to the LiveNFT
- Interact in real time with their audience.
- Provide creator tools to improve stream quality and engagement.

The application target are content creators, but we have also created a stream view experience for consumers. This view will implement all available features of the LiveNFT, and will be used to showcase feature development and increase adoption of the LiveNFT standard.

![image](https://user-images.githubusercontent.com/38107177/213164831-9255f2fb-1bd0-4cca-a4fc-d54c260afb5b.png)

## Product roadmap

Phase 1: 

- Development of the LiveNFT standard implementing the following features:
    - Direct donations
    - Subscriptions
    - Token gated streams
- Development of NFTsTV:
    - Content creators can create and manage LiveNFTs.
    - Content creators can stream to the LiveNFT.
    - Content creators can enable all monetization features for their LiveNFT.
    - Viewers can watch the stream.
    - Viewers can interact with all monetization features.
- Adoption:
    - Onboard 10 content creators onto the application.
    - Iterative testing with content creators to improve ui and ux.
    - Rebrading to [[broadcastr.xyz](http://broadcastr.xyz/)](http://broadcastr.xyz)

Phase 2: 

- Development of two features for the LiveNFT standard:
    - Interactive donations: user will be able to donate to the liveNFT and the client side will react to donation events.
    - Indexing and categorization: define metadata and attribute standards so that we can build a categorization layer for the LiveNFTs.
- Improvement of client application:
    - Modify viewer application to interact with interactive donations.
    - Apply ui / ux changes learned from phase 1 user research
    - Implement recommendations page that uses the categorization layer.
    - Add support for Livepeer VOD uploads.

Phase 3: 

- Develop LiveNFT sdk so that other developer can integrate LiveNFT playback on their streaming applications.
- Focus on marketing and adoption.
- ZKP research for content protection.
- Deployment two multiple l2 solutions.
- TBD …

## Livepeer ecosystem grant
The proposed solution is to build the platform uses livepeer as the main network for content distribution. We hope to massively increase network traffic by becoming on of the go to solution in the early days of web3 content creation. 

Furthermore, this project is being built in the open and will focus on producing well documented components that developers can reuse and learn from, as well as create feedback loops with the livepeer community as we integrate their sdk and tools into our stack.

## Funding required

We are asking for a medium grant from the livepeer community to quick start development of the application, by distributing grant funding to our developers and community lead member. 
Looking at the product roadmap described above, we request funding on a phase by phase basis: 

Phase 1: 
- Eth contract development: 150 hrs. 
- Web application design and development: 300 hrs. 
- Community development and user research: 50 hrs. 

Funding requested: 45000 DAI

Phase 2: 
TBD 

Phase 3:
TBD

## Team. 

You can follow progress of the development here: https://github.com/NFTsTv/nftstv

- Core solidity developer: [Mario](https://github.com/Mario-SO)
- Streaming engineer, fullstack developer: [Pablo] (https://github.com/pabloVoorvaart)
- Community lead: [Shaka](https://twitter.com/Shakaleikaumaka)
- Design lead: Skayaz

**Comment by hansy** [comment]
Hey @pabloVoorvaart thanks for applying for a grant! We're currently revamping our grant system and are introducing a new tier of grants called the Video Disruptors (VD) grants, which is geared towards projects who are doing cutting-edge video research or are building an incumbent-disrupting application. This feels like it hits the former criteria, and so we'd love to offer you a VD grant!

The VD grant is capped at $15K, and has a maximum 3 month timeline for completion. We would need to figure out scope and deliverables together that work for your team.

Given the smaller grant amount and potential scope, some areas of exploration we'd love to see are:

- Indexing and categorization: define metadata and attribute standards so that we can build a categorization layer for the LiveNFTs.
- Implement recommendations page that uses the categorization layer.
- Develop LiveNFT sdk so that other developer can integrate LiveNFT playback on their streaming applications.
- ZKP research for content protection.
- Deployment two multiple l2 solutions.

If there's a way we can incorporate all/some of the above into 3 distinct milestones, please let me know. We want to set ambitious, yet doable goals given the 3 month timeline.

**Comment by pabloVoorvaart** [comment]
Hey, thanks for getting back <3

So here is what we are planning on developing in the next 3 months: 

- Indexing and categorization: define metadata and attribute standards so that we can build a categorization layer for the LiveNFTs.
- Develop LiveNFT sdk so that other developer can integrate LiveNFT playback on their streaming applications.
- Deployment two multiple l2 solutions. (launching on polygon soon)
- Show custom animations on viewer donations (possibly other nfts with text)
- Token gating via JWT 

Let us know if this sounds interesting, 

Cheers, Pablo.

**Comment by hansy** [comment]
Closing in favor of #146
