### ISSUE TITLE
Videso 2.0 Grant Application

### ISSUE THREAD

**Issue by jsonpreet** [livepeer/Grant-Program#117]
**Give a 3 sentence description for your proposal.**
Videso is a decentralized video-sharing social media platform built on top of the DeSo blockchain. This means that Videso is a platform that is not controlled by any central authority, allowing users to have full control over their content and data.

Website: https://videso.xyz/
Testnet: https://testnet.videso.xyz/
Twitter: https://twitter.com/VidesoApp
Discord: https://discord.gg/8T5RUrsP6W
Github: https://github.com/jsonpreet/ViDeso-2.0 (Testnet: https://github.com/jsonpreet/ViDeso-2.0/tree/testnet)

**Describe the problem you are solving.**

Web 2 Video Sharing Platforms, provide a good service to content creators but creators have a lot of problems like Censorship, Monetization, and more. I read many posts on DeSo that creators looking for a web3 video sharing platform where they can monetize their content without any policy, or censorship issues.

**Describe the solution you are proposing and how it will have a positive impact on the LivePeer developer ecosystem.**

We decided to make a Videso 2.0 decentralized video-sharing platform with LivePeer, where content creators can upload their content on LivePeer Studio (IPFS). Users have the option to Store Videos on IPFS or LivePeer Studio. Creators can monetize their content with DeSo Diamonds as Tip. Creators have the option to Create Content for their Coin Holders.

Describe the scope of the project including a 3-month timeline and milestones.

Milestones:

⭐ Create Channels (OnBoard users)
⭐ Publish any video content or Live Streams.
⭐ Members' only Videos are basically Coins Holders Only Videos.
⭐ Notifications.
⭐ Support creators by sending a Diamonds
⭐ NSFW content restrictions.
⭐ Decentralized Video Storage using LivePeer VOD

Phase 1:

In Phase 1, We will launch the Website with the Following Features:

1. Frontend UX.
2. Customizable Channels.
3. Video Upload with NSFW content restrictions using LivePeer VOD.
4. Notifications
5. Support Creators by Sending Diamonds.

Estimated development hours: 2 months
Team Members: 1
Total Estimate: 10K USD

Phase 2:

1. Live Streaming feature.
2. Coin Holders (Video Uploads + Live Streams)
3. Members-Only Videos.
4. Better recommendation algorithms.

Estimated development hours: 1 month
Team Members: 2
Total Estimate: 10k USD

**Please estimate hours spent on the project based on the above and how much funding you will need.***

Estimated development hours: 3 months
Team Members: 2
Total Estimate: 20k USD

**Comment by hansy** [comment]
Hi @jsonpreet, thank you so much for applying. We're currently revamping our grant system and are introducing a new tier of grants called the Video Disruptors (VD) grants, which is geared towards projects who are doing cutting-edge video research or are building an incumbent-disrupting application. We think your project fits the former part of this definition in that we haven't seen a lot of applications integrate Livepeer + the DeSo blockchain. 

We'd love to offer $7K to help fund the Livepeer integrations of the website as well as offer an additional $3K success metric that is unlocked after an agreed-upon metric is reached (e.g. number of videos uploaded, number of minutes streamed, etc).

If this works for you, we can fine tune the scope and deliverables to best suit your team.

**Comment by jsonpreet** [comment]
Hi @hansy Sir,

Can it be $10k + $3k? It's a unique project.

**Comment by hansy** [comment]
For us, the most important aspect is the Livepeer integration. which $7k should cover given a majority of UI/UX appears to already have been completed. I guess we'd be curious on how you plan on tackling NSFW content using Livepeer as well implementing "better recommendation algorithms". If there's a plan there, then we'd be happy to explore bumping initial offer by $3k.

Finally, keep in mind that all projects must be open-source. If you have a link to this project, please also include it here.

**Comment by jsonpreet** [comment]
@hansy Sure Sir Updated the Application with the GitHub repo link. It's currently v1 and In Videso 2.0 will improve UI/UX more a better and nice looking. 

For NSFW Content I am using nsfwjs and @tensorflow/tfjs packages. 

I used both packages for analyzing video in my OrbisTube Package 
(https://github.com/jsonpreet/orbistube/blob/main/src/components/Upload/Video.jsx)

**Comment by hansy** [comment]
Thank you @jsonpreet for the context. Let me confer with my team and I'll get back to you shortly.

**Comment by jsonpreet** [comment]
@hansy Thank You Sir 👍

**Comment by jsonpreet** [comment]
@hansy Gm Sir, i m waiting for your response

**Comment by hansy** [comment]
@jsonpreet After conferring with my team, we don't feel your application is novel enough to warrant something other than a microgrant, which is $2K. The scope would be one month long, and the two criteria are (1) clear and complete Livepeer integration and (2) a production-ready URL for others to test. It seems like you already have the latter in place, so it'd just be the Livepeer integration we're looking for.

Let me know if you'd like to pursue the microgrant!

**Comment by jsonpreet** [comment]
@hansy Sir before you said for $7k grant. It is not possible at least $7k grant? I planned many things with my Project with grant.

**Comment by hansy** [comment]
@jsonpreet Unfortunately the funding decision does not just rest with me; it's a collective effort by our entire committee. While I initially did scope a higher amount, my teammates suggested that wouldn't be necessary as we're only interested in the specific Livepeer integration. In this case, we'd be curious about how you plan on integrating NSFW content restriction with Livepeer. We'd love a writeup on the technical implementation of combining tensorflow with Livepeer. That would be in scope for a microgrant.

**Comment by hansy** [comment]
@jsonpreet At this stage probably not given the narrow scope we're interested in (Livepeer + NSFW content detection). This doesn't mean that you'd be excluded from consideration from future grants. If your application exhibits traction and growth, we're happy to explore a bigger grant that will help you achieve some of your loftier goals.

**Comment by jsonpreet** [comment]
Hi, @hansy Thanks for your response. I tested my NSFW code it only scans Images + Gifs, So there's no chance to read Videos. But I will try if it helps or not.

**Comment by jsonpreet** [comment]
Hi @hansy Sir, I am Ready to Ship the Project in Production. And I agreed on a $2k Grant, Appreciate Livepeer Team.

**Comment by jsonpreet** [comment]
Hello @hansy Sir,

Here's Testnet of Videso 2.0, I updated Github repo link too.

Testnet: https://testnet.videso.xyz/
Github: https://github.com/jsonpreet/ViDeso-2.0 (Testnet: https://github.com/jsonpreet/ViDeso-2.0/tree/testnet)

**Comment by hansy** [comment]
@jsonpreet As mentioned previously, our interest was with your NSFW detection in video. Otherwise, for future grant considerations we want to see growth and traction in your app (number of users, number of uploaded videos, etc). I am closing this application, but we can revisit this in the future if there are any significant updates you want to share.

**Comment by jsonpreet** [comment]
Oops! It's Closed, I have ready NSFW detection in Video.

**Comment by jsonpreet** [comment]
@hansy Oops! It's Closed, I have ready NSFW detection in Video.

**Comment by jsonpreet** [comment]
@hansy I have code ready NSFW detection in Video. You can test on https://testnet.videso.xyz
