### ISSUE TITLE
The marketplace for NFTs with encoded video content

### ISSUE THREAD

**Issue by spreadzp** [livepeer/Grant-Program#119]
**Give a 3 sentence description for your proposal.**
A platform for creating NFTs with video content using **Livepeer**.
Marketplace allows the owner to gain control over their content and receive a lifetime benefit from its further distribution to new owners.
This solution is planned to be transferred to the metaverses

**Describe the problem you are solving.** 
The amount of video content today is increasing exponentially. Content creators have to deal with the problem of copying their content for use by other content creators and even for fakes without any credit to the original source and without any payment to the author. This project solves these problems using **Livepeer**, **NFT**, cryptography, **IPFS** technologies

**Describe the solution you are proposing and how it will have a positive impact on the **Livepeer** developer ecosystem.** 
**Livepeer** is a technology with great promise in web3. The proposed solution is aimed at copyright protection and monetization of video content created using **Livepeer**.
See how it works =>  [video](https://www.youtube.com/watch?v=gFVrgK0WzEo)
test live app =>  [the application in action](https://video-marketplace-spread.vercel.app/)
explore the repository => [repository](https://github.com/spreadzp/encoded-video-marketplace)

**Describe why you are the right team with the capability to build this.**
I have been working in IT for over 11 years as a full stack programmer.
I have extensive experience in developing Node.js applications for both front-end and back-end. There is significant experience in the development of smart contracts since 2017.
I came up with this solution more than a year ago and then made the first prototype. Now, with the meeting with Livepeer, new opportunities for expanding my idea have opened up. To do this, I have both the ability to complete the desired features and the desire to make this product useful and accessible to society.
[My LinkedIn](https://www.linkedin.com/in/paul-spread-bb337b63/)
[My Github](https://github.com/spreadzp) 

**Describe the scope of the project, including a 3 month timeline and milestones.** 
At the moment, the current solution has already implemented the main functionality, so all the work will be built on finalizing the desired features, improving and redesigning the interface, finalizing testing and auditing existing smart contracts in terms of the economic model. I plan to work with a designer to change UX / UI.  Testing the entire application, Refinement of the application to function with the leading blockchains. I really look forward to the appearance of a version of the player from **Livepeer** with the ability to play video from the base64 string. Such a feature will allow the implementation of cryptographically encrypted video content in NFT. This will allow me to implement content protection, which I strive for in this project, at 100%. To do this, I plan to establish contact with developers from **Livepeer**
**1st month**
Working with a designer
implementing **Livepeer** authentication in the application
optimization of code working with web3 using best practices

**2nd month**
new design implementation
refinement of smart contracts, refinement of the marketplace economy
testing and auditing smart contracts
finalization of the application so that it can be used in leading EVM blockchains

**3rd month**
application testing
deployment of smart contracts in leading EVM blockchains
application deployment
development of application integration into **Decentrland Metaverse**

**Please estimate hours spent on the project based on the above and how much funding you will need.** 
I estimate it is possible to spend 400 hours to achieve the goals. Designer's work in 60 hours
I estimate the budget at $ 18,000

**Comment by hansy** [comment]
Hi @spreadzp, thank you for applying! We're currently revamping our grant system and are introducing a new tier of grants called the Video Disruptors (VD) grants, which is geared towards projects who are doing cutting-edge video research. This application falls into that category with your base64 string exploration.

We want to offer you $5K for a writeup exploring this option as an encryption option for video creators. It seems you already have an accompanying demo, so we'd love to see a detailed post on implementation details, how you arrived at this solution for encryption, pros/cons vs other methods, and any other details you think other video developers and creators might find useful. Our team would find this useful as well as we're always striving to improve the Livepeer protocol. If you have any suggestions on how Livepeer can incorporate this feature, we welcome that level of insight as well.

We have a forum (https://forum.livepeer.org/) which would serve as a great place to post to garner feedback from our community, but of course where you post is up to you.

Let me know if you'd like to continue pursuing this grant!

**Comment by spreadzp** [comment]
Hi Hans,
It's awesome news for me, I already started to write the post about
the encryption option with Livepeer. I will post it in
https://forum.livepeer.org/. It will not fast, I have some ideas how it
better explain and it needs some time.
Best regards,
Paul


пн, 6 февр. 2023 г. в 20:17, Hans Yadav ***@***.***>:

**Comment by spreadzp** [comment]
Hi Hans,
I have written an article that discusses the use of Livepeer in creating an
NFT encrypted video marketplace. The article is available at
https://hackernoon.com/safeguarding-your-videos-with-nft-marketplace-and-advanced-cryptography-in-livepeer.
Currently, I am working on the code https://github.com/livepeer/livepeer.js,
which will enable the use of Livepeer Player to play videos from a base64
string. This will make it possible to create a fully encrypted video
marketplace. Once I have completed the implementation, I will write another
article about it.

I am seeking advice on whether to post a copy of my article on the
https://forum.livepeer.org/ forum. Do you think it would be beneficial to
do so?

Best wishes,
Paul

пн, 6 февр. 2023 г. в 20:58, Spread PROFI ***@***.***>:

**Comment by spreadzp** [comment]
Hi Hans,
I already made some changes and made PR to livepeer.js. I  want to write
the description about new features in forum  https://forum.livepeer.org/,
but I can include only plain text without any links.[image: image.png]
But my description in attachments includes many links, because it is more
simple to understand for the community
What I need to next step?
How can I to announce it to the community?
Best wishes,
Paul

пт, 3 мар. 2023 г. в 23:23, Spread PROFI ***@***.***>:

**Comment by hansy** [comment]
Hmm...try asking about this in the [#developer-lounge](https://discord.com/channels/423160867534929930/1051963444598943784) Discord channel. Maybe one of the mods will allow links in the forum.

**Comment by spreadzp** [comment]
Hello Hans,
What else do I need to do to for this grant of livepeer/Grant-Program?
Best regards,
Paul

чт, 6 апр. 2023 г. в 22:34, Hans Yadav ***@***.***>:

**Comment by hansy** [comment]
What kind of feedback did you get? Anything positive or encouraging for your work?

**Comment by hansy** [comment]
Closing in favor of #146

**Comment by spreadzp** [comment]
## Using Livepeer Player in my DAPP
This thread is about using the Livepeer player in my DAPP. For my application, I needed the player to be able to play video sources from a base64 string. This is necessary in order for my application to be able to store encrypted videos with cryptography. I detailed this in my article [Safeguarding Your Videos with NFT Marketplace and Advanced Cryptography in Livepeer] (https://app.hackernoon.com/drafts/XqReWqlbiOkh61vS6iZh) at the end of the post.
At the time of writing, my DAPP could only partially encrypt video access using video playback decoding encoding, but the video itself was not re-encrypted. To do this, it was necessary to modify the Livepeer player.
I made the necessary additions to the functionality of the Livepeer player in a fork of the Livepeer.js library. I tested the new player in my DAPP with patches. I also created a [pull request] (https://github.com/livepeer/livepeer.js/pull/304) in livepeer.js with [description] (/livepeer.js/pull/304#issue-1655985730) of that how i did it.
This PR was merged with the main branch
https://github.com/livepeer/livepeer.js/commit/d2522dd5d9dffce55c1c9d6f18c4db2b1b7eccda
and with livepeer@2.4.2, video playback from a base64 string is available
It will be easy to use like in DAPP
```
<Player title={video?.name}
          source = {base64FileData}
          // player works as usual for the following cases
          // src={'https://ipfs.livepeer.studio/ipfs/QmURv3J5BGsz23GaCUm7oXncm2M9SCj8RQDuFPGzAFSJw8'}
          // playback id={active[0].playbackId}
          topic = {{
              border styles: {
                  containerBorderStyle: "dotted",
              },
              colors: {
                  accent: '#00a55f',
              },
              dimensions: {
                  trackContainerHeight: '50px',
                  thumb: 50
              },
              space: {
                  controlBottomMarginX: '10px',
                  controlBottomMarginY: '5px',
                  controlsTopMarginX: '15px',
                  controlsTopMarginY: '10px',
              },
              radii: {
                  containerBorderRadius: '0px'
              },
      }} />
      ```
      to see more [code] (https://github.com/spreadzp/video-marketplace-with-livepeer/blob/228ff8c84662167a84d070dce62e5029a6fa569f/pages/createAndViewAsset.tsx#L179)
The app now works as it should. Videos can be encrypted and resold using NFT.
What's next:
- new design implementation
- refinement of smart contracts, refinement of the marketplace economy
- testing and auditing smart contracts
@hansy  In the application, the video is re-encrypted into a text file and thus stored in IPFS. Saving in IPFS is done under my account. If you do this using Livepeer, saving is successful, the Asset ID appears in the file, but a check is made in the backend for playback as an mp.4 file, and in this case it is a text file with encrypted video, so an error appears.

**Comment by hansy** [comment]
Great work @spreadzp! So if I'm understanding this correctly, the video's `playbackId` is encrypted and stored in IPFS, then decrypted for playback in the player? Or is the entire video file encrypted?

**Comment by spreadzp** [comment]
The playbackId is still securely stored in an encrypted format in IPFS, as before. However, my commits to the livepeer.js now enable the through the Livpeer Player to play videos directly from base64 strings . My application still encrypts videos from base64 strings and saves them in IPFS as encrypted text files, which can be decrypted using the Metamask wallet and played through the Livpeer Player. The previous version of the player supported playback of video files through playbackId, links to IPFS or Arveawe where  the files have stored  in mp4 format.
