### ISSUE TITLE
ETH 2.0 Funding

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/Grant-Program#12]
**Give a 3 sentence description about this proposal.**

Livepeer runs on Ethereum.

Ethereum is working to upgrade to ETH 2.0

I believe that Livepeer ought to support this work.

**Describe the problem you are solving.** 

The Proof-of-Work foundations upon which Livepeer is building it's Delegated-Proof-of-Stake are legacy and out-dated.

**Describe the solution you are proposing.** 

To financially support the efforts to upgrade the foundations that Livepeer are built on - i.e. the work to build and launch Ethereum 2.0.

I propose a grant of 300-3000 LPT to Prysmatic Labs, who are building an implementation of the ETH 2.0 client in go (the same language that Livepeer is written in.

**Describe the scope of the project including a rough timeline and milestones** 

To build the `go` implmentation of ETH 2.0.

Currently aiming to deliver phase 0 this year, and later phases in later years.

**Please estimate hours spent on project based on the above** 

These guys are working full time until it's done. They are setting their sights high, and are grinding hard, even without funding.

**Comment by ericxtang** [comment]
Thanks for this suggestion @chrishobcroft.  We are impressed with Prysmatic Labs and would love to support the development of Eth2.0.  Even though the development of Eth2.0 is too big of a scope for Livepeer's grants, we have [made a donation](https://etherscan.io/tx/0x683cf2a74dc69dba5f0d9e783b11500eb3032602007e9ec4b679435b51bf456f) of 159LPT (roughly $100 based on 30-day avg price) to Prysmatic Labs as a sign of support.

**Comment by chrishobcroft** [comment]
Thanks @ericxtang 

cc @prestonvanloon

**Comment by criticaltv** [comment]
@videoDAC has [matched the donation made by Livepeer Grant Program](https://etherscan.io/tx/0xb0c4e54d9d75b95fa26c69c82819ed36eff40cb5dc8141920906283807161cda).

**Comment by prestonvanloon** [comment]
Awesome! Thanks so much! 

Are there instructions on how we can delegate our stake of LPT from the multisig? 
The website [here](https://explorer.livepeer.org/) seems to require a web3 wallet, but this wouldn't be feasible for us to use from the multisig. If someone could point me in the right directions for which transactions to send to stake, we'd be happy to participate. 

In any case, thank you so much for the generous grant funding. Your support means a lot and will help us achieve our goals to scale Ethereum.

**Comment by chrishobcroft** [comment]
@adamsoffer @ericxtang @dob @yondonfu are you able to help @prestonvanloon with instructions for approving and bonding LPT held in a multi-sig?

Preston - you will need to choose which Orchestrator to bond to - there's a list in [Livepeer's Protocol Explorer](https://explorer.livepeer.org/).

**Comment by prestonvanloon** [comment]
@chrishobcroft Thanks! We'll bond with the grants orchestrator once we receive instruction. https://explorer.livepeer.org/accounts/0x4f4758f7167b18e1f5b3c1a7575e3eb584894dbc/campaign

Thanks again!

**Comment by adamsoffer** [comment]
Hey @prestonvanloon - thanks for the incredible work you're doing on ETH 2.0 and for supporting the Livepeer Grants Program :) 

Here are instructions on how to delegate to an orchestrator using a multisig or hardware wallet via MyCrypto. Let me know if you have any questions! https://forum.livepeer.org/t/how-to-delegate-lpt-using-mycrypto-and-a-hardware-wallet-ledger-nano-s-trezor-etc/292

**Comment by prestonvanloon** [comment]
We're bonded!

https://etherscan.io/tx/0x6b04873a87b70dece6367802382f99afd0645153df06ee91ecdc5ac63cc43ff3

Thanks so much

>

**Comment by adamsoffer** [comment]
@prestonvanloon woohoo! 🎉
