### ISSUE TITLE
StreamaGenic: Grant Application

### ISSUE THREAD

**Issue by holyaustin** [livepeer/Grant-Program#121]
**Give a 3 sentence description for your proposal.**

StremaGenic is a decentralized video news publishing project with the aim of helping creators publish video news files and share them easily while owning their content and making money from it. This project intends to build a web3 news for everyone around the globe. Users that are Eye witness to events, captures them and publish on the new platform. News / Contents can also be streamed live through Livepeers streams. 

**Describe the problem you are solving.** 

The video media space growing at a fast pace but there is no truly decentralized video media where creators will actually own their work without serving as slaves to the centralized masters. This centralized masters (owners) make policies and take decisions that might not be favorable to creators.  The facts that web3 solves the issue of centralization, Decentralized video publishing was born to make available a platform where creators can become members of a DAO to vote for or against proposals that will keep the community healthy. 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

The facts that web3 solves the issue of centralization, Decentralized video publishing was born to make available a platform where creators can become members of a DAO to vote for or against proposals that will keep the community healthy. Using Livepeer.js to stream news on the fly without the barrier of centralization.  These videos are stored on IPFS which is  a decentralized storage provider through the livepeer protocol. News are curated and displayed to users on the frontend as video on demand (VOD). We are also proposing video NFTs. Creators are incentive as their community grow.

**Describe why you are the right team with the capability to build this.**
I am an IT professional with more than 10 years of experience as a software programmer and student tutor. With over 3+ experience in Blockchain technology. Skilled at operating in a wide range of platforms. Excellent written and oral communication skills; capable of explaining complex software issues in easy-to-understand terms. I have worked on some couple of hacks and projects and StreamaGenic happens to be one am currently working on. It was one of the Finalist project at the just concluded NEXT VIDEO BUILD hackathon by Encode club. I need to continue working on the project so it can be launched by next 3 months.
LinkedIn profile: https://www.linkedin.com/in/holyaustin/
Twitter Handle: https://twitter.com/holyaustin

**Describe the scope of the project including a 3 month timeline and milestones.** 
Phase 1.  Smart contract development, review and testing: :  ($6,400)
1. Develop the Profile Contract and optimized the VideoNFT contract.

2. Develop the streamagenic Contract factory

3. Develop tests for various scenarios of the contract

4. Review and Audit smart contracts for security bugs.

5. Deploy to Testnet, Review and then deploy Mainnet

Phase 2.  Creator / Stream Dashboard with Streaming Profile: ($4,800)
The streaming profile is social landing page for the creator.
1. Integrate Lens protocol with users stream profile

2. Ability to choose stream platform(either from OBS or from Browser).

3. Stream Live news from anywhere possible

4. Optional mint it as Video NFT.

Phase 3. VOD, Video NFT and Launch: ($4,600)
The streaming profile is social landing page for the creator.

1. Create page for creators to upload video on Demand

2. Create the VOD explore news page

3. Test that whole platform and Launch

**Please estimate hours spent on project based on the above and how much funding you will need.** 

Milestones for Phase 1  ($6,400)
Timeline #1 (Estimated Deadline (~1 week) first week of Feb, 2023)
Develop the Profile Contract and optimized the VideoNFT contract.
30 hours by $60 = $1800

Timeline #2 (Estimated Deadline (~1 week) second week of Feb, 2023)
Develop the streamagenic Contract factory
30 hours by $60 = $1800

Timeline #3 (Estimated Deadline (~1 week) third week of Feb, 2023)
Develop tests for various scenarios of the contract
30 hours by $60 = $1800

Timeline #4 (Estimated Deadline (~1 week) fourth week of Feb, 2023)
Review and Audit smart contracts for security bugs.
$1000

Timeline #5 (Estimated Deadline (~1 week) first week of Mar, 2023)
Deploy to Testnet, Review and then deploy Mainnet

Milestones for Phase 2  ($4,800)
Timeline #1 (Estimated Deadline (~1 week) second week of Mar, 2023)
Integrate Lens protocol with users stream profile
30 hours by $40 = $1200

Timeline #2 (Estimated Deadline (~1 weeks) third week of Mar, 2023)
Ability to choose stream platform(either from OBS or from Browser).
30 hours by $40 = $1200

Timeline #3 (Estimated Deadline (~1 weeks ) fourth week of Mar, 2023)
Stream Live news from anywhere possible
30 hours by $40 = $1200

Timeline #4 (Estimated Launch ~Early first week of Apr, 2023)
Optional mint it as Video NFT.
30 hours by $40 = $1200

Milestones for Phase 3  ($4,600)
Timeline #1 (Estimated Deadline (~1 week) second week of Apr, 2023)
Create page for creators to upload video on Demand
Implement the playback url from Livepeer on profile for creators
30 hours by $40 = $1200

Timeline #2 (Estimated Deadline (~2 weeks) third week of Apr, 2023)
Create the VOD explore news page
30 hours by $40 = $1200

Timeline #3 (Estimated Deadline (~4 weeks ) fourth week of Apr, 2023)
Finish alpha version development
Onboard small group of testers to provide application feedback
30 hours by $40 = $1200

Timeline #4 (Estimated Launch ~Early May, 2023)
Launch of Dapp
$1000

Requested funds - $15,800 USDC or LPT

Other things to note:
This is open source - Github Repo: https://github.com/holyaustin/STREAMAGENIC

**Comment by hansy** [comment]
Hi @holyaustin, thank you for your patience on this. At this time, we cannot offer you a grant for this project. Despite this decision, we encourage you to continue work on your project. If in the future you're able to showcase traction and growth, we're happy to revisit this grant and re-evaluate your goals with Livepeer!
