### ISSUE TITLE
Media Production Proposal

### ISSUE THREAD

**Issue by joeyfara** [livepeer/Grant-Program#122]
**Give a 3 sentence description for your proposal.**

**Describe the problem you are solving.** 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

**Describe why you are the right team with the capability to build this.**

**Describe the scope of the project including a 3 month timeline and milestones.** 

**Please estimate hours spent on project based on the above and how much funding you will need.** 

Hypercube is a professional video production company that specializes in creating high-quality, concise animated explainer videos. Our clients include well-established companies such as Binance, Kusama, Neo, Unlimited Network, and many others.

We would like to propose a meeting to discuss how we can assist you in creating an effective and impactful animated explainer video for the Livepeer developer ecosystem. Our solution will effectively communicate the benefits and value of Livepeer's technology, resulting in a positive impact on the ecosystem. As a team with a proven track record and expertise in creating animated explainer videos, we are confident in our ability to deliver a successful project.

The project will have a 1-3 month timeline, with milestones to be determined during the initial meeting. The scope of the project will include the following:

Research and understanding of the Livepeer developer ecosystem and its technology,

Concept development and script writing

Storyboarding and animation

Sound design and composition

Final video production and delivery

The project timeline will be divided into the following phases and can be done concurrently.

Phase 1: Research and Concept Development (1 month)
Phase 2: Script Writing and Storyboarding (1 month)
Phase 3: Animation and Sound Design (1 month)
Phase 4: Final Production and Delivery (1 month)
The number of hours spent on the project and funding needed will be determined during the initial meeting, based on the specific requirements and goals of the project. However, a rough estimate would be around 400 hours and $15,000-$30,000.

Please let us know a convenient time for us to schedule a call.

Best regards,

Hypercube Team.

**Comment by hansy** [comment]
Thanks for your interest in our grants program! At this time, however, we don't think your application is a good fit for what we're looking for. Should we need video services in the future, we'll be sure to revisit this!
