### ISSUE TITLE
Miami NFT Buildathon

### ISSUE THREAD

**Issue by MiamiNFTBuildathon** [livepeer/Grant-Program#123]
**Give a 3 sentence description for your proposal.**

We would like to propose to Livepeer to support Miami NFT Buildathon 2023 as a partner. Miami NFT Buildathon is the hackathon arm of the renowned Miami NFT Week conference, a three-day event that drew more than 5,000 attendees in 2022 for a weekend of speakers, workshops, panels, and creative installations focused on Web3, NFT, and blockchain technology. In partnership with Miami Dade College, this event offers three tracks for Livepeer community members to participate in: Technical, No-Code, & Creative / Design. 

**Describe the problem you are solving.** 

We believe the problem that we are solving comes in two folds: exposure and engagement. Every ecosystem in web3 operates on the basis of dedicated communities consistently building on behalf of tomorrow. At a Buildathon, Livepeer has the opportunity to engage with top talent, grow your community, and increase your level of brand recognition. 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

The objectives of a Livepeer partnership at Miami NFT Buildathon 2023 include:
1. Showcasing Livepeer to 5,000+ IRL conference & hackathon attendees and the 100,000-person student body of Miami Dade College, providing an opportunity to create awareness and educate the audience about the capabilities of the Ethereum network
2. Engaging with top talent and educating them about Livepeer technologies through prizes, challenges, and mentorship opportunities. The goal is to bring more talent to the Livepeer ecosystem and onboard the next generation of builders.
3. Expanding Livepeer's presence in South Florida, being a part of the exciting Miami NFT Week, and being a part of the innovative space in the crypto community.

By supporting Miami NFT Buildathon 2023 as a partner, Livepeer will have the opportunity to:
- Meet and engage with top talent and potential future Livepeer developers at Miami’s top blockchain university
- Host workshops or panels on Livepeer technology and its use cases, providing educational opportunities for participants
- Provide prizes and challenges for hackathon participants that focus on Livepeer technology, encouraging innovation and experimentation
- Leverage the event to increase brand awareness and visibility in the Miami area and surrounding South Florida region.
- Have a presence at the event through logo placement, promotional materials, and on-site branding

**Describe why you are the right team with the capability to build this.**

Our team consists of experienced event coordinators, planners, and builders who have the competency to execute an incredible hackathon-styled event. Furthermore, our team has roots in the crypto ecosystem that date back to the founding of Ethereum and years of professional experience working in web3.

**Describe the scope of the project including a 3 month timeline and milestones.** 

The event will be taking place from March 31st - April 2nd, 2023. Our scope until that date, during the event, and after the event, include the following:
1/27/2023 - 2/17/2023: Partnership sprint to secure 15 partners, Social Media Campaign - Twitter/Instagram; scheduled spaces and already prepared content, 5x speaker lock-in
2/18/2023 - 3/17/2023: Second Partnership sprint to secure 10 additional partners, Continued Social Media Campaign, Coordination with sponsors to lock "Node" objectives and begin placing hackers within nodes, 10x speaker lock-in, event booths placement planning, on-site media printing
3/18/2023 - 3/30/2023: Thirs partnership sprint to secure an additional 5 partners, Consinued social media campaign, finalization of "Node" and hacker placemenet, on-site event build, speaker session time event scheduling release, on-site media placemenet
3/31/2023 - 4/2/2023: See published schedule: https://build.miaminftweek.com/
Post Event: Partnership and hacker survey administration, final edits to event recordings and social media postings, partnership follow-ups / success story documentation.

**Please estimate hours spent on the project based on the above and how much funding you will need.** 
The team is currently spending 50-60 hours per week conducting partnership outreach and social media campaign efforts. This figure will increase to 60-75 hours during the final month of preparation, and each on-site day will be dedicated to the event (72hr/person). After the event, the team will spend a combined total of approximately 120 hours following-up with partners/hackers, create post-event social media content.

**Comment by hansy** [comment]
@MiamiNFTBuildathon Hi do you have more info on your sponsorship package (i.e. how much to sponsor)?
