### ISSUE TITLE
Classic Chords

### ISSUE THREAD

**Issue by Akash114** [livepeer/Grant-Program#126]
**Give a 3 sentence description for your proposal.**

Classic Chords is a community platform that enables artists to perform music and generate art. Local Artists, budding musicians, or established creators can utilize the platform to build their community.

The  NFTs minted by the artists are sold to collectors and fans alike. What's more, is that each NFT's generative art is completely unique and different from each others - so bonus on uniqueness, creativity, and rareness.

These NFTs are more valuable as they double as concert passes when an artist performs. Alternatively, one can lend/borrow NFTs to other users too.

Having live jam sessions and live concerts on Web3 encourages a decentralized community of music and NFT lovers.

**Describe the problem you are solving.** 

New artists have difficulty being found. The platform provides an opportunity. And considering how Web3 provides a decentral, user-owned, secure platform to interact, it's a great place to establish a community.
 
Additionally, with the expanding universe of NFTs and a lack of engagement from the music industry, it's an opportunity for Web2 artists to explore the world of Web3 and the assets within.

Classic Chords thus provides a platform for a community of artists and fans alike on Web3 to showcase their love while learning the world of Web3 through NFTs.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

Classic Chords proposes a community platform that combines music and NFTs by allowing artists to create their favourite music while simultaneously generating unique NFTs. 

These NFTs can be collected and traded by fans and NFT collectors alike. Further, these NFTs can double as tickets for live shows, jam sessions, or concerts on Livepeer. This increases engagement and welcomes both the music and NFT communities to meet up and make music, and NFTs!

**Describe why you are the right team with the capability to build this.**

Just similar to the dual nature of our NFTs, our Classic Chords team doubles up as developers and musicians. Our team is passionate and highly experienced in creating DApps. Smart Contract development and deployment is something most of them can do in their sleep!

With all sincerity, our team constantly strives to develop a Web3 that is better than yesterday. Harshil possesses vast knowledge in the ever-growing decentral web environment leading Akash and Rahul on the project. His understanding of the crypto market and NFTs brings a guide on creating a DApp for musicians and NFT collectors alike.

Akash wears two hats. Developer by day and pianist by night, he has 3+ years of experience in blockchain technology. He can write a smart contract as skillfully as Ludwig Beethoven writes his symphony. While understanding the complexity and necessity of smart contracts and Web3, his logical and technical skills ensure a secure decentral environment for both, users and artists.

Rahul is a full-stack developer with 5+ years of experience. His vast experience in creating websites and including functionalities gives us a platform with an amazing UI/UX. His logical skills, dedication, and time management have been his superpower to participate in and complete close to 20 projects. With various Web3 hackathons lighting his path, he understands the essence of making a web3 application for humans through technology.

Apart from this, **Classic Chords as a project was the finalist at Encode Club’s Next Video Build hackathon w/Livepeer. Thus, we have received recognition from the community as well as judges for our building skills and the idea.**

**Describe the scope of the project including a 3 month timeline and milestones.** 

The scope of Classic Chords includes the development of a web application that utilizes smart contract technology to mint NFTs in real-time while music is playing. Integration with existing music streaming services is also included.

The project timeline is 3 months, with the following milestones: 

**Milestone 1 (1st Feb 2023 - 25th Feb 2023)**

- Taking generative art to the next level by working on the backend algorithms and creating the art. 
- Supporting the MIDI keyboard and MIDI File formats on the application.
- UI for additional instruments

**Milestone 2 (26th Feb 2023 - 20th March 2023)**

- Giving additional audio-video editing features to creators - might require investing in appropriate tools/apps. 
- Auditing and deploying the smart contract on the main net.  

**Milestone 3 (21st March 2023 - 30th April 2023)**

- Collaborating with music artists to generate more exclusive art. 
- Find other options to incentivize the artist in a democratized way.

1. Auditing and deploying the smart contract on the main net. (Needs $5000 funding to complete by 15/02/2023)
2. Taking generative art to the next level by working on the backend algorithms creating the art. (Needs $2000 funding to complete by 20/03/2023)
3. Giving additional audio-video editing features to creators - might require investing in appropriate tools/apps. (Needs $3,000 funding to complete by 20/03/2023) 
4. Collaborating with music artists to generate more exclusive art. (Needs $2000 funding to complete by 30/04/2023) 
5. Supporting the MIDI keyboard and MIDI File formats on the application. (Needs $1000 funding to complete by 25/02/2023)
6. Find other options to incentivize the artist in a democratized way. (Needs $2000 funding to complete by 30/04/2023)

**Please estimate hours spent on project based on the above and how much funding you will need.** 

The estimated hours to be spent on the project are around 1200 hours total, assuming 3 members of the team will spend ~400 hours each.

The milestones mentioned above will be completed in the next 3 months with different team members working on different tasks as per their skills. 

The total budget required for this project is $15000. This will cover expenses such as auditing and deploying the smart contract on the main net, creation of a smoother process of generation, minting, and listing of NFTs, providing additional audio-video editing features to creators, and supporting the MIDI keyboard and MIDI File formats on the application.

**Comment by hansy** [comment]
Hi @Akash114! Thanks for applying for a grant as well as congrats on building this awesome project at Encode! For hackathon projects, we typically offer a microgrant of $2K to builders. But the scope for this type of grant is very simple: (1) showcase Livepeer in your project in clear way and (2) ship your project to production (so others can play with your app). The timeline for this type of grant is 1 month.

Let me know if you're interested in our microgrant!

**Comment by Akash114** [comment]
Dear Hans,
I am truly grateful for your support and recognition of the value of our project. The initial $2K microgrant offer is much appreciated, but as the project has grown beyond its initial hackathon scope, I believe that a slightly larger investment would have a significant impact on its success.
In addition to incorporating MIDI keyboard and file format support, we are eager to build a community of music artists who will create exclusive content for the platform. This will not only enrich the user experience but will also contribute to the growth and vitality of the Livepeer ecosystem. A strong and engaged community will help drive adoption and create more opportunities for collaboration and innovation within the platform.
For these reasons, I respectfully request that you consider increasing the microgrant amount to $5K. This additional funding will allow us to fully realize the potential of the project and make a meaningful impact on the Livepeer community.
Thank you for your time and consideration.
Best regards

**Comment by Akash114** [comment]
Dear Hans,


I am truly grateful for your support and recognition of the value of our
project. The initial $2K microgrant offer is much appreciated, but as the
project has grown beyond its initial hackathon scope, I believe that a
slightly larger investment would have a significant impact on its success.

In addition to incorporating MIDI keyboard and file format support, we are
eager to build a community of music artists who will create exclusive
content for the platform. This will not only enrich the user experience but
will also contribute to the growth and vitality of the Livepeer ecosystem.
A strong and engaged community will help drive adoption and create more
opportunities for collaboration and innovation within the platform.

For these reasons, I respectfully request that you consider increasing the
microgrant amount to $5K. This additional funding will allow us to fully
realize the potential of the project and make a meaningful impact on the
Livepeer community.


Thank you for your time and consideration.
Best regards

**Comment by hansy** [comment]
@Akash114 At this time we can only offer the $2k microgrant for your project given its infancy. That isn't to say that down the line you may be eligible for different grant, provided traction and growth are present. I know this may not cover all features you're looking to build, but as we tell all our grantees, the grants program should not be used as a substitution for actual funding. Our grants are more exploratory for the Livepeer ecosystem.

Let me know if you'd still like to pursue the microgrant!

**Comment by Akash114** [comment]
@hansy We understand what you are saying and appreciate the microgrant of $2K.
Please let me know the further steps to avail of this.
Once again, thanks a lot for trusting in our project and supporting us.

**Comment by hansy** [comment]
Hi @Akash114! We would love to move forward with your microgrant! Details below:

Amount: $2000
Timeline: 30 days for completion (official start/end dates to be added after grant acceptance)
Deliverable(s):

Clear and complete Livepeer integration (e.g. use of REST APIs or SDKs)
For this project, this might include the Livepeer's Video Minting SDK, the Livepeer Player, and/or any relevant API endpoints for creating, fetching video livestreams (these are just relevant examples; how you use Livepeer is, of course, at your discretion)

Deployed to production
The Livepeer team will want to share out a production-ready URL on our socials to solicit feedback and new users to help spur your growth. We want to see ambitious teams get off localhost and publicly launch something that can be viewed, tested, and shared.

Core video mechanic in place
We do not expect your application to be 100%, feature-complete, but anyone should be able to independently use your application to test out your core mechanic. The core mechanic in this case is a user can record themselves creating music in the browser, then let others mint the recording.

If you feel this scope works for your project, please confirm reply with the address of your arbitrum wallet. We'll pay 25% upfront ($500 in LPT), then after 30 days, we'll review your milestone and release the rest ($1500 in LPT) if everything looks good. The first payment should kickoff the official start of the grant.

Additionally, can you also link to your project's Github repo?

**Comment by Akash114** [comment]
Hello @hansy, thanks for trusting us and moving forward with the grant program. 

Here are the functionalities which will be completed next month(between the official start and end date). 

(1) Livepeer integration for Live video streaming and video NFT minting.
(2)Video NFT minting from music played by artists with generative art. 
(3)Production-ready URL.

Here is the **GitHub repo** for the project: https://github.com/RahulAtLamp/classic-chords.git

**Arbitrum wallet address**: 0x78D262EE17922bfB29476E25df20eEC17e252902

**Comment by hansy** [comment]
@Akash114 Upfront payment just went out (https://arbiscan.io/tx/0x031fba0a96e5f99933dd0c4a682eb82a9072d8945c1149cc08bfaf1c4e9ce7eb). The upfront payment is 20%, so upon completion of your milestone, we'll unlock the rest! We'll set your start and end dates to Feb. 24, 2023 to Mar. 24, 2023.

**Comment by Akash114** [comment]
@hansy, thanks for the approval and upfront payment. We will keep you updated about the progress and completion of milestones.

**Comment by Akash114** [comment]
Hello @hansy, As discussed earlier, we are ready with the production-ready URL with minting functionality and LivePeer integration with interactive chat and supper chat functionality. 

Here is the link to the website: https://classicchords.xyz/

Video demo of the mentioned feature: https://youtu.be/hyFMg8tyGww

Let us know your feedback.

**Comment by hansy** [comment]
Thanks @Akash114. Will take a look this week!

**Comment by Akash114** [comment]
Thanks, @hansy, I will wait for your response.

**Comment by hansy** [comment]
Hey @Akash114. Thanks for your patience. I spent some time with your app and was unable to reliably produce the same outcome as your video demo. For instance, I was unable to start a browser recording session and then mint that session as an NFT. Every time I clicked on the record button, I'd get prompted to give the browser permission, but nothing would actually happen after I accepted. Also, hitting the stop record button sometimes brought up the same record permissions as the record button. 

Is there a way to simplify the UI to make it more apparent on what the user should do? For the purposes of the demo, all that's really required is letting people record and mint videos.

**Comment by Akash114** [comment]
Hello @hansy, Thanks for your reply and feedback to improve the user experience. You can try the minting part, it has worked fine since the last update. 

We are trying to resolve these issues in the minting part to make it more user-friendly. 

(1) Recording the **key-press** in place of recording through mike so voice quality can be improved. 
(2) Video generation will happen in the backend to **resolve the memory consumption** on the client side. 
(3) Will **improve UI** by adding some components like a starting timer as well as a recording timer so the user will have an understanding of recording is starting. 

In the past week, we were working on the above points and recording notes as well as generating music part is done. There is a minor issue in combining the video with audio in the backend and are working on resolving it. 

I will update you once the above-mentioned issue gets resolved so that you can test the live site with these new features.
All the features mentioned earlier are working fine as of now.
Let me know if you have any additional feedback to improve the website.

**Comment by Akash114** [comment]
Hello @hansy, 
As discussed earlier we have completed the UI changes and fixed the minting of an NFT. Currently, we are using the microphone to record the sound and the video is being generated using react js. The sound quality may differ based on the system's microphone. 

You can follow the below steps to mint an NFT. 

(1) Click on the player page to see the Piano by default. You can switch between instruments. 
(2) Click on the start recording button to start your session, It will let you know when the recording is being started. 
(3) You can end your session by clicking on the stop recording button. 
(4) You can preview the recording and fill out the necessary details to mint the NFT. 
(5) After successfully minting you will be redirected to the profile page where you can review your NFT. 


Let me know your review.
While we continue developing this, specifically using keystrokes, generating the music, and integrating with random art, we request you release the second milestone and last milestone.

**Comment by Akash114** [comment]
Hello @hansy, thanks for the feedback. 

It is unusual to see minting gets fail. Can you provide the steps you follow or the transaction hash if possible so that I can check what can be a potential issue? 

I will check for the sound and let you update on it. 

Thanks again for your response.

**Comment by Akash114** [comment]
Hello @hansy, 

The issue you have mentioned with the sound is resolved and the minting of NFT is also working perfectly fine. 

Let me know if you have any feedback after reviewing the website.

**Comment by Akash114** [comment]
Hello @hansy 

I would like to share the minting flow so we can verify that the minting is working properly and can identify what issue you might be facing earlier. 

Here is the video demo link of how the minting flow is working:- https://clipchamp.com/watch/msi5bvOh1cK

Here is the link to the Generated Demo NFT:- https://classicchords.xyz/collection/2

Let me know if you have any further suggestions or queries regarding the process. 

Thank you.

**Comment by hansy** [comment]
Running into same issue of Firefox: https://www.loom.com/share/f0d87afe9bf047ba99311203694ce8c0. The minting is failing.

On chrome, mint doesn't play back: https://www.loom.com/share/79b72d0ea07741f49ba48ca8923af7dc

**Comment by Akash114** [comment]
Hello @hansy,

Drums & other instruments are our next phase of development. I have updated the drum component so the users will not be able to record it until we fix that. The current milestone approval will allow us to continue forward.

Please check the piano and other functionalities committed initially.

All feedback is appreciated.
Awaiting approval.

**Comment by hansy** [comment]
Hi Akash, I tested again (on Chrome with piano) and everything seems to be working. I can sign off on the milestone and will let you know when the payment is confirmed.

**Comment by hansy** [comment]
@Akash114 Here's a confirmation of the tx for finishing the milestone: https://arbiscan.io/tx/0x2b9d1da09314f3aca0d048c2bccbdaa7bac3c8eaf2c317d9d6fab84b9eeeb7bf. I hope you continue working on your project and/or with Livepeer! Stop by and say hello anytime in the Discord!
