### ISSUE TITLE
Pin Save Grant Proposal

### ISSUE THREAD

**Issue by Pfed-prog** [livepeer/Grant-Program#129]
**Give a 3 sentence description for your proposal.**

Pin Save is a decentralized video, image sharing and content aggregation platform where users can not only control the content but also the platform itself. Pin Save offers features such as decentralized storage, smart contracts, and creator ownership of intellectual property, which are not available on other platforms. We also provide incentives to share content and encourage user engagement, in particular, it is designed to be user friendly and accessible to users of all levels, making it easier for people to enter the web3 space.

Pin Save Live: https://evm.pinsave.app
Pin Save GitHub: https://github.com/dspytdao/PinSave-EVM

![Pin Save](https://user-images.githubusercontent.com/66903336/217177670-94c896bd-7e52-47ac-8cff-a7289f7f23be.png)

**Describe the problem you are solving.** 

Pin Save is solving the problem of content creators not having control over their content or the platform itself. With Pin Save, content creators can own their intellectual property and have control over how it is used and shared. Additionally, Pin Save provides users with a secure, resilient, and open platform for content sharing and discovery. This will help users to discover new content and connect with other users more easily.

![Pin Save (1)](https://user-images.githubusercontent.com/66903336/217178101-c77fff7d-ad26-4f3c-9838-743f30de5e86.png)

Monolithic online apps maintain control of user material, hindering the adoption of decentralized technologies.
A user might utilize OpenSea to publish the material, however there are considerable obstacles:
- Only a small percentage of collections make it to the homepage.
- Confidence and web3 expertise are required for the content publication procedure.
- Content feedback and engagement indicators are primarily reflected in price fluctuations.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 

To provide a solution to the outlined problem we consider four key elements:
![Pin Save (2)](https://user-images.githubusercontent.com/66903336/217181838-da7f2584-d84d-4dbe-9ab0-de6747a26a7a.png)

Currently we have implemented all four elements and are looking to scale up the engagement and user base. 
In particular, we envision Livepeer as the cornerstone for videos on Pin Save platform. Integrating Livepeer further would allow us to further decentralize the video content feed and potentially venture into the streaming.

**Describe why you are the right team with the capability to build this.**

We are a team of three blockchain developers. As a team we have completed Encode and FIlecoin accelerator, completed Filecoin grant and won multiple blockchain bounties from Algorand, Ceramic, ENS and other projects.

We have also recently received a message from Encode that Livepeer wanted to showcase Pin Save on its website.

Pavel Fedotov

Role: Full Stack Blockchain Engineer

LinkedIn: [https://www.linkedin.com/in/pavel-fedotov-pinsave/](https://www.linkedin.com/in/pavel-fedotov-pinsave/)

Twitter: https://twitter.com/pfedprog

GitHub: [Pfed-prog · GitHub](https://github.com/Pfed-prog/)

Grigore Gabriel Trifan

Role: Full Stack Blockchain Engineer

LinkedIn: [https://www.linkedin.com/in/grigore-trifan-666biyz/](https://www.linkedin.com/in/grigore-trifan-666biyz/)

Twitter: https://twitter.com/grigore_trifan

GitHub: [GregTrifan (Grigore-Gabriel Trifan) · GitHub](https://github.com/GregTrifan)

Seth McCullough

Role: Full Stack developer specializing in Typescript, React (NextJS), and NodeJS

Twitter: https://twitter.com/sethmckilla

GitHub: [Seth-McKilla (Seth) · GitHub](https://github.com/Seth-McKilla)

**Describe the scope of the project including a 3 month timeline and milestones.** 
**Please estimate hours spent on project based on the above and how much funding you will need.** 

Milestone 1 - Upgrading video infrastructure to directly upload with Livepeer (120 - 160 hours, 6000$)

- Integrating with Livepeer to upload videos with Livepeer API on `Upload` section of the platform
- Displaying videos created and liked on the `profile` page of each user
- Adding following creators functionality

Milestone 2 - Building features to increase engagement and provide frictionless user experience (160 - 200 hours, 8000$ )

- Pagination for comments and enhanced UI on each video post with an option to donate to creators
- Recommendation mechanism for videos
- Improved feed page to boost the engagement on the platform and faster on-boarding

Milestone 3 - User Engagement ( 100 hours of non dev work, 3000$ )

- 1,000 videos uploaded with Livepeer on Pin Save through on-boarding creators and strategic partnerships

**Comment by hansy** [comment]
Thanks for applying @Pfed-prog . We'll review your application and get back to you shortly!

**Comment by hansy** [comment]
Hey @Pfed-prog. Unfortunately at this time we cannot fund your project. But please continue to work on it and in the future, should you have some traction/updates, please feel free to apply again!
