### ISSUE TITLE
Automatic bond transfer using Livepeer proxy bonding manager 

### ISSUE THREAD

**Issue by Pon-node** [livepeer/Grant-Program#130]
**Give a 3 sentence description for your proposal.**
Create a script that would transfer staked LPT from main orchestrator to secure wallet using Livepeer Proxy Bonding Manager.Script always leaves 1 LPT staked to keep orchestrator in top 100. Script would eliminate manual calculation  and keep everything automated and secure.

**Describe the problem you are solving.** 
Moving staked LPT can be complicated and where is a possibility to make a mistake, more stake you got in your main orchestrator wallet more chances of someone trying to get in to your wallet and move your stake and eth fees away.
**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
Python script will move your staked LPT tokens to wallet of your choice automatically as soon as you hit threshold that you can set it to whatever you want leaving 1 LPT still bonded in orchestrator's wallet and not dropping out of top 100. Script will move bonded LPT as soon as the round becomes locked reducing your  chances to miss out on ETH rewards.
**Describe why you are the right team with the capability to build this.**
Python Script is already written and in testing stage with my main orchestrator.
**Describe the scope of the project including a 3 month timeline and milestones.** 
Find a way to secure private key in a script.
Modify script to automatically call eth fees and transfer them to wallet address of your selection.
**Please estimate hours spent on project based on the above and how much funding you will need.** 
20 hours, $100 an hour 
![image 1](https://user-images.githubusercontent.com/94224680/217231240-e5c8e1ca-c030-4837-8bec-c4d3eff63231.png)
![image](https://user-images.githubusercontent.com/94224680/217231532-c5116577-d4f2-4e68-ba20-4670c62501e5.png)

**Comment by hansy** [comment]
Hi @Pon-node! Thanks for applying for a grant! Have you by any chance gotten feedback from the orchestrator community about this script? If there's an existing discussion somewhere on this, let me know and I'll be happy to take a look.

**Comment by Pon-node** [comment]
Hi Hansy,
I've started a conversation on discrod.
https://discord.com/channels/423160867534929930/429350403272998913/1072951087725817927

**Comment by hansy** [comment]
@Pon-node Just catching up with this. Is the project already completed? I see the Github repo for the script: https://github.com/Pon-node/Lpt-bond-transfer. Are you looking for a retroactive grant?

**Comment by Pon-node** [comment]
Hi @hansy ,
Thanks for your reply. Yes script is live and some of livepeer user already using. I'll be working on it and adding couple more features in near future.
Retroactive grant would be great if that's ok with you ?

**Comment by Pon-node** [comment]
@hansy i know multiple grants has been submitted and approved after work has been completed and tested.

**Comment by Pon-node** [comment]
Hi @hansy , do we have any update?

**Comment by hansy** [comment]
@Pon-node Sorry for the delay on this. Are any of the orchestrators using your script? I'd be able to make a stronger case for a retroactive grant if there's usage from the orchestrator community.

**Comment by papabear99** [comment]
I've been using the script since Pon had the first version done.  It's great not having to manually transfer stake to my hardware wallet, no more stress worrying did I put everything in the right place and no more trying to time the transfer when a round is locked and missing out on rewards for my externally delegated wallet.  I know several other Orchs are use it as well.

**Comment by RyanC92** [comment]
I've been transferring my stake manually for months and doing it through the contract or the python script I had before was stressful. I've been using his script for about a month, I have my threshold a little high so it will run every few weeks but it takes the load off and since it does the conversion for me from Wei I don't have to worry about messing up! Big win in my opinion! Thanks pon!

**Comment by AuthorityNull** [comment]
This is an extremely useful script that adds hands-off security to our nodes. Moving stake away from our main orchestrator wallet is important for keeping targets off our backs and the script handles that for us. I love it 👌

**Comment by ad-astra-video** [comment]
Implemented this script and appreciate how it automates this task to secure the LPT my orchestrator node earns.  This enhances the livepeer orchestrator by allowing the orchestrator wallet to be a hot wallet that is used to operate the node and allows safe storage of LPT on a hardware wallet without manual contract interaction.  

@Pon-node helped me work through some python related install issues with and will be updated on the readme.  Issues were related to python web3 version incompatibilities.
