### ISSUE TITLE
BubbleStreamr

### ISSUE THREAD

**Issue by SabeloMkhwanzi** [livepeer/Grant-Program#131]
**Give a 3 sentence description for your proposal.**
BubbleStreamr is a decentralized live streaming social content platform. Promoting real-time engagement with the audience, the platform allows you to publish and stream your content.

**Describe the problem you are solving.** 
With the advancement of technology and the widespread adoption of online activities, skyrocketing Live streaming and video content creation have become essential features of communication with a significant number of individuals. With this adoption, storage could be an issue, since video content is stored on centralized servers; hence, creators and users eventually have no control over what happens to their content. Uploading a large amount of content in order to compete with the algorithm for a specific rank and receive rewards or payments for your content can be stressful and draining. Viewers not only enjoy the consumption of the content but also aspire to engage with it and give back to the creators.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
By understanding the needs and views of content creators, we aim to solve these issues directly by creating a better environment for users through decentralization, open-source development, and transparent terms and conditions. Using Ethereum-based decentralized administrations to improve online streaming, video content creation, and content monetization for creators in countless ways We encourage decentralized live video streaming by utilizing and integrating the Livepeer protocol. giving our users the best open-source development in a decentralized manner. Since the advent of Live Streaming, video content creation has become an essential component of communication with a strategic advantage in reaching a large number of people, with the potential to increase usage and awareness of the LivePeer protocol through streaming, video upload, monetization, and decentralized social media communication.

**Describe why you are the right team with the capability to build this.**
I'm a **Software developer** who has been working full-time in the web3 space since 2021. Since then, I have had the privilege of working on some blockchain projects, including web3 open projects and hackathons from [@gitcoin](https://twitter.com/gitcoin?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor), [@ethGlobal](https://twitter.com/ETHGlobal?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor), [@encodeclube](https://twitter.com/encodeclub?ref_src=twsrc%5Egoogle%7Ctwcamp%5Eserp%7Ctwgr%5Eauthor).

- [**GitHub**](https://github.com/SabeloMkhwanzi)
- [**Twitter**](https://twitter.com/SabeloMkhwanaz)
- [**LinkedIn**](https://www.linkedin.com/in/sabelo-mkhwanazi-54ba431b1/)

**Describe the scope of the project including a 3 month timeline and milestones.** 

This project is broken down into 3 phases. The first phase was pre-built from the Next Video Build Hackathon and is intended for innovations and UI improvements. Ideally, the purpose of the project is to focus on building a user-friendly Dapp that allows social communication to flow smoothly as well as onboarding users from traditional use cases to decentralized platforms with ease and awareness of the Livepeer Protocol.

#### Milestones #1 Live Streaming Section Pages

- Create a user profile for the content creator to create a stream channel, then integrate Livepeer to create a stream, connect to your favorite streaming platform, e.g. OBS (required wallet connect).
- View ongoing streams or archived streams stored on IPFS.
- Live stream page to audience from hosted live stream integrating Livepeer playerback URLs.
- Ability to mint-stream it as NFT.
- Integrating decentralized Chat SDK for audience engagement
- Integrating Push notifications for user awareness, eg. live streaming updates
- Implement a smart contract or payment SDK for tipping, implement following, and reactions to the content, e.g. "like" or "love."

#### Milestones #2 Video Section Pages (video on-demand)

- Create a user profile for content creator to create a video channel, then integrating Livepeer to video player back, (required wallet connect)
- Archived page for videos stored on IPFS
- integrating Livepeer to video player back to view publish videos
- Integrating Push notifications for user awareness, e.g. Recent uploads and updates
- Implement a smart contract or payment SDK for tipping, implement following, and reactions to the content, e.g. "like" or "love."

#### Milestones #1 BubbleMeetings Pages (This section of the project has to do with Livestreams Engagements eg. Meetings, Tutoring, Podcasting….)

- Huddle01 integration with Livepeer SDK for Live Streams
- Integrating Push notifications for user awareness of the upcoming meeting and updates.
- Integrating SuperFluid for money streams, especially for subscription tutoring,

#### Milestones #1 BubblePremium Pages (This section of the project has to do with User Monetization eg. Subscribed offers, once-payments)

- Create a user profile for content creator to create a stream or video channel and the ability to set payment method using Unlock Protocol, Superfluid
- Integrating Livepeer to create a stream, connecting to your favorite streaming platform, e.g. OBS
- Integrating Livepeer for video playback, for videos uploaded for Premium offers
- Integrating Push notifications for user awareness of recent uploads and upcoming streams
- Integrating Stream Fluid for money streams, especially for subscription tutoring

#### Milestones #2 Launching & Marketing

- Establish twitter community
- Acquire Livepeer promotion support

**Please estimate hours spent on project based on the above and how much funding you will need.** 
- Phases 1-3 of the project are expected to take 920 hours to complete.
- BubbleStreamr is looking to obtain grant funding of $20,000 USDC (2136 LPT) separated into 3 phases.
- Open-source project: **https://github.com/SabeloMkhwanzi/bubbleStreamr**
- [**Live Demo**](https://bubble-streamr.vercel.app)
- [**Project Mockup**](https://github.com/SabeloMkhwanzi/bubbleStreamr/blob/main/BubbleStreamr%20Mockup.pdf)
- [**BubbleStreamr  Flowchart**](https://github.com/livepeer/Grant-Program/files/10722196/BubbleStreamr.-.Flowchart.pdf)
- [**Screenshot** ](https://github.com/SabeloMkhwanzi/bubbleStreamr/blob/main/BubbleSteamr-hp1.png)

**Comment by hansy** [comment]
Hey @SabeloMkhwanzi, thanks for applying to our grant program. Normally for hackathon projects we offer a microgrant, to which we award up to $2k. Microgrants are small in scope, and should take no more than 1 month for completion. For hackathon projects, usually the scope is to demonstrate a clear and complete Livepeer integration while having the app pushed to production for others to play with. It seems you've more or less completed those.

The next tier of grants is a Video Disruptors grant, which we award up to $15k. However, before offering the grant we typically want to see traction and growth in your app. I'm curious to know what your plans are for BubbleStreamr and if you have any new numbers/metrics to share since building?

**Comment by SabeloMkhwanzi** [comment]
Hi **@hansy**, Thank you very much for your response.

The plans for BubbleStreamr are relatively straightforward: BubbleStreamr is a social platform for live streaming. With the goal of boosting real-time engagement and allowing content to be published as well as live streaming with monetization options.
My ambitions for BubbleStreamr are to continue developing a decentralized application that will use Livepeer's infrastructure as well as other web3 technology capabilities to scale.
1. Continue to expand on the existing project by adding new features and enhancing it.
2. Launch the product and collect feedback/metrics to assess the project's success.
3. Promote BubbleStreamr to the community to encourage acceptance and growth.
4. To engage with Livepeer to learn better way to take this project to the next level.

Since the project was created during the hackathon, there are no numbers or metrics to provide at this time.

**Comment by hansy** [comment]
Great to hear! The grants committee will be reviewing any outstanding applications at the end of March; we should have a funding decision for you around that time.

**Comment by SabeloMkhwanzi** [comment]
Thank you @hansy, that's sounds good, and for your response really appreciated it.

**Comment by hansy** [comment]
Hi @SabeloMkhwanzi. Apologies for the delay on this. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.
