### ISSUE TITLE
Streamlivr

### ISSUE THREAD

**Issue by streamlivr** [livepeer/Grant-Program#133]
Streamlivr.com is a video livestream dapp for content creators and everyone that loves to stream and create content of any kind, perform for their fans and earn crypto rewards. Streamlivr token is the native cryptocurrency of the Streamlivr platform and ecosystem. 

github.com/streamlivr 

Why we buidl is because creators aren’t compensated properly for their livestream which accounts for 30% of entire internet usage. Streamlivr hopes to solve that problem through event & video NFTs and most importantly the Livestream2Earn model. 

We are buidling a platform for creators to create livestream content and earn in crypto from streams and minting as video NFTs, connecting creators and fans. This will have a high network effect on the Livepeer network and expose the ecosystem to a bubbling Nigerian (African) mainstream entertainment industry through community events/concerts and bootcamps. 

The Streamlivr team is made up of passionate persons: seasoned entertainment business executives, technical yet innovative youngsters and Gen-Z marketing experts. 

Streamlivr as a livestream product spans across the Music, Gaming and Social media (broadcast) sectors. 
Roadmap:

Road Map
- Q4 2022 : Website Launch, Token Launch on Testnet 

- Q1 2023 : Community Events & Partnerships.

- Q2 2023 : MVP & Alpha Test launch (Streamlivr V1.0)

- Q3 2023 : Beta App V2.0 Update 

- Q4 2023 : Main net Token Launch, Seed Round,Public sale.

A detailed 3 month milestone:

Milestone 1 - 4 Weeks:
- Streamlivr x Livepeer media announcement 
- Test & Launch Alpha V1

Milestone 2 - 5 weeks
Host music concert at The University of Portharcourt to onboard 500 creators and 2000 users (fans). 

Milestone 3 - 5 Weeks
Launch Alpha-bolt V2 with integrated socials and chat features. 

14week Milestone = 98 days (2,352 hours)
Our team will be effectively working for 1,000 hours (an average of 5days per week, 13 hours per day). 
 Furthermore we are requesting a grant size of $30,000 to effectively build, launch product and execute marketing/event plans. Thank you.

**Comment by hansy** [comment]
Thanks for applying @streamlivr. We'll review your application and get back to you shortly!

**Comment by hansy** [comment]
Hi @streamlivr. Apologies for the delay on this. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.
