### ISSUE TITLE
[Builder Grant]: Pink Paper, Decentralized Publishing Platform

### ISSUE THREAD

**Issue by pinkpaper** [livepeer/Grant-Program#134]
### What is your project, and what problem does it solve?

**Introduction:** 
Pink Paper is a decentralized and permissionless publishing platform for individuals and communities worldwide to express their opinions and share information with the rest of their communities. Users can come and publish blogs and other forms of content on the platform and showcase it to the world. 

At the same time, one can raise funds for their endeavors on the platform allowing donating to world-changing technologies. Pink Paper will provide a decentralized and censorship-free platform for everyone to use and express their views about different topics.

**Problem Statement:**

There are increased attacks from big tech worldwide on free speech. Big Tech platforms are increasingly banning specific individuals and communities from their platforms. In these testing times for free speech, Pink Paper aspires to protect the ethos of free speech and freedom for communities who want to raise their voice.

### Link to public GitHub repo (if applicable)

https://github.com/pinkpaper/pink-paper-frontend

### Link to demo website (if applicable)

https://pinkpaper.xyz/

### How is Livepeer used for this project?

Livepeer will be used for video streaming for the video part of the articles published on the Pink Paper platform. With the help of Livepeer, creators, and publishers can add a video to their articles or reports. 

### How will you improve your project with this grant? What steps will you take to meet this objective?

Currently, publishers and creators can add text and graphics to their blogs and articles on the platform. With the help of this grant, we will provide them the option of adding the video as well which will surely enhance the overall appeal of the post. We will be integrating Livepeer into the platform to provide the video add the option to the publishers and creators. 

### Was this project started at a hackathon or another web3 event? Which one?

N/A

### What is the project’s expected deliverable at the conclusion of the grant time period?

Video can be added to the blogs/articles and can be easily streamed by the end users on the Pink Paper platform at the conclusion of the grant. 

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Publishers and creators can easily add videos to their posts and end users and play the video content will be the core mechanic as part of the deliverable. 

### How will this deliverable benefit the Livepeer ecosystem?

With increased censorship by big tech decentralized, censorship-free platforms will be in high demand. We want to cater to this growing demand and it will directly push the growth of the Livepeer ecosystem.

By offering a censorship-free decentralized publishing platform we are providing the opportunity to everyone and anyone to freely express their opinions and views.

**Comment by hansy** [comment]
Thanks for applying @pinkpaper. We'll review your application and get back to you shortly!

**Comment by pinkpaper** [comment]
Thank you @hansy , please let me know if you require any particular information or details regarding the project.

**Comment by hansy** [comment]
Hi @pinkpaper. Apologies for the delay on this. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.
