### ISSUE TITLE
[Video Disruptors Grant]: Livepeer plugin for WordPress Integration

### ISSUE THREAD

**Issue by fqclean** [livepeer/Grant-Program#135]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

 

Auction Website to use Crypto Currency to pay for Legal Fees.
BACKGROUND OF THE INVENTION
From the time humans have come together as a social group and formed legal institutions Law men have been needed by Lay men to interpret, and assist when needed to obtain justice from a judge. Present day has an ULTRA subset of law men political, personal injury, social security, tax law, and various other focal points of law.
 The specialties within the legal field have created a need for class, or subsets in the field of law to which it is not black, or white. Often times it results in the Color GREEN, meaning the lawyer or firm can obtain the proper defense needed when a price point premium is met; otherwise you may get a Bar approved Lawyer but his defense in a certain subset could be weak. The only way for him to enhance his skills is practice; which could result in a client’s expense, and with court imposed penalties. Today we have a NEED to acquire proper representation within the subset of legal expertise for not doing so could absolutely stain a individuals record causing damage to their career path, vacation destinations, and even places that allow residence categorized by public records. Having proper representation can influence the rest of a person’s life in many ways.

Problem Solved:
The Problem of Legal Fees being expensive has led to underrepresented, lack of representation and judicial injustice. 
The issues with the current advances are the lack of publicity, only major cases are commented on resulting in hundreds or thousands who have no voice by a specialist. My invention and intervention for this advance in the legal system is media to promote transparency, uniformity and growth of legal experts as eBay grew merchants online from physical locations.

Essentially as a venue to gain real support to overcome life altering accusations, by evidence of video or documentation, even testimonial users can then acquire support from social media and have assistance from others needed to hire the proper law representation. 

Lawyers who specialize in a particular case would be able to shop reviewing evidence, and evaluate case specifics to deliver the poorer less advantaged person the value of freedom to choose. Additionally by legal education, obtaining public opinion, from a supportive community they can close the gap on representation for an accused person regarding money, race or class value in courts because the Lawyer selected is the best for the subset and monetarily matched.

### Link to demo website (if applicable)

http://wp.bethejury.org/2023/02/18/application-for-integration-of-livepeer-grant-for-plugin/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

My Platform will engage users to use their livepeer account, essentially the personal plan will be what most start out as using and very quickly to upgrade to the paid business plan. My platform will educate users as to why having their own account is important, while Google and Other companies have their own free technology, they have terms and conditions which limit the use. The only use that should be limited with any video shared content is that which is illegal for reasons of criminal activity. The freedom of information should be in the hands of the people and that is my mission. The platform will integrate with Livepeer by utilizing Bitpay or another exchange to let users store Tokens for their personal utility on the platform as uses increase. I am educating users by allowing my Media Company to let the users have their own channel and monetize it with LPT. Essentially we will allow users to contribute for causes converting LTP this will promote and distribute the cause for justice. As a foundational Partner Livepeer will gain notoriety, and popularity which in the next 5 years will be they only credible way of telling a bilateral picture which often times is lacking in existing cases presented in media.

### Please describe in details what your final deliverable for this project will be.

The livepeer template I am seeking to have developed in a wordpress plugin for my platform will integrate the Users livepeer studio accounts with the post submissions on my site. The "WHY" is answered in ownership if you are not hosting and paying for a membership you don't truly own the content. Social media and other platforms can censor and block the playing of content or remove it all together. Livepeer will allow subscribers to share the Truth from their perspective, and that is worth the price paid in the subscription. With the exciting feature integrated into my website I will be able to share the reality that most people don't know about, and it is absolutely for an awesome cause. The buying of Truth and not the Selling of it. 

### Please break up your development work into a clear set of milestones

My Project, is only needing 1 milestone for completion 

The template creation plugin will need to be coded and written for wordpress. 

The features to integrate with livepeer studio will be created and tested 

Once the plugin has been created with the wallet information and the studio confirmed  

The expected time for completion of this project is 6 weeks 

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

The funds will be used to 

1. Develop the Wordpress plugin Integration with LIvepeer studio

2. Set up business office for real in person studio  according to the theme of our website

3. Complete the patenting for the existing provisional patent of this platform

4. Cost for additional patents and business processes as expenses require

### Specify your team's long-term plans to maintain this software and upgrade it over time

The progression of the template or website will need to be maintained, as the website grows and users are added more changes and updates and developments will be implemented. The purpose of composing this plugin currently, is to integrate it with a working solution, since wordpress is the most popular, changes should happen when a correction or error is observed. Additional technical advancement will be the primary focus of daily operations once everything is functioning according to specifications. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

I have as a process engineer hired several teams to achieve my vision. I have an existing team for this project, and am looking for the completion to get started. I know I am the right one to bring it about because it's my vision!

1. I have applied for the provisional patent
2. It is my world changing solution that only I know how deep it will impact the world
3. My specifications will result in livepeer being a household name aside my brand

My developers usually come from a marketplace platform which I am able to explain my requirements and then confirm once the job is completed. I am the right persons for this grant because I have developed 3 apps, and own several domains in the way of experience, yet this project will CATAPULT  LIVEPEER and its coin value. 

### How did you learn about the Livepeer Grants Program?

I have knew about the program for a while but Livepeer support was able to guide me how to make my submission to which I am grateful to Shih-Yu from technical support and Ben. 

### Was this project started at a hackathon or another web3 event? Which one?

 no this is a project of mines personally

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

http://wp.bethejury.org/

Is my website that I am working on for users to be able to have their livepeer studio attached video to be evaluated. I will require some users to have their own livepeer studio account which will result in profitablity for livepeer. The over all project is to champion Justice, unlike other media companies and social media my website will be RESOLUTION media. It will put the power in users hands to gain the justice and notoriety they deserve. Finally they will have a voice, thanks to livepeer allowing them to OWN their media,"Truth"....

**Comment by hansy** [comment]
Thanks for applying @fqclean. We'll review your application and get back to you shortly!

**Comment by fqclean** [comment]
Thanks for your review I'm super excited about this Livepeer integration
with my patent pending platform.

Dell

**Comment by fqclean** [comment]
Hans I going to need a banner for my website advertising livepeer studio is
there one already approved by Livepeer? I like the theme of owning your
content so if one is available for that purpose it would be great.

**Comment by fqclean** [comment]
Hans

I am following up for the status of the grant program because I do need it
for my project to be a success,  is thier a new update?

My web hosting is due and other business expenses need to be handled I
would Love to champion LPT for my platform.

**Comment by hansy** [comment]
Hi @fqclean. Apologies for the delay on this. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.

**Comment by fqclean** [comment]
Thank you for the update Hans I understand the climate for crypto is tense
at present but this too shall pass.

Dell

**Comment by fqclean** [comment]
I must say however with people subscribing to Livepeer studio for ie:
testimony in support of legal issues it would become a house hold name. I
think reconsidering might be bilaterally productive!

**Comment by fqclean** [comment]
Hans, to
I am writing this email to inquire of submitting another request for my
development of livepeer into my already existing app. Previously my word
press project was turned down but this new request, is more exciting should
I submit it through the grant again?
