### ISSUE TITLE
[Video Disruptors Grant]: Niftgen: Hub for video creators to better monetize their content

### ISSUE THREAD

**Issue by Niftgen** [livepeer/Grant-Program#136]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

**Problem:** 
There are over 60 million video creators on YouTube/Twitch. 98% of them earn less than $12,000/year. The reason they struggle to monetize is that they have low engagement rates ( Avg <2%). The reason engagement rates are low is that users are not rewarded for their engagement. 

**Solution:**
Users will be rewarded for their engagement with utility tokens. These tokens will grant access to features. One of these features is access to a creator live stream. Users will use the token to vote for what content a creator should produce during the live stream. Users will also be rewarded tokens for commenting during the live stream. The creator can also reward a user who gave the best comment during the live stream. The goal is for the creator and fans to form a deeper connection with each other. 

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Niftgen can be a proven use case that decentralized video streaming web 3 applications can be built using Livepeer. It will show that there are innovative ways for creators to better connect with their fans. This will help creators better monetize their content. 

The risk of not getting this right is that creators will struggle to monetize. Creators are not going to use web 3 platforms unless they can provide more value than web 2 platforms. Especially on he monetization aspect. 

The biggest challenge is to keep the hosting costs low. The reason why there aren't many web 2 streaming platforms is that hosting costs are too expensive. Keeping costs low compared to our competitors will create a competitive advantage. 

### Please describe in details what your final deliverable for this project will be.

A creator will be able to host a live stream. Users will need to pay a certain amount of engagement tokens in order to access it. When a user access the live stream, they will be able to comment and earn tokens for it. 

The creator will create polls during the stream where users can vote on what content the creator should be producing in real-time. 

### Please break up your development work into a clear set of milestones

**Milestone 1 - Creator can start a live stream.** 
- A creator can go to his profile and start a live stream. 
- The objective is to make sure that the live stream works. 
- There will be two developers working on this, frontend and backend. 
- Time to complete: 2 week
- Funding amount: $4,000

**Milestone 2 - Users paying tokens to join the live stream** 
- Users will need to pay tokens to access the live stream. 
- The objective is to determine if users can quickly join and watch the stream after paying the engagement tokens. 
- There will be two developers working on it: frontend and intelligent contract
- Time to complete: 1 week 
- Funding amount: $2,000

**Milestone 3 - Creator can schedule a live stream**
- A creator should be able to schedule when he wants his live stream to start in the future. 
- The objective is to make it simple for the creator to schedule a live stream
- 2 developers will work on this: frontend and backend
- Time to complete: 1 week 
- Funding amount: $2,000

**Milestone 4 - Sending notifications to subscribers**
- When a creator starts a live stream, a notification will be sent to all their subscribers that the live stream has begun. If a creator schedules a live stream to occur in the future, a notification will be sent out to their subscribers about the event. 
- The objective is for subscribers to notify subscribers when a live stream starts or when a live stream will start. 
- 2 developers will work on this: frontend and backend
- Time to complete: 1 week 
- Funding amount: $2,000

**Milestone 5 - implementing chat for live stream**. 
- Users can use the chat feature during the live stream. They will be rewarded engagement tokens for commenting. 
- The objective is for users to communicate during the live stream 
- 3 developers will work on this: frontend, backend, and smart contract 
- Time to complete: 1 week 
- Funding amount: $2,000

**Milestone 6 - Creators can do polls**
- This is where creators can do polls during the live stream, where users can vote on what content the creator should produce in real-time
- The objective is for fans to be able to vote on what content creators should produce in real time. 
- 3 developers will work on this: frontend, backend, and smart contract 
- Time to complete: 1 week 
- Funding amount: $2,000

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

**Total Budget:** $14,000 
The funds will be spent to pay our 3 developers to implement the milestones. 

### Specify your team's long-term plans to maintain this software and upgrade it over time

More features will be added over time to improve live-stream. Therefore it will always need to be upgraded. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

**Christian Casini: Co-Founder**
- Bio: Christian is a serial entrepreneur. His first endeavor was working with his parents in managing their high-end luxury rentals. He then went on to become a real estate specialist in Miami. His tenacious persistence, ability to connect with others, and passion for blockchain technology, are what motivated him to start a blockchain startup. He strongly believes that blockchain technology is going to improve all the current systems of the world for everyone. 
- LinkedIn:https://www.linkedin.com/in/christiancasini

**Philip Grichener: Co-Founder**
- Bio: Philip has a background in data analytics, which he utilized in his work as both a real estate agent and as a freelance personal tutor. He first got interested in blockchain technology in 2014 after reading the Bitcoin whitepaper. His interest took off in 2018 when he was introduced to DeFi (decentralized finance) by a relative. His strong belief in blockchain technology disrupting humanity’s current legacy systems inspired him to create a blockchain startup together with this team.
- [Philip Grichener | LinkedIn](https://www.linkedin.com/in/philip-grichener-b53074226/)

**Nikita Butenko: Full Stack and Lead Front-End Developer** 
- Bio: Nikita started his web-development career in 2000, graduated as a Computer Networks Engineer a few years later, and continued as a full-time web and dev-ops engineer through many startups, established businesses, and even government agencies such as Arbor Networks, Woolworths, and Rocket Internet. Is an author and contributor to multiple open-source projects, a speaker, and acts as a mentor to young developers. 
- LinkedIn:[ https://linkedin.com/in/nbutenko](https://linkedin.com/in/nbutenko)
- GitHub: https://github.com/nkbt

**Etienne van Tonder: Full Stack + Lead Back-End Developer** 
- Bio: Etienne has been a full-stack software developer since finishing his Computing degree in 1985, initially working for Telecom and then Cadbury Schweppes before becoming an independent contractor in 1994. Since then he has worked on many projects from small to very large-scale systems in a variety of industries and for clients including the Australian Broadcasting Corporation, Movember, Eastlink, Moreland City Council, and many more. He has a wide range of experience in many technologies, computing languages, and database management systems.
- Linkedin: https://www.linkedin.com/in/etienne-van-tonder-33a29811 

**Andy Chipperfield: Product Designer**
- Bio: Andy has been designing experiences and interfaces since leaving University in 2001. Specializing in working with early-stage start-ups since 2013, Andy has worked with clients such as Plated, IGN, and Spotify, and has more recently been Lead designer at Tiltify and Snr Product Designer at Imperva.
- Personal Website: https://andychip.com/

**Matias Torres Diaz: Blockchain and Front-end Developer**
- Bio: Matias is a blockchain enthusiast. Upon graduation, he began working with KNOBS (2019) as a blockchain developer. Matias became a freelancer after a few years to work on more different projects and ideas, helping people develop and execute their ideas. He has worked in various blockchain ecosystems such as Ethereum, Solana, NEAR, Algorand, and BNB Chain.
- Linkedin: https://www.linkedin.com/in/matiastorresdiaz 
- GitHub: https://github.com/Tias84

### How did you learn about the Livepeer Grants Program?

From the Livepeer Discord server 

### Was this project started at a hackathon or another web3 event? Which one?

No,

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

We will launch the first version of Niftgen on the Mainnet on March 1st. We plan to start working on Livestream integration on March 15.

**Comment by hansy** [comment]
Thanks for applying @Niftgen. We'll review your application and get back to you shortly!

**Comment by Niftgen** [comment]
Thank you @hansy !
Looking fiorward to your feedback

**Comment by hansy** [comment]
Hi @Niftgen. Apologies for the delay on this. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.
