### ISSUE TITLE
[Video Disruptors Grant]: Vibehut.io 

### ISSUE THREAD

**Issue by 1dolinski** [livepeer/Grant-Program#137]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

[Vibehut](http://vibehut.io/) is the first social video platform that cross-connects social Web2 platforms and Web3 blockchains. In one-click you can instantly match with leading influencers, creators and builders, based on follower count, coin price or NFT ownership. Vibehut allows you to login with your popular social or crypto accounts such as DeSo, Facebook, LinkedIn, Twitter and MetaMask. Vibehut is the best way to instantly match with like-minded people. An epic new connection is 1-click away.

### Link to demo website (if applicable)

https://www.vibehut.io

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Calls on Vibehut have a 16 person max at the moment. Calls can be singular or broken out in many breakout calls. Many prominent users of Vibehut have requested a "presentation mode" where their calls could reach a wider audience. Streaming from Twilio (our current provider) -> LivePeer could be a great match.

### Please describe in details what your final deliverable for this project will be.

The deliverable would be simple -- to broadcast our calls using Livepeer to an audience of hundreds -> tens of thousands of people. We work with many prominent NFT collections and will continue to grow in the Web2 and Web3 space.

### Please break up your development work into a clear set of milestones

**Milestones**

Setup Livepeer API
Connect with Twilio stream, programatically setup each calls to have the option of turning on Presentation Mode.
Have individual pages for people to watch on or stream to other distribution channels. 

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

**Buget is 15k USD**

10k spent on development resources
5k spent on marketing of our setup with high profile clients with huge reach.

### Specify your team's long-term plans to maintain this software and upgrade it over time

We're a funded startup and have experience raising several rounds. Our goal is become a globally recognized leader in video-first online social networking. We will upgrade and support the platform in all ways necessary to reach our milestone.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Chris Dolinski, the founder of Vibehut, has experience building highly polished and highly performant technology startups. The most notable is Clutch.ca which is the Canadian version of Carvana. 

### How did you learn about the Livepeer Grants Program?

I was recommended to look into it by one of the users on Vibehut.io

### Was this project started at a hackathon or another web3 event? Which one?

We originally were built for the DeSo ecosystem and have since grown to support all of Web2. 

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

Our video calls may be public, password protected, and token gated. 

Importantly, I'm more than happy to talk about this, last year we hosted thousands of calls on Vibehut.io. We'd like more people to be able to listen in. 

<img width="440" alt="image" src="https://user-images.githubusercontent.com/1243216/220703524-f247b23a-77bc-4e48-981b-24dd09ec1324.png">

**Comment by hansy** [comment]
Thanks for applying @1dolinski. We'll review your application and get back to you shortly!

**Comment by hansy** [comment]
Hey @1dolinski. So your application seems like a straightforward Livepeer integration. For these, we usually offer a microgrant of $2k. It doesn't take much time at all to integrate with Livepeer.

That being said, I'm curious what your video calls entail. If you're doing a Twitter Spaces-like experience where a bunch of people can listen/watch speakers and occasionally join them if invited, we don't quite support that yet. If however the broadcast is a typically livestream (one to many broadcast), that's certainly within our wheelhouse.

Let us know!
