### ISSUE TITLE
[Builder Grant]: Videso 2.0 Grant Application

### ISSUE THREAD

**Issue by jsonpreet** [livepeer/Grant-Program#139]
### What is your project, and what problem does it solve?

Videso is a decentralized video-sharing social media platform built on top of the DeSo blockchain. This means that Videso is a platform that is not controlled by any central authority, allowing users to have full control over their content and data.

**Describe the problem you are solving.**

Web 2 Video Sharing Platforms, provide a good service to content creators but creators have a lot of problems like Censorship, Monetization, and more. I read many posts on DeSo that creators looking for a web3 video sharing platform where they can monetize their content without any policy, or censorship issues.

### Link to public GitHub repo (if applicable)

https://github.com/jsonpreet/ViDeso-2.0

### Link to demo website (if applicable)

https://videso.xyz/

### How is Livepeer used for this project?

We Used LivePeer VOD to Store Videos on LivePeer Studio and Used a LivePeer Player. We also implemented LivePeer Live Streams.
On DeSo Creators have a limit to uploading max 250 MB video. But Videso is providing an opportunity for upload max 1GB Video.

### How will you improve your project with this grant? What steps will you take to meet this objective?

Do Marketing for Creators. Most creators have problems with Web2 Video Sharing Platforms. Add more features: Live Chat, Membership Program, Live Stream Points System.

### Was this project started at a hackathon or another web3 event? Which one?

No

### What is the project’s expected deliverable at the conclusion of the grant time period?

⭐ Create Channels (OnBoard users)
⭐ Publish any video content or Live Streams.
⭐ Support creators by sending a Diamonds
⭐ NSFW content restrictions.
⭐ Decentralized Video Storage using LivePeer VOD

Production Launched.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Creators can upload max 1GB of videos on Videso and Can create Live Streams for DeSo. NSFW Content Detection 

### How will this deliverable benefit the Livepeer ecosystem?

We decided to make a Videso 2.0 decentralized video-sharing platform with LivePeer, where content creators can upload their content on LivePeer Studio (IPFS). Users have the option to Store Videos on IPFS or LivePeer Studio. Creators can monetize their content with DeSo Diamonds as Tip. Creators have the option to Create Content for their Coin Holders.

**Comment by jsonpreet** [comment]
Hi @hansy Ser, Waiting for your response.

**Comment by hansy** [comment]
Thanks for your patience @jsonpreet. Our committee has decided not to fund your project at this time. However, please continue to work on it and feel free to apply again in the future with more updates and traction.
