### ISSUE TITLE
[Open LN Grant]: YAR

### ISSUE THREAD

**Issue by YARlabs** [livepeer/Grant-Program#142]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

YAR - blockchains interconnector that brings together all of blockchains in one place, in any place.

### Link to public GitHub repo (if applicable)

https://github.com/YARlabs

### Link to demo website (if applicable)

https://yarchain.org

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

YAR makes any blockchain interoperable with Livepeer, and Livepeer is interoperable with any blockchain. It means more assets, more transactions, more users, and more cash flow. It means that assets from another blockchain can be tradable and transferable into Livepeer, into Livepeer-based projects. It means more TVL, more community, and more power.

### Please describe in details what your final deliverable for this project will be.

YAR makes any blockchain interoperable with Livepeer, and Livepeer is interoperable with any blockchain. It means more assets, more transactions, more users, and more cash flow. It means that assets from another blockchain can be tradable and transferable into Livepeer, into Livepeer-based projects. It means more TVL, more community, and more power.

### Please break up your development work into a clear set of milestones

MILESTONE - TIMING - FUNDING
YAR protocol connector development - Up to 2 mo - 30’000USDT
Addressed Chain smart smart contract development - Up to 2 mo - 30’000USDT
Addressed Chain smart smart contract security audit - Up to 1 mo - 20’000USDT
Connector & Smart contract testing - Up to 2 mo - 10’000USDT
Connector & Smart contract deployment - Up to 1 mo - 0USDT

Total milestones: 5
Total time: up to 3 mo
Total funds: 95’000USDt

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total funds: 95’000USDt

### Specify your team's long-term plans to maintain this software and upgrade it over time

https://docs.yarchain.org/testnet-instruction/v.0.2mvp-roadmap
https://docs.yarchain.org/testnet-instruction/v.0.3alfa-roadmap
https://docs.yarchain.org/testnet-instruction/v.0.4beta-roadmap

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

For the last 7 years, we have developed 17 private blockchains and taken part in developing public 7 blockchains and protocols. We have a great idea that came true in August 2023.

### How did you learn about the Livepeer Grants Program?

Google

### Was this project started at a hackathon or another web3 event? Which one?

No

**Comment by hansy** [comment]
Hi @YARlabs, thanks for applying for a grant. For Livepeer Network related grants, typically we try and get orchestrator or protocol-level buy-in. I recommend pitching your idea in our [#grants](https://discord.com/channels/423160867534929930/680142091174543362) or [#protocol-discussion](https://discord.com/channels/423160867534929930/1079763495194742986) channels in Livepeer's Discord. If there seems to be community support for your idea, we'll be happy to discuss next steps. Also, typically our grants cap out around $15k, paid out in LPT.
