### ISSUE TITLE
[Builder Grant]: Web3 Goals

### ISSUE THREAD

**Issue by kiv1n** [livepeer/Grant-Program#143]
### What is your project, and what problem does it solve?

Web3 Goals is a social space that helps any person or community to achieve their goals!

The space where you can set soulbound goal with a stake, verify its achievement via smart contracts, and earn on-chain reputation. Meanwhile, your friends and followers can take the role of motivators to inspire you and also earn a reputation.

The space where your community can start a challenge to achieve a significant goal with a prize pool to boost engagement of existing members and attract new ones ones.

### Link to public GitHub repo (if applicable)

https://github.com/web3goals

### Link to demo website (if applicable)

https://web3goals.space

### How is Livepeer used for this project?

Each goal has a group chat where the author can share videos of how he's achieving the goal, and his friends and followers can send him videos to motivate him and earn a reputation as good motivators.

For this videos, to provide a better user experience, I want to use Livepeer.

### How will you improve your project with this grant? What steps will you take to meet this objective?

With this grant, I will be able to release the first version of the app with Livepeer integrated as soon as possible, start engaging users, and build a community of achievers.

### Was this project started at a hackathon or another web3 event? Which one?

ETHforAll (https://devfolio.co/projects/web-goals-fbd8).

### What is the project’s expected deliverable at the conclusion of the grant time period?

1. Released in mainnet the first version of the app with integrated Livepeer, in which users can set goals, motivate others, and earn reputation

2. 100+ users of the first version of the app.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Set soulbound goal with a stake, verify its achievement using videos and smart contracts with oracles, motivate other people with videos and earn on-chain reputation.

### How will this deliverable benefit the Livepeer ecosystem?

This project will be a good example for other developers of how videos can be integrated into group or private chats. That should help attract more creative builders to Livepeer and its features.

**Comment by kiv1n** [comment]
@hansy, I noticed that you have a new grant application format. So I deleted my previous application (https://github.com/livepeer/Grant-Program/issues/132) and created this one with the up-to-date information.

**Comment by kiv1n** [comment]
For ease of understanding, I attach the concept of a group chat with videos 😉

![group-chat-with-videos](https://user-images.githubusercontent.com/2692122/224297896-f9a5025a-a19a-4549-b139-f8540a8fefe8.png)

**Comment by hansy** [comment]
Hi @kiv1n! After reviewing your application, we would love to move forward with a microgrant! Details below:

**Amount:** $2000
**Timeline:** 30 days for completion from time of first payment
**Deliverable(s):**

**Clear and complete Livepeer integration (e.g. use of REST APIs or SDKs)**
For this project, this might include the Livepeer Player and/or any relevant API endpoints for creating, fetching video assets (these are just relevant examples; how you use Livepeer is, of course, at your discretion)

**Deployed to production**
The Livepeer team will want to share out a production-ready URL on our socials to solicit feedback and new users to help spur your growth. We want to see ambitious teams get off localhost and publicly launch something that can be viewed, tested, and shared.

**Core video mechanic in place**
We do not expect your application to be 100%, feature-complete, but anyone should be able to independently use your application to test out your core mechanic. The core mechanic in this case might be a user can set a goal, stake an amount, and provide video updates on that goal for confirmation.

It might be really cool to use your app for this grant to keep you motivated! 

If you feel this scope works for your project, please confirm with me and we can kick off the grant. Otherwise, please feel free to amend any part of the scope that will better suit your team!

**Comment by kiv1n** [comment]
Aloha @hansy! Great news, let's do it 🚀

**Comment by hansy** [comment]
Cool. Some of our committee members are in Tokyo for an event, so can we sync back to this next week?

**Comment by kiv1n** [comment]
Okie dokie 👌

**Comment by kiv1n** [comment]
@hansy any news from the team?

**Comment by hansy** [comment]
Not yet. But I'll be sure to let you know as soon as they come back.

**Comment by hansy** [comment]
What's your wallet address? I'm going to start setting up the upfront payment. We send 20% upfront, then the rest upon milestone completion and review. We send funds in the form of LPT, sent on the arbitrum network. Make sure your wallet is compatible with arbitrum.

**Comment by kiv1n** [comment]
0x4306D7a79265D2cb85Db0c5a55ea5F4f6F73C4B1

**Comment by kiv1n** [comment]
@hansy How does the review process work? Do I need to fill out some form or make a presentation in the apple style?

**Comment by hansy** [comment]
Ha nothing that formal, especially for builder grants. I'll check your Github to see if you actually used Livepeer, then play with your product a bit. If your core loop works, then I'll bring in our marketing team to see if we can showcase your product on our socials. Then we'll close out your grant. That's it!

**Comment by hansy** [comment]
Also let me know if you want to use your product for the milestone, i.e. for accountability. Happy to sign up and see your progress through there.

**Comment by hansy** [comment]
The upfront payment has been made! Here's the tx hash: https://arbiscan.io/tx/0x4e9fa5b8495c0626005a7927fceca61eefe881f817335865cba5f26e0beea163. Should we set May 21 as the end date for the milestone?

**Comment by kiv1n** [comment]
That's great news! I think May 21 is the best day 🚀

**Comment by hansy** [comment]
Great! I'll pencil that in. With that, the grant is officially kicked off. Let me know if you have any questions (Livepeer integrated related or otherwise)!

**Comment by kiv1n** [comment]
![](https://media.giphy.com/media/rD62fdKGwIgZrSC7mk/giphy.gif)

**Comment by kiv1n** [comment]
@hansy I set a goal for myself to complete this grant:

https://web3goals.space/goals/3

I would be happy to get motivation from you and give you reputation points 😊

**Comment by hansy** [comment]
Great! How do I add myself as a motivator?

**Comment by kiv1n** [comment]
First you need to connect a wallet and create a profile. After that you can send any motivational message.

**Comment by kiv1n** [comment]
It looks like the interface isn't very friendly right now, I'll fix that 💪

**Comment by kiv1n** [comment]
Aloha @hansy, I released the project on Polygon Mainnet! I would love if your team would take a look at it and share their opinion.

Here's a link to the app - https://web3goals.space/

**Comment by hansy** [comment]
This is awesome! Just tested it out! Great work with the Livepeer integration! We'll be happy to release your payment!

**Comment by hansy** [comment]
Hey @kiv1n! Payment has made to finish the grant. Here's the tx receipt: https://arbiscan.io/tx/0xc30948d4a2cb8179ee64c31cbcc0e834884733425dbf34d5d9b5082796f2a41d.

Let me know if you have any questions! And keep building!
