### ISSUE TITLE
[Builder Grant]: 

### ISSUE THREAD

**Issue by shivamchhuneja** [livepeer/Grant-Program#145]
### What is your project, and what problem does it solve?

I run a blockchain and crypto educational channel which has a YouTube at 86000 people, telegram and twitter both at 14k people and another educational twitter at almost 2k people.

I create videos talking about various projects, on chain analysis, blockchain fundamentals and technicals of the markets.

### Link to demo website (if applicable)

https://www.youtube.com/@shivamchhuneja
www.twitter.com/shivamchhuneja
www.telegram.me/shivamchhunejafinance
www.twitter.com/thebtcschool

### How is Livepeer used for this project?

I wish to create multiple Livepeer videos and also talk about how it is beneficial in general when it comes to pushing blokchain tech into the right direction.

### How will you improve your project with this grant? What steps will you take to meet this objective?

The aim is to bring more brand awareness and get more people onto the network

### Was this project started at a hackathon or another web3 event? Which one?

NA

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

I'm a marketing professional in web3 industry with 3+ years of work ex now and also a crypto content creator, fortunately one of the leading content creators in India.

### What is the project’s expected deliverable at the conclusion of the grant time period?

The plan is to push 1 video every 10-15 days and a collection of 4-5 videos in total

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Watch the video and take action to get working on the network ideally becoming a delegator or an orchestrator.

### How will this deliverable benefit the Livepeer ecosystem?

It will bring more attention to the ecosystem and help build the brand awareness

**Comment by hansy** [comment]
Hi @shivamchhuneja, thanks for applying. Unfortunately at this time, we can't offer a grant to you. But please keep building and educating with Livepeer! Maybe we can revisit this application in the future.
