### ISSUE TITLE
[Video Disruptors Grant]: Ad bidding inside livestreaming content

### ISSUE THREAD

**Issue by Mario-SO** [livepeer/Grant-Program#146]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

1. Currently content creators are forced to choose one streaming platform because:

    -   They rely on monetization tools provided by the platform
    -   They rely on discoverability mechanisms provided by the platforms.
    -   They have custom non compete agreements.
    -   They rely on the content creator tools provided by the platform.

2. Content creator platforms hold monopolies because:

    - Live video distribution at scale is really expensive.
    - Video storage at scale is really expensive.
    - Recommendation algorithms rely on getting better the more data a platform has.

With broadcastr, we don't only tackle this problems directly thanks to the NFT tech for the real ownership of content by creators + livepeer solving the infrastructure problem, but we are able to offer new monetization options like `live ad bidding`, the focus of this proposal.

### Link to public GitHub repo (if applicable)

https://github.com/NFTsTv

### Link to demo website (if applicable)

https://broadcastr.xyz

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

This proposal is valuable for the Livepeer ecosystem for several reasons:

1. Enhanced Monetization Opportunities: By implementing live ad bidding on Broadcastr, we can provide content creators with an additional revenue stream. This feature will attract more creators to the platform, which in turn will lead to a more diverse and engaging content ecosystem within Livepeer.

2. Increased Adoption of Livepeer Technology: As we develop Broadcastr on the Polygon network using web3 technology, we will contribute to the adoption and growth of the Livepeer ecosystem. By providing an alternative to traditional content platforms, we can showcase the benefits of decentralized streaming infrastructure, which will drive further interest in and usage of Livepeer.

3. Reinforcing Decentralization and Creator Empowerment: By addressing the monopoly issue in the content creation industry, Broadcastr will promote a more decentralized and democratic ecosystem. This aligns with the core values of Livepeer, further strengthening the project's mission and vision.

Benefits of getting this right include an increased adoption of the livepeer technology and ecosystem resulting in a more diverse user base and also an enhanced reputation for Livepeer as an innovative and empowering technology within the content creation industry.

When talking about the risks that will make this project difficult to execute, we can think of technical issues that may occur during the development of the project, being such a novel approach in the web3 world, there is no roadmap on how to develop something like this, so we may encounter problems that first timers have.

### Please describe in details what your final deliverable for this project will be.

The live ad bidding feature will be a core component of the Broadcastr platform, designed to provide content creators with an innovative and dynamic way to monetize their livestreams. The feature will be seamlessly integrated into the platform's smart contracts and user interface, ensuring a smooth user experience.

Key Components:

1. Smart Contract Modifications: Broadcastr's smart contracts will be modified to accommodate the live ad bidding feature. This will include the implementation of bidding logic, and payment processing. The smart contracts will ensure that the highest bidder's ad is displayed during the livestream.
 
2. User Interface (UI) for Ad Upload: The platform will include a dedicated user interface for advertisers to upload their video ads. This UI will allow users to easily submit their ads, set a bidding price, and monitor the bidding process. The ad upload interface will support various video formats and sizes, ensuring compatibility and ease of use for advertisers.

### Please break up your development work into a clear set of milestones

Milestone 1: 

- Smart contract logic and testing
- 1 Month
- Mario, Solidity Developer
- $5,000

Milestone 2:

- Front-end UI elements + Front-end Logic
- 2 months
- Pablo, Fullstack
- $10,000

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

In total we are asking for $15,000 and the funds will go to the teams multisig wallet to reinvest in the product.

### Specify your team's long-term plans to maintain this software and upgrade it over time

As we are in the early stages of the broadcastr protocol and app, this features and a bunch of other ones will need continuous updates and enhancements. This one being one of the multiple monetization options for content creators, it will receive more attention.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

Filippo:
//COMMUNICATION LEAD//

Filippo is a talented and driven individual who founded Soogo Vintage, an online platform promoting sustainable fashion, at 16. He has a background in Economics and Business Economics and has worked with a Jordanian NGO on enhancing their communications and operations. Filippo also has expertise in UX/UI development and blockchain technology, making him a rising star in the field.

Mario:
//SOLIDITY LEAD//

Mario, a computer engineer from Madrid, is dedicated to bringing the decentralized future to reality. He has a passion for open-source software, user ownership, and freedom from centralization. He has expertise in hardware and software through hands-on experience and self-study, producing impressive projects. Mario has been part of the Ethereum community since 2016 and has worked on various projects including the DeveloperDAO, Nation3, and Lens protocol. He's now fully focused on developing the Broadcastr app to bring his vision of a revolutionary new platform to life, putting user freedom and control first.

Pablo:
//FOUNDER/FULLSTACK DEVELOPER//

Pablo is a software and video engineer with an entrepreneurial background. He got involved in the Ethereum community in 2018 and was an early adopter of the Livepeer protocol. Pablo founded Shamaon, a video production company that became the streaming provider for multiple crypto events such as Devcon 2022. In collaboration with Livepeer and the Ethereum Foundation, Shamaon developed[ Streameth.org](http://streameth.org/), becoming a leading streaming platform for Ethereum events. Pablo's vision and passion for innovation were recognized at EthBerlin 2022, where he won the hackathon with his project "NFTs Are Live at EthBerlin". He is now dedicated to building Broadcastr, bringing his winning idea to life

### How did you learn about the Livepeer Grants Program?

By research.

### Was this project started at a hackathon or another web3 event? Which one?

Pablo hacked a first really simple demo at ETH-Berlin and won the "Freedom to transact" prize

**Comment by hansy** [comment]
@Mario-SO Thanks for the proposal! This is really interesting! A few things:

1.) Can you add specific deliverables at the end of each milestone? For each milestone, what's something tangible we can play around with and/or test?
2.) Can you maybe break down milestone #2 into separate, more specific components? This will help in defining specific deliverables.
3.) Ideally we'd like to structure the payment to include a success bonus. An example would be $4k for milestone 1, $6k for milestone 2, then a $5k bonus if you have, say, 10 advertisers lined up. We can play around with the numbers a bit to better accommodate what your team is trying to accomplish.

What do you think?

**Comment by Mario-SO** [comment]
More than happy to provide additional clarity and restructure our milestones and payment plan as requested. And sorry for the delay mate

1.) **Specific deliverables at the end of each milestone:**

**Milestone 1:**
- Completed and tested smart contract logic for live ad bidding.
- Documentation on the smart contract functionality and testing results.

**Milestone 2:**
- Fully functional front-end UI for ad upload and management.
- Integration of front-end UI with the smart contract.
- Documentation on the front-end implementation and integration with the smart contract.

2.) **Breaking down Milestone 2 into separate, more specific components:**

**Milestone 2A:**
- Design and develop the front-end UI for ad upload and management (1 month).
  - Deliverable: Completed and functional ad upload UI, ready for integration with the smart contract.

**Milestone 2B:**
- Integrate the front-end UI with the smart contract and test the end-to-end functionality (1 month).
  - Deliverable: Fully integrated and tested UI and smart contract, ensuring smooth user experience and correct functionality.

3.) **Restructuring the payment plan:**

We agree to the suggested payment structure and are willing to accommodate the success bonus. Here's the updated payment plan:

**Milestone 1:**
- $4,000

**Milestone 2A:**
- $3,000

**Milestone 2B:**
- $3,000

**Success Bonus:**
- $5,000

We hope that these updates address your concerns and provide a clearer picture of the project scope and objectives. We appreciate your consideration and look forward to the opportunity to contribute to the Livepeer ecosystem.

**Comment by hansy** [comment]
This looks pretty good, thanks. Does milestone 2 include a working demo with video and an ad?

**Comment by Mario-SO** [comment]
Oh I see what you mean by deliverable. Ok yes, we will make a video as a demo.

**Comment by hansy** [comment]
Hey @Mario-SO, after committee review, we'd like to offer a grant for your application. We'd like to propose a few tweaks to the milestones:

### Milestone 1
Completed and tested smart contract logic for live ad bidding.

**Deliverable:** Documentation on the smart contract functionality and testing results
**Amount:** $3k

### Milestone 2
Design and develop the front-end UI for ad upload and management

**Deliverable:** Completed and functional ad upload UI, ready for integration with the smart contract.
**Amount:** $3k

### Milestone 3
Integrate the front-end UI with the smart contract and test the end-to-end functionality

**Deliverable:** Fully integrated and tested UI and smart contract, ensuring smooth user experience and correct functionality
**Amount:** $2k

### Milestone Success Metric
Successful showcase of at least 3 advertisers using the new feature and demonstrable increase in new users of Broadcastr

**Amount:** $5k


For the success metric, in addition to seeing real world use from advertisers, we'd love to also see how the new monetization option in turn brings more users/creators to Broadcastr. In terms of creator adoption, what's a stretch goal you feel is challenging, but achievable?

**Comment by pabloVoorvaart** [comment]
I believe that what we are doing here is state of the art, and it should be supported with more enthusiasm by the livepeer community fund. 

It would be nice to understand what the committee does not want to award the full amount that we asked for initially.

@hansy

**Comment by hansy** [comment]
$13k isn't far off from the max amount of $15k we grant, but happy to discuss. Where would you like to see the additional $2k allocated?

FWIW, we're trying to put a lot more stock into adoption and growth of applications, not just the implementation of an idea. This is why we're putting more emphasis on the success bonus because we want to reward not just pure building, but adoption of the tech as well. We are extremely excited about your application, and again, willing to work with you what you think is best for your team.

**Comment by pabloVoorvaart** [comment]
I understand the adoption part, but I would like to understand why the livepeer team feels the full 15k can't be allocated. 

We already scoped a proposal on how the full 15k should be distributed across milestones.

**Comment by hansy** [comment]
If $2k is the bottleneck, we'd rather just allocate it across milestones 1 and 2, than have you guys come up with extra work for yourself. So:

Milestone 1 - $4k
Milestone 2 - $4k
Milestone 3 - $2k
Success - $5K
