### ISSUE TITLE
[Video Disruptors Grant]: 

### ISSUE THREAD

**Issue by blkluv** [livepeer/Grant-Program#147]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

ARVRtise created a new positive vibes only PPV token gated channel. 

### Link to demo website (if applicable)

https://ppv.arvrtise.com/

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Good vibes

### Please describe in details what your final deliverable for this project will be.

https://ppv.arvrtise.com/

### Please break up your development work into a clear set of milestones

Finalized, we are using the grant to promote our network. 

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

15K Total
🟰
5K ATL onboarding creator event
5K PR 
5K Influencer marketing 

### Specify your team's long-term plans to maintain this software and upgrade it over time

We’re onboarding brands and creators to our ARVRtise platform to create DIY AD campaigns. We promote the purpose based use cases.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

https://arvrtise.com
https://luvnft.com
https://lnelord.luvnft.com

### How did you learn about the Livepeer Grants Program?

Long time follower.

### Was this project started at a hackathon or another web3 event? Which one?

No

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

ARVRtise your purpose here.

**Comment by hansy** [comment]
Hi @blkluv, I noticed you also have another grant application out (#120). We typically fund only one project per team. For which project are you seeking a grant?

**Comment by hansy** [comment]
Closing in favor of #120

**Comment by hansy** [comment]
Thanks for applying @blkluv. After review, our team has decided not to fund your application. This is mostly due to how far along your project is, as the funds being requested are going towards marketing-related activities, and not towards any video-/Livepeer-related integration.

With that being said, please keep us updated on your project. We'd love to keep an eye on it and amplify it across our socials as an example of a successful Liveeper integration.

**Comment by blkluv** [comment]
@hansy the Dapp is fully integrated with Livepeer! The grant is being used to onboard brands and influencers onto the Livepeer network with the LPT token.
