### ISSUE TITLE
Subsidy for AldeaCrypto mini course

### ISSUE THREAD

**Issue by aldeacrypto** [livepeer/Grant-Program#149]
### What is your project, and what problem does it solve?

Hi, my name is Daniel Puro.
I am an audiovisual producer and I have experience in crypto issues.
My project is audiovisual, I have been checking the web and I can't find quality and valuable content (video) that explains the usefulness of Livepeer in Spanish.
I am currently turning my youtube channel (AldeaCrypto) around where I am going to start creating content related to web3, DEFI, Smart Constracs, NFts and other topics related to blockchain but for an audience in Spanish. Through 2D animations and explanatory videos.
The project would consist of a series of videos (5) animated with videoscribe, which would be published on my youtube channel and shared on my other social networks twitter and telegram to give it further expansion. The content will be developed as follows
1.- What is Livepeer?
2.- Operation of Livepeer
3.- Liverpeer features
4.- Liverpeer utility
5.- How to use liverpeer?
After people who complete the video, they can be rewarded with some poap or recognized that makes them knowledgeable about Livepeer

### Link to demo website (if applicable)

https://www.youtube.com/@AldeaCrypto/videos

### How is Livepeer used for this project?

Explanatory content will be projected where the Spanish-speaking public will be able to learn about the benefits of Liverpeer and the way in which videos can be created through decentralized networks.

### How will you improve your project with this grant? What steps will you take to meet this objective?

I have to pay service to use videoscribe; valued at $150, pay for the voiceover service that would be around 30 minutes of voiceover for $150, and the animation services would be developed by me to be able to complete the 5 explanatory videos.

### Was this project started at a hackathon or another web3 event? Which one?

no, I have been looking for content on decentralized video protocols in Spanish and the information is almost null or non-existent.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

I have experience creating content for other youtube channels
https://www.youtube.com/@Cryptoversity
https://www.youtube.com/@archicrypto
And that style of animation seems appropriate to me so that people can learn in a simpler and more practical way.

### What is the project’s expected deliverable at the conclusion of the grant time period?

Create content in Spanish and that Spanish-speaking people can know all these protocols, of which they have no idea, but with the content that I am proposing they can be useful and benefit their lives and work.

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

I would like people who watch the videos to be rewarded with a poap at the end of the videos where they are recognized for the learning they have acquired.

### How will this deliverable benefit the Livepeer ecosystem?

Attract more Spanish-speaking people to their protocols and be able to see how they should not necessarily use centralized providers, but rather make them see that there are other options

**Comment by hansy** [comment]
Thanks for applying @aldeacrypto. However at this time, our team has decided not to fund your application. But please continue educating others and building your brand. Should you have other ideas or additional traction with your current project, please feel free to apply again in the future!
