### ISSUE TITLE
[Video Disruptors Grant]: Songcaster / Collabs

### ISSUE THREAD

**Issue by JRFriedman** [livepeer/Grant-Program#150]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

Songcaster is solving the problem of how musicians and visual artists can collaborate together and create MTV on-chain, i.e. music video tokens (“Collabs”)

Web3 is a visual space, but a lot of visual NFTs, i.e. images, GIFs, animation, or longer videos, would benefit from collaboration on music & soundtrack that can bring the ideas to life!

This creates problems because there is no simple way to collaborate in the Web3 ecosystem, and there's no simple way to dynamically manage ownership, revenue & royalty sharing for the token throughout the collaboration process.

Our mission is to build Collabs on the Lit Protocol to foster a collaborative token minting framework to (i) enable collaborators to have programmatic control about all aspects of the collaboration, (ii) enjoy the interoperability across all ECDSA blockchains, and (iii) “Slow Collab,” without the pressure of mint first and build later! 

We believe this is the best way for musicians and visual artists to bring their respective files and metadata together and create something truly special and unique that could only come from artist collaboration!

Through this grant, we aim to accelerate the integration of Collabs into Livepeer's ecosystem, enhance its features and functionalities, and provide the necessary resources and support to attract and onboard creators and users.

### Link to public GitHub repo (if applicable)

https://www.notion.so/atlascaster/Collab-Documentation-41cd4905f79148d3a6462800daca9522?pvs=4

### Link to demo website (if applicable)

https://www.notion.so/atlascaster/Collab-Templates-721eb2f4ec9149a1ac4283151ca9f002?pvs=4

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

By integrating the Collabs functionality into Livepeer's platform, we empower creators to tap into new revenue streams and incentivize collaboration within the creator economy.

The adoption of Collabs on Livepeer will attract a diverse range of musicians who seek to create unique, immersive, and interactive music video experiences. By offering a seamless integration between Livepeer and Collabs, we create an ecosystem that fosters creativity, collaboration, and monetization.  This will not only attract established creators but also empower emerging talent, thereby expanding the creator economy and attracting a wider user base to Livepeer.

Furthermore, the integration of Collabs can enhance the social and interactive aspects of Livepeer's platform.  Users can engage with the immersive music videos and visual experiences created by artists and contribute to their success by owning and trading the tokens. This fosters a sense of community and participation, driving increased engagement and usage of the Livepeer platform.

Together, Livepeer and Collabs can empower creators, foster collaboration, and revolutionize the way video content is monetized and consumed in on-chain apps, open social platforms, and the emerging creator economy.

### Please describe in details what your final deliverable for this project will be.

We are open to a discussion about the final deliverable for this project (i.e. SDK / possibly some front-end), but in general the functionality will be as follows:

We will provide a framework for a musician and video artist to mint a programmable key pair that contains the respective metadata for their collaborative work 

Together the two PKPs will control the mintToken() function for a blockchain token

The mintToken() function will enable the musician and visual artist to collectively mint a new collaborative token. 

The function will take in parameters such as the name and symbol of the token, the collaborators involved, and potentially the revenue, royalty, and ownership terms. 

Once the function is called, a new token is created on the blockchain

This provides a seamless way to go from collaboratively working on a project to collaboratively deploying the project to the blockchain 

And conceivably the PKP can control a mintToken() function on a number of different blockchains as there are interesting possibilities and opportunities for cross-chain minting from Lit Protocol

### Please break up your development work into a clear set of milestones

This project will be managed by myself, Jacob Friedman, a Web3 founder and attorney with a strong understanding of IP agreements & a good understanding of Web3 tech.  I am speaking with a talented developer experienced in programmable key pairs / Lit Protocol who will be assisting me with this project, and I am referring to him as Senior Engineer below.  

The below dates and milestones are a rough approximation of the project goals, scope and timeline, and I'd be happy to discuss further with the Livepeer team!

**Milestone 1:**
_Define & create the PKP metadata schema_
This will provide a framework for any application to integrate Collabs using the Lit Protocol framework and integrate videos using the Livepeer video schemas 
Jacob Friedman (Project Lead)
(Senior Engineer)
$3,000
June 5 - July 7

**Milestone 2:**
_Define & create the Lit Actions_
This will provide a framework for the PKPs to broadcast signatures to target blockchains to create the collaborative music video tokens
Jacob Friedman (Project Lead)
(Senior Engineer)
$6,000
July 10 - August 11

**Milestone 3**
_Testing, deployment, de-bugging_
This will be used to test-drive the software with initial proofs of concept from musicians and visual artists, demonstrating the utility and fun functionality of on-chain music video collaboration
Jacob Friedman (Project Lead)
(Senior Engineer)
$6,000
August 14 - September 5

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

The budget breakdown is provided above, and in general the funds will be used for technology development & product design for the Collabs framework on the Lit Protocol. 

This is complex & new technology so we anticipate that most of the time will be discussions regarding the programmable key pair (PKP) framework, and how to integrate the Lit actions with two signers controlling the two PKPs

$10,000 for engineering 
$5,000 for product development 

### Specify your team's long-term plans to maintain this software and upgrade it over time

The team plans to bring Collabs to other music platforms to enable more musicians and visual artists to collaborate together on-chain

We will provide open source developer resources & SDKs so it will not be dependent on one team to manage the long-term utility of the Collabs framework

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

The engineer that I am speaking with has significant experience as an R&D lead at a major blockchain company, and is currently working on a number of Lit Protocol use cases 

As an attorney, I am familiar with creating collaborative IP agreements between multiple parties, and mapping those terms onto token metadata

Together we are a lean team that can execute on this project, and set up Collabs for future success and continued development!

### How did you learn about the Livepeer Grants Program?

Discord 

### Was this project started at a hackathon or another web3 event? Which one?

It started as a passion project, have been developing the idea since August 2022

### Please include any additional information that you think would be useful in helping us to evaluate your proposal.

I am excited to discuss further and hope we can speak live to drill down on the core value of our solution and how we can unlock on-chain collaboration as a new, exciting Web3 behavior!

**Comment by hansy** [comment]
Thanks for applying @Jacob-Atlas! Our team will review your application, and you should receive a decision from us within 2-4 weeks!

**Comment by Jacob-Atlas** [comment]
Great, thanks very much 🙏 Looking forward to discussing further!

**Comment by hansy** [comment]
Hi @JRFriedman. After review of your application, our committee has decided not to fund your project at this time. We encourage you to continue exploring this space, especially given your IP law background. We'd love to keep an eye on this project; please feel free to update us with any additional traction you gain. And of course, we welcome you to apply again in the future!
