### ISSUE TITLE
[Video Disruptors Grant]: Rob Framework and Farm Trust

### ISSUE THREAD

**Issue by alextitonis** [livepeer/Grant-Program#152]
### Please describe your project. Start with the need or problem you are trying to solve with this project. Describe why your solution is going to adequately solve this problem.

We want to combine rob framework, farm trust and Livepeer, for the robot to capture live video from the farms it is, publish it to Livepeer and be able to show it in Farm Trust.

What is Rob Framework and Farm Trust:
Rob Framework, is an advanced AI-powered robotic solution designed to enhance the efficiency and safety of agricultural operations. Equipped with a robotic arm, wheels for mobility, and cutting-edge computer vision capabilities, Rob performs farm surveys, detects crop health, identifies potential fires, and monitors for intruders and animals. By leveraging artificial intelligence and advanced mapping techniques, Rob Framework conducts comprehensive farm assessments while providing smart notifications in real-time whenever anomalies are detected.
In addition to these features, Rob Framework incorporates a Web3 platform to enable users to reward farmers with cryptocurrencies based on the quality of their crops. This innovative approach promotes knowledge-sharing and incentivizes farmers to adopt sustainable farming practices, ultimately leading to increased crop yields and better overall farm management.

### Link to public GitHub repo (if applicable)

https://github.com/Rob-Framework

### Please describe in more detail why this proposal is valuable for the Livepeer ecosystem

Generally it will increase the visibility of livepeer, the solution will be easily plug and play, which will help others copy the livestream code for their projects as well, finally the project is aimed for food security, thus increasing visibility of Livepeer to these communities.

### Please describe in details what your final deliverable for this project will be.

Milestone 1:
- Add Python connection to livepeer, get data from OpenCV and post the data to a stream
- General Livepeer api in python, with documentation

Milestone 2:
- Connect livepeer to Farm Trust website, users will be able to attach the livestream url to their farms
- Live player of the livestreams when active (to see the current state of the farm)

### Please break up your development work into a clear set of milestones

Milestone 1:
- Add Python connection to livepeer, get data from OpenCV and post the data to a stream
- General Livepeer api in python, with documentation

Milestone 2:
- Connect livepeer to Farm Trust website, users will be able to attach the livestream url to their farms
- Live player of the livestreams when active (to see the current state of the farm)

### Sum up the total requested budget across all milestones, and include that figure here. Also, please include a budget breakdown to specify how you are planning to spend these funds.

Total Budget: 8.000 - 9.000$
Half amount for both milestones

### Specify your team's long-term plans to maintain this software and upgrade it over time

We are aiming to make a completely opensource robotic frame work with streaming and computer vision capabilities and Farm Trust platform, which will be used by farmers to raise funds by users in case of bad production.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

https://github.com/alextitonis

### How did you learn about the Livepeer Grants Program?

I've applied again in the past

### Was this project started at a hackathon or another web3 event? Which one?

No

**Comment by hansy** [comment]
Thanks for applying @alextitonis. Good to see you again! We'll review your application and get back to you within 2-4 weeks with a decision!

**Comment by alextitonis** [comment]
I've got an update as well, finished the base site for Farm Trust, can be found here https://farmtrust.site/

**Comment by hansy** [comment]
Hey @alextitonis. After review, the committee has decided not to fund this project. While we think this represents a novel use case for Livepeer, we feel your project is still a bit too early. Please continue working on this and feel free to apply again in the future with more updates!
