### ISSUE TITLE
[Builder Grant]: Waves

### ISSUE THREAD

**Issue by GageVanK** [livepeer/Grant-Program#153]
### What is your project, and what problem does it solve?

Waves, in short is Twitch meets Twitter. It's built on the Deso Blockchain. Right now, in the Web2 Live Streaming space were seeing new platforms like Kick and Rumble pop up in similar way that the Microsoft owner platform, Mixer, did back in 2016 where although they provide more options for streamers, they don't improve the space at all and will likely have the same fate as Mixer. 

Waves offers a fresh approach by incorporating a Twitter-like social layer that allows streamers to not only livestream but also engage with their community on a deeper level. Unlike Web2 platforms that claim to be censorship-resistant, Waves is built on the Deso Blockchain, ensuring true censorship resistance.

One of the key advantages of Waves is the ability for streamers to monetize their content. We enable streamers to generate revenue through the sale of NFTs(not yet built out), as well as receive tips and subscriptions from their audience.

By combining the best aspects of Twitch and Twitter while leveraging the power of blockchain technology, Waves provides a unique and innovative solution for the live streaming industry. Our goal is to empower streamers, enhance community engagement, and create a decentralized and censorship-resistant platform for the future of live streaming.

### Link to public GitHub repo (if applicable)

https://github.com/GageVanK/waves-2.2

### Link to demo website (if applicable)

https://waves-2.vercel.app/

### How is Livepeer used for this project?

Used to power all streaming capabilities and vod playback

### How will you improve your project with this grant? What steps will you take to meet this objective?

Users will be able to view livestreams on the homepage under the "waves", similar to tiktok live feeds. They will also be able to view them on the discover page, organized categorically. Users will will be able to search users via username/publickey to view their channel with their stream, if available, and their deso profile data,

Ill focus building out the livepeer aspects of the app and then finish with the deso functionality - Mint/List NFTs, Chat, Post Action(Like, comment, repost, tip diamonds)

### Was this project started at a hackathon or another web3 event? Which one?

It was not i started this my last semester of college back in december 2022 and had been waiting for the deso blockchain to do another hackathon, but they only did one exclusive to princeton students.

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

During the pandemic I was only consuming media through Twitch, mostly valorant, but I feel like i have a really good grasp on the space and what streamer/viewers want. Right now the team is only me and have a team to help but this just started as an idea for a final project.

LinkedIn: https://www.linkedin.com/in/gage-v-b5a04319a/

Pitch/Demo: https://www.youtube.com/watch?v=Brk5ZEXxsEA&t=8s

### What is the project’s expected deliverable at the conclusion of the grant time period?

App launch | Video tutorial/walkthrough

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Livestream & View Streams/VODs

### How will this deliverable benefit the Livepeer ecosystem?

Its open sourced so at the very least it can be used for other devs to learn and build but hopefully well get some actual growth I can add stuff to the website to show were powered by livepeer

**Comment by GageVanK** [comment]
Thank you! Here's a much more in depth breakdown of Waves and the problem we solve:

**Transparency and Fairness:**
- Open Source: Encourages open-source applications and algorithms.
- No hidden algorithms: The platform operates with transparent code and data.

**Data Ownership and Accessibility:**
- Open Data: Your data is freely available to you.
- Content Ownership: All content is stored on-chain, ensuring ownership and portability across platforms.

**Monetization and Revenue Sharing:**
- Monetization options: Social-Tips, NFTs, Creator-Coins.
- Direct to Creator: Payments go directly to content creators.
- Creator Coins: Each account has its own creator coin for fans to invest in creators.
- Minting and Listing NFTs: Streamers can sell NFTs and set future royalty percentages.
- Direct Cash Out: Creators can convert earnings to USD using their DeSo wallet.

**User Experience and Accessibility:**
- Interconnected: Followers and content are accessible across all apps on the DeSo Blockchain.
- No Investment Needed: Users can benefit without investing money.
- Easy Onboarding: Sign in/up via Metamask, Google email, or DeSo seed.
- Free $Deso for new users: Phone number verification provides free $Deso for transactions.

**Affordability and Low Fees:**
- Extremely Low Fees: Transactions on the DeSo Blockchain have minimal fees.
- $80 per gigabyte of storage on deso



Our decentralized social media platform on the DeSo Blockchain aims to provide transparency, fairness, data ownership, and accessible monetization options for creators. It offers an interconnected user experience, affordability, low fees, and resistance to censorship.

**Comment by hansy** [comment]
Hey @GageVanK! We'd love to fund this microgrant! Let's hop on a call to iron our the deliverable. Feel free to message me on Discord (hansy#9576).

**Comment by GageVanK** [comment]
Holy shet!! Sounds great thanks so much!!

**Comment by hansy** [comment]
Thanks for chatting with me @GageVanK! Based on our conversation, here are the details of the microgrant:

**Amount:** $2000
**Timeline:** 30 days for completion (starting from initial payment)
**Deliverable(s):**

**Clear and complete Livepeer integration (e.g. use of REST APIs or SDKs)**
For this project, this might include the Livepeer Player and/or any relevant API endpoints for creating, fetching livestreams (these are just relevant examples; how you use Livepeer is, of course, at your discretion).

**Deployed to production**
The Livepeer team will want to share out a production-ready URL on our socials to solicit feedback and new users to help spur your growth. We want to see ambitious teams get off localhost and publicly launch something that can be viewed, tested, and shared.

**Core video mechanic in place**
We do not expect your application to be 100%, feature-complete, but anyone should be able to independently use your application to test out your core mechanic. The core mechanic in this case would be a user can:

- see all current livestreams (via Waves tab)
- can see livestreams of followers
- can create a livestream and go live

If you feel this scope works for your project, please send me an Arbitrum-compatible wallet address so I can kick off the upfront payment (20%). Otherwise, please feel free to amend any part of the scope that will better suit your team!

**Comment by GageVanK** [comment]
Same, really happy to be a part of this and perfect! 

0x7ad5e3c3e55012dc7f5546d82be5ceafb4c4dd3d

**Comment by hansy** [comment]
@GageVanK Hey! Your upfront payment tx has been confirmed: https://arbiscan.io/tx/0x8f558a4a4ef6aea203b9c1b380fc0c27697d7c8c9a4546ad518a4b5066a84b8c!

With that, we can officially kickoff the grant. You have until **July 6, 2023** to complete the remainder of the grant. Let me know if you have any questions along the way. Good luck!

**Comment by GageVanK** [comment]
Ayyy thank you!!

**Comment by GageVanK** [comment]
Hey just finished with the deliverables. All the features can be seen on waves but because I don't have active users streaming on Waves I wanted to record a demo of the features so you and the livepeer team can see the full scope of what was added.

https://www.youtube.com/watch?v=eFWRMIYoVQA

Thank you!

**Comment by hansy** [comment]
Wow that was quick! I will review shortly, but definitely spend the extra time testing with real users and getting their feedback!

**Comment by GageVanK** [comment]
Thank you! Didn't expect to finish with them that fast but this was a really motivating opportunity for me. I've been looking for an excuse to really dig into this project, even since the 13th Waves has changed so much.

I am still drafting my application for the Disruptor Grant but should be submitted this week. The last couple of weeks I've spent testing out streams, improving the UI, and building out the DeSo side of things - Users can now like, comment, repost, and microtip posts. There's still a lot of things that need to be ironed out but it's coming along really well.

**Comment by hansy** [comment]
@GageVanK Here's the tx receipt for completion of the grant: https://arbiscan.io/tx/0x79a1c350c6a8456ae3f100a2bf52bcbbf1eeed94c9b8efb4fc6f482fddc54474. Great work! While you have the basics of your app in place, we'd love to see more real-world users using your app. Keep building, keep soliciting feedback from others. We'd love to stay updated on your progress. Say hi anytime in the Discord!
