### ISSUE TITLE
Grant request: SUN ZU Lab: leading quantitative data provider on a mission to bring better data to the global crypto ecosystem.

### ISSUE THREAD

**Issue by SunZuLab** [livepeer/Grant-Program#159]
**Project title**: SUN ZU Lab : leading quantitative data provider on a mission to bring better data to the global crypto ecosystem. 

**Description**: 
SUN ZU Lab is a leading data solutions provider, on a mission to bring better data to the global crypto ecosystem through independent quantitative analyses. We collect the most granular market data from major liquidity venues, analyze it, and deliver our solutions through real-time dashboards. 

**Vision**: 
SUN ZU Lab allows crypto professionals to monitor the activity of crypto tokens across multiple trading venues, providing token holders with a 360 degree view over crypto market movements.

**Problem and solutions:** 
Crypto has shown a tremendous growth potential but is still lacking institutional standards that help protect basic token users' rights. We believe that this is starting to change post defining events such as the Terra Luna ecosystem implosion or FTX's bankruptcy, and that our tools can help bring a deeper understanding and monitoring of tokens' market activity: SUN ZU Lab dashboards and insights will help bring more maturity and institutionalize the crypto markets, driving the next wave of mass adoption from banks and asset managers managing trillions of retail investors money

**Project features:** 
Tokens are often an essential element of the ecosystem governance & well functioning, and the community is interested in knowing where to buy and sell the token and following what’s going on. The idea of the collaboration with your ecosystem would be to create a free, open-source dashboard for token holders, allowing them to track the tokens’ activity in real time on a single interface. We could also make it available through API & Flat files.
A second use case is for your foundation directly (and CFO if exist); foundations are often asked to buy/sell large quantities of tokens. SUN ZU Lab Dashboard enables them to have an aggregated view and real-time monitoring tool of the market and, therefore to better choose or execute but also to be alerted if there is a liquidity issue on a market X, for example.

The dashboard, will allow the community to:
Follow the most accurate price action in real time;
Identify and monitor price anomalies between different exchanges;
Get alerted of large unusual transactions or periods of exceptional volatility;
Identify the venue with the best price for users who want to adjust the inventory of their token;
Get similar information for other tokens listed on the platform

**Progress:** 
Drastic progress has been made through funding: 
$1.5m raised in 2022: Backed by BPI France, Kima Ventures & Elaia
$1.5m secured on $2m (current seed round)
We already have 4 paying clients amounting around $200k ARR.

**Differentiation:** 
We differ from other crypto off-chain data dashboard providers such as Messari or Token Terminal by providing client-centered and customizable dashboards. With SUN ZU Monitoring Dashboard, we can provide customized real-time alerting on market events, granular data on a tick-by-tick basis, pre/post-trade analysis, and fair price computations and proprietary feeds, among others. Using our dashboard, our token ecosystem clients have been able to have a full 360 degree view of their token’s liquidity, and were able to react in real-time to urgent market events that could be catastrophic if not well handled (deppeg, liquidity crunch, bid-ask spread spikes…)

**Team:** 
We are a team of 13: 
2 co-founders:
Stéphane Reverre, Co-Founder & CEO (https://www.linkedin.com/in/stephanereverre/)
Vincent Madrenas, Co-Founder & COO (https://www.linkedin.com/in/vincent-madrenas-90bb3591/)

And 11 other employees: 
Alexis Troubnikoff, Chief Data Officer (https://www.linkedin.com/in/alexis-troubnikoff/)
Toussaint Behaghel, VP of Engineering (https://www.linkedin.com/in/toussaint-behaghel-328661b4/)
Chadi El Adnani, Crypto Research & Business Lead (https://www.linkedin.com/in/chadi-el-adnani-405a2b10a/)
Timothée Fabre - Phd Quant Researcher - https://www.linkedin.com/in/timoth%C3%A9e-fabre-39aa6812a/
Maxime Garcia - Quant Researcher - https://www.linkedin.com/in/maxime-garcia-1a21841a2/
Rafael Gameiro Contente - Software Engineer - https://www.linkedin.com/in/rafa%C3%ABl-gameiro-contente-5b584077/
Thibault Caillieret - Data Engineer - https://www.linkedin.com/in/thibault-caillieret-b845bb82/
Jeffrey Degrenne - IT Frontend
Guillaume Bournel - IT Backend
Mathieu Beucher - IT Backend
Corentin Cadieu - Advisor -[ https://www.linkedin.com/in/corentincadieu/](https://www.linkedin.com/in/corentincadieu/)

Here is our team's experience: 
Stéphane has held operational and managerial positions in the major financial marketplaces of New York, Tokyo, London, Singapore, and Paris.
He has launched and developed many trading activities at some of the biggest financial institutions: Société Générale, Natixis, Millennium Partners, Dresdner Bank, and Exane. He has particular expertise in financing and execution (MiFID). 
Stéphane is a graduate of Ecole Centrale Paris and a CentraleSupélec Business Angels association member and holds an MBA from Harvard Business School.

Vincent created from scratch an electronic trading platform dedicated to the crypto asset at SESAMm.
He has also worked on the design & implementation of quantitative investment strategies using alternative data.
Vincent holds a Master’s degree in Probability & Finance (Ex DEA El Karoui) from Paris 6 & Ecole Polytechnique X.

Alexis spent 17 years as CDO at CFM, a prominent investment manager and a pioneer in the field of quantitative trading applied to capital markets across the globe.

Chadi holds a double degree from HEC Paris and Télécom Paris, majoring respectively in International Finance and Applied Mathematics / Data Science. His previous experiences include full-time roles and internships in Investment Banking, Private Equity and Asset Management within leading institutions such as Goldman Sachs, Lazard and BlackRock.

**Grant request:** $37k

**What the funds are for:** 
100% of the Grant is used to deploy the infrastructure of the integrated protocol & maintain it
(Maintenance = $03k / Month). Here are our milestones:

1) Milestone 1: Deployment on your ecosystem (Deadline: Q3 2023 ): $10k Deployment + $09k Maintenance
2) Milestone 2: 2k Unique Users on your ecosytem (Deadline: Q4 2023): $09k Maintenance
3) Milestone 3: 10k Unique Users on your ecosystem (Deadline: Q1 2024): $09k Maintenance

**Help needed:** 
We'd also like to get in touch with the people in charge of partnerships in your ecosystem to see how we can integrate our solution & bring the maximum value to our respective users.
The idea of the collaboration would be to create a free, open-source dashboard for token holders, allowing them to track the tokens’ activity in real time on a single interface. We could also make it available through API & Flat files.

**Additional resources:** 
Twitter: https://twitter.com/sunzulab1
Telegram: https://t.me/Cox_xyz
Our website: https://sunzulab.com/
And our pitchdeck: https://drive.google.com/file/d/1mb4-x1IuX7xaB26K2OENZixDmNQeNzqJ/view?usp=sharing

**Comment by hansy** [comment]
Thanks for applying @SunZuLab! Unfortunately at this time, we cannot offer a grant for your project. But please continue building, and feel free to apply again in the future with additional updates and progress!
