### ISSUE TITLE
Get `install_ffmpeg.sh` script working on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by chrishobcroft** [livepeer/Grant-Program#16]
**Give a 3 sentence description about this proposal.**

The current [documented build process for `go-livepeer`](https://github.com/livepeer/go-livepeer/blob/master/doc/install.md) includes a script ([`install_ffmpeg.sh`](https://github.com/livepeer/go-livepeer/blob/master/install_ffmpeg.sh)) to install a specific version of `ffmpeg` required by `go-livepeer`.

This script runs successfully on `Ubuntu 18.04 LTS`, but fails on `Ubuntu 20.04 LTS` as described in https://github.com/livepeer/go-livepeer/issues/1500

This grant application is to fund work to get `install_ffmpeg.sh` completing successfully on `Ubuntu 20.04 LTS`, such that users of this newly release LTS version of Ubuntu can build `go-livepeer` from source.

**Describe the problem you are solving.** 

Any user of `Ubuntu 20.04 LTS` will be unable to use the current documented build process to build from source.

This will exclude Ubuntu users who have upgraded to the latest (and also the latest _long-term-supported_ version of Ubuntu).

**Describe the solution you are proposing.** 

I propose to add a 300 LPT bounty to this issue using [Gitcoin](https://gitcoin.co/), to incentivise work to upgrade the `install_ffmpeg.sh` script

**Describe the scope of the project including a rough timeline and milestones** 

- Bounty hunter submits PR with proposed changes
- PR is tested on Ubuntu 20.04 by three independent community members
- If 2 of 3 confirm that it is working, pay out the bounty.

**Please estimate hours spent on project based on the above** 

Unknown.

**Comment by chrishobcroft** [comment]
Has there been any deliberation on this grant application proposal?

Also - I'm talking to some people who want to apply for grants - can I still tell them they will have a decision within 2-4 weeks, as published?

**Comment by nelsorya** [comment]
Hi @chrishobcroft, sorry for the delay on this one. We feel that a $100 LPT grant should be enough to get the Ubuntu 20.04 LTS implementation working. Given that Ubuntu 20.04 LTS is not a top priority for the development team at the moment, if you are willing to create a gitcoin campaign, the community committee node would be happy to fund 75% of this proposal leaving the remaining 25% to the community. 

Yes, 2-4 weeks for grant applications is still our goal, unfortunately, we missed this one.
