### ISSUE TITLE
[Sponsorship]: ETHRome

### ISSUE THREAD

**Issue by EclecticSamurai** [livepeer/Grant-Program#161]
### Referral

I know Livepeer since long time. Probably friends or conferences

### Point of Contact

Sarah

### Email

sponsor@ethrome.org

### Team Bio

Established in Rome in May 2022, [Urbe.eth](https://twitter.com/urbeEth) has swiftly emerged as Italy's foremost web3 community, paving its path across Europe. A vibrant hive of nearly 600 web3 enthusiasts, we boast a diverse mix of developers, lawyers, marketers, project managers, and business developers, all thriving on our Discord.

Our strength lies in our community-oriented approach, fostering collaboration through a myriad of engaging activities. These are designed to encourage experience sharing, deepen web3 understanding, and bolster collective growth.

In our relentless pursuit of sustainability and community participation, we've recently founded a non-profit organization. This initiative is a testament to our long-standing commitment to a grassroots approach, empowering our community members to shape our collective future.

Our [ETHRome](https://ethrome.org/) event, organized by a dedicated team of 20 from our community, exemplifies this commitment. Each member brings their unique skills and experiences to the table, ensuring the continued evolution and success of Urbe.eth.

**Core Team Bio:**
https://www.linkedin.com/in/simone-staffa-8b3b79158/
https://www.linkedin.com/in/pcdg/
https://www.linkedin.com/in/paolo-rollo/
https://www.linkedin.com/in/matteo-d-andreta%F0%9F%90%BA-a1a385175/
https://www.linkedin.com/in/francesco-cirulli/
https://www.linkedin.com/in/marco-galluccio/

**We have only one rule**: we don't talk about prices, we are totally against speculation and financial stuff.

**Our activities:**
- UrbeTalks: monthly meetups involving different speakers and topics (check previous ones here https://www.youtube.com/@urbetalks) with an avg of 40-50 attendees (the last one was part of the Swarm Summit calendar)

- UrbeCoworking: weekly coworking days in Talent Garden Ostiense (Rome)

- UrbeForStudents: we go to universities and talk about web3 and do technical workshops (https://www.youtube.com/watch?v=0KWSFUezPPA&list=PLtRePrZ9E4IgNq0p9GMSPVJ62J_K0uIj0)

- UrbeDelegations: we travel together to web3 events around the world, we participate in- and win hackathons! Past delegations: ETHDenver, ETHPorto, ETHGlobal Lisbon, ETHDam, SpaghettETH, ETHPrague. Next delegations: ETHBarcelona, ETHCC, Devconnect Instanbul.

- UrbeUnplugged: we interview key players shaping the future of the web3 ecosystem (https://www.youtube.com/watch?v=B1TECHeNubI&list=PLtRePrZ9E4IgQyNlaenUplNy1PU1tLNgV)

- UrbeAMAs: online sessions with special guests italian and non, talking about their projects or their experience (check this https://www.youtube.com/watch?v=XWym-553dtg&t=5s about hackathon or this https://www.youtube.com/watch?v=0XQ0NuPJMis with thirdweb)

- UrbeAperitifs: not to forget the best meetups aka casual hangout with drinks & networking

**Marketing strategies for the community and event:**
everything is happening organically, we are not spending money for online & digital advertisting, we just show ourselves at conferences and hackathons (we recently won a 1st prize bounty at ETHGlobal Lisbon and 5 1st prize bounties in ETHPrague), print and share some posters/stickers/ads and talk with the different stakeholders (attendees, hackers, partners, organizers, sponsors etc..). ETHRome indeed will be an hackathon for builders, by builders.

**Internal projects** (coming out from the hackathons I mentioned):
🧠 [Brian](https://devfolio.co/projects/brian-bb34)
👷[Bob is Safe](https://www.ethglobal.com/showcase/bob-is-safe-p2ba2 and https://taikai.network/cryptocanal/hackathons/ethdam/projects/clhxb1zdk121806501xznmsng7ur/idea)

### Previously Organized Events

9 UrbeTalks, 2022-2023, Rome, Barcelona
SpaghettETH MidTerm, 2022, Rome
ETHNaples, 2023, Naples (co-organized with SpaghettETH)

### Event Type

Hackathon

### Type of Sponsorship Requested

- [X] Financial
- [ ] Speakers
- [X] Mentors
- [X] Judges
- [ ] Other

### Are Workshops/Talks part of the event?

- [X] Yes

### Please share more information on planned Livepeer-related content

[ETHRome Deck.pdf](https://github.com/livepeer/Grant-Program/files/11895989/ETHRome.Deck.pdf)

### Please provide more information on planned talks and workshops (both confirmed and not yet confirmed)

We have 2 sidevents already set and 2 under development.

1) [Web3 Privacy Summit](https://prague.web3privacy.info/)
2) [UrbeTalks](https://www.youtube.com/channel/UC15_amrqg-rAKHlH8eYGD2Q)

3) Polygon Meetup
4) DarkFi Meetup

### Budget Requested

5 / 15 / 25 depending on your preferences

### Other Sponsors

Confirmed:

Gnosis
ESP
Sismo
Status
Base
FactoryDAO
ENS
PSE (privacy scaling exploration + semaphore)

Potential (not yet signed the contract):

Dusk Network
Espresso System
Tusima Network
Keyko
Panther
Secret Network
Aragon
The Graph
Starknet
ZKSync
Anoma
Hopr

### Start Date of the Event

10/06/2023

### End Date of the Event

10/08/2023

### Location of the Event

https://goo.gl/maps/iMXXvdJdzKXuezpJ7

### More Information on Location

We have both internal and external huge spaces, with dedicated rooms for workshops and sponsors.
The site is quite underground but easy to reach by metro or bus. Its nearby the center and a step away from Trastevere.

We also have 3 close venues for sidevents and closing party.

### Expected Number of Attendees

350/450

### Who is the Target Audience of the Event?

- [ ] Students
- [X] Developers - newcommers to space
- [X] Developers - expeienced builders
- [X] Academia
- [X] Livepeer Users/Community
- [ ] Broader Crypto Community
- [X] Potential New Users of web3 video/Livepeer
- [ ] Other

### How is the event tailored for the Target Audience?

This hackathon is entirely made by builders for builders.

### How do you plan to promote your event to potential attendees?

Already have 130 application. Word of mouth and community partners are doing a great job.
Of course during ETHBarcelona (where we are hosting a side-event), ETHCC and other meetups around Europe before the hackathon we will engage with multiple actors.

Plus being very active on Twitter.

### How can Livepeer connect with audience after the event?

Before the event during AMA sessions on our twitter spaces.
During the event by organizing a workshop (recreational or technical if you offer bounties), sponsoring coffee/wifi/pizza or even the closing party.
After the event we can find the best way together.

### Links

https://ethrome.org/
https://linktr.ee/urbe.eth
[ETHRome Deck.pdf](https://github.com/livepeer/Grant-Program/files/11896267/ETHRome.Deck.pdf)

**Comment by hansy** [comment]
Thanks for applying @EclecticSamurai! Unfortunately at this time, we're unable to sponsor your event, as awesome as it looks! For any future events, please feel free to submit again. All the best!
