### ISSUE TITLE
[Microgrant]: 

### ISSUE THREAD

**Issue by MartinMontero** [livepeer/Grant-Program#162]
### What is your project, and what problem does it solve?

inspired by all the recent adances by NVIDA & Epic. Some rendering, storage & distribution advances by some blockchain protocols. 

With [Epic's new releases](https://www.youtube.com/live/teTroOAGZjM?feature=share), [Adobe Firefly](https://www.adobe.com/sensei/generative-ai/firefly.html), [Ligthtwist Virtual Studio](https://www.lighttwist.com/), [Move AI](https://www.move.ai/), [NVidia Foundations](https://www.nvidia.com/gtc/keynote/?ncid=pa-srch-goog-896352), [RealityScan](https://www.epicgames.com/site/en-US/news/epic-games-releases-free-realityscan-ios-app-for-3d-scanning?sessionInvalidated=true), [ViewMagic](https://www.viewmagic.com/) & tools like [LumePad 2](https://www.leiainc.com/newsroom/introducing-the-lume-pad-2), iPhone 14 ProMax, and the Samsung S23 Ultra smart phones, could a [Mobile VolCap stage](https://en.pronews.com/special/2023021017242021.html) with much lower CapEX to get started, with better prices, faster production timelines and higher margins be possible?

For around $150k USD & 1/3 of the staff we can create something at the same level as what it took [large volumetric capture stages](https://arcturus.studio/blog/2022/07/27/2022-q2-volumetric-capture-stages-worldwide/) $3+ million USD to get. Lower overhead, faster production times.

The short of it is we think we can create a system for creating a VolCap studio that is much more cost-effective and more portable. 
By integration of this tech stack we have come up with.

### Link to public GitHub repo (if applicable)

https://github.com/FilmAvengersVP/Web3VirtualProduction

### Link to demo website (if applicable)

https://docs.google.com/document/d/19PVViGG2ew7f_qkD594M5ZWIPpg1PW_gv_jvFC0uDJc/edit?usp=sharing

### How is Livepeer used for this project?

1. For rendering the volumetric content to be production ready. 
2. hosting the produced shows and movies 

### How will you improve your project with this grant? What steps will you take to meet this objective?

To create the MVP during BuildSpace Season 4 of Night and Weekends](https://buildspace.so/#more) and there build our MVP using a Samsung S23 Ultra smartphone and a LumePad 2 as our foundational hardware tools. From our [downtown Vancouver hackspace](https://betakit.com/how-dctrl-creates-the-foundation-for-vancouvers-blockchain-companies/) with our 3 university partners.
Work with indie music, tv and film pros to launch it into the market. 

### Was this project started at a hackathon or another web3 event? Which one?

No. We tried to start it at ETH Waterloo but I had an emergency at my day job and could not attend the hackathon. 

So now the plan is to start it and promote it at ETH Paris. 

### Please describe (in words) your team's relevant experience, and why you think you are the right team to build this project. You can cite your team's prior experience in similar domains, doing similar dev work, individual team members' backgrounds, etc.

I have been working in Spatial computing since 2017. I have assembled a large advisory board of industry pros to help guide us. I have done the same on the Web3 side. 

The other team member is the 1st ambassador for SuperFluid.  

We will be working with the Future Primitive / Token Bound team locally in Vancouver. 
We will be building this out long term out of the hacker space that is the headquarters of Ethereum Vancouver. 

### What is the project’s expected deliverable at the conclusion of the grant time period?

What the Front End MVP for ETH Paris will look like

The MVP on Sunday night will be a 1 minute video from the ETH Paris Hackathon that showcases the Front end integration of tech stack.
It will have 3 different characters that showcase different use cases. All humans at the hackathon who are converted into characters.  20 seconds each:
1. A person who eats a thesaurus and gets turned into a Nouns character. Collectible on Lens
2. A person who eats cotton candy and is converted into a Bufficorn. Collectible on Lens
3. A person who gets a MetHuman version of themselves.  This is an NCP ERC 6551

The end user (consumer) is watching this on Orb (Lens mobile app) 
The end user (creator) is using Lens Studio integration with Unreal Engine (they will give a large grant for this)
Beem that makes a Web3 streaming platform. Integreat streaming and subscription payments via SuperFluid

### What is the one thing (the core mechanic) you want someone to do when using your deliverable?

Got to a Lens account, collect a video posted on there. rendered and hosted on livepeer, and watch it. 

### How will this deliverable benefit the Livepeer ecosystem?

It's a working title. LensFlix. 
A streaming platform built on Livepeer, Lens and Superfluid. 

Where creators can use our Web3 Volumetric capture studio kit to produce and collect episodes & movies. 
Have them streamed on our own front end video streaming platform. 

That is the long term, big goal, end game.

### What's your wallet address?

0x753144AA78E12D097925C8aA815C489e6EE8B22E

**Comment by MartinMontero** [comment]
Hi @hansy , the plans have changed. I am no longer going to ETH Paris. 

I will instead focus on the long term development of this MVP in our hacker space in Vancouver. with our 3 university partners. 
We realized this needs a longer term plan. A 3 day hackathon does not fit well with creating the project well built. We also have a the tech stack well picked based on what is best for the project rather than what will win us a prize at a hackthon. As this is long term project we been planning for months. Not an idea we want to try out and use it as way to learn from. Our goal as always been to create this into a commercial product. This also means many of the key members, who have core skills we need, can ot make most 3 day hackathons. They can work with us on a daily basis remotely on a longer term basis.  

Part of the MVP is helping create the infrastructure for how Livepeer can do rendering. We been talking with folks at Unreal Engine for that. For this MVP the primary use will be transcoding. So the videos can be uploaded to Lens via the Orb app. 

I messaged on Discord earlier to make this change from traveling to ETH Paris to staying in Vancouver to work on it at DCNTL. the hacker space that is also the home of Ethereum Vancouver.  So the funds will go to the further dev and fine tuning of the MVP into a V1. 

Can that change still be made? 

Thank you.

**Comment by hansy** [comment]
Makes sense! Unfortunately it sounds like your project might be a bit too early for us to fund. I think the Nights and Weekends program is an amazing place to hone and hack on the idea. Once there's something to refine, please feel free to come back with your exciting updates and re-open this application. We look forward to seeing what you build with your team!
