### ISSUE TITLE
Livepeer Analytics Dashboard

### ISSUE THREAD

**Issue by napolean0** [livepeer/Grant-Program#18]
**Give a 3 sentence description about this proposal.**

In Spark hackathon, Livepeer Broadcaster/Orchestrator focused [Analytics dashboard](https://dashboard.dappquery.com/livepeer) is built by [Dappquery](https://dappquery.com) team. We are an ideal small team with good mix of backend, frontend and blockchain engineers.

Below features are available on the current dashboard:

*Broadcaster Metrics*
- Broadcasters aggregated deposit/spend in `ETH & USD`.
- Bar chart to show top Broadcasters by current deposit value.
- Table displaying each broadcaster details including deposit/spend in current USD value.

![Broadcaster Graphs](https://duhy7tdvrc6v6.cloudfront.net/assets/img/dapps/livepeer/broadcaster.png)

*Transcoder Metrics*
- Transcoder aggregated stake metrics in `LPT & USD`.
- Bar chart showing top transcoders by their staked value in USD.
- Table displaying transcoder details including if they are active or not and stake value.

![Transcoder Graphs](https://duhy7tdvrc6v6.cloudfront.net/assets/img/dapps/livepeer/transcoder.png)

*Reward Metrics*
- Aggregated reward metrics in `LPT & USD`.
- Time series growth graph for rewards distribution

![Transcoder Graphs](https://duhy7tdvrc6v6.cloudfront.net/assets/img/dapps/livepeer/reward.png)

Based on Livepeer team feedback, we would like to extend the current dashboard with below time series graphs and metrics:

- Fee volume growth chart for 1 week. 
- Fee volume growth chart all time.
- Total stake growth chart for 1 week 
- Total stake growth chart for all time.
- All time total fees.
- Total ETH locked up dedicated to broadcasting.
- While calculating the USD values on the dashboard, use historical `ETH => USD` or `LPT => USD` prices.

**Describe the problem you are solving.** 

- Implement time series graphs and aggregated metrics on current dashboard  to see the growth of fee expenditure on the livepeer network in both `ETH & USD`. 
- ETH price fluctuations might give a wrong idea as the current dashboard shows USD value based on current `ETH => USD or LPT => USD price`. [Coinmarketcap historical quote API](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyQuotesHistorical) will be integrated to display the historical USD value.

**Describe the solution you are proposing.** 

- Store incremental time based metrics like fees, stake value on API backend.
- Implement efficient transformation logic while storing time based data so that data can be queried efficiently.
- Use the time based data from API backend for displaying time based charts and metrics.
- For historical  `ETH => USD` or `LPT => USD` price to be displayed on dashboard:
       - integrate [coinmarketcap historical quote API](https://coinmarketcap.com/api/documentation/v1/#operation/getV1CryptocurrencyQuotesHistorical) and store on API backend.
       - Use the stored historical USD value for display on dashboard. 

**Describe the scope of the project including a rough timeline and milestones** 

Scope of the project would be to deliver the following specifics:

- Deliver above mentioned time series graph and aggregated metrics on the current dashboard.
- After project completion, maintaining and bug fixes based on user feedback for 3 months.
- For 1 year support if the system goes down.

**Please estimate hours spent on project based on the above** 

- Estimate will be around 3-4 weeks of effort covering:
   - Architecture and design of API backend for efficiently storing time based above data.
   - Incremental development for above mentioned metrics and iterate based on feedback.
   - Manual testing.

- There is also cost to running and maintaining the dashboard on cloud. Request to consider fee for maintenance over the course of 12 months.

**Comment by adamsoffer** [comment]
Thanks for the proposal @napolean0. We're excited to surface some of these market dynamics in a dashboard. The committee will review this proposal and respond shortly.

Some quick feedback: we're big fans of Dune Analytics - what are your thoughts on using Dune to surface these data points instead of a custom dashboard? Something [along these lines](https://explore.duneanalytics.com/public/dashboards/c87JEtVi2GlyIZHQOR02NsfyJV48eaKEQSiKplJ7)?

One of the benefits of using Dune is that it can cut down on maintenance costs as well as time to build.

**Comment by napolean0** [comment]
Thank you @adamsoffer  for the suggestion. I checked Dune and here is my take on it:

- Dune doesn't have subgraph integration. Current [Livepeer dashboard](https://dashboard.dappquery.com/livepeer) is integrated with the Livepeer [subgraph](https://thegraph.com/explorer/subgraph/livepeer/livepeer) which is written very nicely.
  Our Ingestor tool(data extraction tool) has integrations with subgraphs. It extracts data from Livepeer subgraph and transforms it to be queried efficiently.

- Subgraph integration gives a lot of power to accommodate custom requirements and also upgrade to future changes. 

- Data related with broadcaster fees for time series graph is already present in the subgraph.
   e.g. `WinningTicketRedeemed` has timestamp column which will be needed for broadcaster overall/weekly fees time series graph.
  Implementation wise it needs to be stored efficiently from the subgraph for a time series graph. 
  I feel time wise it's faster to implement with subgraph integration. 

- Each of current Livepeer dashboard metric/card/graph/chart can be embedded on any app for integration. e.g.
  Broadcaster details table can be embedded on any app using [this link](https://dashboard.dappquery.com/d/i2B7yVIGz/livepeer?orgId=1&from=1535903472129&to=1599061872129&panelId=21&fullscreen&kiosk&presentation_mode)
  This is really helpful for Livepeer community who can embed any of dashboard widget for display/analysis.

- The solution which we are building will later(Phase2 or Phase3) on can be exposed by APIs(GraphQL/Rest) also. Idea behind this is that it can be integrated by any app on Livepeer ecosystem.

- Dune free version has "DuneAnalytics" watermark on almost every graph/chart which I think should not be preferred. It has a fixed cost of $390 per month to remove the watermarks and customizations which I feel is very costly. Please see their [pricing](https://www.duneanalytics.com/pro).

- Historical USD value integration will be a nice addition for data accuracy. I tried to find in their docs if they support that but couldn't find.    

- In later phases(Phase2 or Phase3) we can also support per Broadcaster/Orchestrator dashboard. In the [Livepeer dashboard](https://dashboard.dappquery.com/livepeer), a dropdown with all Broadcasters/Orchestrator address can be shown. On selecting any of Broadcaster/Orchestrator from dropdown, specific Broadcaster/Orchestrator dashboard will be rendered.

We will release the listed features for phase1 incrementally on weekly/bi-weekly basis. 3-4 weeks is the final outcome of all the features. Considering above points in mind, I recommend to extend the current dashboard for flexibility and customizations.

Thanks

**Comment by napolean0** [comment]
Hi @adamsoffer 
What are your thoughts on above points?

**Comment by adamsoffer** [comment]
Thanks @napolean0. This all sounds good. Glad you're finding the livepeer subgraph helpful. The committee has a call this Friday. We'll discuss your proposal follow up with any feedback.

One thing to keep in mind is that we plan on displaying most of these charts in the livepeer explorer in the near future. Is your dashboard written in React? It would be great if you could build these charts as reusable components (using something like [recharts](https://recharts.org/en-US/)) which the explorer can then theme/customize and reuse.

**Comment by napolean0** [comment]
Sure @adamsoffer. Displaying the graph/charts components in explorer would be great 👍 
We can support embedding of the components. Below small html can be inserted in explorer with dark/light theme. All components can be enabled for embedding.

- Light Theme Embed Component
```
<iframe src="https://dashboard.dappquery.com/d-solo/i2B7yVIGz/livepeer?orgId=1&from=1536531045555&to=1599689445555&panelId=21&theme=light" width="1350" height="600" frameborder="0"></iframe>
```

- Dark Theme Embed Component
```
<iframe src="https://dashboard.dappquery.com/d-solo/i2B7yVIGz/livepeer?orgId=1&from=1536531045555&to=1599689445555&panelId=21&theme=dark" width="1250" height="440" frameborder="0"></iframe>
```
Please find attached working examples.

[broadcaster_details_component.zip](https://github.com/livepeer/Grant-Program/files/5198216/broadcaster_details_component.zip)

**Comment by napolean0** [comment]
Hi @adamsoffer 

Any update after your call to move this project forward?

**Comment by adamsoffer** [comment]
Hey @napolean0 - thanks again for submitting this proposal idea. After discussing with the committee we realized that between the analytics dashboard on scout.cool and some of the recent fee charts created on Dune Analytics (which also account for historical USD prices), we felt it doesn’t make sense to fund another analytics dashboard. If you have any other proposal ideas please feel free to open another issue.
