### ISSUE TITLE
Orchestrator Performance Based Subsidy Program

### ISSUE THREAD

**Issue by nelsorya** [livepeer/Grant-Program#23]
**Give a 3 sentence description about this proposal.**

A performance-based subsidy program that distributes ETH rewards to the top 10 orchestrators based on performance scores on the leaderboard. 

**Describe the problem you are solving.** 

In the Livepeer network today, orchestrators must “call reward” every round (roughly every 24hrs) to claim their inflation reward and network fees for themselves and their delegates. The Livepeer network’s economic design relies on orchestrators being incentivized to call reward to receive both inflation rewards and network fees. Gas costs on the Ethereum network today are high in $ terms during periods of high Ethereum network congestion and as orchestrators pay the brunt of this cost when they call reward, many orchestrators are opting to not call reward during periods of high gas prices. 

This negatively impacts orchestrators who are already incurring costs for running infrastructure, particularly those who are running highly performant setups, while also hurting delegators who are not receiving inflation rewards and network rewards when their orchestrators do not call reward. 

While this subsidy program does not solve the impact of Ethereum congestion on Livepeer, the subsidy program is a show of support for orchestrators which are calling reward daily and an additional incentive for orchestrators to get into the top 10 leaderboard. 

**Describe the solution you are proposing.** 

A performance-based subsidy program paid out in ETH to subsidise gas costs for the top-performing orchestrators on the leaderboard funded through an LPT grant. The proposed grant amount is 6.72 ETH paid out in ETH each week over 4 weeks to the top-10 performing orchestrators each week.

Based on our observations, the average cost of calling reward in the past 30 days is around 0.048 ETH. 6.72ETH spread over 30 days amongst the top 10 orchestrators would give every orchestrator 50% subsidy for the cost of calling reward. Distributed in ETH Only Orchestrators who call reward every round will qualify for the subsidy program. 

The goal of this program is to subsidise top-performing orchestrators to continue calling reward during periods of elevated gas prices. 

**Describe the scope of the project including a rough timeline and milestones** 

**Timeline**

- One week for community feedback from the 03/19 to 03/26
- The program will last for 4 weeks starting on 03/29/21 and ending on 04/25/21

- The program will be divided into 1-week rounds
      - Rewards will be distributed by a program administrator account that holds the grant ETH
      - Weekly performance will be determined by the average global success rate for the week
      - Reward will be distributed at the END of each week
      - Only orchestrators who have call rewards consecutively for the whole week will qualify for the reward
- If an orchestrator in the top 10 performance leaderboard does NOT qualify, the reward will go to the next best orchestrator that has a success rate above 50%
      - The administrator will distribute the rewards to the best of their ability based on the rules for a round and the leaderboard 
        data, but given that this program is experimental and the leaderboard infrastructure is fairly new, the administrator does not 
        provide any guarantees to participants that take actions based on the rules of the program
- The reward distribution rules will be fixed for the duration of around
- The reward distribution rules can change in-between rounds
      - Any changes to the rules for the next round will be announced at least 2 days before the start of the round
      - The reasons for allowing reward distribution rules to change in-between rounds are:
      - Adjust distribution based on results of previous rounds and community feedback
      - Allow for updates to leaderboard scoring that capture aspects of performance that are currently not incorporated into 
        scoring (i.e. capacity/scale)

**Metrics To Track**

- On a weekly basis, the number of orchestrators that are calling reward
- On a weekly basis, the number of orchestrators that met the threshold total score
- On a weekly basis, the number of newly registered orchestrators
- On a weekly basis, the total scores of the top 5 orchestrators in each region

**Please estimate hours spent on project based on the above** 

The program will last for 4 weeks and an additional week after its conclusion will be used to finish compiling metrics for the program.

**Call for Feedback**
 
We have allowed one week before the program begins for community feedback on this proposal and are open to community input on how this program could be improved to meet it’s stated goals.

**Comment by kyriediculous** [comment]
Thanks for writing this up, I have a few concerns. 

- What about the matthew effect? Smaller stakes aren't going to call reward even if they get 50% subsidised
- There are useful nodes outside of the top 10 because they are not ran from datacenters.

**Comment by dob** [comment]
Looks great in theory. My first reaction upon reading it is that subsidizing only 50% won't matter for new entrants with small stakes. It would be great to see an at or near 100% subsidy if possible for some period of time that bridges to LIP-56.

**Comment by nelsorya** [comment]
@kyriediculous @dob thanks for sharing your thoughts and feedback on this proposal. After thinking more about this and discussing it with the others on the grants committee, we are going to reevaluate this proposal until after LIP-56 is live where we feel we can explore a more comprehensive subsidy program.

**Comment by kyriediculous** [comment]
Something useful after LIP-56 could be to only subsidise reward calls for nodes it is not profitable for. Because LIP-56 is already addressing the cost of reward calls. The majority of accounts this wouldn't be profitable for is those with very low stakes (we are probably talking less than a thousand here). 

This means  LPT_amount * reward_cut * LPT/ETH price < Gas cost * gas price
