### ISSUE TITLE
Tender Livepeer Token (tLPT)

### ISSUE THREAD

**Issue by kyriediculous** [livepeer/Grant-Program#26]
**Give a 3 sentence description about this proposal.**

The Tender protocol does liquid staking and yield aggregation for web3 projects like Livepeer, The Graph Network, NuCypher, Polygon, ... . It provides a missing link between the booming world of DeFi and the nascent but still overlooked web3 space. 

DeFi became popular with the rise of Yield farming, the act of supplying liquidity to receive token incentives. These strategies quickly became more complex and due to rising gas fees it quickly became a whale game. Until the advent of yield aggregators, automated on-chain strategies that would aggregate user deposits and yield farm on them. 

An analogy can be drawn to the web3 space, where you can stake to receive yield. This process was very simple in the early bootstrapping days of networks as profitability and performance between node operators wasn't distinguishable until these decentralised web3 protocols actually started seeing usage. Now the complexity of staking and optimally allocating funds is quickly increasing as performance and earnings differences are quickly becoming visible. When you add the complexity of navigating the delegation markets on top of rising gas prices, funds management (some protocols pay out rewards in tokens other than the native token such as Livepeer and Keep network) and  risk management (staked funds are locked) one can quickly see the benefit of a **liquid staking yield aggregator**. 

As a result of the aforementioned complexities of staking (as well as other potential causes), capital has a hard time finding its way to the well performing nodes on the network. We believe that Tenderize as a community governed project allows to optimise this and strengthen the symbiotic relationship between capital providers (token holders) and node operators (hardware providers) for web3 networks. 

**Describe the problem you are solving.** 

To summarise the introduction, Tenderize aims to solve the following problems: 
- Reduce the complexity and cost of staking for token holders
- Make staked funds liquid through a derivative to bridge the gap to other DeFi protocols

**Describe the solution you are proposing.** 

We are looking to build a Tenderize integration for Livepeer. 

In short this will include the following features: 

- A set of smart contracts to enable the aforementioned features
    - **Tender Livepeer Token** (tLPT) , a staking derivative representing staked funds 1:1 (1tLPT == 1 LPT)
    - **Livepeer Tenderizer** , the protocol specific integration to manage funds deposited into the Livepeer protocol
    - **Elastic Supply Pool**, a liquidity pool for swapping between tLPT and LPT that avoids impermanent loss when staking rewards are earned
    - **Controller**, the user and admin entry point and owner of the above set of contracts. 
    - **Livepeer Ranch**, where users can deposit their tLPT/LPT liquidity pool tokens to receive incentives for providing liquidity (liquidity farming).
    
    ![](https://i.imgur.com/UccJEGj.png)

    For a more detailed description of the workings of the Tender protocol check out this hackmd doc: https://hackmd.io/DouAZ0PsSiGr3BkJtoCCcQ?both
  
- A front-end application to deposit, withdraw and manage deposits into Tenderize (both for staking itself as for liquidity farming). 

- A subgraph implementation to serve as the data layer for user dashboards and data analytics of protocol performance. 

**Describe the scope of the project including a rough timeline and milestones** 

1. Smart contract MVP (75% DONE)
2. Public Testnet Deployment (75% DONE)
3. Front-end application with basic functionality linked to public testnet (40% DONE)
4. Subgraph implementation
5. Integrate subgraph data into front-end
6. Improve test coverage and audit
7. Launch on mainnet + bootstrap liquidity pool 

**Please estimate hours spent on project based on the above** 
1-3: 2 weeks (3 people)
4-5: 2 weeks (3 people)
6-7: 4-5 weeks (2-3 internal testing and internal audit, 1-2 weeks external audit)

**Additional Context**
ETHOnline submission (October 2020), includes video demo of an early version of the protocol and app https://hack.ethglobal.co/showcase/tenderize-me-recr3dMejGdwaMJ82

Most of the grants funds will be spent on bootstrapping the liquidity pool with LPT and tLPT. There is also the possibility of a solution whereby Livepeer Inc. or The Grant node remains custody over the LPT/tLPT to (partially) bootstrap the liquidity pool (which earns yield in turn!). 

The other funds will be spent on expenses such as contract deployments and security audits.  

**Team**
- Nico Vergauwen
- Reuben Rodrigues
- Frederic Moser

**Comment by kyriediculous** [comment]
Live demo on rinkeby: https://tender-app.vercel.app/stakers/livepeer

**Comment by nelsorya** [comment]
Hey Nico, thanks for sharing this, very interesting. How would this differ to existing staking derivative platforms like Lido?
We would like to suggest posting this somewhere like ETH Research first, to get broader Ethereum community feedback on the proposed design. 

For a proposal like this we could split this into the 3 phases you mentioned above, we would thinking broadly $15k for the first phase, $15k for the second phase and $20k for the final phase, so $50k all up. We would want to see some of these funds allocated for the design on the user interface. Do you have someone planned for that already or could we link you with a resource for this? In addition to the grant, the community node would be willing to delegate some LPT and potentially LP in the pool to help bootstrap liquidity for this.

**Comment by kyriediculous** [comment]
> Hey Nico, thanks for sharing this, very interesting. How would this differ to existing staking derivative platforms like Lido?
We would like to suggest posting this somewhere like ETH Research first, to get broader Ethereum community feedback on the proposed design.

Hi Nelson, thanks for the feedback. We have been through a couple of hackathons with the project already (currently doing our fourth) which allowed us to validate the idea and design with multiple people in the community and potential users. In our backpack: 
- 1.Inch exchange runner up prize for coolest hack at ETHOnline 
- Keep Network grand prize for allowing delegated staking (plus all of our other features) at ETHOnline
- Matic Buidl-and-earn invitees
- Solana DeFi hackathon third place 
- Currently participating in 0xHack 

From a high-level Lido and similar competitors have been focussing exclusively on ETH2. They have been live for months now and have not been able to produce additional integrations. Other staking derivative platforms such as StaFi have promises of cross-chain liquid staking but have yet to make good on those. Tenderize has already 3 integrations lined up that are undergoing testing and will be live on public testnet soon: Livepeer, The Graph and Polygon/Matic. We don't plan to stop there. Every team member of Tenderize has a strong belief in the web3 ecosystem and it is from that core belief that we build for web3 specifically, which everyone else overlooks. 

On a technical level Lido is fully custodial and centralised. The users of Lido have to trust the custodian to spend their funds correctly (i.e. stake it towards nodes in the queue). The Lido system itself depends on an oracle to report ETH2 funds back to ETH1. In Tenderize there are no oracles or custodians, everything happens fully on-chain and remains on-chain.

While Tenderize has some actions reserved for governance, it is completely trustless and unstoppable. It also allows for emergency exits through manual unstaking rather than having to go through liquidity pools. 

> We would want to see some of these funds allocated for the design on the user interface. Do you have someone planned for that already or could we link you with a resource for this?

The team is going to participate in HackMoney in june to deliver an application that includes a subgraph. We'll be looking for a UX/UI designer to work with us during this event and maybe beyond. 

Keep an eye out for our first public testnet release next week !

**Comment by kyriediculous** [comment]
Tenderize won the Polygon DeFi bounty at 0xHack with its liquid staking solution for Matic https://twitter.com/0xPolygon/status/1400475586305294341

**Comment by nelsorya** [comment]
Hey Nico, that's great to hear. After discussing more with the grants committee, we have decided we would like to fund this grant, but linked to the milestones we mentioned above. Could you provide an ETH address or reach out to me privately on discord for the first milestone grant

**Comment by wanyy062** [comment]
can you send me somen test token Lpt , thanks a lot  0x331179a191656164ddfe3248b06bf21876cBB82F
