### ISSUE TITLE
How to set up an Orchestrator node - Video Series

### ISSUE THREAD

**Issue by Titan-Node** [livepeer/Grant-Program#27]
**Give a 3 sentence description about this proposal.**
This proposal is for a step by step video guide on how to start a Livepeer Orchestrator. 
Currently there are two forms of tutorials for setting up an Orchestrator, first is the official documentation for Livepeer and the second is a written guide on medium.
This would be a third form of media to help bring new Orchestrators into the ecosystem.

**Describe the problem you are solving.** 
People prefer different forms of educational material for on-boarding. Livepeer would benefit from a video series on how to get their Livepeer Orchestrator up and running. Many redundant questions asked in discord could be answered in a video.

**Describe the solution you are proposing.** 
This would be a video series going through the set up process of setting up their first Livepeer Orchestrator node.

**Describe the scope of the project including a rough timeline and milestones** 
Video topics include:

1. How to set up a Livepeer Orchestrator
 a. requirements
 b. hardware
 c. benchmarking
 d. installation

2. How to set up Prometheus/Grafana
 a. installation
 b. troubleshooting

3. Livepeer Orchestrator Advanced Configuration
 a. O/T O+T set ups
 b. Dual Mining
 c. Private Pools vs Public Pools
 d. Set Pricing and other metrics

**Please estimate hours spent on project based on the above** 
Each video takes 12 hours to complete.
Roughly 36 hours for 3 videos.

**Demonstration of capability**
Here are some examples of previous videos and their quality.
https://youtu.be/6nZrZHz12-g
https://youtu.be/PH1kpXowXBY

**Comment by adamsoffer** [comment]
Hey @Titan-Node! Thanks so much for submitting this proposal and apologies for the delay! The grant node committee is excited about a video series for orchestration set up and will get back to you by EOW with a response.

**Comment by adamsoffer** [comment]
@Titan-Node - thanks again for submitting this proposal. The grant node committee met today (@nelsorya, @ericxtang, and myself) and we'd like to fund the 3 video guides with a $3k grant in LPT. We propose sending $1k in LPT to your wallet upon submission of each video in the series (exact amount of LPT to be determined based on the 30 day average price upon submission).

How does this sound?

**Comment by Titan-Node** [comment]
Hi @adamsoffer - Thank you very much for the consideration and of the grant node committee collectively. 
Yes I would like to accept this offer, I can get started on this right away.
Please let me know if you require any further information or have any questions. My email is Hello@Titan-Node.com
Thank you again

**Comment by adamsoffer** [comment]
Fantastic. Sounds good. Likewise, let us know if there's anything you need.

**Comment by Titan-Node** [comment]
The first video has been completed and published. It can be viewed here:
https://youtu.be/-gfSkX5xL-U
I will be sharing it and promoting it through my channels and be available on discord to answer viewers questions.
Please let me know if you have any questions or comments about the video.
Thank you

**Comment by adamsoffer** [comment]
This is fantastic 🔥

This first grant has been sent to the Titan Node address based on the [30 day average USD price](https://docs.google.com/spreadsheets/d/1nDOCYd8mwrc4NfPI5Y1W1BQMIyRS2f2BMI4g2Y1v2N4/edit?usp=sharing). 

https://etherscan.io/tx/0x38e903816504b00fc794d6fcfb5a971574b558e67a02c26677c5fac4c01d0be0

**Comment by Titan-Node** [comment]
The second video has been completed and published. It can be viewed here:
https://youtu.be/Cpt9Arpzhg8
Please let me know if you have any questions or comments about the video.
Thank you

**Comment by Titan-Node** [comment]
Third video is now live and can be viewed here:
https://youtu.be/aipCGJVwT0s
Please let me know if you have any questions or comments about the video.
Thank you

**Comment by adamsoffer** [comment]
Video 2 and 3 came out great. Thank you for your amazing work! Here's the [tx receipt]( https://etherscan.io/tx/0x2bc16aa00f53a5c4e099c52b12f1d6a2c70b1e4a513e8cb1ea3043ef4630d12b) for the second video based on the [30 day average](https://docs.google.com/spreadsheets/d/1yCC8uYykI4j67bMUPcLtPjAojYHYBTmoYOfA4hEeQF4/edit?usp=sharing). Payment 3 forthcoming.

**Comment by Titan-Node** [comment]
Hi @adamsoffer thank you for putting this through!

I have split up video 3 into two videos as there is still lots of content to go through and I needed to cover basic commands before moving onto the advanced topics.

Video 3 title is: Basic Livepeer Commands

and the 4th video I propose is: Advanced Livepeer Configurations

Video 4 will be going through more theory and ideas on how to improve the Orchestrator node.

Video 4 will include the following topics:
1. O/T and standalone Os
2. Dual mining
3. Livepeer Pools
4. Geo-locating DNS

If this sounds good, I would like to propose a 4th video for funding in the same fashion as the previous 3 videos.

In addition I have been asked by new community members to include the videos on Livepeer.org official website as they found them really helpful. Just a thought for the future.

Thank you

**Comment by Titan-Node** [comment]
This is the final video in the series for now.

https://www.youtube.com/watch?v=TCykA53RaJY

Will be uploading the 4 videos in multiple places such as Youtube, Udemy, Medium and other platforms that come to mind.

If you have any suggestions on where I can upload them to further reach new-comers please let me know.

Cheers

**Comment by adamsoffer** [comment]
Amazing! Thanks @Titan-Node. And good call re: posting it to other platforms. The committee will send the final payment this week.
