### ISSUE TITLE
SEO Optimization

### ISSUE THREAD

**Issue by anthonyten4** [livepeer/Grant-Program#28]
**Give a 3 sentence description about this proposal.**
Livepeer properties can use an improvement around SEO.  This will allow Livepeer to be ranked higher in organic search results, thus driving more users to Livepeer.  Doing SEO optimization is low hanging fruit for growing the Livepeer project.

**Describe the problem you are solving.** 
Livepeer is not yet optimized for SEO.

**Describe the solution you are proposing.** 
SEO optimization, which involves keywords, content, and metadata improvement.

**Describe the scope of the project including a rough timeline and milestones** 
This is an on-going process with a monthly cadence.

**Please estimate hours spent on project based on the above** 
10 hrs / month.  100LPT / month.

**Comment by ericxtang** [comment]
Hi @anthonyten4 - the grants committee had a discussion about this proposal, and we wanted to see if you would be happy with a 4-month long grant of $2000 of LPT per month.  If that works for you, we can start immediately.

**Comment by anthonyten4** [comment]
Eric,

Thanks for update. Can we revisit a token grant after the 4 months in
regards to performance marketing or other activities?

-T

**Comment by ericxtang** [comment]
Absolutely.  Happy to revisit a token grant after the 4 months in regards to performance marketing and other activities.

**Comment by anthonyten4** [comment]
Great, let’s move forward with this agreement. Are we able to make it
retroactive to July when we started?

-T
