### ISSUE TITLE
Atlantis World x Livepeer

### ISSUE THREAD

**Issue by mkshnik** [livepeer/Grant-Program#30]
LivePeer <> Atlantis World Grant Funding Request

Total grant funding request = 250 LPT 
Payable to 0x8Ca2FBF18c57999d07109eF257d5340746EFBC9D

Summary
Atlantis World would love to integrate LivePeer technology inside of our lightweight virtual world (pixel metaverse) to enable a multitude of Web3 native live streaming events, workshops, and webinars where we plan to host top players + thinkers in the space. 

In the future, we will also build interactive learning modules centred around LivePeer in our Web3 Academy and add a portal to LivePeer inside of our city.

Introduction to Atlantis World
Atlantis World is a pixel metaverse with token-gating, video calling, gamified DeFi + in-game DAO voting. We believe that as much as metaverse should be open, it should be accessible (lightweight) + plug into DeFi applications in a fun / gamified way. 

Existing virtual worlds are inaccessible because they have a 3d/immersive focus, resulting in a high-cost barrier to entry (since in order to enjoy seamless loading experience, users must go out + buy the latest iPad / gaming pc, this technology / hardware is neither inexpensive or readily available globally). 

Also, we believe that we are missing a huge onboarding opportunity into DeFi as a collective space by not gamifying leading dApps / protocols inside of virtual worlds with additional interactive learning modules.

We are adding video/audio calling capabilities to user-owned, token-gated spaces inside of our pixel metaverse for communities to interact with each other; whilst gamifying DeFi protocols like Aave / Yearn / Sushi, curating interactive learning modules in our Web3 Academy + gamifying DAO voting.

To provide further value to the space, we’re exploring adding tooling products like CoinGecko to the Atlantis experience, as well as transforming our favourite NFT avatars into versatile, hyper-composable playable characters by building open source sprite sheets + full walk cycles ready to be used by those communities not just in Atlantis, but in all of pixel metaverse.

We’re also building public spaces + rethinking decentralized governance in collaboration with our community. We plan to build the City of Atlantis -> ​​a buzzing, entrepreneurial capital owned / governed by its users / inhabitants, where ETH is money + creative culture is king. If users want to open a business, like a virtual cafe, music venue, movie theatre (think, LivePeer!) or an independent art exhibition, they'll be able to apply to occupy land for free until they're seen to be making revenue (which is always verifiable on-chain). 

Deliverables 
We plan to benefit the wider LivePeer ecosystem + build innovative products using LivePeer API by:
Adding live streaming / broadcasting to enable a multitude of virtual events, workshops and webinars for top players in the space during ETHOnline hackathon.

Next steps to explore:
Creating a LivePeer powered movie theater inside of Atlantis.
Adding a portal to https://livepeer.org/, a Livepeer booth (where users can learn more) and a custom building to Atlantis City.

Additional Support Requests 
Mentorship;
Tech support if needed (docs should be sufficient) -> IE integration;
Joint marketing efforts.

Links
Website: https://atlantisworld.io 
Discord: https://discord.gg/TYA2kmzJq6 
Twitter: https://twitter.com/atlantis0x 
Hack FS submission (Won Best DeFi Project on Polygon):
https://showcase.ethglobal.co/hackfs2021/atlantis-world
Yearn announcement: https://twitter.com/iearnfinance/status/1432387438014435332
The Defiant featuring Yearn <> Atlantis + Aleksandr from Axie Infinity:
https://thedefiant.io/yearn-degens-metaverse/

Demo (v0.4): https://demo.atlantisworld.io 
// we're currently just debugging some huge updates before pushing them to the main link, such as buying and viewing NFT collections on Rarible, as well as auctions, minting and crafting (even basic treasure hunt feature) and depositing into Yearn vaults.

// We're also exploring adding other DeFi products and chains, such as CREAM on Fantom, and even Aave on Avalanche, whilst building v2 of our Audius widget (so users can sign in and play their own music / playlists) and adding a billboard of crypto market data powered by CoinGecko; v1 will feature live price feeds of ETH, YFI, MATIC, AUDIO, PERP, BAL and any other ecosystem partners we onboard (such as Livepeer / LPT).

Final Notes
Our current ecosystem partners have social media communities of 1M+ that will be invited to beta test Atlantis and become our early adopters. Joint marketing is a core part of our GTM and we’re onboarding new partners at an unprecedented rate. 

We also plan to enable network effects for all parties involved, by incentivising and encouraging different partner communities to try each other's products inside of Atlantis. As well as this, we’ll also target non crypto natives with interactive learning for DeFi and other Web3 building blocks like DAOs, blockchain games and blockchain wallets.

We currently have 1000+ early access sign ups, and 1.3k super active Discord users, with 700+ of those actually mobilising to make a contribution to our GR11 grant. We raised a total of over $10k (including matching), with intentionally little to no sharing from our side.

**Comment by ericxtang** [comment]
Hi @mkshnik - thank you for submitting this great proposal!

The grants committee discussed this proposal and really liked the theme.  We think the big opportunities are:
1. Showcase Livepeer in front of a wide audience, a lot of whom are new to crypto.
2. Showcase the opportunity of streaming in/out of the metaverse, which is one of the focus areas for the grants program.
3. Increase the number of mins processed by the Livepeer protocol.

We want to suggest the following structure:

**1. The grant amount will be $4700 worth of LPT**
This roughly 250LPT based on the avg LPT price in the last 30 days.

**2. The grant will be distributed based on the following milestones**
* $1175 of LPT will be release up front (25%)
* $1175 of LPT will be released upon finishing the implementation (25%)
* $1175 of LPT will be released upon finishing the first 100 hours of video broadcasted through Atlantis World
* $1175 of LPT will be release upon completion of the first 500 hours of video broadcasted through Atlantis World

Note - the 500 hours of broadcasting usage on the livepeer.com has a total cost of $150, payable via credit card.

Please let us know if you have any questions or concerns.

**Comment by shann7** [comment]
Hey @mkshnik! Shannon here, the new Head of Community at Livepeer helping to facilitate our grants process. I joined @ericxtang yesterday for a call with your teammates @revmiller and @cj_atlantis.world. Just circling back on next steps to get your grant rolling :)  ​

I hope we clarified your questions about the Livepeer public network vs Livepeer.com API. We are super excited and supportive of Atlantis hosting its own Livepeer broadcasting node in future, but the scope of this grant is to use our hosted API and explore ways to incentivize the Atlantis community to fund those streaming costs

With that clarification, my understanding is that the above structure looks good; you were going to circle back internally to  make sure your resources are aligned to meet those milestones and come back to us with a workplan.  If there's anything else you need answered, please let me know!
