### ISSUE TITLE
ColorPixels Decentralized Streaming & NFT platform 

### ISSUE THREAD

**Issue by antoniomarquis** [livepeer/Grant-Program#33]
**Give a 3 sentence description about this proposal.**

ColorPixels is a decentralized live streaming platform that enables creators to monetize via the minting of NFT clips during their live events. ColorPixels won Livepeer 3rd Place, Livepeer Pool Prize, and Best use of the Rarible Protocol for EthGlobal Hackathon.

**Describe the problem you are solving.** 

Live Streaming reached new heights in 2020 and has continued to grow in 2021. But the way creators earn money hasn’t evolved as rapidly. Many have hopes of making a living from streaming daily, however platforms like Twitch and YouTube are still not transparent about payments for creators. 

**Describe the solution you are proposing.** 

By integrating ColorPixels with Livepeer's decentralized video and minting NFTs with the Rarible Protocol, we open the world of live streaming to transparent and innovative payments for creators.

**Describe the scope of the project including a rough timeline and milestones** 

Our focus is allowing the creator to control their live streaming experience and mint NFTs.
Phase 1. Stream Dashboard:
    1. Live stream to audience via ColorPixels app.
    2. Multicast live stream to Facebook, YouTube, and Twitch.
    3. Select up to 60 seconds of video during live stream
    4. Add clip to NFT collection on OpenSea and Rarible 
    
Phase 2. Streaming Profile: The streaming profile is social landing page for the creator. 
    1. Archive previous live streams
    2. Display NFTs made from previous live streams
    3. Display current live stream 

Cost Breakdown:
1. Stream Dashboard ($4,000 in LPT)
2. Streaming Profile ($4,000)
3. Community Feedback ($4,000)
4. Success Metric Bonus ($1,000)

If time permits, we will explore adding graphics and filters during a live stream.

**Please estimate hours spent on project based on the above** 

We estimate 240 hours to completion. 120 for the dashboard and 120 for the streaming profile.

**Comment by antoniomarquis** [comment]
ColorPixels has taken a deeper look at our grant proposal. We would like to make the following updates: 

1. The focus of minting live stream NFTs will shift from viewer to creator initially.  Because there is an abundance of edge cases with viewer minting, we will master making video clip NFTs by creating the tools for the creator that’s delivering the live stream. Milestone #1 consists of developing a streaming dashboard that delivers video streams to ColorPixels, Facebook, YouTube, and Twitch. From the dashboard a creator can clip, mint, and store NFTs during a live event. After the completion of Milestone #3 we will revisit Milestone #1 to add clipping and minting for viewers. (Estimated 3 Weeks)

2. Milestone #2 Metaverse Streaming - ColorPixels users will be able to stream in both the real world and the metaverse. We are working to identify which metaverse projects will enable us to integrate. We will test this functionality with a music performance/concert. (Estimated 3 Weeks)

3. Milestone #3 Decentralized Streaming Profile — This profile will act as social landing page and live streaming feed for the creator. Though we will stream to the major platforms it is the goal for creators to come to ColorPixels, setup up their profile and dashboard, purchase a url like “thehottestsinger.crypto” for the audience to visit, and begin streaming. The URL will route to the creator’s decentralized streaming profile. We estimate 6 to 8 weeks of development for this milestone. This milestone will also include NFT gating for restricting content access.

**Comment by nelsorya** [comment]
Hey @antoniomarquis, thanks for making this updated proposal. We are happy to move forward with this proposal. If this sees usage from the community we would also be happy to fund ongoing maintenance for the tool, initially for a 6 month period. 
- Ongoing support for 6 months ($500 per month)
