### ISSUE TITLE
Website + App to Manage all your Orchestrators and Trancoders at the same time!

### ISSUE THREAD

**Issue by Justin99b** [livepeer/Grant-Program#34]
**Give a 3 sentence description about this proposal.**
---
A Centralized Platform (Website and APP) to manage and maintain multiple Orchestrator and Transcoder Nodes between multiple servers.

Simplifies the Setup Process to allow Novices to simply get started with livepeer so more people can join the Network and grow their node.

Provides a large toolset to Automate Tasks, Reduce Errors and maximize your Profits aswell as minimize your fees

**Describe the problem you are solving.** 
---
Currently it’s rather difficult to get started and a lot of Quality of Life features are lacking that make working unnecessary elongated and difficult.
It's also really complicated to manage multiple Orchestrator or Transcoder Nodes and keep track of statistics and Errors as well as downtime.

**Describe the solution you are proposing.** 
---
We provide a centralized management platform for people to add their O’s and T’s to allow for easy management of multiple servers which is pretty difficult even for more advanced users

We are offering a large toolset here are some examples:

### Automatic Claiming Rule Options
- At what gas price should the reward Automatically be claimed
- Select a time Period when to retry claiming if the previous try failed
- Enable/Disable Automated Claiming
- Automatically claim reward when gas price is under the value of the claiming returns
- Allow increasing the margin of gas price to pay towards the end of the Round so ist “guaranteed” it gets claimed

### Remote Control Orchestrator and Transcoder
- Autorestart Orchestrator/Transcoder when they crash
send Push (or E-Mail) Notifications to Phone (or any other platform you wish) if there are errors, packet loss, crashes, updates, winning tickets, reward claims, etc
- Easily Benchmark Transcoders when you need
- See your Success Rates for all Orchestrators
- Shows your Orchestrator’s Ranking and Performance on the Leaderboard
- Start/Stop/Pause Encoding
- Alert you if there is a new Livepeer client update available. Let it automatically update or Update it yourself
- Remote shell for your orchestrator and trancoders

### Discord Bot
- Alerts (Gas prices, Ticket Winning, Reminder for Claiming, Errors, Crashes)
- Lists O+T Sessions, Utilization (Memory, Clock speed, Fan speed, Temperature etc), Performance, Ranking, Success Rate etc
- Much more the community is asking for :)

### Future Ideas (things we thought of but are not sure if we will implement them):
- We might enable people to easily create a Transcoder Pool so you can create your own private pool.
- You can create your own Orchestrator in the Cloud without the need of a complicated setup procedure.
- Auto GeoLocate your orchestrator for max performance

### General
- Control everything from our Website or simply via the App
- API Access to our Servers for you to Implement your own Automations as you wish

We aim to work Community driven. So if people for example want a feature added we if its a good idea and if many people would like it. If yes, we try to add that feature.

**Describe the scope of the project including a rough timeline and milestones** 
---
### Stage: Preparing (2-4 Days)
- We Prepare everything we need in order to start programming
- Opening a YouTrack for keeping track of ideas and issues
- Searching for people who would like to help us
- Buy a Domain
- Create a Github Organization
- Research api’s and Docs of Livepeer

### Stage: Programming (2-4 Months, maybe 1-2 if we have more than one developer)
- Deciding which stack to use
- Using the Testnet to test things
- Create a Scalable and secure backend aswell as Frontend
- License Agreements and DSGVO (We need to do this in Germany)
- Implementing the most usefull features first and see if there is enough time for more small features.

### Stage: Testing (5 Days)
- Test If everything works as intended
- Stress Test servers to see if it could handle more than enough requests

### Stage: Documenting (5 Days)
- Create API docs
- Making Video Tutorials if necessary
- Create Wiki articles that helps you use the website

### Stage: Discussing Price models (if allowed) (1 Day)
- Some of the Services mentioned like hosting a Orchestrator node in the cloud would maybe need a subscription to compensate for server usage (which costs us money obviously)

### Stage: Oppurtunity
- We will Discuss the future of the Project and see what else there is to implement.
- Support for atleast 6 Months
- Support for as long as possible (possible foreaver) when its commercially viable (when im able to pay my bills with this poject)
- Any money we would make with this Project will go towards...
  - Paying our Server Infrastructure
  - Expanding our Server Infrastructure
  - Paying Artists and Developers
  - Funding new Projects with the Same goal in mind (making it easy for novices)

### Stage: Deploying
- We switching from Testnet to Mainnet
We deploy our website and share it on our discord as well as in the Livepeer Discord.

**Please estimate hours spent on project based on the above** 
---
Minimum: 150 - Maximum 450
#### Note
The time is calculated on how much im able to work. since im on a full time job i only have about 3-5 hours when im home. obviously im not working alone on this.
It propably be about

## About myself
Im a 22 Year old Software Engineer from Germany with 10 years of Programming Knowledge.
In the past i worked with alot of Languages and gather really usefull Information.

### HTML/CSS
- Vue.Js
- Quasar
- Bootstrap
- tiny bit of React

### Typescript/Javascript
- Using it for my own Fivem server
- Used it for a [School Project](https://github.com/itf191-raum3/raum3-thegame)
- Currently Writing a Axie Infinity Automatisation Service
- Hopefully this project when it gets funded :)
- Nest.js
- Currently Learning Geth and Web3

### Java
- Too many Spigot/Bukkit plugins to count
- Minecraft Forge VoiceChat for my Community Porject
- Teamspeak Bots
- Twitch Bots
- Socket Server and Client connections
### C#
- Wrote a Twitch bot in it where people could redeem their channel points to shoot me with my airsoft which got triggered by an arduino/esp32 as well as my fog-machine and my Fan. Also connected my Amazon Echo to it so people could use Text to speech to annoy me lol
- Sometimes I have a lot of fun in Unity :)
### PHP
- Using it everyday at Work

### SQL
- Don't use it often since i only use ORM's (Entity Framework, Typeorm)
### SQF (Scripting language of Arma 2/3)
- Had alot of fun with my friends
- Created Scripts for my overpoch/exile server that never went online
- Helped out some friends with their Altis life server

### Bash
- Mainly using it when working on our own linux distro at work
### C/C++
- Created a [Lightdm Exec Greeter](https://github.com/RangeeGmbH/lightdm-exec-greeter) which accepts an exit code to controll the Login flow
### Lua
- Started using it in Fivem a while ago…. hated it since haha. i mean comeone why do you start counting your array at 1 lua!

#### Solidity (not yet used but fascinated by it)
- Really want to get into it and fiddle around with Smart contracts

## Conclusion
Im always trying new things because Programming is basically my live and its my favorite thing to do everyday
I Never released any project because i thought “they are not perfect” or “nobody would ever want to use it”
I changed that mindset now and want to be more open source :)

**Comment by Justin99b** [comment]
> I think we can cut a lot of the groundwork by integrating with https://github.com/decentralized-authority/node-launcher
> 
> This is the back-end engine powering https://nodepilot.tech/ a one-click deployment tool for Pocket Network and Blockchain nodes.
> 
> node-launcher is an engine for spinning up and managing docker images, support for Livepeer can be added by adding a configuration file for it, here's an example for [Ethereum](https://github.com/decentralized-authority/node-launcher/blob/master/src/types/ethereum/ethereum.ts).
> 
> We've also been in talks with the Node Pilot team for a possible grant to add support for Livepeer so I can see some potential for a collaboration here.

**Comment by nelsorya** [comment]
Hey @Justin99b, thanks for making this well-thought-out proposal. 
There are a few additional points we were thinking would be great to add to this proposal. 

The first is a wireframe and community feedback milestone, where any community feedback can be incorporated into the app before it is finished. Another is a success metric linked milestone, to align your incentives with that of our own, which is building tools that see usage from within the Livepeer community. E.g 20 Orchestrators actively using the app. 

With these proposals, we typically break up the grant across the milestones. So for this proposal, we would propose we break up the grant like so. 

1. Preparing & Programming ($7,500 in LPT)
2. Wireframe & Feedback ($2,500)
3. Testing & Documenting ($2,500)
4. Price Models, Opportunity & Deploying ($2,500)
5. Success Metric Bonus ($5,000 in LPT)

If this sees usage from the community we would also be happy to fund ongoing maintenance for the tool, initially for a 6 month period. 
- Ongoing support for 6 months ($500 per month)

**Comment by Justin99b** [comment]
Hello Everybody
Im answering this so everybody outside the DM's knows whats going on.
We are currently in development and are grateful this got approved!
Its going to be a lot of fun programming this 💯 
If you have any questions or concerns please let us know!
