### ISSUE TITLE
Translation To European Languages

### ISSUE THREAD

**Issue by bjimmybrown** [livepeer/Grant-Program#37]
**Give a 3 sentence description about this proposal.**

**I can  translate , https://livepeer.org/primer in the native languages of the readers, as the owner of https://cryptostec.com/ we have built educational content in 16 languages** 

**We have translated our content on our website, * Czech, Danish, Dutch, Estonian, Finnish, French, German, Hungarian
, Italian, Polish, Portuguese, Slovak, Slovenian, Spanish, Swedish.** 

**Provide translation service as a start in German and Polish as this is the countries that your website is currently attracting the most after Asian regions.** 

**It will take me about 5 hours to translate each language

**Comment by nelsorya** [comment]
Hi @bjimmybrown, thanks for making this proposal. Sorry for the delay. 

The grants committee is not looking to fund translations for any additional languages at the moment. The website currently has Chinese, Korean, Russian and Spanish which we feel is a broad enough base for now
