### ISSUE TITLE
Livepeer staking strategies on Stakeall Finance

### ISSUE THREAD

**Issue by cryptostaker2021** [livepeer/Grant-Program#40]
**Give a 3 sentence description about this proposal.**

In last 2-years, there has been advent of staking protocols where users stake to nodes. Staking helps the POS protocols to secure and decentralize it. We at stakeall finance wanted to ease out the process of staking for DeFi users. Using our unique approach to building strategies for staking, we achieve increased usability and higher returns for users.

**Describe the problem you are solving.** 
Many users wanted to stake but unable to do so due to :
1. DeFi and staking protocols are currently scattered.
2. Inconvenient process of participating in DeFi and staking protocols.
3. High opportunity cost while using DeFi legos.
4. Requires in depth knowledge of different protocols to generate high staking yield.

**Describe the solution you are proposing.** 

We build DeFi strategies that is basically series of interaction with DeFi legos and staking protocols. All these interactions in a strategies are executed in a single transaction for a user. This massively enhances the user experience along with saving cost and time.

**1. Leverage stake** : This strategy allows user to borrow tokens like ETH from Aave by collateralising any other asset like WBTC. Borrowed ETH will be swapped using 1inch and received LPT will be staked to Livepeer orchestrator/nodes.

Whole strategy will be executed in a single transaction. This will greatly increase user-experience of staking to Livepeer.
Below diagram demonstrate the Leverage staking of ETH using Livepeer Protocol :

Below are the strategies we propose for LPT staking :

![image](https://user-images.githubusercontent.com/85118498/146187884-9aa55f4d-b4b8-4bae-a17b-0eb0a4417513.png)

**2. Swap and stake** : This strategy allows user to swap the asset to LPT token and stake to Livepeer orchestrator. This strategy will also be executed in single transaction which leads to higher user satisfaction of staking.

![image](https://user-images.githubusercontent.com/85118498/145776129-6051e4c1-f8e0-44d3-92e2-bed79b25bd35.png)

**Describe the scope of the project including a rough timeline and milestones** 

1. Build connector smart contract for Livepeer staking.
2. Build leverage staking strategy for LPT along with frontend.
3. Build swap and stake strategy for LPT along with frontend .
4. Integrate Livepeer contracts and subgraph for unstake flow.
5. Public Testnet release.
6. Testing and auditing.

**Please estimate hours spent on project based on the above** 
Roughly below are the estimates :

1. Points 1, 2 and 3 would take up 3-weeks.
2. Point 4 would require 2-weeks
3. Point 5 and 6 would take up around 3-4 weeks. It includes internal testing, auditing(both internal and external)

These couple of strategies are live on Ethereum Mainnet for GRT and Matic staking at https://app.stakeall.finance/.

**Adding example of the strategy:** 

Example of leverage staking of LPT using ETH as user is  bullish on ETH and LPT.

I deposit 1 ETH i.e. $4K against which I borrow 3K worth USDT. I swap 3k USDT for 93 LPT.

Overall I am earning:
Deposit ETH APR: 2.41% + 0.39% (Aave Rewards) =  2.8%
Staking LPT APR: 20%

Overall I am paying:
Borrow APR: 3.42% - 1.06%(Aave Rewards) = 2.36%
Gas cost: $$

Overall APR of earning is lot more than what I am paying. That's the reason this strategy is referred as Leveraging.
  

**Team Achievements** : 
1. Secured finalist postion in HackMoney 2021 Hackathon:  https://showcase.ethglobal.co/hackmoney2021/stakeall-finance
2. Listed as top 15 Project in Polygon Grant Hackathon: 
3. Release Beta Version of Stakeall Finance on Ethereum Mainnet with below Strategies 
     1. Leverage Staking of GRT
     2. Leverge Staking on MATIC
     3. Aave Dashboard to maintain Aave position created in leverage staking. 
     
     https://app.stakeall.finance/
     https://blog.stakeall.finance/introducing-stakeall-finance-1e063b71ee98
 

**Edited** 
1. Diagram for leverage staking:
2. Example of Strategy

**Comment by cryptostaker2021** [comment]
> How does your solution help with those points? Also, point 4. makes sense since yield is not free. There's always risks involved and users should know that when staking. So listing that as a negative seems strange to me.

3. We reduce opportunity cost by integrating with various DeFi protocols so that users get the best outcome while doing any action. For instance, if a strategy requires a swap then platform will find best swap rates across leading DEX aggregator like 1inch and paraswap. Similarly in case of lending and borrowing, platform will provide best deposit and borrow APR across the protocols. 

4. One of the goal of building strategies is automate and ease out interaction across DeFi protocols so that it enables any new users to participate in DeFi. Currently DeFi legos are scattered and it's a big hurdle for any new user to use them effectively. This doesn't obscure the risk per se. 


> How is this leveraged? Only thing you're doing is going long/short (and introducing a liquidation risk) by borrowing & swapping against a certain asset.
Oh and would be nice to know where I can swap 1 MKR for 3215 LPT - just replacing GRT with LPT doesn't really work ;)


> "In finance, leverage is a strategy that relies on using borrowed money to increase the potential return of an investment."

In this strategy users can stake in Livepeer protocol by borrowing assets and without selling their current holdings. 
Yes, there is a liquidation risk and we have build a dashboard for managing their borrowed position. If health factor goes below a limit user can deposit more collateral or payback some of the borrow assets. There are features in our roadmap like liquidation protection framework which would help reduce liquidation risk. 
Also, Thanks for pointing out  typo, corrected the token conversion. 

> So essentially the only thing you're providing is swapping & staking in a single tx. Which is where the other problem comes in: There's barely any LPT liquidity on Dexes.

I checked balancer AMM. It has 50K LPT tokens as liquidity and there are other DEX's too. 
Liquidity can be moved from centralised exchanges like Binance and Coinbase exchanges to Dexs if there are enough incentive of doing it for the users.

**Comment by 0xVires** [comment]
> We reduce opportunity cost by integrating with various DeFi protocols so that users get the best outcome while doing any action. For instance, if a strategy requires a swap then platform will find best swap rates across leading DEX aggregator like 1inch and paraswap. Similarly in case of lending and borrowing, platform will provide best deposit and borrow APR across the protocols.

That's not what is generally understood as "opportunity cost". This is simply comparing rates. Reducing opportunity cost would be if staked LPT could be used as collateral to borrow e.g. USDC against. And then farm with those USDC.

> "In finance, leverage is a strategy that relies on using borrowed money to increase the potential return of an investment."
In this strategy users can stake in Livepeer protocol by borrowing assets and without selling their current holdings.

Yes, the quote is true. But it doesn't work if you have to deposit MORE money to borrow that money... 
Think about it, you're depositing 1 ETH (let's say $4k), you can borrow at max 0.85*$4k against that. So you can only stake $3.4k worth of LPT (vs. $4k if you'd just swap). This is NOT leverage.
Your diagram really hardly makes any sense... You'd bet that LPT increases more than MKR (and it has to be by a lot to make up for the gas fees), but even if that happens you still have a liquidation risk if the ETH/MKR rate or the borrowing cost increases. I doubt that your users (or even you) understand this...

An example for leverage would be: I deposit 1 ETH, I borrow 3k DAI against that, I swap those DAI for ETH, I deposit that ETH, I borrow 2.5k DAI against that, I swap those DAI for ETH, and so on .... -> Instead of only 1 ETH, I now have exposure to 2-3 ETH (and DAI debt). So if the ETH price increases, I have a higher return.

I like the overall idea of you platform, but you seem to not understand some important economic terms that you're writing about and building around.

**Comment by cryptostaker2021** [comment]
Thanks for you feedback. 

> "opportunity cost" 

We believe comparing rates helps reducing opportunity cost as it let's you select best rates. It can save you the difference between best and non best selection.  I understand if you have different notion of it.  

> Leveraging 

Well, You seem to misinterpret the diagram. Deposit ETH to borrow MKR is a demonstration of how it would work. It's not the best example. 

Example of leverage staking of LPT using ETH as **_I am bullish on ETH and LPT._** 

I deposit 1 ETH i.e. $4K against which I borrow 3K worth USDT. I swap 3k USDT for 93 LPT. 

**Overall I am earning:** 
Deposit ETH APR:  2.41% + 0.39% (Aave Rewards) =  2.8%
Staking LPT APR: 20% 
 
**Overall I am paying:**
 Borrow APR: 3.42%  - 1.06%(Aave Rewards) = 2.36%
 Gas cost: $$
 
Overall APR of earning is lot more than what I am paying. That's the reason this strategy is referred as Leveraging.  

So choice of Deposit token, Borrow token is variable in the strategy and totally depends on user.

**Comment by cryptostaker2021** [comment]
I would also request feedback from other reviewers 🙏

**Comment by nelsorya** [comment]
Hi @cryptostaker2021, sorry for the delay and thanks for sharing your proposal. Livepeer Grants has funded another proposal, Tenderize (https://github.com/livepeer/Grant-Program/issues/26), which aims to introduce LPT staking derivatives to help facilitate use of staked LPT collateral in DeFi and leverage staking.  How do you see this proposal differing from their approach? It seems the key difference is the use of other non-LPT assets as collateral. Also what do you see as the key benefits of the platform vs users interacting with Aave and then staking Livepeer themselves?

**Comment by cryptostaker2021** [comment]
@nelsorya  Thanks for your feedback. Below are benefits of using stakeall platform: 

 **1.  Single transaction :**  DeFi strategy on stakeall finance platform may require interacting with multiple DeFi protocols.
                      We have grouped these interactions such that it is executed in a single transaction.

Consider user don't have LPT token and would like to leverage on other assets. Let's try to understand what user can do :

   a) Case 1(without stakeall finance) : User would hunt through multiple protocols to borrow using  available assets having low borrow APR and risk factors. If the staking protocol token is not available for borrow, then user would search through different DEXs to find best swap rate available to get staking protocol token. After getting token, user would go to staking protocol UI and stake it to get benefits. I believe only users aware of DeFi world extensively, will be able to pull-off this task successfully and efficiently. 
                      
Also, it would require more than 5  transactions(deposit to AAVE, borrow, approval, swap and stake) by the user just for staking. 

  b) Case 2(with stakell finance) : User would come to stakeall finance platform, user can view and borrow asset with minimum borrow APR by collateralising  available asset. Platform would fetch maximum staking token available for staking using borrowed amount. User would then simply select validators and stake it.
                      
This unified view would greatly help users to perform staking. Entire staking process got reduced to just 2 transaction(approve + strategy).  
                                           
In future, platform would have more strategies to help users achieve high yield and staking experience.


   **2. Different protocols :**  Currently, stakeall supports Aave, 1inch protocol to facilitate staking in case user doesn't have underlying staking protocol token. 
We are actively adding support of more protocols like Paraswap ,Compound, etc. This would help users to view what is best for them across protocols in a single platform. 


**3. Cross-chain :**  Due to high gas cost on mainnet, Staking is not profitable for users who owns small fund.
 We are integrating cross-chain interoperable protocol to helps users to perform staking from L2's like matic, fantom, etc .

In future, Stakeall finance platform would support to staking to protocols from L2's.
This also allows us to move heavy DeFi operations like leveraging to L2's. This will greatly reduce gas consumption and results in more savings for users.

**Comment by nelsorya** [comment]
Hey @cryptostaker2021, thanks for this context, that is very helpful. With these proposals, we typically break up the grant across the milestones. We also like to set a success metric linked milestone (e.g 100 unique addresses using the LPT market). So for this proposal, we would propose we break up the grant like so.

1. Build connector smart contract for Livepeer staking. ($1,000 in LPT)
2. Build leverage staking and swap and stake strategy for LPT along with frontend ($1,500)
3. Integrate Livepeer contracts and subgraph for unstake flow and Public Testnet release ($1,500)
4. Testing, auditing and community feedback ($1,000)
5. Success Metric Bonus - 100 unique addresses ($1,000)

**Comment by 0xVires** [comment]
Just FYI: Livepeer is migrating to Arbitrum in a few weeks. So the above mentioned proposal would probably need to include cross-chain support, otherwise the LPT can not be staked.

**Comment by cryptostaker2021** [comment]
> 

Thanks @nelsorya  
I will get back to you on this, we are discussing this internally.

**Comment by cryptostaker2021** [comment]
Hey @nelsorya , 
would you be open to consider below proposal ?   I have updated it based on dev efforts, auditing and operational cost. 
Auditing cost is going consume major chunk of the fund.  

1. Build connector smart contract for Livepeer staking. ($1,500 in LPT)
2. Build leverage staking and swap and stake strategy for LPT along with frontend ($2,000)
3. Integrate Livepeer contracts and subgraph for unstake flow and Public Testnet release ($1,500)
4. Testing, auditing and community feedback ($4,000)
5. Success Metric Bonus - 100 unique addresses ($1,000)

**Comment by nelsorya** [comment]
@cryptostaker2021 thanks for sharing this. Just to clarify, given Livepeer has now migrated to arbitrum would this proposal include cross-chain support?

**Comment by cryptostaker2021** [comment]
> @cryptostaker2021 thanks for sharing this. Just to clarify, given Livepeer has now migrated to arbitrum would this proposal include cross-chain support?

Yes, that will be supported.

**Comment by nelsorya** [comment]
@cryptostaker2021 could you tell us more about what this cross-chain flow would look like? I'm concerned that the user needing to use a bridge to Arbitrum in the process could break the user flow of what you have currently built.
