### ISSUE TITLE
Web3Weirdos Web Series

### ISSUE THREAD

**Issue by angiesaurus** [livepeer/Grant-Program#41]
Web3Weirdos is a web3 advocacy Youtube series aiming to bridge the gap between the deeply technical and non-technical consumer with the hopes of bringing a more diverse set of creators and consumers into the web3 space. We're breaking down the language and existing barriers to open doors for those who wouldn't normally consider web3 a space for them.

We hope to address the diversity and access problem in web3 by breaking down the existing barriers and educating a broader community about the possibilities and opportunities in web3. This work will bring more people into the web3 ecosystem as consumers and creators, extending web3's reach and usage. Existing developers and creators will benefit by getting more consumers interested in their projects.

We're proposing an educational web series to break down current knowledge barriers and bring more consumers and creators into the space.

Episode 1 is already up on Youtube, and future episodes will drop on a weekly basis. Each episode is ~10 minutes covering a variety of web3 topics in a fun, non-technical way. With additional funding we can bring on our video editor full time for higher quality content and eventually bring on some great guests.

Current time spent on the project has been about ~30hrs and between researching, writing, test run-throughs, edits, and posting we spend about ~15-20hours/week.

Episode 1 here: https://www.youtube.com/channel/UCmzoJA-npHeqhpx0j7YB7LA

**Comment by nelsorya** [comment]
Hey @angiesaurus sorry for the delay, thanks for reaching out. We really like the format of your web series, however, we only fund grants for projects specifically related to Livepeer. If you were interested in proposing say an introduction to Livepeer episode in a similar format, this could be something we would be interested in funding.
