### ISSUE TITLE
Livepeer Setup and Installation, Data Migration, Cleanup Scripts

### ISSUE THREAD

**Issue by RyanC92** [livepeer/Grant-Program#42]
**Give a 3 sentence description about this proposal.**

I would like propose creating scripts and documentation for Linux/Windows/Docker/Ansible to help get orchestrators and transcoders up and running as fast as possible. Tackling majority of the hurdles that newcomers face and create a more streamlined process to getting users started transcoding. 

**Describe the problem you are solving.** 

When I joined Livepeer as an Orchestrator I found it difficult to get started with the setup of the Livepeer client, Prometheus, Grafana and getting everything to work properly without the need for hours of research, troubleshooting and background knowledge on the platform I was in. I wanted to create scripts that would handle the biggest hurdle steps so I could get an Orchestrator running quickly. I'd like to propose creating, updating and possibly maintaining the documentation for script writing.

**Describe the solution you are proposing.** 

I have already created a base line script for Linux (ubuntu) to download, permission, copy and install Livepeer, Grafana and Prometheus as well as supporting scripts and files and services setup. My aim would to eventually add complexity to the scripts where it is needed, shore up any security concerns and apply best practices then expand the focus to other platforms and applicable deployment methods (Windows, Ansible, Docker, etc.) Additionally, include community feedback to further develop and implement changes, features and fixes. 

Link to existing repo: https://github.com/NightWolf92/NightNode_Livepeer_Docs

**Describe the scope of the project including a rough timeline and milestones** 

1. Linux shell script for initial setup and configuration: Completed
    - Documentation of Linux script and setup: (Less than 1 week)
    - https://github.com/NightWolf92/NightNode_Livepeer_Docs
2. Ansible script research, coding and implementation: (3-4 weeks)
    - Documentation: (Less than 1 week)
3. Docker script research, coding and implementation: (2-3 weeks)
    - Documentation: (Less than 1 week)
4. Windows script research, coding and implementation: (1-3 weeks) likely less as I am more familiar in this environment.
    - Documentation: (Less than 1 week)
 5. Seek Community Feedback at each stage for each script. Make modifications and look towards security hardening suggestions. 
   
Later additions could include system maintenance, cleanup, migrations, monitoring etc as needed. 

**Please estimate hours spent on project based on the above** 

All time spent on every implementation as it would require time for familiarization, creation, testing, documentation. As such, overall I could expect everything to be completed in 2-3 months with an estimated 5-10 hours per week.

**Comment by nelsorya** [comment]
Hey @NightWolf92, thanks for putting together this proposal. One thing we would love to see in this proposal is also a feedback stage where the community can give feedback to be incorporated into the scripts and documentation. We also like to add a success metric bonus milestone to align your incentives with that of our own, which is building tools that see usage from within the Livepeer community. E.g 20 Orchestrators actively using your scripts.

We typically break up these proposals across milestones, so based on your time estimates, we would propose the following:

1. Linux Shell Script & Ansible Script Research, coding and implementation ($1,500 in LPT)
2. Docker Script Research, coding and implementation ($1,500)
3. Windows Script Research, coding and implementation ($1,000)
4. Community Feedback ($1,000)
5. Success Metric Bonus ($500)

If this sees usage from the community we would also be happy to fund ongoing maintenance for the tool, initially for a 6 month period. 
- Ongoing support for 6 months ($500 per month)

**Comment by NightWolf92** [comment]
@nelsorya 

Thank you for your reply! I look forward to working with you all on this. I'm certainly open to the feedback and guidance of the community, we have a lot of smart and talented people here that definitely know more than me on some of these platforms. 

What would be the next steps going forward for this? 

As far as development on myside, I'd like to start off with the documentation for the Linux script then move onto the ansible script. If you have any particular format you'd like for me to follow, please let me know. Thanks!

I am also available on Discord @Nightwolf92#3062 or as Nightwolf92 - Nightnode in the livepeer discord.

**Comment by NightWolf92** [comment]
@nelsorya 

Good Afternoon Nelson, 

After speaking with Hunter and Shann regarding the milestones and the project and getting clarification on how its expected that milestones be reached. We thought it would be worth revisiting the order of the milestones and the allocations for a few of them. 

In particular. We originally grouped Ansible and Linux together, while the linux portion is complete and ansible isn't the compensation for linux has been distributed. Leaving $500 in LPT to be distributed. However, after looking at the load that would go into getting ansible running and the limitations of not having a deb repository to build off of (see go-livepeer issue here: https://github.com/livepeer/go-livepeer/issues/2224) we were considering changing how the values were distributed. Assuming we can complete Ansible either with a supported deb package or via copying a script, the value could be $1500 for completing ansible, and $500 for docker (switching the values, total remains the same). Reason being, ansible would require much more legwork and overhaul where as the docker portion may be fixes/improvements upon the current implementation that is being supported by livepeer.

Additionally I have been working out of order, I completed linux and am almost complete with the dev side of the windows installer and would need to work on documentation and improvements. As such we were wondering if we could re-order the milestones to look more like this.


~~1. Linux Shell Script reasearch, coding and implementation ($1,000 in LPT)~~
2. Windows Script Research, coding and implementation ($1,000 in LPT)
3. Docker Script Research, coding and implementation ($500 in LPT)
4. Ansible Script Research, coding and implementation ($1500 in LPT)
5. Community Feedback ($1,000)
6. Success Metric Bonus ($500)

Additionally making 3/4 reversible as milestones based upon what is possible for completion. 

Granted, I know this may be non-traditional however with other factors and limitations as well as scope creep (first iteration of Linux was miles different from the final one) time frames are probably extended slightly and priorities would need to be shifted to continue to produce results without pausing for pending items like better support and resources for a better ansible solution.

**Comment by nelsorya** [comment]
Hey @NightWolf92, thanks for this. These changes all look fine to me. Happy to reorder the milestones
