### ISSUE TITLE
[Grant Proposal] Dbeats social media of NFTs & Decentralised Community

### ISSUE THREAD

**Issue by supersapiensdevlab** [livepeer/Grant-Program#45]
# Dbeats 
DBeats is a decentralized Social media & NFT marketplace on Polygon for Creators, Game Streamers, Bloggers, Music Artists & everyone else. We are building a decentralised community where users can mint NFTs of their videos, create NFTs during Live streams or post Photo & make it a NFT. Creators can set up royalties for every sale. Currently the Beta version of the platform is up at [dbeats.live](https://www.dbeats.live/)

**The Problem** 
We are solving the problem of centralization where the creator itself has no ownership of his content but the platform he chooses to upload it on. Platforms like Youtube, Twitch & Spotify earn Billions of dollars through selling ads on the content of their millions of creators while they pay/incentivize this creator a little more than half of what they make in revenue. 
Commission rates of 
>Twitch - 50% of subscription fees  & 29% from Donations
OnlyFans - 20% of subscription fees
Patreon - 5% - 12% based on Plans
YouTube - ~45% 
Facebook - ~30% 
 

**The Solution** 

> "_The value of content should be decided by the audience & not by the platform_" - Rushikesh, Founder  

### Superfan - An awesome feature on DBeats
Let's take an example of a live streamer & a hilarious content creator who receives a good amount of engagement from audience in the form of donations. This donation can now be paid directly to the creator's wallet through a one-time payment or a stream of payment paid per second(using superfluid) for a month. The content creator can setup customized plans through his dashboard

### NFT-fied Social Media - our USP
User can post announcements, videos, pictures, music & buy NFTs of such other posts while vertically scrolling through a redefined web2 social media experience on Web3. 

### NFTs from livestreams
Live streamers during any Livestream can extract a short clip of video which they can mint as NFT with 1 click & post it for sale.
Dbeats also supports multistreaming on 3 platforms from a range of 25+ platforms over RTMP. 

### Tickets & Events
Creators can host scheduled Live events & let the audience buy passes for the event in advance (using Unlock Protocol).

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-da36f219-7fff-2f5d-1333-3b4e2e88bae5"><h2 dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:23pt;margin-bottom:0pt;padding:0pt 0pt 8pt 0pt;"><span style="font-size:17pt;font-family:Roboto,sans-serif;color:#222222;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Journey &amp; Achievements</span></h2><br /><div dir="ltr" style="margin-left:0pt;" align="left">

Integrations & Adoptions | Awards | Related Links
-- | -- | --
Inception : Presented the first initial idea at the ETHGlobal’s ETHOnline 2020 Hackathon | Compound Protocol - $1500 cUSDCBest use of Audius runner ups | [Link](https://showcase.ethglobal.com/ethonline/dbeats)
Integrated Unlock Protocol & Livepeer at the Web3Weekend Hackathon | Event FinalistLivepeer - $2000 | [Link](https://showcase.ethglobal.com/web3weekend/dbs-decentralized-broadcast-stream)
Integrated Zora for NFT Marketplace during HackFS 2021 | Zora Prize PoolLivepeer Prize Pool | [Link](https://showcase.ethglobal.com/hackfs2021/dbeats)
Received grants from Protocol Labs | $5000 | [Link](https://github.com/ipfs/community/discussions/592)
Presented Multistreaming & Video on Demand Feature at the ETHOnline 2021 | Livepeer - 2nd PlaceLivepeer Pool Prize | [Link](https://showcase.ethglobal.com/ethonline2021/dbeats-decentralised-creators-community)
Web3Jam 2021 - Presented the concept of NFT Marketplace on Polygon with Community Rooms & 1 Click NFT minting | Livepeer 2nd PlaceLivepeer Pool PrizeCovalent Pool PrizeNFTPort Pool Prize | [Link](https://showcase.ethglobal.com/web3jam/dbeats-decentralized-beats)
Minting NFT during Livestreams & integrated MATIC token for users to make direct donations to Creators in return of perks. | Superfluid Pool Prize | [Link](https://showcase.ethglobal.com/nfthack2022/dbeats)
  |   |  

</div></b>
</body>
</html>
 
DBeats is forming a DAO with 5 out of 9 multi-sig & members  
3 from Core Devs, 
3 from Creator Community  
1 from Livepeer Team
1 from Polygon
1 from Superfluid
$DBEAT will be the governance token for the platform. [Polygonscan link](https://polygonscan.com/address/0x92e918ea7aa872F91BF7EC9BcD248a5920C9f3CB)
 
 Community members can fill out this application : [Dbeats DAO Application](https://forms.gle/KCkJGechX6njYt867)
 
<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-b51b9fa5-7fff-e0b8-921b-254760adcac4"><h2 dir="ltr" style="line-height:1.38;background-color:#ffffff;margin-top:23pt;margin-bottom:8pt;"><span style="font-size:17pt;font-family:Roboto,sans-serif;color:#222222;background-color:transparent;font-weight:700;font-style:normal;font-variant:normal;text-decoration:none;vertical-align:baseline;white-space:pre;white-space:pre-wrap;">Roadmap :&nbsp;</span></h2><div dir="ltr" style="margin-left:0pt;" align="left">

Beta Launch | Done | Q4 2021
-- | -- | --
Integrating fiat-on Ramp (MoonPay) | Done | Q1 2022
Minting 300 Million DBEAT Tokens on Polygon | Done | Q1 2022
Integrating $DBEATx (DBeats Super Token) for streaming audience’s donation payments into the creator’s account. | In Progress | Q1 2022
Redesigning of Landing Page (dbeats.org) | Done | Q1 2022
forming a DAO with 5 out of 9 multisig | In Progress | Q1 2022
Official Launch | Upcoming | Q1 2022
Launching an IDO on  DxSale after first 1K registered users | Upcoming | Q1 2022
Creating DBEAT/MATIC pool on Quickswap | Upcoming | Q1 2022
Releasing DBeats Mobile App with in-app Crypto Wallet | Upcoming | Q2 2022
Partnering with Verified Content Creators | Upcoming | Q2 2022
  |   |  

</div></b>
</body>
</html>

Current Traction 
On the Beta release
Daily Active Users : 100 (since 23/01/22)

Social Media Followers : 1K+ across Instagram, Twitter, Discord, LinkedIn, Telegram
(Daily new 100+ organic followers)
 
## Forecast

 
Launch   
Q1 2022
 
Users with Registered Wallets | 5K+
-- | --
Transactions finalized on Polygon(Donations, NFTs, Superfan) | 1000+
Posted Content - Videos, Pictures, Music | 1000+
 
 
Marketing
Q2 2022 

Users with Registered Wallets | 10K+
-- | --
Transactions on Polygon(Donations, NFTs, Superfan) | 5K+
Posted Content - Videos, Pictures, Music, Live streams | 7K - 8K+
 
 
DBEAT Token listing on exchanges & Partnerships with creators
Q3 2022 

Users with Registered Wallets | 25K+
-- | --
Transactions on Polygon(Donations, NFTs, Superfan) | 20K+
Posted Content - Videos, Pictures, Music, Live streams | 30K+
 

 
More Listings, Partnerships & Marketing
Q4 2022 

Users with Registered Wallets | 70K+
-- | --
Transactions on Polygon(Donations, NFTs, Superfan) | 100K+
Posted Content - Videos, Pictures, Music, Live streams | 100K+
 

### Approx 150 Hours per team member will be spent for the further development, generating traction, building marketing materials
Rushikesh Kardile - Founder & Blockchain Dev , CEO Supersapiens Devlab 
Aniket Tandale - QA & Relations, COO Supersapiens Devlab 
Sahil Punjabi - Fullstack Developer 
Prasad Karmalkar - Fullstack Developer 
Om Gaikwad - Mobile Developer  

### Requested funds - 500LPT tokens 

For more information :
Website - [dbeats.org](https://dbeats.org)
Discord - https://discord.gg/9AurAjMb
Instagram - https://www.instagram.com/dbeats.app

 
 
### Screenshots
 <a href="https://ibb.co/ZgNJRJQ"><img src="https://i.ibb.co/ZgNJRJQ/screencapture-dbeats-live-2022-01-16-13-53-51.png" alt="screencapture-dbeats-live-2022-01-16-13-53-51" border="0"></a> <a href="https://ibb.co/tPnQSxT"><img src="https://i.ibb.co/tPnQSxT/screencapture-localhost-3000-2022-01-29-04-10-18.png" alt="screencapture-localhost-3000-2022-01-29-04-10-18" border="0"></a> <a href="https://ibb.co/cxdJYL7"><img src="https://i.ibb.co/cxdJYL7/ezgif-com-gif-maker-1.gif" alt="ezgif-com-gif-maker-1" border="0"></a> <a href="https://ibb.co/QX333v0"><img src="https://i.ibb.co/QX333v0/screencapture-dbeats-live-profile-orion-posts-2022-01-22-20-33-57.png" alt="screencapture-dbeats-live-profile-orion-posts-2022-01-22-20-33-57" border="0"></a>

**Comment by nelsorya** [comment]
@supersapiensdevlab thanks for putting this proposal together, this seems like it could be a great use case for Livepeer. How many hours do you think this grant would take to complete? It would also be great to clarify if this would be open-source?

**Comment by supersapiensdevlab** [comment]
Hello @nelsorya , DBeats is an open-source platform here are the links to the repos :
https://github.com/supersapiensdevlab/dbeats-frontend
https://github.com/supersapiensdevlab/dbeats-backend
We estimate a total of 750 Hours delegated among a team of 5. est - 1 Month
Which includes UX Design, Development, Security tests, Deployment.

**Comment by nelsorya** [comment]
Hi @supersapiensdevlab, thanks for this context, that is very helpful. With these proposals, we typically break up the grant across the milestones. We also like to set a success metric linked milestone (100,000 streamed minutes). We also pay 20% of the total grant upfront so you can start development. 

1. Official Launch ($5,000 in LPT)
2. Community Feedback ($5,000)
3. DBeats Mobile App Launch ($5,00)

Success Metric Bonus - 100,000 streamed minutes ($5,000 in LPT and we will cover the transcoding costs)
Estimated infra cost of 200,000 mins (00 concurrent viewers) = $5,200)

**Comment by Rishikeshk9** [comment]
💫Thank you so much for the approval @nelsorya 

I would like to connect with you on discord where we can discuss how the initial 20% grants can be disbursed.

Also would need some details on how Livpeer will be covering cost for 100,000 transcoding minutes.

Thank you so much for believing on Dbeats & we are going to make the best out of the grants. WAGMI🎉

**Comment by nelsorya** [comment]
@Rishikeshk9 @supersapiensdevlab ok great, I'm Nelson#6080 on discord or if it's easier I'm one of the Community Admins in the Livepeer discord
