### ISSUE TITLE
Livepeer Grant community node as community transcoding orchestrator

### ISSUE THREAD

**Issue by JJassonn69** [livepeer/Grant-Program#47]
**Give a 3 sentence description about this proposal.**
Seeing the recent changes in the grant application for small orchestrators to bootstrap and help grow, the sponsors are in the dilemma, as they can delegate to themselves to earn higher rewards instead of putting some LPT aside to become a sponsor, this had led to the sponsors forcing to set the orchestrators to set their reward cut to 0%.

**Describe the problem you are solving.** 
I understand that the sponsors don't want to lose the money which they wouldn't if they just staked to themselves but setting the fee cut to 0% for the the grant period and having to increase it later, as 0% keeping forever is not sustainable to any orchestrators  is not very helpful in boosting the small orchestrators because even if the orchestrators might get some unsponsored delegation at 0%, those delegators certainly not be very happy if the orchestrator has to increase it later which leaves the small orchestrators back to where they started from.

**Describe the solution you are proposing.** 
I propose that we run a community transcoding server, we already have a livepeer grant node which is being helpful in funding some good projects but the real benefit hasn't been used as the same node can be used as an actively transcoding server. 
I have linked the details in the pdf from the website for grant application so its easier to go through it.

**Describe the scope of the project including a rough timeline and milestones** 
The transcoded fees received will be used to fund new orchestrators and we wont have to force anyone to make their fee cut 0% as the fund is a community fund rather than personal. With the success of the -redeemer -orchestrator setup we can successfully set the actively transcoding server in those members willing to lend hand with the project. We wont even have to actively look for sponsors as the fees earned will act as the automatic sponsor.

**Please estimate hours spent on project based on the above** 
The active hours hasn't been estimated yet, but it shouldn't take more than couple of weeks after the confirmation of the grant and node from livepeer grant committee.

**Comment by nelsorya** [comment]
Hey @JJassonn69, thanks for putting this together. Just to clarify a few things. In regards to the grant application for small orchestrators, is this referring to Titan Nodes Orchestrator start-up grants? 

Also just to clarify, are you proposing a new orchestrator in which the fees earned would be used to bootstrap new orchestrators? The Livepeer Grants Node does perform transcoding currently with the rewards generated going towards ongoing grants funding. 

How much $LPT would you be requesting to get this orchestrator started? Also, how would you see this orchestrator being operated?

**Comment by JJassonn69** [comment]
@nelsorya yes, the start-up grant program doesn't seem to be functioning very well, there are many small orchestrators who would be very happy to get some support from the community to jump start their node to reach an audience.

AFAIK Livepeer grant (community node) isn't transcoding actively, as I haven't seen any ETH payouts in the last 8 months. It is actively calling inflationary rewards in LPT which is a different topic.

My proposal is to set up a transcoding node from Livepeer grant (community Node) which seems be only doing orchestraing and calling inflationary rewards. 

I had linked all the details in the grant application in the website for the Livepeer Grant page, but. I guess I could do it here again.

[Livepeer grant application.pdf](https://github.com/livepeer/Grant-Program/files/8202715/Livepeer.grant.application.pdf)

Since, this would be a community run project as we need orchestrators who are active to support this project. First testing can be done with just basic setup as I explain in the PDF above. 

The budget for getting started is pretty small, we would need to setup a domain name and traffic routing options. The time spend on it can be couple of days for the testing phase. Once it the testing phase is success we can continue about the next phase of the project - community vote. I would assume 100 LPT would be more than enough to get it running in test phase.

**Comment by nelsorya** [comment]
Hey @JJassonn69, Titan Node's orchestrator start-up grant program is independent from Livepeer Grants, but it's certainly something we are open to supporting if the demand is there. Yes, the community node isn't actively performing transcoding work anymore. Our thinking on this is we would rather not crowd out the network, instead leaving this work for other orchestrators on the network to win while yes still calling reward to fund grants on an ongoing basis. 

Thanks for sharing this, I believe that must have been on Livepeer Academy which is community run. The main challenge we see with this approach is that it does require creating a public orchestrator pool, which right now is an unsolved problem in the  community. There are a few different community members working on this as well as private orchestrator pools such as Livepool (https://www.livepool.io/), however there wouldn't be a way to do this in a trustless way at this stage.

**Comment by JJassonn69** [comment]
Thank you for your response @nelsorya. I think the redeemer setup would be a way to go if we want to run a node. Most of the public pools are trying to run a O+T setup but with the redeemer-orchestrator setup we can run O/T which is more reliable. This also solves the issue of having to trust anyone with the keys to the wallet as only a single Orchestrator would have the access to the keys which can be Livepeer grant team themselves.

The main objective of the project is to have community engaged and feel supported. The startup grant being run by individual entity goes against the self interest for that person. So if possible we could start a grant project from the grant node we already are running and allocate some LPT for startup grant program where individual  orchestrators can apply for support at the early phase.

**Comment by nelsorya** [comment]
@JJassonn69 hmm yeah ok, how would this setup differ to the current community node run by Livepeer Grants? After discussing with the grants team, our concern with this proposal is that we don't want Livepeer Grants to be picking winners in the orchestrator space, especially given that there are still a number of open orchestrator slots in the network. We feel it's more impactful for Livepeer Grants to focus on supporting new applications which can drive demand to the network.

**Comment by JJassonn69** [comment]
Thank you for the prompt response @nelsorya. 

The setup would work such that the current community node would run as usual with `-redeemer` command, the wallet with the funds will only be available with the livepeer team so that the security of the wallet and funds wont be at any risk. The individual orchestrator run by the community would run with `-orchestrator` command with a random wallet but will be pointing to the `redeemer` for ticket redemption.

In this scenerio, only the redeemer (run by the livepeer team) is able to call rewards and redeem the winning tickets received from transcoding, however the actual transcoding happens in the orchestrators run by the community. I believe @authoriy_null has this setup running successfully without much hiccups.

I understand the concern about picking winners but I would say a startup grant is more of a support for a short duration rather than a prize to be won. The funds wont be just granted to any random orchestrator who joins the network: performance, reliability and the contribution to the network will be vital metrics to take into consideration. Since, the funds will be only granted for an individual for a fixed period of time, it encourages the beginner orchestrators to compete for reliability and performance, this ultimately makes the network more robust.

Livepeer Grants focusing on supporting new applications to increase the utilization of the network is an important part of the process but we should not forget that, if the network itself is not performing well because of the lack of motivation for new orchestrators to continue, we wont see the decentralization of the network as well as we are hoping to see.

Finally, I want to make it clear that, the main goal is to have more engaging and welcoming environment, whatever-way we can achieve that. I trust that the livepeer team will make a decision that is best for the community and the network.

**Comment by nelsorya** [comment]
Hey @JJassonn69, thanks for this additional context. While we certainly agree that the performance of the network is important, we feel the network economic incentives play a key role in incentivising orchestrators, particularly after the migration to Arbitrum which has done a lot to reduce costs for orchestrators and for delegators to change their delegation. 

Livepeer Grants also want the Livepeer community to be engaging and welcoming, however, we believe there are more ways we can achieve that besides providing additional economic incentives.
