### ISSUE TITLE
Imbue - Decentralized Twitch

### ISSUE THREAD

**Issue by carrabre** [livepeer/Grant-Program#48]
Give it a try (: https://imbue.eth.limo (message below if you need some test ETH or test ONE)

**About me**
I have been involved in the crypto space since early 2017, but didn't go full time until the fall of 2019 with Presearch. Since then, we've grown from 200k searches a day to over 6 million searches a day and have added over 2.5 million registered users in that time period. As the sole biz dev leader, i am a self taught developer, hacking on things from mobile apps to decentralized apps like [this](http://45.138.26.38:8002/form). I am will be working with a contract developer on this project who i've worked with for 6 months on different projects with Presearch and outside!

Where you can find me
- [Linkedin](https://www.linkedin.com/in/alexcarrabre/)
- [Twitter](https://twitter.com/alexcarrabre)

We just won a bounty at ETH denver from [livepeer](https://www.ethdenver.com/in-person-bounties-winners) too!

**Give a 3 sentence description about this proposal.**

Imbue is building a decentralized, web3 native platform that will allow users to have a say in how the project is run and share in the value that Imbue creates through the IMBUE token. Everything from the streaming itself, to the site it's hosted on IPFS to the streaming through Livepeer, to the ENS domain and the .limo, which is a decentralized alternative to Cloudflares reverse proxy for ENS names and IPFS content. 

**Describe the problem you are solving.** 

Creators on platforms like Twitch or Youtube are the sole value creators for the platforms. They bring all of the attention to the platforms for the platforms to monetize and in the best case, split revenue. But what about all of the value that they are creation for the company? Taking that into consideration, the best case scenario on Youtube, the platform is keeping more than 95% of all value created. On some platforms, creators can arbitrarily be removed or restricted based on the beliefs they have.

**Describe the solution you are proposing.** 

We’re here to change that, and bring more value back to the people who are creating it. Decentralizing the power and decentralizing the wealth creation to all levels of people who participate in a protocol is the future of business in all areas. Building a decentralized protocol means that it’s censorship resistant as well, so no one entity can take away someone’s right to earn an income or their place to voice their opinions even if they differ.

**Describe the scope of the project including a rough timeline and milestones** 

- MVP - live as of early February
- Initial Feedback - Looking to get 100 hours of streaming and feedback from my usage and usage of my friends on the platform over the next 2 weeks, (ending early March). One of whom is a tik-toker with over 1M subscribers, but is starting to test with a small group.
- Early Creator/Gamer users - My tiktok friend has a network of friends who are open to trying out our platform. We want to get at least 250 stream hours of test/feedback from them from them by the end of March.
- First large scale live stream event - In early April, we want to have our first mass marketed live stream event on the platform with my tiktok friend. It will be a live stand up show (as he’s a comedian), live stream gaming or live streamed workout. Our goal with this is to pass 1000 people on a stream.
- Many Live Stream Events - host a suite of live streamed events throughout April, with the goal of hitting 1,000 hours streamed in April.

DAO-ify & Token-ify Imbue - Either do a token Airdop, or a token sale, for the IMBUE token and sign over all IP to the Imbue DAO in Early May.

EOY Goals - 500 creators on the platform, 10,000 monthly streamed hours.

Upcoming Product Releases:

- Mobile streaming - Allow influencers to stream from the convenience of their phone, and users to view & sign web3 transactions from their phones.
- NFT event tickets - when a user purchases, or attends a live stream, they receive and NFT ticket in their wallet that can be used for things like accessing a discord channel, or just to show off to their friends.
- Pay and View from any Chain - if the event is minted on Polygon, the event can be purchased and viewed on Optimism, or Harmony. If the event is minted on Optimism, it can be purchased and viewed on 
- Gas Free events - no need to sign a transaction to view free streams.
- Custom Streaming - allow creators to input the stream key into a streaming source of their choice to allow for maximum flexibility on streams (OBS, etc.)
- Creator Coins - allow users to support their followers even more by purchasing coins and tapping a heart, spending the coins. The top 3 people who donate the most hearts will get a 1 minute 1 on 1 call with the creator after the stream.
- Subscriptions - subscribe to any user to access all of their streams all the time

**Please estimate hours spent on project based on the above**

Hours & funds spent on project so far:

- 20hrs/wk for 8 weeks - 160hrs 
- My own funds spent so far ~ $5,000

Funds requested and time for above dev sprint (work with contract developer as well)

- 500-750 LPT (~$15k-$20K)
- 15k would be to cover all essential technical tasks related to building the product, and allow us to build a lot quicker.
- 20k extra $5k would be nice to have to assure creators will have guaranteed income for the streams, especially if they are large influencers to help them mitigate risk. ( i.e. we guarantee that you’ll make $1000 from this stream, if you don’t, we’ll foot the bill for the difference)
- Hours projects for continued project (still have full time job) 20-30hrs/wk. to complete product sprint releases mentioned above, will probably take 12-16 weeks

Other things to note:

- This is open source - https://github.com/imbueworld/influence-create
- This will transition to a DAO with multisig holders from every decentralized protocol (livepeer, ens, l1/l2 chains, and from our team) that we use through the $IMBUE token

**Comment by nelsorya** [comment]
Hi @carrabre, thanks for putting this together. This is a very interesting proposal and all very well thought out. With these proposals, we typically break up the grant across the milestones. We also like to set a success metric linked milestone (100,000 streamed minutes). We also pay 20% of the total grant upfront so you can start development (all payments are in $LPT).

1. Official Launch ($5,000)
2. Community Feedback ($5,000)
3. Large Scale Livestream Event ($5,000)
4. Success Metric Bonus - 100,000 streamed minutes ($5,000 in LPT and we will cover the transcoding costs)
Estimated infra cost of 200,000 mins (00 concurrent viewers) = $5,200)

**Comment by carrabre** [comment]
Amazing!! Thank you guys so much 🙏

Sounds good to me! Excited to keep building 🥳

**Comment by nelsorya** [comment]
Ok great @carrabre. If you can add me on Discord we can talk next steps there, I think you have dms closed. I'm Nelson#6080

**Comment by carrabre** [comment]
Just added you @nelsorya! Think you have your DM's closed as well haha. Friend request sent though!

**Comment by carrabre** [comment]
Milestone 2 has been completed!

https://www.producthunt.com/posts/imbue-eth

Excited to get community feedback over the next 2 weeks!

We also surpassed 1,377 transcoding minutes for tests last month!

**Comment by carrabre** [comment]
Milestone 3 has been completed. We completed a live stream within the core community at Presearch, and had about 25 join!
