### ISSUE TITLE
NFT | LA Promotional Video/Commercial 

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/Grant-Program#49]
**Give a 3 sentence description about this proposal.**
This proposal focuses on content creation for Livepeer, specifically pertaining to the NFT | LA event coming up soon. The goal is to create a fast paced ~3 minute video charging through the history of video/media with the potential to be condensed and used across many different platforms. Through the use of pre-existing footage the video will tell the story of innovation through time and is an attempt to highlight the importance of video production in the Web3 space.

**Describe the problem you are solving.** 
Livepeer lacks an original production showing off how truly innovative and accessible the protocol is.  After some back and forth with Livepeer's global head of marketing, Meredith Tretiak, we've established a concept that aims to solve this problem through creative story telling.

**Describe the solution you are proposing.** 
I propose a creative piece primarily designed for NFT | LA, which can be used to promote Livepeer as a brand and attract a larger user base across the entire protocol.

**Describe the scope of the project including a rough timeline and milestones** 
This project is broken down into two phases. Phase 1 is pre-production and involves extensive research into not only current innovations in video/media but also archived material from as far back as the 1930's. In phase 2, footage will be meticulously edited into a fast paced story that leads up to an epic reveal shot of the Livepeer network expanding over earth. 
 
One weeks worth of work has already been completed, including a significant portion of the research and editing phase. Due to the deadline of March 28th, this specific video will be comprised of pre-existing footage but focuses strongly on maintaining creativity throughout. 

During the process of creating this video it is important that the appropriate measures are taken for proper licensing of footage and music. While licensing stock footage is a simple one-click process, reaching out to video owners is not so clear cut and does not have a definitive timeline. 

A question I have regarding licensing is should this be something I take care of myself or is there a legal team in-place that can handle permissions?

**PHASE 1**
- 1 day of storyboarding
- 1-2 weeks of research where necessary footage is collected and sorted

**PHASE 2**
- 2-3 weeks of editing 
- Additional story-driving graphics
- Final reveal scene and call to action
- Necessary revisions and polishing

Throughout this process communication with the marketing team is ongoing and the work is subject to feedback and critique.
 
**A hard deadline has been set for the 28th of March** 

**Please estimate hours spent on project based on the above**
An estimated 40 hours have been spent researching and editing a rough concept.
As this is a solo operation with some assistance from the core team and a hard deadline I'm estimating a full months worth of work will be required to have a final version ready by the NFT | LA event on March 28th.

I'm requesting a direct payment of $10,000 which will cover my fee based on labor, hours and work completed.
The cost of licensing for any copy-right footage or material used, however, is currently unknown but a very rough estimate would be $2,500 - $3,500. This includes stock footage, music, necessary 3D assets, effects and any videos requiring a license to use. If the committee decides to agree on the estimated cost for licensing and it comes out to less than what's listed, the remaining amount will be returned.  

As well as being a videographer/editor I am also an active high performing Orchestrator and would like to maintain that status for many years to come. Depending on the companies interest in content creation for Livepeer, I would like to open a discussion for a potential future Livepeer company delegation to my Orchestrator node.

If nothing else, I hope this proposal can open the floor for future creative opportunities in the community. 

Please feel free to ask me any questions.

Thank you.

**Comment by nelsorya** [comment]
Hey @AuthorityNull, thanks for making this proposal. This all sounds great and we are happy to move forward with this. We will follow up over discord in regards to next steps.
