### ISSUE TITLE
Web 3 Edi

### ISSUE THREAD

**Issue by cryptotwilight** [livepeer/Grant-Program#50]
**Give a 3 sentence description about this proposal.**
The **Web 3 Edi** is an opensource and new decentralized educational learning experience powered by Livepeer. It provides permissionless learn to earn broadcast, recording and nft course minting to digital communities.  In short with academy box you own your educational experience. 

**Describe the problem you are solving.** 
The challenge with Web2 educational platforms is two fold, first the attribution rates are not high leaving instructors feeling unrewarded for their efforts. Second for students they have no way to share their learning or recoup their investment beyond applying their new knowledge, think all the ancient text books you still have from school. 

**Describe the solution you are proposing.** 
The solution to this challenge is to provide a platform that enables instructors to better engage and deliver value to their audiences availing them of new methods of commercialising content such as Web3 tips, money streams, drips and more. For students the solution is to enable them to mint their learning experience on completion and trade them on open platforms.

This is **Web 3 Edi**. We enable instructors to broadcast and monetize their communities using Livepeer and we enable students able to mint and monetize their completed course experiences.

**Describe the scope of the project including a rough timeline and milestones** 
The scope of this project will be to further develop the **Web 3 Edi** project post hackathon* over a 3 month timeline: 

***Technology - Milestones***
- Augment our smart contracts
   - introduce scaling support using the Open Block EI 
- Update our UI to 
   - Develop out our user dashboards 
   - Improve content creation and management controls
- Update our tokenomic reward model
   - Add student rewards 

***Business - Milestones***
- Engage community markets
   - Web2 Instructor markets 
   - Web2 Student markets
- Build our following
   - Establish discord following
   - Establish twitter community
- Establish our business calendar
   - Align with any Livepeer promotion support

**Please estimate hours spent on project based on the above** 
The estimate is approximately 720 person hours split across a team of three over a period of 3 months. 

--------------------------------------------------------------------------------------------------------------------------------------------------
* We are currently competing in Web3Con

**Comment by nelsorya** [comment]
Hey @cryptotwilight, thanks for making this proposal. Could you tell us more about what you already built at Web 3 Con? Is there anything you can share?

**Comment by cryptotwilight** [comment]
Hello @nelsorya thank you for getting back to us. Please find below a link to the Github Repo and a link to our live demo.
Repo: https://github.com/cryptotwilight/web3edi
Demo: https://bold-bonus-6282.on.fleek.co/index.html

Thank you

**Comment by nelsorya** [comment]
Hey @cryptotwilight, that's great. We are happy to be fund this. Let's create a shared chat on discord where we can provide support and talk next steps. I'm Nelson#6080 on discord.
