### ISSUE TITLE
Creation of Greek Community

### ISSUE THREAD

**Issue by johnarva95** [livepeer/Grant-Program#51]
**Give a 3 sentence description about this proposal.**
We plan to create a newsletter translated into Greek, a Greek Twitter account that will be grown organically and around which the Greek community will be structured. We also plan to translate the documentation of the project, the app as well as the website.

**Describe the problem you are solving.** 
Greece is a country that has suffered extremely as a result of the financial crisis.

Despite the repayment of IMF loans granted as aid during the financial crisis, Greece's debt situation remains precarious. Public debt reached a new record at the end of 2020. The Corona pandemic is setting the country far behind in debt reduction. So we always have to look at the sociopolitical background as well before comparing figures and countries.

In some countries it will take much longer to build a community than in others. This is due to the size of the population, the cost of living (i.e. what you still have available for financial investments), the willingness to take risks and much more.

**Describe the solution you are proposing.** 
By creating a Greek community, the Greek audience will become more engaged with Livepeer. The rate of engagement of Greeks with cryptocurrencies is relatively low. A big problem in this is the lack of knowledge of the English language. Many Greeks use English only at a basic level, i.e. what the tourism industry requires. That is why creating a community in their native language will give them the impetus to be more active with Livepeer.

**Team**:

Our team consists of experienced translators and Community Managers. We have a background in many Crypto Projects such as Monero, Ocean Protocol, The Graph and others and have consequently gained a lot of experience in Community Building. 

[**Ioannis Arvanitakis**](https://daoconstructs.xyz/team/community-growth/ioannis-arvanitakis/)
[**Iason Andreou**](https://daoconstructs.xyz/team/community-growth/iason-andreou/) @zero-andreou
[**Donald Iljazi**](https://daoconstructs.xyz/team/builders/donald-iljazi/) @Xk9eboF6
[**Stavros Kylonis**](https://daoconstructs.xyz/team/builders/stavros-kylonis/) @DAOConstructs

**Describe the scope of the project including a rough timeline and milestones** 
Milestone 1: 
- Creation of Greek Twitter account
- Creation of the newsletter and translation of [blog posts](https://medium.com/livepeer-blog)
- Translation of the [website](https://livepeer.org/)

Milestone 2:
- Translation of the [docs](https://docs.livepeer.org/)
- Translation of the [WHITEPAPER.md](https://github.com/livepeer/wiki/blob/master/WHITEPAPER.md)

**Please estimate hours spent on project based on the above** 
We are applying for $5000 for our project.

The funding will be used to cover the team's salary, the costs of professional translators and the expansion of our project.

We estimate that we will spend 100 hours to complete the project and credit $50 per hour.

**Within one month of confirmation of the grant, all milestones will have been met.**

**Comment by nelsorya** [comment]
Hey @johnarva95, thanks for putting this together. We are currently in the process of revamping the Livepeer Website and will review translation proposals after that is complete. As for the Greek Livepeer Twitter and Newsletter, while we are in full support of organic Livepeer communities forming focused on different geographies, I'm afraid translating the Livepeer Newsletter and Twitter to Greek is not something we are focused on funding right now.

**Comment by johnarva95** [comment]
Hey @nelsorya, Thank you.
