### ISSUE TITLE
Odyssey DAO - Quality Web3 Education

### ISSUE THREAD

**Issue by mltan4** [livepeer/Grant-Program#52]
**Give a 3 sentence description about this proposal.**
We're creating quality web3 education to onboard the next 1 million people to web3. Check out our learning paths and articles: https://www.odysseydao.com/

**Describe the problem you are solving.** 
We are creating more learning paths, protocols, and platform tutorials to help onboard people. We are also working on localized technical and non-technical education and tutorials in native languages. 

**Describe the solution you are proposing.** 
1. Content guide that will be published on our site and for public goods. Showcase the potential of technology and add use cases on how to get started
2. Dedicated page, a placement on the landing page, and web3 companies
3. Add a profile under people of web3
4. Promotion on social and email our newsletter subscribers (12k+)
5. Option to do an event or community workshop to increase awareness of the product
6. Option to localized technical and non-technical education and tutorials including Chinese, Italian, Spanish, Russian, Japense, Portuegese, and German

**Describe the scope of the project including a rough timeline and milestones** 
Target to complete the content, dedicated page, people of web3, and promotion, and event and workshop within 30 days of grant approval. 

**Please estimate hours spent on project based on the above** 
30 to 40 hours

https://www.notion.so/Odyssey-DAO-Grant-Proposal-ba64bd74982d407c892570a056112ccf

**Comment by nelsorya** [comment]
Hey @mltan4, thanks for putting this together. After looking over OdysseyDAO, I'm afraid this isn't something we are willing to issue a grant for right now. While we see the benefits to broad Web 3 education, we feel it's more impactful for Livepeer Grants to focus on supporting new applications which can drive demand to the network and community-created content focused on Livepeer and its community.
