### ISSUE TITLE
Getting Started with Livepeer Blog

### ISSUE THREAD

**Issue by camiinthisthang** [livepeer/Grant-Program#53]
**Give a 3 sentence description about this proposal.**
Writing a Getting Started with Livepeer suite of content to help devs start building with Livepeer. 1 blog post and two workshops that are linked in the blog post: minting a video NFT and using the Livepeer streaming API

**Describe the problem you are solving.** 
Making it easier for devs that are not video experts to understand the value of Livepeer and streamline the process from awareness to shipping a project.
**Describe the solution you are proposing.** 
Content suite
Blog - https://camiinthisthang.hashnode.dev/the-developers-guide-to-getting-started-with-livepeer
Livestream API workshop - https://github.com/camiinthisthang/livepeer-demo-app-instructions
Mint a video NFT - https://github.com/camiinthisthang/livepeer-nft

**Describe the scope of the project including a rough timeline and milestones** 
Discussed in emails

**Please estimate hours spent on project based on the above** 
20 hours

**Comment by Ahmetelsemeli** [comment]
Good project
