### ISSUE TITLE
WeShare Live Streaming Platform: Advanced System Expansion for Livepeer Creators

### ISSUE THREAD

**Issue by portl13** [livepeer/Grant-Program#55]
![WeShare-Main](https://user-images.githubusercontent.com/72527391/162813126-0d5351f5-1502-4dda-9d75-ece89458975e.jpeg)

**WeShare History:**
Our team has come together, with decades of experience creating large scale music, art and pop culture events. Our first app, PORTL was initially conceived of as a platform to connect people with events in their local community or on their travels around the world. We completed the iOS app in late 2019 and were planning a spring 2020 roll out, when the pandemic put the brakes on our best laid plans. We quickly pivoted to promoting and producing large scale online events, including One Earth Live, Virtual Burning Man, Faerieworlds, and the Shift Summit. Many of our events were benefits for social causes, raising hundreds of thousands in donations for environmental causes, covid relief and to support the artists who were part of the events.

Our experience working with creators both online and in the real world led us to focus on building our new WeShare platform in the creator space. WeShare is a live streaming platform focused on creating an equitable space for content creators to monetize their content in a fair and empowering way. Concurrently our platform provides consumers the ability to support their favorite creators and to find exciting new creators. From a technical standpoint, we are utilizing tools from Web2 and Web3 to bring a marketplace to the forefront that works for everyone.

So for the last 18 months we have been building WeShare, a place for content creators to get a fair connection with their fans, and a fair share from the platform. WeShare is a place where creators of all types have space to connect and monetize their amazing offerings to the world. Video is a big part of that plan, wherein we came across the Livepeer project. We’ve been exploring with the Livepeer community for almost 2 years now, and have met multiple times with Eric, Angie, Paige and Doug … We’ve built our MVP video live streaming functionality around LivePeer and look to form a strong partnership as we officially launch in Q4 of 2022

**WeShare Deck with features:**
https://spaces.hightail.com/space/rNnqiU0GxZ

**Identified Problems we are seeking to solve:**

a. No way for easily integrating Livepeer’s Web3 solution with legacy systems such as wordpress
b. Currently, when using LivePeer, we are using LivePeer’s Storage system for on demand videos, which is limiting for us in what we can do with our video content
c. Currently, we lack the ability for Live stream creators to mint NFTs from Livepeer video recordings.
d. We need for more controls and features in Livepeer webcam SDK
E. Livepeer has an amazing platform, and WeShare large scale global events will market both projects to millions of people.

Our Solutions

a. Plugin development for auto generating Livepeer channels and video players for Wordpress creators.
b. Improvements to Livepeer browser based streaming interface written in React
c. NFT Minting of Livepeer recordings using the EVM. (React and Wordpress Compatible)
Timeline:
The WeShare platform is 90% developed and we have a team of developers working on the project full time.  We have been developing the platform with a global tech team for 18 months and are 2-3 months from Beta launch. 
These new features and the promotion of the Livepeer / WeShare partnership would both be included in our grant scope. 

Estimated Developer Hours: 600

Milestones:

MileStone #1: Complete a Wordpress plugin that allows a user of WP to input their livepeer credentials and embed their video on a page or post with a shortcode or via templates: 
$15,000. 

Milestone #2. Improvements to function of Browser based LivePeer streams 
$15,000

Milestone #3  Automatically Mint NFT’s based on a published Stream and deliver them via Wordpress or React $12,500 (also possible Varda integration for storage)
$15,000

Milestone #4 Global Marketing of WeShare platform with focus on Web 3.0 features including Livepeer.   We will be launching a series of concerts called ONE FUTURE which will feature global artists in support of major nonprofits. 
$15,000+ (open to larger grant for major exposure events)

Marketing Partnership: We’d love to be close collaborators with the Livepeer project. Let’s meet soon to discuss possibilities as we build to a public launch in the fall.  We would also like a chance to demo for your team the advanced Live stream marketplace system we have developed for creators.
![WeShare-TheProblem](https://user-images.githubusercontent.com/72527391/162813210-46aaf24e-edfc-456c-849f-e492f4fbd4d4.jpeg)
![WeShare-TheSolution](https://user-images.githubusercontent.com/72527391/162813251-1d02a095-667d-4347-8967-f4f9bad8e9dd.jpeg)
![WeShare-Revenue](https://user-images.githubusercontent.com/72527391/162813284-06373649-9634-4a1b-a8c0-c042c0af6708.jpeg)
![WeShare-Technology](https://user-images.githubusercontent.com/72527391/162813300-b73abf93-fe7c-4280-a09c-f7b8aac935ef.jpeg)

**Comment by nelsorya** [comment]
Hey @portl13, thanks for putting this together. This is very interesting. With these grants we typically prefer to break them up into smaller more measurable milestones. For this grant we would propose cutting the scope back to the Milestone 1 WordPress plugin and then we can explore the other milestone projects from there. 

The milestones we would propose for the Wordpress integration could be something along the lines of:
1. Wordpress Plugin integration ($5,000)
2. Wordpress web page video embedding ($5,000)
3. Community Feedback ($5,000)
4. Success Metric Bonus - 100,000 streamed minutes ($5,000 in LPT and we will cover the transcoding costs)
Estimated infra cost of 200,000 mins (00 concurrent viewers) = $5,200)

**Comment by portl13** [comment]
Greetings Nelson,

This sounds like a good plan for the first project.  Let us know what the community feedback process would be.  Everything else feels clear, and we feel optimistic we can deliver this project efficiently.  Let us know next steps to proceed.

**Comment by earthjeffone** [comment]
Hi I'm Jeff, A member of the WeShare team, I help us with operations and systems architecture! We have a channel that Alexander setup on the LivePeer Discord already, let us know your handle and we can invite you.Or send us an invite,  Emilio's @portl13  Discord handle is Emilio#8282 and mine is earthjeffone#6337 ,  Looking forward collaborating with the community to create a useful resource and cocreate!

**Comment by nelsorya** [comment]
Ok great, I've just added you both on discord
