### ISSUE TITLE
 Kokonut Network "Unlimited Scalable Coconut Farms"

### ISSUE THREAD

**Issue by aaempire** [livepeer/Grant-Program#56]
**Give a 3 sentence description of this proposal.**
Kokonut Network brings blockchain governance and open-source accounting, to the agriculture industry. Kokonut Network promotes, organizes, funds, and manages coconut farms. We gather funds from the community using the DAOHaus framework for decision-making and project development funds allocation.

**Describe the problem you are solving.** 
High demand from the national and international markets. Annual domestic production does not meet demand. Every year the Dominican Republic imports about 25 million units of coconuts, which return to international markets as exports of coconut derivatives.

**Describe the solution you are proposing.** 
 Incorporate six hundred and twenty (620) Acres of land for phase 1 and (3,100) acres of land for phase 2, into the national production system; to be able to increase national annual production, and reduce demand.

**Describe the scope of the project including a rough timeline and milestones** 
The coconut plants will be positioned at a sowing frame of 7.5 x 7.5 meters away from each other. That is equivalent to ninety-six (96) plants per acre of land, which equals 60,000 plants within the six hundred and twenty (620) Acres of land in hand. This variety is capable of producing about three hundred (300) fruits per plant, which makes about 18,000,000 units each year. The market price is around USD 0.44 per unit, which is equal to USD 7,920,000.00 per harvesting year, the DAO will get 40% of the profits.

With the investment in this project, the organization seeks to incorporate into the productive process of the area. A total of 10,663 direct and indirect informal jobs. Which has to do with the labor that is required for agricultural tasks such as weeding, application of pesticides, fertilizers, irrigation, and harvesting. As well as other activities to guarantee major success for this project.

We count on all the permits necessary from the government, economy, weather, and fertile land. Coconut farming is a proven business that has a lot of upsides.

**Please estimate hours spent on the project based on the above** 
We as a team have more than 1 year working on this project so we can be at the stage we are right now. Land, Plantation Design, Planting Permits, Local Permits, Workers, and Business Plan. We have been working hard, we just need a community of people that invest and work on the project.

**Comment by aaempire** [comment]
All of our links are here > https://linktr.ee/kokonutnetwork

**Comment by nelsorya** [comment]
Hey @aaempire, while this is interesting, I'm afraid Livepeer Grants only funds grants focused on the Livepeer ecosystem so this is out of focus for us.
