### ISSUE TITLE
Decentralized Library

### ISSUE THREAD

**Issue by holyaustin** [livepeer/Grant-Program#57]
**About me**
I am an IT professional with more than 10 years of experience as a software programmer and student tutor. With over 3+ experience in Blockchain technology. Skilled at operating in a wide range of platforms. Excellent written and oral communication skills; capable of explaining complex software issues in easy-to-understand terms. I have worked on some couple of hacks and projects and decentralized Library happens to be one am currently working on.
LinkedIn profile: https://www.linkedin.com/in/holyaustin/
Twitter Handle: https://twitter.com/holyaustin

**Give a 3 sentence description about this proposal.**
Decentralized Library is a LEARN and EARN project that uses ERC-721 to create ebooks and video books for users. It leverages the power of Decentralized storage to store books (ebooks and video books) for students and other users who can read books or watch video books online or download them for offline usage. The second feature is the streaming of Live classes, tutorials, academic Presentation, academic conferences and workshop which can be achieved using the Livepeer Protocol.

**Describe the problem you are solving.** 
Sometimes in 2018, the government of my country (Nigeria), removed major academic courses from the school's curriculum without any justification. A Course like History is no longer been studied and our children cannot be told or taught what happened in the past. This kind of government censorship policy necessitated this project. Secondly, there is a decline is the quest for knowledge.  The facts that web3 solves the issue of centralization, Decentralized library was born to make available academic materials for users who which to gain insight and knowledge in areas that some government policies have masked from her citizens and also get rewarded (earn) for using the library.

**Describe the solution you are proposing.** 
We are proposing a decentralized where of storing and accessing academic materials for posterity's sake. Our future generation should have something to read about us and our predecessors. Using Livepeer Protocol to stream classes, webinars, and academic conferences without the barrier of centralization.  This is where Decentralized Library comes to play. The Library uses the power of decentralization to store wealth of books in ebook and video formats. Users are incentivized to actually earn knowledge by visiting and reading books /watching video books from this library and joining live streams. You earn when you show you have acquired knowledge from the material read.

**Describe the scope of the project including a rough timeline and milestones** 
The scope of this projects is not only focused on the academic community, but to the entire human populace at large. We are focused to make contents for both academic and non-academic communities.  The creators of stream will control their live streaming experience and mint those streams as NFTs.

**Please estimate hours spent on project based on the above** 

Phase 1. Stream Dashboard and smart contact:  ($15,000)
1. Unlock Stream with Unlock
2. Ability to choose stream platform(either from OBS or from Browser).
3. Live stream to audience from Decentralized Library live stream page.
4. Store live streams to IPFS 
5. mint it as NFT. Viewable on Opensea and Rarible

Phase 2. Streaming Profile and Testing: ($15,000)
The streaming profile is social landing page for the creator.
1. Display the playback URL from Livepeer on profile
2. Display current live stream
3. Product Launch 

Milestones for Phase 1  ($15,000)
Milestone #1 (Estimated Deadline (~1 week) end of April 2022)
Create a user profile and registration for streaming with Unlock

Milestone #2 (Estimated Deadline (~2 weeks) May 2022)
Develop the front-end for users to choose which way to stream (from OBS/Browser)

Milestone #3 (Estimated Deadline (~4 weeks ) May/June 2022)
Integrate to Livepeer network for live streaming
Implement smart contract for minting streams as NFT
Collaborate with Livepeer team for smooth implementation

Milestone #4 (Estimated Deadline (~1 week) June 2022)
Create a decentralized storage for live tream storage

Milestone #5 (Estimated Deadline (~1 week) June 2022)
Create a links to view minted NFTs on Rarible and OpenSea

Milestones for Phase 2  ($15,000)
Milestone #1 (Estimated Deadline (~1 week) July 2022)
Implement the playback url from Livepeer on profile for creators

Milestone #2 (Estimated Deadline (~2 weeks) July 2022)
Develop to display live-stream stream

Milestone #3 (Estimated Deadline (~4 weeks ) July/August 2022)
Finish alpha version development
Onboard small group of testers to provide application feedback

Milestone #4 (Estimated Launch ~Early September, 2022)
Launch of Dapp

**Requested funds - $30,000 USDC **

Please estimate hours spent on project based on the above
Livepeer network for live streaming: 100-200 hours total (Might increase in course of development)

Other things to note:
This is open source - Github Repo: https://github.com/holyaustin/decentralized-library

**Comment by holyaustin** [comment]
Decentralized Library grant

**Comment by nelsorya** [comment]
Hey @holyaustin, thanks for putting this proposal together. This sounds like a very interesting project. With these grants we typically prefer to break them up into smaller more measurable milestones. We would propose cutting the scope back of the proposal to the more essential features to begin with: 

1. Steam dashboard and smart contract ($1,000 in LPT)
2. Streaming profiles and Livepeer live streaming integration ($1,000)
3. Product testing ($1,000)
4. Testing, auditing and community feedback ($1,000)
5. Success Metric Bonus - 20k video views on the platform ($1,000)

**Comment by holyaustin** [comment]
Hi LivePeer Grant Team,

I am indeed Overwhelmed that the project caught the attention of your team Haven has broken the project into smaller milestones, Which is accepted by me. What should I do now to start off with the grant? is there any form to fill? How do I get the first tranche to help with the project development?

Thanks for the support,

Augustine Onuhora





On Monday, May 2, 2022, 07:45:55 AM GMT+1, Nelson Ryan ***@***.***> wrote: 







Hey @holyaustin, thanks for putting this proposal together. This sounds like a very interesting project. With these grants we typically prefer to break them up into smaller more measurable milestones. We would propose cutting the scope back of the proposal to the more essential features to begin with:

     
    1. Steam dashboard and smart contract ($1,000 in LPT)
    
    2. Streaming profiles and Livepeer live streaming integration ($1,000)
    
    3. Product testing ($1,000)
    
    4. Testing, auditing and community feedback ($1,000)
    
    5. Success Metric Bonus - 20k video views on the platform ($1,000)

**Comment by nelsorya** [comment]
Ok great @holyaustin. In terms of next steps, reach out to me on discord and we can create a shared group to stay in touch and coordinate the first payment. I'm Nelson#6080 on discord.
