### ISSUE TITLE
ContiDAO - Mass Adoption of Livepeer Network

### ISSUE THREAD

**Issue by Megalo-don** [livepeer/Grant-Program#58]
Author: **Adonis Ferreira**
Role: Gov Lead in [Continent DAO](https://contidao.com/)
Documentation: https://docs.contidao.com/introduction/

_**Give a 3 sentence description about this proposal.**_

**Summary**
Continent DAO or ContiDAO is a DAO that supports economic and social programs to bring cryptospace products to billions of people around the world.

**Our Mission**
The Continent DAO was created with the mission to include people who really need their inclusion in the Crypto, Meta and DeFi universe, these people need their inclusion for survival, they fight hyperinflation, lack of financial and banking options, lack of access to social assistance, among other factors.

**Vision**
We believe in the inevitability of Web 3 and its products like Crypto, DeFi, NFTs, DIDs and the Metaverse. It is our conviction that these are goods that must be accessible to everyone and especially the populations that most need these resources, not just a group or class.

_**Describe the problem you are solving.**_ 

The Web 3 industry is creating many solutions and products that can change people's lives, but they forgot to solve existing problems of Web 1 and 2, mainly the network infrastructure:
- 37% of the world's population has no access to the internet
- Brazil is one of the richest countries in South America and in the world, but more than half of the population still uses limited internet packages and many still do not have access coverage.

_**Describe the solution you are proposing.**_ 

We solved basic Web 3 infrastructure issues, such as large-scale internet access. For this we form private and governmental partnerships.
An important part of our project is the monetization of advertisements and advertising during the time intervals on connections, we believe that we can develop a collaboration with the creators of content in your ecosystem and also directly with the Livepeer Network. We can be a great ally and distributor of the contents present on Livepeer.
We are a DAO deployed on the Near Protocol, but our programs are cross-chain and public goods.

_**Describe the scope of the project including a rough timeline and milestones**_ 

Phases | Description | Status
-- | -- | --
Phase 1 | Creation of Continent DAO and Token (CONT) | Completed
Phase 2 | Approval of the first and second Grant via NEAR Foundation | Completed
Phase 3 | Approval of government Internet distribution programs | Completed
Phase 4 | Fundraising for application of programs in Latin America. | In progress
Phase 5 | Signing of documents relating to the partnership of a private company (service provider; telecom) | In progress
Phase 6 | Period of implementation of the first distribution services. (20 days of term) | In progress
Phase 7 | Token Release (CONT) - IEO/IDO | In progress
Phase 8 | Monetization/Data Market | In progress
Phase 9 | After 4 months of successful operations in the city of São Paulo, start expanding in other countries. | In progress
Phase 10 | Development of collective and individual solutions and tools for Data Economy, DIDs, projects with NFTs. | In progress

_**Please estimate hours spent on project based on the above**_ 

We aim to complete all these milestones by the beginning of next year, but an integration with Livepeer technology may vary depending on the availability of our teams, we are available to plan this in detail.

**Comment by Megalo-don** [comment]
> Hey @Megalo-don, thanks for putting this together. Could you provide some more context on how this would use Livepeer specifically?

- Incentive to government and private structures to transcode, host and stream videos through Livepeer instead of traditional means of cloud services.
- Use of hotspots for the dissemination of marketing/advertising material from Livepeer and its ecosystem.
- Massively scalable enough for us to implement future functionality described in the whitepaper as "Ad insertion/monetization and analytics can plug into the Livepeer ecosystem and potentially make use of the security provided by LPT."
- Incentive to use LPT token to increase token demand and fee collection.

Local Contexts

- The state of São Paulo recently spent approximately **$20M USD** on marketing, advertising, cloud and streaming services.
- There is a billion dollar revenue capacity for the Livepeer niche in Brazil.
- The greatest communicators and studios today seek solutions with freedom and independence. (Brazil has the second largest commercial television network in the world).

**Comment by ericxtang** [comment]
These are interesting concepts.  Would love to see concrete proposals around how exactly they can be implemented, with clear milestones and scopes.

**Comment by Megalo-don** [comment]
> These are interesting concepts. Would love to see concrete proposals around how exactly they can be implemented, with clear milestones and scopes.

Great, thank you @ericxtang !

We think of the following scope and milestones:

1. Include Livepeer Network in our existing collaboration initiative with several cities, including the cities of Rio de Janeiro and São Paulo. -  (_$25,000 USD_ in LPT) 

We have a public funding proposal with BitDAO at $55M USD where we will hire hundreds of hotspots, we would love to include Livepeer technology in this collaboration as well. 

2. First contract to use Livepeer in state services - (_$10,000 USD_ in LPT: amount will be delivered **after** milestone reached).

3. Hiring a hotspot, for Livepeer's exclusive use and showing materials created for advertising/marketing/education during connections - _$25,000 USD_ in LPT every three months. + We include translation/subtitles in local language for free.

The cost of the hotspot is calculated annually at an average of $100,000 USD, if you prefer, we can think of different payment tranches based on this calculation.

The costs will be fully directed towards installation, maintenance and service provision with Telecom. Remembering that the governmental partner contributes with public places and electricity, we do not have expenses with them.

4) With the property of hotspots, Livepeer can integrate your ecosystem with connections and include insertion/monetization of ads and analytics with security by LPT. 

5) Encourage use of LPT token to increase token demand and fee collection. - (_$10,000 USD_ in LPT)

Users to connect to hotspots must fill in their data with CPF (Like Social Security Number in Brazil) and are verified, it is a requirement by law, with this we can make airdrops and fair campaigns.

IIf third parties are interested in marketing and advertising while connecting to Livepeer Network hotspots, ad payments must be **paid exclusively in LPT**.

We suggest _$10,000 USD_ for the first airdrop campaigns.

__________________
The initial grant is $ 50,000 USD in LPT. 
Completing the second milestone will add $10,000 USD and with airdrop $10,000 USD, a total of $70,000 USD in LPT (can also be done after previous milestones).
Livepeer can also set a larger number of hotspots.
_________________

What do you think of this scope?

**Comment by nelsorya** [comment]
Hey @Megalo-don, thanks for sharing this additional context. While this sounds like an interesting use case, we do not feel this is a public good which can benefit the entire Livepeer developer community
