### ISSUE TITLE
Integrate Livepeer with Apple.

### ISSUE THREAD

**Issue by criticaltv** [livepeer/Grant-Program#6]
**Give a 3 sentence description about this proposal.**

Livepeer is a project to build open-source video infrastructure services on Ethereum.

Apple is a producer of premium blue-chip quality consumer devices.

This proposal is to build a set of simple minimal template applications, to make it as easy as possible for someone to reskin and launch an app which plays content from a Livepeer `-broadcaster` on _all_ of Apple's devices.

**Describe the problem you are solving.** 

In current society, live and streaming video is consumed via a finite set of apps and channels, with content provided by a closed-source set of opaque institutions.

These institutions are typically:

- Privately funded (e.g. Netflix, YouTube, Facebook, Twitch, Fox, Sky, Al Jazeera, CNN) with extensive reliance on advertising funding, or
- Publicly funded (e.g. via national governments) by the nation's tax payers.

**Describe the solution you are proposing.** 

The solution is to develop a set of template applications to run on Apple's devices (iPhone, iPad, Apple Watch, Apple TV, MacBook, iMac).

This would enable anyone to launch their own decentralised streaming platform, and to be paid directly by viewers in real time, per second / minute.

The apps would have the following basic functionality.

- Play streaming `hls` video content from a Livepeer `-broadcaster` node

This should play in as high resolution as the internet connection and bandwidth can allow, thus likely making extensive use of Livepeer's Transcoding network and marketplace.

Additional functionality, to provide a financial incentive for people to publish content, would be:

- Force a viewer to pay per second / per minute to view the content (similar to how Gorli TV works):

![Screenshot_20200222-034944](https://user-images.githubusercontent.com/59374467/75109924-ba857380-564d-11ea-986d-fd00602e4d44.png)

**Describe the scope of the project** 

Scope of the project would be to deliver the following specifics:

- Template app code for 4 Apple operating systems (iOS, tvOS, watchOS, macOS)
  - Apps play hls content from a hardcoded Livepeer `-broadcaster` source URL
  - User of app must load up the app's wallet in order for it to pay the broadcaster to watch
  - Code published to https://github.com/videoDAC/apple

- Sample application(s) available for download from Apple's digital app store(s), which can be installed on all Apple's consumer devices (iPhone, iPad, Apple Watch, Apple TV, MacBook, iMac)

**Please estimate hours spent on project based on the above** 

Estimate: total 400 hours, covering:

- **Architecture and Design** of codebase for multi-OS application
- **Software Development** for **all 4** release paths
- **Prototyping and User Testing** - find early users in [Görli TV Telegram channel](https://t.me/GorliTV)
- **Manual Testing**, with full documented test plan and scripts on github (example [here](https://github.com/empowerthedao/compound-aragon-app/issues?q=is%3Aissue+is%3Aclosed+label%3Atest-case))
- **Security Audit Report**, with responses to any vulnerabilities identified
- **Design** for images for submission to Apple Stores
- **Copywriting** for submission to Apple Stores.

More details are [here](https://github.com/videoDAC/android/issues/22), aiming to launch under the brand of Goerli TV.

**Comment by criticaltv** [comment]
Also, you can just contribute to this gitcoin bounty :) until someone decides they want to do it (or LPT moons and there'll be easily enough to fund all this:

https://gitcoin.co/issue/videoDAC/apps/22/

:)

**Comment by nelsorya** [comment]
Hey @criticaltv, interesting proposal. Could you specify what the simplest version of this proposal is and what are the main features you have in mind for the application? Could you also clarify what the goal of this template is for developers and if the project will be open source? 

For this proposal to be fully assessed, it will need to be fleshed out more to demonstrate that the idea is practical and achievable. 

We have also noted that this project is also partially being funded by VideoDAC’s inflation rewards. This certainly doesn’t disqualify the project from grant funding, but it would be helpful to understand how videoDAC's funding will be used towards this project.

**Comment by criticaltv** [comment]
The simplest version of this proposal is a simple iOS smartphone app which plays a single stream served by Livepeer in `-broadcaster` mode.

Code will of course be open-source, otherwise the template will be quite useless to the community.

The goal of the template is to enable even a non technical user to launch an app for their own livestreaming channel served using Livepeer.

This "minimum viable integration" should be highlighted as a baby step on the path to:

- supporting more Apple OSs (macOS, tvOS, watchOS)
- adding more features to the app.

Regarding whether this idea is practical and achievable, I will ask the following questions in response

- Practical: do you think that having a minimal integration between applications running Apple's OS is a good thing or not for Livepeer?

- Achievable: what we are proposing is not rocket science. Is there something about what has been proposed above which you believe to not be technically possible?

**Comment by criticaltv** [comment]
As regards funding, this project is seeking funding from many sources and so far it has received a starting grant from @VideoDAC (thank you!)

The aim is that many parties can collaborate together to ensure that what is being delivered is useful for the community as a whole, and not only members of @VideoDAC

**Comment by criticaltv** [comment]
As regards the functionality for the application, it would be incredibly simple:

- tap launcher to "turn TV on" (takes over the whole screen, no buttons, only content)
- tap screen to "turn TV off"

This simple approach is by design, to minimise complexity for new users.

**Comment by nelsorya** [comment]
Hey @criticaltv, thanks for these answers. What if to start we focused the initial proposal on just iOS as opposed to the four types of devices?

I also have a few follow-up questions just to help us understand the project better. 

1. How would Gorli measure success after this gets listed in the app store?
2. Why does Gorli use GoETH instead of ETH? Will it be possible to use ETH in the future?
3. What is the end goal for Gorli TV? Is it to become an open-source OTT for brands ala Vimeo OTT? https://vimeo.com/ott/home
4. Who are the end-users of these templates? What sort of users/content creators are you targeting?
5. What sort of content will Gorli TV stream? Will there be any sort of scheduled programming?
6. Why the name Gorli TV? Will there be a Gorli TV on the Gorli testnet and then say Critical TV on the Ethereum mainnet? Using Gorli for the mainnet version could be confusing.

**Comment by criticaltv** [comment]
> What if to start we focused the initial proposal on just iOS as opposed to the four types of devices?

I think that's the wrong thing to do. Here's why:

- The scope of the proposed (initial) functionality for each app is (intentionally) incredibly limited:
> Play streaming hls video content from a Livepeer `-broadcaster` node
- Getting a basic app working on iOS only would be trivial, and in fact, a draft of this already exists in Video DAC's repo, we de-prioritised it in favour of Android to begin with.
- The real prize here is in being able to use _the same codebase_ to release to at least 3 platforms (`iOS`, `watchOS`, `tvOS`, maybe let's de-scope `macOS` for now)
- Starting with something really simple (a simple single-stream player), but **aiming to be multi-OS**, enables any evolution of the codebase (e.g. multi-stream, pay-as-you-go etc) to target being able to be used on a broad array of premium consumer devices (iPhone, iPad, Apple Watch, Apple TV)

**Comment by criticaltv** [comment]
And in response to your other questions:

> How would Gorli measure success after this gets listed in the app store?

There would be no measurement of success. Goerli TV is merely a sample deployment of Video DAC's MVP Android Pay-As-You-Go Livestream Viewer App Template. It is intended to be only be a demonstration of the capabilities of the template.

> Why does Gorli use GoETH instead of ETH? Will it be possible to use ETH in the future?

Because when testing a new application, it makes sense to not use real money. This is why testnets exist to enable a live-like experience, without putting real money at risk. Users of the Goerli TV app can test how it works using goETH.

As regards using real ETH, anyone is free to configure these templates to connect to a mainnet endpoint, which would then work with real money.

> What is the end goal for Gorli TV? Is it to become an open-source OTT for brands ala Vimeo OTT? https://vimeo.com/ott/home

No. As above, Goerli TV is merely the first "test" deployment of Video DAC's Pay-As-You-Go Livestream Viewer App Template.

> Who are the end-users of these templates? What sort of users/content creators are you targeting?

The end user of these template is anyone who wishes to deploy their own Livestream Viewer application. They may need help from a friend, or if they have the technical skills, they can follow the published instructions in order to generate and publish their own-branded app.

This project is not targeting any specific types of user or content creator. It is building generic tools which can be used by any content-creator to get started e.g. by running their own livestreaming infrastructure (using [Infinite Digital Stage](https://github.com/videoDAC/infinite-digital-stage/)), and by publishing their own livestreaming app (using the app templates)

> What sort of content will Gorli TV stream? Will there be any sort of scheduled programming?

Goerli TV will stream a test signal. There will not be any sort of scheduled programming, because, to re-iterate, this project is not concerned with content, or programming, or production. It's concerned with creating reusable software to allow other people to run their own livestreaming.

> Why the name Gorli TV? Will there be a Gorli TV on the Gorli testnet and then say Critical TV on the Ethereum mainnet? Using Gorli for the mainnet version could be confusing.

I don't know. Nobody knows what will happen in the future. But all the above options are made possible using the application templates - I don't want to predict how these templates will be used.

**Comment by criticaltv** [comment]
As a final point, please be clear: this project is about integrating Livepeer with Apple, by creating open-source software which can be used by the community as base-level building blocks, upon which they can permissionlessly and freely launch whatever they wish.

The aim is to empower anyone to build "video-enabled applications" which use Livepeer, and ultimately which increase usage of Livepeer's marketplace for Transcoding (and any other video infrastructure) services. Furthermore, the project aims to assist Publishers of Livestream content with building a source of revenue from viewers, which can be used to fund usage of Livepeer's marketplace.

And for the avoidance of any doubt, this project is **not** about building a consumer-facing brand (e.g. Goerli TV), nor is it about producing / selling content, nor is it about increasing viewer numbers.

**Comment by nelsorya** [comment]
Hey @criticaltv sorry for the delay. Ok great, we do really like the idea of creating something like these templates to showcase some of these livestreaming use cases and to help developers understand how to go about building these kinds of apps using Livepeer. We think it could be very beneficial to the community. To go alongside the templates, we also thought it could be a great idea if there was a guide which helped explain how the templates work with developers in mind.

With all of this said, it is important to us that we measure all grants against some measurement of success. Previous grants that have been allocated in the past with this metric defined have delivered far greater results and impact to the community over time. This could be the number of streams, the number of applications built using the tool or some other measure to allow us to quantify the impact over time.

**Comment by criticaltv** [comment]
Let's get a livestreaming app installed on 10 Apple Watches

**Comment by chrishobcroft** [comment]
@criticaltv I like the idea of prioritising for Apple Watch. It would be so unique, and cool, and would raise awareness of the capabilities of Livepeer.

I would also recommend adding in a pay-to-play element ([per this issue](https://github.com/videoDAC/apple/issues/1)), so that the Watch App _Template_ can allow publishers to:

- launch their own app from _template_, with their own brand, etc.
- make viewers pay-to-play published livestream content

And what about something more like this for the success metrics:

- 2 differently branded apps, launched from the same _template_, submitted to Apple App Store
- 1 document detailing how 3 members of community (e.g. @nelsorya, @adamsoffer and @ericxtang) can submit the 3rd, 4th and 5th apps to Apple App Store.
- Race to see who can get 1 ETH income via viewers watching their app, perhaps with a bounty for the winner

Question for @f1l1b0x: can we transcode into a format optimised for playback on Apple Watch? Current models have `272x340` and `312x390` retina displays.

**Comment by ericxtang** [comment]
@criticaltv @chrishobcroft is there video streaming capability on the apple watch?  A little google search shows this <https://www.businessinsider.com/can-you-watch-videos-on-apple-watch>.  I'd be interested to know if you have found a way to stream live video.

**Comment by criticaltv** [comment]
@ericxtang thanks.

No work has started on anything to do with this proposal, as no funding has been secured.

If you're interested in funding some prototyping, and feasibility studies, this will be considered.

**Comment by criticaltv** [comment]
Hi, is there any update on this?

**Comment by ericxtang** [comment]
Hi @criticaltv - the committee has made a proposal of [application guideline](https://github.com/livepeer/Grant-Program/issues/13).  Unfortunately the funding of feasibility studies (especially application-related) isn't in scope.  I understand this can feel like the goal post has been moved - so I want to clarify the reason - there are simply too many possibilities for applications to be built on Livepeer.  At this moment, the committee feels that the funding can be more effectively deployed towards projects that can create more immediate impact.

I think a lot of the thinking here is on track though.  For example, I think it would be very interesting to have an iOS SDK that integrates with the Livepeer API, or even an example broadcasting application.  If you want to work with the Livepeer team on that, please let us know.

**Comment by criticaltv** [comment]
Yeah, sounds good. What do I need to do next?

**Comment by ericxtang** [comment]
@criticaltv if you are interested in exploring either the SDK or the example broadcasting app, the next step would be to create a new proposal (either in this thread or starting a new thread).  Please focus on:
1. Propose a realistic project scope, ideally with milestones
2. Propose success metrics
3. If possible, point to prior examples of projects in a similar space

If the proposal is made before 4/24 (the next grants committee meeting), the committee will review it and get back to you within a few days.
