### ISSUE TITLE
Free Pizza Day

### ISSUE THREAD

**Issue by huglif3** [livepeer/Grant-Program#60]
**Give a 3 sentence description about this proposal.**

We are PizzaDAO - we threw the worlds largest pizza party ever, and this year we aim to go even bigger! Through our initial NFT sale we were able to feed thousands of people in 69+ countries. This year we will go even bigger, because we believe pizza should be free!

**Describe the problem you are solving.**

We feed people all over the world, and empower local pizza shops in the process. Our open source software will help pizzerias with distribution, accounting, delivery and more-- all made possible through partnership opportunities like this. Our partners work with us because they too want to feed the world, and let individuals worldwide know they support a mission as powerful as feeding people worldwide.

**Describe the solution you are proposing.**

Through our partnership we will be able to feed 500 people in major cities like New York, Los Angeles, Chicago, Buenos Aires, and more. There will be over 10 pizzerias supported, and you will also be featured in all comms leading up to, and after Free Pizza Day, May 22nd.

**Describe the scope of the project including a rough timeline and milestones**

- On May 22nd we will activate 9 events in major cities with your support <May 22, 22>
- A small logo will be added to the rarepizzas.com website <After May 22, 22 // DUE: June 6, 22>
- And we will work with you to bring attention to Livepeer through our global livestream, online collaborations-- like twitter spaces, comms, PR <Leading up to Free Pizza Day, May 22, 2022>

**Please estimate hours spent on project based on the above**

100

[PizzaDAO_largest_pizza_party_ever_5_22_2022_.pdf](https://github.com/livepeer/Grant-Program/files/8675163/PizzaDAO_largest_pizza_party_ever_5_22_2022_.pdf)

**Comment by huglif3** [comment]
Hey @nelsorya thank you for getting back to us. We would love to have you take part in our Road to DevCon initiative in q4.

Take a look at our deck :) Let me know if you have any questions.
[PizzaDAO Pizza Sponsors Deck.pdf](https://github.com/livepeer/Grant-Program/files/9387865/PizzaDAO.Pizza.Sponsors.Deck.pdf)

**Comment by nelsorya** [comment]
Hey @huglif3, sorry for the delay in getting back to you. After discussing, I'm afraid we are unable to sponsor this as it's outside of Livepeer grants focus on funding public goods driving developer adoption to the Livepeer network. With that said, if there is any way Livepeer could potentially help support any of your events from a livestreaming perspective, we would be happy to discuss this.

**Comment by huglif3** [comment]
This is awesome news!

We would love to take a look at this for an upcoming event we are hosting
in Davos, Switzerland in January. Would setting up a call be beneficial?
here is my calendly.com/estefaniaochoa
