### ISSUE TITLE
iris

### ISSUE THREAD

**Issue by Victoriakim** [livepeer/Grant-Program#61]
**Give a 3 sentence description about this proposal.**
hello! we're iris, the team behind your two favourite hackathon projects both using Livepeer technology. [Iris](https://showcase.ethglobal.com/lfgrow/iris-bnw7a) and [Tempra](https://showcase.ethglobal.com/ethamsterdam/tempra-xnxf4). 

iris is a social platform for web 3 creators. We want to create a world where users can share exclusive content, grow a community, and own their identity all on-chain.

**Describe the problem you are solving.** 
The future of web3 social media is around the corner, thousands of protocols are being built to tackle governance, moderation, and monetization -however, there is one big opportunity that is lacking: an application layer that utilizes the right technology to deliver an amazing low friction user experience. 

**Describe the solution you are proposing.** 
iris is building a social platform for web 3 creators, with a special focus on an amazing user experience. Our ultimate vision is a platform where users can: 

- Share content on chain (Photos, Videos, Short-form messages, and Live-streaming) 
- (Private messages & token gated content), 
- Grow a community (Gain followers & create shared accounts for DAOs) 
- Own their identity (Sell, buy, and trade their profiles and content) 

We will be utilizing the Lens ecosystem and protocol to build an extensive front-end experience where users can take advantage of a fully composable and portable social media. In addition, our app will be built on polygon, with Lit protocol for token gating, and Livepeer for video streaming. 

**Describe the scope of the project including a rough timeline and milestones** 
MVP Features Progress so far
- [x] Create (mint) profiles 
- [ ] Publish multimeda content (videos, photos, long form text) 
- [x] Publish text posts 
- [x] Follow account
- [ ] Gate content (followers vs. not following)
- [x] Like posts (collect) 

Phase 1 (~$10K USD worth of LTP)
- [ ] 3k Twitter followers, 1.5k Discord community
- [ ] Implement VOD capabilities using Lens & Livepeer SDK*
- [ ] Feedback session around Livepeer & Lens SDK 
- [ ] Co-host Twitter spaces with Livepeer around using Lens SDKs

*note, if Lens SDK is not ready by this point, we can set up the API ourselves.

Phase 2 (~$10K USD worth of LTP)
- [ ] Add Live Streaming & Stories feature utilizing Livepeer transcoding capabilities
- [ ] Monthly check-in meetings with Livepeer 
- [ ] MVP Mobile app designs

All of our milestones revolve around expanding and engaging with Livepeers' ecosystem. In addition, we will ensure that the portion of the code integrating Livepeer's product with Lens will be open source, so we have a more composable product that the Livepeer community can learn from. Each achievement will take us closer to creating an amazing social application layer for the end-user to be able to experience Livepeer's technologies. In total we're asking for 40K USD worth of LTP. 

**Please estimate hours spent on project based on the above** 
Collectively around 80-100 hours a week.
- 2-3 Developers 
- 2 Designers
- 1 PM/ Business Dev

** Check out our alpha mainnet launch here https://www.iris.social/ **

**Comment by nelsorya** [comment]
Hey @Victoriakim, thank you for putting this together. This is a really interesting concept. We are interested in funding this grant, but we would like to rescope this to just the essential features, we were thinking phase 3 and 4 milestones for $20k in LPT. We would also ask that you open-source the tooling you build for integrating Lens and Livepeer to make it easier for other developers to use Lens.

**Comment by Victoriakim** [comment]
> 

Hi Nelson! I've edited the grant proposal to reflect your suggestions. Please let me know next steps from here.

**Comment by nelsorya** [comment]
Great thanks, @Victoriakim. Let's connect on discord and we can create a group to coordinate next steps from there. I'm Nelson#6080 on discord
