### ISSUE TITLE
Rad Radio — a decentralized radio show built on Livepeer and Radicle

### ISSUE THREAD

**Issue by abbey-titcomb** [livepeer/Grant-Program#62]
# **Proposal Overview**

> This is a Marketing and Community Initative proposal

Alongside [NFTBerlin](https://nftberlin.org/#events), a non-profit annual unconference on NFTs, Livepeer and Radicle are launching Rad Radio, an online radio show hosted by [HÖR](https://hoerberlin.com/).

[HÖR](https://hoerberlin.com/) is an independent Berlin-based electronic music streaming platform. With 387k subscribers and an average of 800k views per week, [their streams](https://www.youtube.com/channel/UCmfF7JZv26UUKyRedViGIlw) are an iconic staple of the electronic music scene. [Radicle](https://radicle.xyz/) is a decentralized network for code collaboration. With its Ethereum integration, Radicle enables global ENS-compatible names, decentralized organizations, and funding protocols that help maintainers sustain their open-source work.

Rad Radio will be streamed directly to the Livepeer network, via a custom front-end designed by the maintainers of [streameth.tv](http://streameth.tv) and radicle.xyz. Additionally, the team will attempt to integrate with [Radicle Drips](https://www.drips.network/), to allow for real-time crypto tipping.

## Team

Livepeer: Shannon, Hans, Austin
Radicle: Abbey, Brandon, Jason 
streameth.tv: Pablo 

## **Problem**

Typically, independent streaming platforms & radio shows find themselves locked-in to centralized streaming platforms without an alternative. Organizations like HÖR have no other choice but to build their communities on platforms like YouTube, and often find themselves shorted by copyright & monetization policies. 

## **Solution**

Rad Radio (similar to [streameth.tv](https://[streameth.tv](http://streameth.tv/)/)) is basically a demonstration of how Livepeer can be used in the wild by independent creators looking for an alternative to YouTube. Our custom front-end (built by the Radicle and streameth.tv team) will be open-source and forkable for anybody who’d like to replicate the experience. 

This product is a beta test of a drag and drop open source Livepeer player that can be easily added to any custom front end as a no code solution. We hypothesize that providing an embeddable livestream player with minimal config to seamlessly livestream an event will increase adoption of Livepeer among streamers. If test goes well, the underlying open source player could be further marketed to wider users and additional Web3 features added including Video NFT minting, token-gated livestreaming and Radicle Drips payments streaming. This is HÖR's first foray into Web3 and the test will yield imporant user research on tooling and solutions that can support adoption of Livepeer. HÖR has a sizeable audience and reputation in the global electronic music community and — if the test goes well — could be interested in promoting the solution to that community.

## **Scope & Timeline**

Rad Radio will premiere on **Wednesday, May 25th** from **10pm - 1am CET** at [HÖR](https://hoerberlin.com/)’s on-site location. It will feature three one-hour sets from local Berlin DJs, curated by [HÖR](https://hoerberlin.com/). 

- Create a custom website for hosting the livestream (Radicle w/ support from [streameth.tv](http://streameth.tv/) team)
- Set up Livepeer livestream w/ [HÖR](https://hoerberlin.com/) (Livepeer w/ support from Abbey in Berlin)
- Promote and co-market livestream during week of NFTBerlin (23.5 - 25.5)
- Provide live support for Livestream on 25.5 from 10pm-1am

## **Budget**

**Total:** 6.5kEUR (3.25kEUR each from Radicle & Livepeer)

**Cost Breakdown:**

- [HÖR](https://hoerberlin.com/) studio rental: 4.5kEUR
- DJ booking fees: 1.5kEUR (500EUR for three DJs)
- Day-of support: 500EUR (5-8hrs @ 60EUR/hr)
    - Rough estimate from [pablo](https://mobile.twitter.com/voorvaart) based on his day rate and experience managing [streameth.tv](http://streameth.tv/) during DevConnect.

_A little taste of the website we're building!_

![photo_2022-05-19 16 40 22](https://user-images.githubusercontent.com/18275452/169323290-fdf2799e-703d-4b0b-818c-5b9eecfde2f1.jpeg)

**Comment by nelsorya** [comment]
This grant was funded and has been completed
