### ISSUE TITLE
PeerStream: A Web3 Livestream Application

### ISSUE THREAD

**Issue by karasakalmt** [livepeer/Grant-Program#63]
# PeerStream
## Introduction
*Give a 3 sentence description about this proposal.*  
PeerStream is a livestream platform which is built in ETHAmsterdam you can see the submission [here](https://showcase.ethglobal.com/ethamsterdam/peerstream-234tq). It is a Twitch like application which has a strong [API service](https://github.com/peer-stream/api), [web application](https://github.com/peer-stream/PeerStream), and [mobile application](https://github.com/peer-stream/PeerStream-Mobile-APP). Our concern is building pure decentralized live streaming platform on-chain.
#### Tech Stack Used
- LivePeer
- IPFS
- Lens Protocol
- WalletConnect
## Problem Statement
*Describe the problem you are solving.*  
In Web2 streaming platforms, the platform earns most of the money and creators get too less. Also, Streaming is some peoples' full time job and it can be stopped by only one firm's decision. Current Web3 alternatives only available on desktop which makes it hard for the smart phone users to access the streams to watch or make streams on their smart phones.  

## Solution
*Describe the solution you are proposing.*  
Stream is creator's own property and users can mint the clips of the stream, creators can get donations from watchers with both platform's own token and other currencies, also there will be subscription option for the users to streams. Since everything is Web3 there won't be a chance to shutdown. Also, we are building the platform that is available on both web, Android, and iOS so everyone will be able to access the streams and stream on their devices.
## Scope of PeerStream and Milestones
*Describe the scope of the project including a rough timeline and milestones*
### MVP
*Early September*
- Feedbacks from inital testers
### Alpha Stage
*Late December*
- Collecting feedback from testers and develop onto those feedbacks
- Collecting A/B tests
- Initial marketing from our own platform -> [Free Games Codes](https://freegames.codes/) which is a post-game promotion platform has 3M active users.
### Beta Stage
- Co-branding and co-marketing with LivePeer
- Seed investment
## Estimated Hours
*Please estimate hours spent on project based on the above*  
Estimated hours for each developer is ~320h total hours is ~640h.
- UI/UX desing $3000
- Frontend development $2000 
- Branding, logo desing $500
- Backend development $3000
- Android app $2000
- iOS app $5000
- Server maintance ($200 * 12) -> 1 year cost is $2400   
**Total Amount =  $17.900**

### Twitter
- [@izzetemredemir](https://twitter.com/izzetemredemir)
- [@karasakalmt](https://twitter.com/karasakalmt)
### GitHub
- [@izzetemredemir](https://github.com/izzetemredemir)
- [@karasakalmt](https://github.com/karasakalmt)

Our advisor [ahmetaygun](https://www.linkedin.com/in/ahmetaygun/)

### Marketing Advisors
- [@whoistherabbitt](https://twitter.com/whoistherabbitt) - Crypto Streamer
- [@LibraryDefi](https://twitter.com/LibraryDefi) - Crypto Influencer

<img src="https://i.hizliresim.com/84bu09j.png" alt="PeerStream" width="300"/>

**Comment by izzetemredemir** [comment]
With Lens Protocol and Livepeer, we can Twitch on Web3
[https://lenster.xyz/posts/0x06-0x10](https://lenster.xyz/posts/0x06-0x10)

**Comment by nelsorya** [comment]
Hey @karasakalmt, thanks for putting this together. PeerStream looks like a very interesting application. After discussing internally given Livepeer Grants recent narrowing in on focus on public goods, while we see the potential for PeerStream, we do not feel this is a public good which can make it easier for developers to build on Livepeer and will not be funding this grant.
