### ISSUE TITLE
Web3 Gaming Promotion Event

### ISSUE THREAD

**Issue by majacholewka** [livepeer/Grant-Program#64]
**Give a 3 sentence description about this proposal.**
Web3 Devs Poland is a polish community of web3 developers. This proposal focuses on promoting web3 gamedev by organising events, hackathons and workshops. Thanks to this grant we will be able to organize live event in Warsaw promoting web3 gaming hackathon where Livepeer would be an official sponsor.

**Describe the problem you are solving.**
We are solving the problem of still low popularity of decentralised solutions within gaming industry and connected with that deficiency of game developers in web3. We want to show Livepeer’s protocol - how innovative, easy and fun it is to use.

**Describe the solution you are proposing.**
We want to promote play2earn game industry. We're co-orginizing web3 gaming hackathon ([https://www.elympics.cc/gamejam](https://www.elympics.cc/gamejam)) where developers can publish their game later. We're hosting an event to promote it ([https://www.meetup.com/web3-devs-poland/events/286091035/](https://www.meetup.com/web3-devs-poland/events/286091035/)). We want to host a live coding workshops. We want to promote web3 on universities where programmers are studying.

Livepeer would become an official sponsor of the event, its logo will be visible on our website in partners section ([https://web3pl.eth.limo/](https://web3pl.eth.limo/)) and in all marketing materials for the events. We could also have a short panel about LivePeer and its solution during the events.

**Describe the scope of the project including a rough timeline and milestones**

Event promoting web3 gamedev:

1. Book the venue - DONE
2. Set up an event committee - DONE
3. Hold a planning session - DONE
4. Create an event on meetup - DONE
5. Create marketing materials (28-31.05.2022)
6. Find and confirm two more speakers - one is confirmed now (28.05-02.06.2022)
7. Look for sponsors&partners for an event - one is confirmed now (28.05-09.06.2022)
8. Confirm agenda (03.06.2022)
9. Promotion on LinkedIn and Twitter (30.05-11.06.2022)
10. Announce agenda (04.06.2022)
11. Prepare a presentation (04-05.06.2022)
12. Gather presentations from all speakers (09.06.2022)
13. Prepare a place for an event (10.06.2022)
14. Host an event (11.06.2022)
15. E-mail campaign (04.06-12.06.2022)
16. Share photos from an event on Twitter&LinkedIn (12.06.2022)
17. Conduct post-event evaluation/send surveys for improvements next time (12.06.2022)

Web3 promotion on universities:

1. Confirm a date of an event (05.06.2022)
2. Set up an event committee (05.06.2022)
3. Hold a planning session (08.06.2022)
4. Create an event on meetup&Facebook (12.06.2022)
5. Create marketing materials (09-12.06.2022)
6. Finding and confirming one more speaker - three are confirmed now (05.06.2022)
7. Confirmed agenda (06.06.2022)
8. Promotion on LinkedIn and Twitter (06.06-05.07.2022)
9. Announcing agenda (07.06.2022)
10. Preparing a presentation (12-15.06.2022)
11. Gathering presentations from all speakers (03.07.2022)
12. Preparing a place for an event (04.07.2022)
13. Hosting an event (05.07.2022)
14. E-mail campaign (06.06-06.07.022)
15. Sharing photos from an event on Twitter&LinkedIn (06.07.2022)

**Metrics to track**

- The number of participants of an event
- The number of participants in the hackathon
- The number of accounts reached on LinkedIn
- The number of e-mails collected

**Please estimate hours spent on project based on the above**
We estimate we will spend 78h for each event, so 156h for those presented. We plan to organise more in the future as so far only few web3 events were organised in Warsaw and they have been very populary among developers.

Most of the grants funds will be spent on working hours for the team, promotional materials, paid marketing, merchandise, renting out the venue, tools like Streamyard or Meetup.

The time is calculated for the whole team. We have now 6 team members:

Maja Cholewka - Founder & Marketing

Łukasz Olender - Social Media & Community

Kacper Adler - Front-end Developer

Konrad Kokosa - Back-end Developer

Przemysław Paczoski - Blockchain Developer

Kuba Kublik - Operations & Developer

**About us**

We’re the first polish community for web3 developers. We share knowledge, exchange experiences and build projects together. Our community has more than 300 members now. 

**More information:**

Landing Page: [https://web3pl.eth.link/](https://web3pl.eth.link/)

GitHub: [https://github.com/orgs/WEB3-Devs-Poland/](https://github.com/orgs/WEB3-Devs-Poland/)

LinkedIn: [https://www.linkedin.com/company/web3-devs-poland/](https://www.linkedin.com/company/web3-devs-poland/)

Twitter: [https://twitter.com/web3devspoland](https://twitter.com/web3devspoland)

YouTube: [https://www.youtube.com/channel/UCvV6USxk59dGeCQgxBp61bQ](https://www.youtube.com/channel/UCvV6USxk59dGeCQgxBp61bQ)

Depending on the interest, we would like to proceed with more events and more initiatives like web3 gaming newsletter, education around it certified with NFTs, hackathons. We are a very active community working only 4-weeks now. We are also open for a discussion with Livepeer Team to develop some new ideas together.

Feel free to ask me any questions.

Thank you.

![Screen Shot 2022-05-29 at 11 36 49](https://user-images.githubusercontent.com/36901365/170861668-77d50cc1-8f6f-4a12-bc2c-cd0e62bcd197.png)

**Comment by nelsorya** [comment]
Hey @majacholewka, thanks for putting this together and sorry for the delay in response. Could you tell us how many people you are expecting at this event?

**Comment by majacholewka** [comment]
Hi @nelsorya thanks for the answer! First event already took place, we had 70 attendees but only because of the venue limitation. We're having the second event on 13th of July. We expect at least 100 participants. Here's a link to meetup: https://www.meetup.com/web3-devs-poland/events/286616597/

**Comment by majacholewka** [comment]
Hey @nelsorya - have you decided anything regarding our proposal?

**Comment by nelsorya** [comment]
Hey @majacholewka, sorry for the delay. This sounds like an interesting event. Unfortunately, this is outside our hackathon sponsorship budget at the moment, so we won't be able to sponsor this proposal.
