### ISSUE TITLE
Eclectica : Metaverse for everyone

### ISSUE THREAD

**Issue by harshu4** [livepeer/Grant-Program#65]
﻿## **Introduction**
*Give a 3 sentence description about this proposal.*

Eclectica is a platform where users can deploy their metaverse from various pre-built editable templates in single click powered by web3. An event-driven metaverse exclusively focuses on hosting various events driving the creator economy by eliminating entry barriers. We believe art is about experience and the art which will be valued over time is the one that provides exotic experience. 

Eclectica values the power of open source community and strives to become a platform where everyone can contribute from developers to artist without any entry barrier

[***https://eclectica.network/***](https://eclectica.network/)
[***Livestreaming Concert Demo***](https://www.youtube.com/watch?v=mnilZ7EVEVg)

## **Problem Statement**
*Describe the problem you are solving.*
### **Entry-Barrier:**
Entry cost is prohibitively expensive in current metaverse platforms.For hosting events, users need to buy or rent land parcels.
### **Invite-Only Events:**
Current metaverses do not allow users to host invite-only events. As a result of this, use-cases of metaverse drop significantly

### **Scarcity Driven Economy:**

The value of most of the metaverse platforms are to derive from scarcity of land instead of creativity and entertainment values. The goal of the metaverse is to embrace creativity and create a world class experience for end users.
## **Solution**
*Describe the solution you are proposing.*

Eclectica, a chain agnostic platform where users can deploy their metaverse from various pre-built editable templates in single click powered by web3.

**Unique selling proposition :**

- Token-gated web3 platform where users can deploy their own metaverse.
- Template based metaverse platform.
- Supports Live-Streaming and Creator Studio 

**Team**

We are passionate about technology and we have a vast experience in technology and marketing .We have not only won hackathons but we have also been involved  in various projects which are now unicorns in their respective space. We are united with a vision to create amazing products to provide extraordinary experiences for users. 

1) [**Harsh | Github**](https://www.github.com/harshu4)

1) [**Dwij | Github** ](https://www.github.com/ssd39)

1) [**Jobin Devasia | LinkedIn**](https://www.linkedin.com/in/jobin-devasia-011bba29/)

1) [**Harsh Bhanushali | Instagram**](https://www.instagram.com/ig_annon/)

## *Describe the scope of the project including a rough timeline and milestones*

**Milestone 1 : MVP       (June-July 2022)**

1) 3D spaces for various events  (Concert, Conference, Meetings, Party)
1) Token gated spaces implementation
1) Scaling interaction layer to support 100+ users concurrently
1) Dashboard for organizing and hosting.
1) Adding control UI for better experience 

**Milestone 2 : Live peer integration & community feedback  (August 2022)**

1) Live peer integration 
1) Implement direct stream via browser to livepeer 
1) Testing
1) Feedback

**Milestone 3:  Large scale event preparedness  (September 2022)**

1) Template architecture
1) Customizable avatar support 
1) Different moves for characters 
1) NFT ticketing support for various events
1) Mock events and Testing
1) Marketing

**Milestone 4: Alpha launch     (October 2022)**

1) Host concert with a 100,000 streamed minutes 

**Requested funds -  USD 50,000**

Funds will be utilized for product development, team expansion and marketing

**Comment by nelsorya** [comment]
Hey @harshu4, thanks for putting this together. This look like an interesting use case for Livepeer. Unfortunately, when it comes to issuing a grant for this integration, we do not feel this is a public good which can benefit the entire Livepeer developer community
