### ISSUE TITLE
Project: MetaRacerX

### ISSUE THREAD

**Issue by MetaRacerX** [livepeer/Grant-Program#66]
**Give a 3 sentence description about this proposal.**
We are METARACERX! We are a Racing NFT game that will enter the Metaverse in mobile game play and VR. We are a virtual play-toearn game that will be in future iterations will be played in the Metaverse. MetRacerX is a new sort of blockchain game, one that tempts you with the opportunity to earn rewards – but keeps exciting, competitive racing at the center of it all.

**Project Goal** 

We want to transform gaming into your life and be able for you to play competitively at every level as a job, profession, or just for fun & games but to be able to earn. The way we want to bring a virtual experience to be like magic, at home, in the classroom for learning, work jobs, and business, this is just the start of what we have in goal.

Long-term, we see MetaRacerX as one foray among many. We would like to make our mark on the metaverse by working with other projects and creators, offering sponsorship opportunities in order to encourage the more involved and higher-profile players to commit themselves to the game over time.

**Describe the scope of the project including a rough timeline and milestones** 
Here is our Roadmap: 
 
Phase 1
 
Team Development
Project concepts and Discovery
Concept development and testing 
Financial plan analysis 
Communities and Discord 
Website development 
White paper
 
Phase 2
Start Crowdfunding 
(Crowdfunding Manager Stella Livaniou ) 
Design UI Game 
Game content development
NFT Collection Concept phase
Launch All Communities
 
PHASE 3
Develop Ecosystem for investors 
NFT creation pre-production
NFT Sneak peek 
Demo app game version
 
Phase 4
Start Whitelist 
Solidify Collaborations with NFT 
projects, Cryptos & Brands for MRX 
Establish Racing Teams network 
Begin Promotions, Giveaways and 
Airdrops 
Start Token creation
 
PHASE 5
Token Audit 
Token Launch 
Release Game Beta Version
Public Launch of NFT 
Test PvP, PvPvP, and PvPvPvP 
ADD Prodigy Tokens to game
 
PHASE 6 
Finalize Staking Program 
Announce game partnerships 
Create Giveaways program 
Version 1 Update Mobile Game
 
PHASE 7
Implement Mobile Version 
Begin Virtual Reality Version (VR) 
Development : Purchase Land 
Development of VR land Beta test 
MRX VR Beta
Concept next iterations of game
 

**Project Length** 
6 months to 1 year with continual updates for a better experience.

**Comment by nelsorya** [comment]
Hey @MetaRacerX, thanks for putting this together. This look like an interesting use case for Livepeer. Unfortunately, when it comes to issuing a grant for this integration, we do not feel this is a public good which can benefit the entire Livepeer developer community
