### ISSUE TITLE
The eVerse Network - Grant Application

### ISSUE THREAD

**Issue by MyEVerse** [livepeer/Grant-Program#67]
Abstract

The eVerse blockchain protocols address the greatest challenges facing content creators on existing social media platforms, and create a framework to allow for future social-media applications and to embody clearly defined creator-to-platform agreements and transparent smart contract payouts; in addition to offering community members incentives to enforce community standards and voting rights to evolve these community standards over time.  Creators are rewarded for publishing popular creative works while retaining provenance and ownership of these creative works, as well as licensing rights for derivative works and selling editions of their video NFTs to their fans. The protocols provide a framework for content distribution and monetization via a token, which manifests as a vehicle for a robust economy for creators, advertisers, licensees, and fans, alongside a token economy that offers incentives to all parties to participate and earn on the platform. The eVerse.tv network, built upon the eVerse protocols, is a first proof point and embodies a streaming short-form video platform with a gorgeous dynamic UI to help usher in the new era of creator asset ownership and platform transparency.

Complete description here: https://tiny.cc/livepeerGrant

**Give a 3 sentence description about this proposal.**

We presently use a CDN-based streaming service as a streaming source for our app as a bridge on the way to integrating a blockchain-based peer-to-peer solution for our decentralized application.  We are very much aware that we need to scale well to millions, tens of millions, and then hundreds of millions of users.  eVerse utilizes EVM-compatible smart contracts to power our platform and this makes it easier to integrate with Livepeer as a partner, the end goal of this proposal; Our ideal is to meet with you and share the end-to-end demo and then bring the Livepeer technology to deliver a seamless content delivery system to our user base as we grow, where the Livestream protocol will share in our collective success, as our team is particularly adept at solving problems and our participation on the project will improve the Livepeer experience for everyone.

**Describe the problem you are solving.** 

In 2021, the user-created content ecosystem continued to grow exponentially, generating hundreds of billion dollars in revenues including 50 billion dollars in ad revenues in the US alone. The vast majority of revenues went to a handful of legacy “web2” platforms rather than to the content creators themselves. The platforms’ owners control earning opportunities of the very creators that enabled their success through opaque and ever-changing monetization rules, which vastly limits the creator’s creative freedom to create the content their fans enjoy. This creates a power imbalance between creators who seek to capitalize on their creative work and platforms that seek to maximize corporate revenue at the expense of users and creators.

**Describe the solution you are proposing.** 

 The eVerse protocols and the eVerse.tv network provides a novel solution to these challenges, enabling more freedom of expression, transparency, and a better social contract for creators and their co-creators, as well as six in-app monetization pathways covered in our development roadmap including content view revenues, donations, subscriptions, original content sales, content rights licensing, and merchandise sales.

**Describe the scope of the project including a rough timeline and milestones** 

Presently we have an upload and transcoding process in place that’s a nominal cost option.  We intend to integrate Livepeer with the eVerse protocols via the Livepeer API and we expect to stream our content via Livepeer rather than just the current CDN solution within 3 months. It is essential for us to integrate in order to compete with large-scale video streaming platforms. We can offer to provide service metrics to improve the quality of the Livepeer video streaming network.

**Please estimate hours spent on project based on the above** 
Our web and mobile apps offer a significant step up from the present web2 UI/UX landscape with a world-leading dynamic user interface adored by our current user base, with excellent user reviews.  The video segments are provided via an API through our CDN in our present tech stack and we need to convert this API for use with Livepeer on our eVerse.tv client apps.  We expect that the initial integration will take approximately 3-4 engineer weeks.

Further questions?  Ready for a demo?  tg: @Felix_Baum email: felix@everse.tv

**Comment by nelsorya** [comment]
Hey @MyEVerse, thanks for putting this together. It looks like your application could certainly benefit from using Livepeer. Unfortunately, as far as Livepeer Grants is concerned, we do not feel this is a public good which can benefit the entire Livepeer developer community
