### ISSUE TITLE
WHL - Matter.direct Grant Appliction

### ISSUE THREAD

**Issue by moskalyk** [livepeer/Grant-Program#69]
**Give a 3 sentence description about this proposal.**

Matter.direct livepeer grant - requested amount - $7200 for ~5 weeks of work

WHL aims to unravel contributors relationship with time and IRL activities
symbolizing a type wheel of fortune for lore creators to earn a fee for
constructing calendars. We are generally curious as to what are the
uncensorable characteristics that come from just pure gratitude for
someone, something, an idea, or to that of a symbol derived from media lore
to encompass an epoch of certain passing times, like chords of notes
with alchemical performant standards for which are upheld astrally.

Personally we've followed this calendar & activity relationship with a dial
found online for over 140 days and have found fulfillment, and would like
to amplify knowledge transfer in the space to other community members

**Describe the problem you are solving.** 

Degen chaotism in web3 and NFTs has trends misaligned with astrological significance. Can we align internal insight with cultural modes of memetic production for helping to steer media in the direction of proof of stake beliefs.

**Describe the solution you are proposing.** 

We've begun to construct blueprints for new lore as seen here:
https://twitter.com/MatterDirect/status/1533837209257771013?cxt=HHwWioCwkZa0pMkqAAAA

Some screenshots for design: https://imgur.com/a/007Vi4i

Presentation Overview: https://github.com/moskalyk/whl/blob/master/WHL.pdf
& Ethglobal showcase: https://showcase.ethglobal.com/ethamsterdam/whl-xu3i6

Features
* "Bind" - Streaming Crypto to dial calendars that represent lore that members can follow
* "Explore" Progress Page & Search Based on Rune
* "Play" - Rune Input Selection from various Forms of communication
- upload a video (learning something, on a bike, clothes, etc.)
- upload some text (spice you used, poem you wrote, song you listened to)
- or one of the following non-verbal forms of communication:
https://twitter.com/twi_mar/status/1531487328228716545?s=21&t=xLX5Ym0ElSn6Pps0efmQ-Q

question: Can you track your progress across multiple dials and create an easy export
to timeline?

question: Could you choose from a handful of dial services or activities,
paid for in a native token to the ecosystem, or something from another ecosystem

**Describe the scope of the project including a rough timeline and milestones** 
A rough timeline of the project is 5 weeks, with partial implementations of features along the way.
- bind - 30
- explore - 20
- play - 50

**Please estimate hours spent on project based on the above** 
Approximate spent time on milestone 1 of project, 100 hours

**Comment by nelsorya** [comment]
Hey @moskalyk, thanks for putting this together and reaching out. Could you tell us more about how this would use Livepeer or benefit the Livepeer Ecosystem?

**Comment by moskalyk** [comment]
Thanks for the response @nelsorya, and apologies for not getting back to you, I missed this.

I would be using the Livepeer Video NFT feature. It could be baked into ephemeral viewership as well which could be a key feature to integrate in other projects.

Philosophically, by accumulating on a shared agree upon set of signs with NFTs, or, various journal entries, I think we can bridge geopolitical boundaries across languages. I think this is a win win for Livepeer, as video distribution is a touchy censorable topic already.

It’d be really nice to just be able to simply display a carousel of key moments. One that you can share publicly, and one that you can keep private. I think our right to journal and keep a log of events uncensorably could be useful for certain public governance decision making.

As network states breed, I think this might be a keep piece to modern archeology of uncovering city lore. Who knows, maybe you’ll get a CCTV contract if progress of time sensing alchemy sways city builders.

And ya, we might get better at using esoteric languages so we can talk to aliens :)

**Comment by nelsorya** [comment]
@moskalyk thanks for this context. While this seems like an interesting use case to explore, I'm afraid we don't feel this is a public good which can help achieve Livepeer Grant's focus on making it easier for developers to build on Livepeer and as I result we won't be able to fund this grant.

**Comment by moskalyk** [comment]
My suggestion is to update your grant guidelines if “making it easy for developers” is your only focus.

I don’t believe protocols (possibly even language protocols in esoteric dialectic for learning comprehension & memory palaces in parks or cities) are anything without people.  

I felt the grant covered these topics (3/5) 
- Open Source Public Good Applications
- Integrations
- Marketing and Community Initatives

While I was not focused on developers, that’s an interesting angle. I’m not sure where my communication lacked sufficient clarity on the fact that this is a consumer application. 

Most crypto apps are really only for the technical minded. My target was for ages +13 (with subtle moderation requiring delicate experience), so people can browse the world of new media to know what “Strength” means to them. e.g Today I measured out a new garden and posted online some photos about the design of a bench. Arguably, I will become a better programmer by beginning my journey to be come a more focused developer, which others can share and mimic if desired.

Something can be easy, or something can be culturally empowering. Just trying to help deficiencies in the future of networked states I’d like to be a part of.

Moonshot Side Note, it’d be cool if a portion (10%) of the US student loan bill $300000MM (https://abcnews.go.com/Business/wireStory/bidens-student-loan-plan-dont-88840329) was able to be redeemed for city vouchers instead to explore and create stronger crypto hubs in geographic regions with NFT video media production and photography. E.g. Maybe students can have travel and discounts to tour a few hospitality businesses in a city to find the right job as people develop their taste making apparatus.   

All the best. 

🙏

**Comment by nelsorya** [comment]
Hey @moskalyk, sorry for the delay, I missed this. 
Very fair points. Thanks for this feedback. We will spend some time work on our grant guidelines to make sure our criterea is clearer. 

This sounds like a very interesting concept and agreed there are certainly shared learnings to be had in everything that is built on Livepeer. With that said, we feel this is more of an consumer application than a public good which can help developers build on Livepeer.

**Comment by moskalyk** [comment]
Not a problem. Thanks for the response. Looking forward to it.
