### ISSUE TITLE
Public transcoding pool for Livepeer - Proposal

### ISSUE THREAD

**Issue by gsampathkumar** [livepeer/Grant-Program#7]
Hi Guys,
        We're interested in building a public transcoding pool for Livepeer. From what I understand this is what exists today (shoutout to NicoV for taking the time to explain this to me):

a. the Livepeer orchestrator software already supports the option for Multiple transcoders to connect to it using a shared secret 

b. work is distributed to transcoders based on how many livestreams they are processing at this time. The one with the absolute minimum streams will get the new work

c. enough information in the logs for an Orchestrator to determine how many pixels a transcoder has decoded. They can then choose to build a report on this and make manual payouts every round.

d. the revenue share between the Orchestrator and Transcoder is not part of the Livepeer configuration and is agreed upon outside the protocol

What needs to be built (in our opinion):

a. Include O/T split of transcoding fees in the Livepeer protocol.

b. Automate the process of determining pixels transcoded and making payouts to transcoders.

c. Introduce historical performance, latency based weighting to how streams get assigned to Transcoders.

d. Additionally, introduce Delegated stake as a parameter into determine how streams get assigned to Transcoders i.e. to more LPT a Transcoder has staked to the Orchestrator, the more work they get (all other things like performance remaining equal)

e. Build a dashboard like Ethermine or other standard mining pools with all the historical data, stats and graphs.

I was hoping for guidance on a few things: 

a. Is the above something that could qualify for a grant?

b. Feedback on the high level details.

c. Some of this may be already built or in the works. What should we not focus on to avoid duplication of effort.

d. Any advice on formalizing this into a grant request, other than answering the high level questions on milestones and costs.

e. Honest question: Assuming we're building this on a grant, the software would be open source and usable by any Orchestrator out there? In this framework is there any competitive advantage we can derive to grow in delegation size and transcoding fees, other than street cred for building this?

thanks
Gautam

**Comment by adamsoffer** [comment]
Hey @gsampathkumar! Thanks for your inquiries. Answers below:

> a. Is the above something that could qualify for a grant?

Yes. This proposal seems best suited to a milestone-based research grant. Have you completed any research grants like this previously? Typically our research grants are spread out with ongoing weekly payments, with ongoing updates and calls on progress weekly.

> b. Feedback on the high-level details.

The high-level details provided and your assumptions look good.

> Some of this may be already built or in the works. What should we not focus on to avoid duplication of effort?

As you mentioned NicoV is also working on a public transcoding pool. I think it would be helpful to communicate with each other to avoid/identify duplicative effort and/or share learnings.

> Any advice on formalizing this into a grant request, other than answering the high-level questions on milestones and costs.

We suggest using the Grant Proposal issue template when formalizing this into a grant request. Also, it might be helpful to look at past submissions on the [old grant program repo](https://github.com/Livepeer-Community-Node/Grant-Program/issues) to get a gauge on the type of proposals that were successful.

> Honest question: Assuming we're building this on a grant, the software would be open source and usable by any Orchestrator out there? In this framework is there any competitive advantage we can derive to grow in delegation size and transcoding fees, other than street cred for building this?

Good question. If you decide to submit a formalized grant proposal, yes the assumption would be that the software is open-sourced. We suspect building and running one of the first public transcoding pools would be a competitive advantage for achieving delegations both from a community alignment standpoint and revenue earning opportunity standpoint. It’s perfectly reasonable, however, not to go through the grant program and create a closed source solution if you feel this would give you a competitive advantage. Something to think about while you weigh your options is that it's likely some transcoders will prefer to work with a pool where the code is open-sourced and fully auditable.

**Comment by gsampathkumar** [comment]
Thank you for the reply @adamsoffer 

I'm going to be formalizing this into a grant request in the new few days. Do let me know if you have a preference for if I should convert this into a grant request based on the template, or close this out and create a new issue. Thanks.

**Comment by adamsoffer** [comment]
@gsampathkumar let's close this out and create a new issue so there can be a thread dedicated specifically to your proposal.

**Comment by gsampathkumar** [comment]
Sure. Sounds good.
