### ISSUE TITLE
HYVE Business Proposal

### ISSUE THREAD

**Issue by vniregrbldskqncib3j43cjn4h54** [livepeer/Grant-Program#71]
We saw the potential of the project and we have a proposal, but before I get into details, I want to tell you a few words about [HYVE](https://app.hyve.works/) - the company I represent.

First of all, I want to say that we just launched v2 and the mobile version of our [freelancing platform](https://app.hyve.works/), so go check it out!!! 🥳

We have a user base of more than 50k dedicated followers, the payments are instant and safe and always escrowed. Everything is on blockchain, and by now we are live on ETH, BSC, Polygon, and Fantom with +25 tokens integrated as a payment method. We are also talking with some big companies and they will integrate their token as well, and other companies will integrate their blockchain.

We want to have a call with the team to see how we can work together. We can add your blockchain/token as a payment method and offer our onboarding services if you want to post a task/job (if you are looking to hire freelancers). Book the call [here](https://calendly.com/tudor_stomff).

We can also set up a telegram group chat with our team, including our CEO, Tudor Stomff.

Let me know what you think!

**Comment by nelsorya** [comment]
Hey @vniregrbldskqncib3j43cjn4h54, thanks for reaching out. I will pass this onto the Livepeer Inc team to take a look at, although it sounds like you aren't looking for a grant from Livepeer Grants

**Comment by vniregrbldskqncib3j43cjn4h54** [comment]
@nelsorya Thank you for answering me! Indeed, it is more of a proposal, but I was told to leave the proposal here.
