### ISSUE TITLE
GovtJobKaro

### ISSUE THREAD

**Issue by GovtJobKaro** [livepeer/Grant-Program#74]
**Give a 3 sentence description about this proposal.**
GovtJobKaro is a learning platform with offline and online course structures based in India. Our intent is to educate people in various subjects that are useful for them to get jobs. Our portfolio of teachers include graduates from India's top most institutes dedicated towards the fullfillment of the students.

Website: https://govtjobkaro.com/

**Describe the problem you are solving.** 
India has the largest young population of the world which requires equal amount of job opportunities. We are helping aspirants and students in getting their dream job. We help them prepare for the exams for the jobs. 

**Describe the solution you are proposing.** 
We are looking to decentralise the video streaming of our website. We will integrate the Livepeer into our tech stack to stream the course videos.

**Describe the scope of the project including a rough timeline and milestones** 

First milestone: Livepeer Integration (By 30th July)

Second milestone: Uploading of content (15th August)

**Please estimate hours spent on project based on the above** 
The total hours will be a minimum 500 including the tech integration plus content creation. 

We are requesting $5,000 for integrating the Livepeer into our tech stack. We propose the following payment schedule:

On approval of grant ($1,000)

Integration of Livepeer ($1,000)

Upload of all the video content on Livepeer ($1,000)

Improve content creation and management controls ($1,000)

Success Metric Bonus - 20k video views on the platform ($1,000)

**Comment by GovtJobKaro** [comment]
Hi @nelsorya at GovtJobKaro we are providing free coaching for students which will help them get job. In India we have more than 10 million job aspirants and providing the education free is helping these people. 

We request Livepeer support in providing education to such a large number of students free of cost.

**Comment by nelsorya** [comment]
I'm afraid this is outside of the scope of Livepeer Grant's goal which is on making it easier for developers to build on Livepeer. With that said, we are still willing to offer Livepeer credits to support the cause and get you started using Livepeer.
