### ISSUE TITLE
CodeUp Blockchain Festival - Nigeria 2022

### ISSUE THREAD

**Issue by ogasky** [livepeer/Grant-Program#75]
**Give a 3 sentence description about this proposal.**
We are a community of blockchain enthusiasts that are passionate about the Tech Ecosystem particularly the Blockchain Space, our goal is to Educate people about the various aspects of the Blockchain and the several opportunities available in it and also provide a platform for corporate brands to connect with their users.

**Describe the problem you are solving.** 
This event is organized to skill-up the under-represented people in blockchain technology with basic knowledge in blockchain development, and career opportunities. Also, we shall be having over 500 participants to attend this event and we have lined up speakers from different cities around the world.

**Describe the solution you are proposing.** 

Theme: Accessing BlockChain Digital Economy

This event is organized to skill-up the under-represented people in blockchain technology with basic knowledge in blockchain development, and career opportunities. Also, we shall be having over 500 participants to attend this event and we have lined up speakers from different cities around the world.

Focus is on:

Blockchain & Web 3.0
Legal Frameworks on Blockchain
Smart Contracts
NFTs
DeFi
DAO
DApps
Cryptocurrency
Used Cases of Blockchain
Available Blockchain Grants

Schedule Sessions:
1. Keynotes session
2. Syndicate / Master class
3. Panelists
4. Hackathon
5. Pitching

Confirmed Speakers:
Currently our confirmed speakers in the blockchain space include:

1. Deborah Enyone Oni; Managing Partner Hilton Top Solicitors & Blockchain Lawyer. She will be speaking on topic "Blockchain & Web 3.0: The regulatory framework in Nigeria".

2. Dominic Uririe Rume; Is a Certified MetaVerse Expert and Certified Blockchain Architect, an enthusiastic IT professional with proven abilities to analyze engineering concepts clearly and a significant driver of innovation, solutions, and disruptive technologies Globally. He is a valuable member of SiBAN (Stakeholders in Blockchain Technology Association of Nigeria). Through this platform, he has contributed immensely by supporting other players in securing the future through the power of the Blockchain. He is the founder/CEO of VOREM Nigeria. He will be handling a syndicate session on the "MetaVerse & Web 3"

3. Gino Osahon; is a Developer Advocate with IOV Labs. He will be speaking on "DeFi for Beginners"

4. Edegware Gift; he is the Founder/CEO of Gsoft Interactive Systems Ltd & he will be handling a syndicate session on "How to create your crypto wallet"

5. Onose Ogaga; he is the Founder/CEO of WittyHub and the convener of CodeUp Blockchain Festivals. He will be talking on "The Available Blockchain Opportunities"

More speakers will be listed in due course. However we ask for your support to help us spread the word about this event to your network & get more people to register. Thank you.

**Last Year's Edition:**
You can have a view of photos taken from the last edition via the link https://bit.ly/CBF-NG-2021-Pic and watch the news media coverage via https://youtu.be/zizqslKdhEs and https://youtu.be/r-B8KF6SkT8

**Sponsorship Packages**
We have different sponsorship packages that fits into your budget and for more details visit https://bit.ly/CodeUpFest-2022-Sponsor to book your sponsorship for the CodeUp Blockchain Festival 2022 in the city of Warri, Nigeria.

**Code Of Conduct (https://www.meetup.com/CodeUp-Africa/):-**
Our meetup is dedicated to providing a harassment-free meetup experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion (or lack thereof), or technology choices. We do not tolerate harassment of meetup participants in any form. We do not hold meetups in religious and political settings, also sexual language and imagery are not appropriate for meetup venue, including talks, workshops, parties, Twitter and other online media. Meetup participants violating these rules may be sanctioned or expelled from the meetup at the discretion of the meetup organizers.

**Describe the scope of the project including a rough timeline and milestones** 

**Budget/Milestone**
1. Hackathon Prizes = 5000 USD
2. Publicity = 1000 USD
3. Venue = 1200 USD
4. Attendees Breakfast = 3000 USD
5. Attendees Lunch = 3000 USD
6. Speakers Flight = 6000 USD
7. Speakers Hotel = 1400 USD
8. Media Coverage = 1000 USD
9. Swags = 2500 USD
10. Miscellaneous = 500 USD

**TOTAL = 24,600 USD**

**Please estimate hours spent on project based on the above** 
From the above, 450 hours is estimated for the project.

**Comment by nelsorya** [comment]
Hey @ogasky, thanks for reaching out. This sounds like an interesting event. Unfortunately, this is outside our hackathon sponsorship budget at the moment, so we won't be able to sponsor this proposal.

**Comment by nelsorya** [comment]
@ogasky I'm afraid it is not, we have already allocated our hackathon/conference budget for the quarter, but all the best with the event.
