### ISSUE TITLE
Clipto Grant Proposal

### ISSUE THREAD

**Issue by jonomnom** [livepeer/Grant-Program#76]
**Give a 3 sentence description about this proposal.**
Clipto is a personalized content platform which allows users to purchase personalized content from their favorite creators. Creators sign up and their fans can request content from that creator and it gets minted as a NFT. We want to improve Clipto’s video infrastructure by integrating with Livepeer’s video services.

Clipto is live: [https://clipto.io/](https://clipto.io/)
Clipto is opensource: [https://github.com/orgs/Clipto-Platform/repositories](https://github.com/orgs/Clipto-Platform/repositories)

**Describe the problem you are solving.** 
[Gabriel Haines](https://twitter.com/gabrielhaines), a crypto content creator, tried to create a profile on cameo but his application got rejected. Frustrated as to why Cameo would restrict creators from joining their platform, Clipto was born. We let any content creator join our platform to start receiving booking requests as an additional revenue stream. Our vision is to build the relationship between the fan and the creator with the values of web3. A core part of the product is being able to upload videos and sending it as a NFT to the user. Currently we use glass.xyz for uploading, but there are some limitations with their service.

- Unexpected downtime of their service
- Limits to size of video that can be uploaded and processed
- Lack of developer support
- Lack of documentation

**Describe the solution you are proposing.** 
Livepeer offers services to upgrade our video infrastructure. We want to use Livepeer for uploading and processing videos that would be minted as NFTs and other general improvements when Livepeer adds more features (like Lens x Livepeer integrations). 

**Describe the scope of the project including a rough timeline and milestones** 
Milestone 1 - Designing, developing, and testing video infrastructure upgrade to Livepeer (80 - 120 hours)
- Integrating with Livepeer (research, development, testing)
   - to open files and upload it to Livepeer API
   - transcoding video
   - exporting to ipfs
   - Displaying videos on user video feed on creator profiles (dev, UI/UX, testing)
   - Pulling and posting videos made by Livepeer onto Lens (dev, UI/UX, testing)
   
Milestone 2 - Success Metric Bonus (variable hours)
- 1,000 videos created with Livepeer on Clipto
   - This will be achieved through:
     - Onboarding new creators and their audiences
     - Marketing - outreach, promotion, branding, incentives, referrals
    
Milestone 3 - Community Feedback (40 hours)
- Seek community feedback for issues, performance and suggestions
       - Talking with creators and requesters about their experience
- Collecting feedback and during milestone 2

**Comment by nelsorya** [comment]
Hey @jonomnom, sorry for the delay in getting back to you. Thanks for putting this together, what you have built is a very interesting use case for Livepeer. After discussing with the Livepeer Grants team, we would like to support Clipto with a grant for $5k in LPT. We would split this across milestones 1 and 2. 

Milestone 1 - Integrate Livepeer ($1,500 in LPT)
Milestone 2 - Success Metric Bonus - 1000 videos created ($3,500 in LPT)

**Comment by jonomnom** [comment]
Thanks! Is the best way to update the progress of this grant on github?

**Comment by nelsorya** [comment]
Hey @jonomnom, best way to move forward is to reach out to me on discord and we can create a shared group to keep in touch. I'm Nelson#6080 on discord.
