### ISSUE TITLE
Intermediate Guide for Multi-Node Livepeer Production Deployment

### ISSUE THREAD

**Issue by AuthorityNull** [livepeer/Grant-Program#78]
**Give a 3 sentence description about this proposal.**
-
This proposal outlines an easy-to-implement scaling solution for orchestrators by incorporating Docker and an enterprise-level management application, Portainer, to deploy and manage advanced multi-node setups all from one central UI.   

**Describe the problem you are solving.** 
-
Many orchestrators are rapidly expanding to compete on the network, which is a good thing, however, with rapid expansion comes rapid problems. Without a cleanly managed operation, orchestrators will find themselves struggling to manage their nodes. There is a clear need for documentation/guidance in this area. Livepeer's documentation is a good starting point but lacks detail for intermediate/advanced multi-node orchestrator deployments.

**Describe the solution you are proposing.**
-
Mike Zupper (xodeapp.xyz) and I (authority-null.eth) are proposing an end-to-end intermediate guide, taking orchestrators from 0 to multi-node setup using Docker and Portainer. We'll provide docker-compose templates and a public GitHub repo containing all the necessary resources. We will be keeping the docker-compose stacks up-to-date as we're using them in production ourselves.

Some of the key features are:
- UI for all node management, logging, and troubleshooting.
- Easy upgrades and instant deployments.
- Centralized management of multiple nodes.
- Less reliant on Linux know-how.
- A great first step for orchestrators looking to explore scaling solutions.
- Enterprise tooling for technology standards like Docker, Swarm, and Kubernetes.
- True flexibility and security.

These are the docker-compose templates that have been tested and will be made available in the GitHub repo:
- Monitoring 
  * Grafana
  * Prometheus
  * Node exporter
  * Nvidia exporter
- Livepeer
  * ETH account creation
  * Combined O/T
  * Standalone O
  * Standalone T
- Deployment tools
  * Portainer
  * Portainer edge agent
  * Traefik
  * SSL certs

As part of this grant, We will create a complete video tutorial, which will demonstrate our written guide step by step. We will stream the video through Livepeer Studio as well as publish it on YouTube and other social media platforms. 
We're also promoting the guide/documentation on public channels, bringing more attention to Livepeer by combining well-known enterprise-level solutions with Livepeer software.

![Portainer_Tweet](https://user-images.githubusercontent.com/95463891/178606708-103ea655-07ce-49b9-b8d1-37c638ce9cee.png)

**Describe the scope of the project including a rough timeline and milestones.** 
-
June (completed):
- Install and configure Docker for Livepeer with proper Nvidia support. - 6 hours
- Install and configure Portainer single node and multi-node. - 4 hours.
- Provision and install multiple vps’ for testing. - $100
- Several live working sessions in Livepeer’s Discord (office hours channel), involving the community (Titan, Nightnode, Pon, Papa_Bear). – 10 hours
- Testing all stacks in production. – 5 hours
- Migrated multiple production orchsestrators for validation. – 12 hours
- Wrote [full guide](https://forum.livepeer.org/t/guide-livepeer-with-docker-and-portainer-for-operating-at-scale/1850/6) and posted on Livepeer forum. – 6 hours

July:
- Grant-proposal write-up. – 1 hour
- Record and edit video walkthrough. – 12 hours
- Publish Github repo. - No cost
- Continued social media engagement supporting our docs (Twitter, Discord, Lens, etc…). - No cost
- Continue supporting the community as orchestrators transition to Docker and Portainer. – No cost

**Please estimate hours spent on project based on the above.** 
-
Total hours: 56
Hours spent: 43
The bulk of the work has already been completed and the architecture is being actively used in production by orchestrators.
Rate: $125/hr
Team: Mike Zupper and Ben (Authority_Null)
Total cost: $7100

**Comment by nelsorya** [comment]
@AuthorityNull thanks for putting this together, this looks very useful for orchestrators. We would love to fund this. I will dm you on discord and we can discuss next steps
