### ISSUE TITLE
FinFlix: Crypto and Blockchain Learning Platform

### ISSUE THREAD

**Issue by NishantFinstreet** [livepeer/Grant-Program#81]
**Give a 3 sentence description about this proposal.**

Finstreet is India’s First Crypto Education Platform. This platform is an easily accessible medium for people to learn about the importance of cryptocurrencies and their different asset classes. We have a strong community of more than 3 million crypto enthusiasts on different social media platforms.

We are looking to build FinFlix, a decentralized content platform for learning about crypto and blockchain. We are working on a vision of providing the platform as the content aggregator for crypto education where we can aggregate the best explanatory videos as well as the latest trending videos on our platform on crypto and blockchain concepts.

**Website:**
https://finstreet.in/
https://finflix.finstreet.in/

**Community Channels:**

YouTube: https://www.youtube.com/c/Finstreet
Trell: https://trell.co/@Finstreet
Chingari: https://chingari.io/finstreet
Rizzle: https://rizzle.tv/u/finstreet
Josh: https://share.myjosh.in/profile/a1d3a003-0db0-41ed-abfc-fe28e6b76a7a?u=0x99e7f1a8b7805eb9
MX Takatak: https://usr.mxtakatak.com/vQZT/yr5q2siu

**Github:** https://github.com/finflix/finflix-demo/

**Describe the problem you are solving.** 

Big tech is increasingly banning content about crypto. We need a decentralized platform where anyone can come and learn about different blockchain and crypto subjects. Every now and then YouTube bans the crypto and blockchain based channels. FinFlix will provide a platform where anyone can post educational content around crypto and blockchain concepts and people can learn by watching the content free.

**Describe the solution you are proposing.**
 
We will be building a decentralized learning platform with Livepeer integration. It will provide a one-stop solution to learning different blockchain and crypto subjects. We will be using Livepeer for the streaming platform. We will provide a decentralized learning platform where anyone can come and learn about different crypto and blockchain concepts free.

**Describe the scope of the project including a rough timeline and milestones** 

Initial Phase (Two months):

- Launching the first version with the following features:

1. Decentralized video streaming using Livepeer 
2. Tipping / Donations for the creators to contribute to creators' economy
3. A dashboard for the content creators to upload their videos on crypto
4. Viewer friendly playback system integration

- Educating the community about the platform and bring initial users
- Publish the initial videos on FinFlix

Advanced Phase (Three months):

- On-boarding new KOLs for publishing content
- Partnerships with Crypto projects and companies to build educational content on the platform.
- An admin control to check the performance of the platform and made that stats public
- User content analytics, creators would be able to see how their videos are performing
- Exploring options of crowdfunding from FinFlix
- Enhancements in UI/UX and security of the platform
- Exploring watch and earn models

Apart from the above mentioned development roadmap we will actively engage with the community along the KOLs in the space to add the required features to enhance the user experience. 

**Please estimate hours spent on project based on the above** 

The total hours will be a minimum 700 for the tech integration and content creation. 

We are requesting $25,000 for integrating the Livepeer and build the platform. We propose the following payment schedule:

On approval of grant ($12,500)

Integration of Livepeer ($12,500)

**Comment by nelsorya** [comment]
@NishantFinstreet thanks for putting this together. While this seems like an interesting use case, I'm afraid we don't feel this is a public good which can help achieve Livepeer Grant's focus on making it easier for developers to build on Livepeer and as I result we won't be able to fund this grant. We would however be willing to offer $5k in streaming credits to use the Livepeer API.

**Comment by NishantFinstreet** [comment]
Hi @nelsorya we will be creating content for Livepeer as well for the platform. We will release the tutorials for Livepeer developers and introduction to the project. This grant will surely help Livepeer achieve its target of helping developers in building on Livepeer.

**Comment by nelsorya** [comment]
@NishantFinstreet for sure, while educational content on crypto is helpful for the broader ecosystem, we see this more as an application than a public good
