### ISSUE TITLE
Lenstream - Community Driven Streaming

### ISSUE THREAD

**Issue by andr-dev** [livepeer/Grant-Program#83]
## Give a 3 sentence description about this proposal

Hosting online events on platforms like Discord or Twitter is a convenient and easy way to gather community members, but is not a Web3 friendly approach since the DAO must depend on a centralized service. On the other hand, making posts on DAO forums results in slow updates from members and a lack of true interaction between proposers and voters. As such, we propose creating a web toolkit that enables DAOs / communities to seamlessly integrate live stream components for community discussions, events, and Q&As into their web applications.

## Describe the problem you are solving

**Virtual Event Hosting Centralization**

Most DAOs currently host community events on Discord, Twitter, and other centralized services. As a result, anonymity between the Web2 and Web3 worlds cannot be preserved without taking additional steps such as creating alt accounts.

**DAO Proposal Inefficiency**

The proposal process takes a long time merely due to the lack of fast updates to the DAO forums in which the proposals are held. Many members have to wait hours, days, or maybe weeks to hear a response for questions and concerns raised by the community.

## Describe the solution you are proposing

The solution would use the Livepeer network behind the scenes to process live video, solving the problems discussed above.

- Proposal owners can easily start live Q&A sessions to get rapid feedback from the community, reducing inefficiency and significantly speeding up the proposal process
- Members are empowered to speak and interact with other community members more meaningfully than through a public chat forum, generating a true sense of community for DAOs
- Livepeer also addresses the decentralization issue that Twitter and Discord have for interaction with communities. Additionally, sessions may be recorded and stored on IPFS or other decentralized storage options for all community members to view.

## Roadmap and Milestones

**Milestone 1: 120 hours [5500 USDC in LPT]**

MVP demo open source app that integrates the Lens protocol to allow anyone to start a public live stream to followers.

**Milestone 2: 60 hours [3500 USDC]**

Launch open source app on an ENS domain.

Transcoding cost support for 6 months ($500 in LPT per month)

Success Metric Bonus: 100,000 minutes streamed [6500 USDC]

**Milestone 3: 200 hours [12500 USDC]**

Launch open source front-end toolkit to integrate Livepeer with existing DAO front-ends (i.e. Aragon UI: https://github.com/aragon/ui).

Success Metric Bonus: 3 DAOs in top 25 on CMC ([https://coinmarketcap.com/view/dao/](https://coinmarketcap.com/view/dao/)) implement our toolkit with cumulative 100,000 minutes watched [8500 USDC]

**Future Milestones**

Additional features to be determined and discussed. Some of our ideas:

- Implement features for preserving anonymity (using ZK Proofs as proof of membership in a community) so that users would not have to reveal anything about their wallet address
- Integration with other DAO contracts, i.e. MolochDAO (https://github.com/MolochVentures/moloch-frontend)
- Mobile app / integration
- Gate access to encrypted recorded sessions using community token

## About Us:

We are two students studying at the University of Waterloo (@andr-dev, @bowenyou) who started this idea at ETH Toronto. Due to some issues with the docs, we were unable to get the live stream integration of our project completed. After the hackathon, we chatted with a Livepeer developer and were able to resolve the issue. We see great potential in this project and would like to continue it.

**Comment by Titan-Node** [comment]
Love it, can't wait to see many integrations with Livepeer!

**Comment by nelsorya** [comment]
Hey @andr-dev, thanks for putting this together. This sounds like a very interesting use case. After looking over your proposal, I'm afraid we have decided we do not feel Livepeer Grants can fund this as we feel this is more of an application than a public good that can make it easier for developers to build on Livepeer.
