### ISSUE TITLE
Livepeer in Africa; Lagos Edition (WEB3.LAGOS CONFERENCE)

### ISSUE THREAD

**Issue by olouwaseun** [livepeer/Grant-Program#86]
This is a proposal request for funds to support an upcoming Web3.Lagos conference. These funds will be used to purchase a package for the conference on the 6th-8th of October 2022 organized by Web3bridge.

**Introduction.**
In an ever-evolving world where we have seen immense growth in technology which has directly impacted industrialization for over a century, it is sad to see that the profit-driven ambition of the few is threatening the livelihood of the vast majority.

Where innovation is mainly driven by profit rather than progress, large Institutions make it almost impossible for the regular joe with great innovative ideas to raise capital to ensure the actualization of these ideas. Cryptocurrency has solved the majority of the problems plaguing the financial sector by creating a secure means by which transactions are verified and records maintained by a decentralized system using cryptography rather than the conventional centralized system.

The narrative changed when Vitalik Buterin introduced the concept of smart contracts by introducing programs into blockchain technology that only execute when certain conditions have been met; thus, the era of Web3 was born.

Nigeria has since dived into the crypto world emerging as the topmost engaging community in Africa.

**WHY WEB3 LAGOS?**
Yahoo finance described Nigeria as one of the highest cryptocurrency users in the world. Approximately 32% of respondents confirmed their awareness of web3 and cryptocurrency compared to other countries such as Peru with a 16% cryptocurrency awareness.

[https://financ](https://finance.yahoo.com/news/countries-using-cryptocurrency-most-210011742.html)[e.yahoo.com/news/countries-using-cryptocurrency-most-210011742.html](https://finance.yahoo.com/news/countries-using-cryptocurrency-most-210011742.html)
An article by []([restofworld.org](http://restofworld.org/)) describes Lagos as Africa’s Silicon valley having raised over $663 million dollars for tech startups based in Lagos. Lagos is undoubtedly the home for tech entrepreneurs looking to use new opportunities technology offers. The idea of collaborating on an international scale while managing a treasury in a transparent and decentralized system will definitely sound appealing to entrepreneurs aiming to expand their reach to global investors and collaborate by creating a system where stakeholders can actively participate in the success of its organizational goal.

There is no doubt that there is a huge opportunity for Web3 in Nigeria so the question is what role do DAOs play in the picture?

Nigeria is seen as Africa’s largest economy and one of the fastest-growing in the world. Yet, more than half of the Nigerian population still grapple with extreme poverty, while a small elite enjoys ever-growing wealth.

The report, [[‘Inequality in Nigeria,’](https://www.oxfam.org/en/research/inequality-nigeria-exploring-drivers)](https://www.oxfam.org/en/research/inequality-nigeria-exploring-drivers) exposes the large and growing gap between rich and poor. It reveals how the benefits of economic growth have been captured by a wealthy elite at the expense of ordinary Nigerians.

It is nearly impossible for the average Nigerian to start up an organization mostly due to capital. Large organizations and institutions have made sure that wealth circulation is also centralized and limited within the few making it extremely difficult for the regular joe to raise the capital he needs through loans or grants to make his innovative ideas become a reality. These constraints have over the years pushed the emerging youth population of Nigeria to engage in more innovative ways to find lasting solutions to these challenges.

The Idea of Decentralized Media platform like Livepeer will revolutionize the content creation community and Journalism in Africa as they are expensive, highly centralized and most of all censored by the government. 

Meaning to say that Decentralized streaming network is untapped in the emerging web3 development in Nigeria. What better way to introduce these concepts with Livepeer as the face of this in Nigeria and Africa at large?

There are a few individuals who are already coming together to collaborate using leveraging the idea of DAOs such organisations include;

- **Proxify DAO**: proxify DAO is a DAO that makes use of the decentralised model to bridge the gap between organizations in need of technical services and the individuals who offer these services. To help contributors connect, as well as collectively build and maximize their skills.
- **Africa DAO**: AfricaDAO is a DAO that has currently raised around $90million with reach and founding members from countries like Nigeria, South Africa, and Ghana. AfricaDAO is a perfect example of the capability of DAOs to collaborate on an international level. AfricaDAO seeks to create awareness by investing part of its treasury to train and spread the word about DAOs and their advantages to individuals and organizations in Africa.
- **Chess DAO**: chess DAO is a community of chess lovers hanging out, learning, and challenging themselves with fun and engaging activities to promote the awareness of chess in Africa and collaborate on a larger scale.
Web3.LAGOS is an excellent opportunity for Livepeer to boast about its disruptive technology that offers a fully decentralized, highly scalable live video streaming network protocol incentivized through LPT token, to result in a solution that can serve as live-media layer in the web3 decentralized development stack.

**Event Information.**

web3.Lagos is an event organised by Web3Bridge a tech organisation of web3 professionals seeking to provide solutions and awareness amongst entrepreneurs within and outside the web3 space.

Web3.Lagos will take place in the region of Lagos in Nigeria on the 6-8th of October 2022.

Packages include 
Platinum $10,000
Gold $5,000
Sliver $2,000
Links to more Info on the benefits of these packages
[[[WEB3BRIDGE_ETH_LAGOS_CONFERENCE_PROPOSAL_2022_.pdf]](url)(https://cdn.discordapp.com/attachments/992146444393926737/1003982593072578660/WEB3BRIDGE_ETH_LAGOS_CONFERENCE_PROPOSAL_2022_.pdf)](https://cdn.discordapp.com/attachments/992146444393926737/1003982593072578660/WEB3BRIDGE_ETH_LAGOS_CONFERENCE_PROPOSAL_2022_.pdf)

[http://event.web3bridge.com/](http://event.web3bridge.com/)

The Pdf contains a detailed description of the event.

**AIM**

Web3 bridge was founded in 2019 by a group of tech entrepreneurs aiming to create and train individuals and organisations in blockchain development, DAOs ,web3 products, and tools.

Web3Bridge mission is to identify Web3 passions and train them in a collaborative and

supportive remote environment and create an African Web3 Community, which over

the years will have been executed through our learning series called “COHORT” from the edition

1 to edition 7, with more than 2000 trained on Web2-Web3 Blockchain development for free with access to accommodation, feeding, and internet access in their learning facility in Lagos.

**SPONSORSHIP/PARTNERSHIP BENEFITS**

With Web3bridge having its reach in Ghana, South Africa, Kenya, and Nigeria, this conference in regards to DAOs will be targeted at

- DAO Coordination.
- Decentralisation in work,
- Decentralised Voting and Governance and
- Developer training.
    
    To accomplish this, one of the conference's purposes will be to beam its lights on the emerging generation of web3 enthusiasts and developers who are leveraging the technology and taking it to the next level. These include Web 2 and 3 developers, project founders, industry moguls, experts in different career fields, and of course anyone whose mind is open to engaging and exploring this new technology.
    

During the event, Livepeer will be having a market opportunity of

1. The number of event participants is estimated at around
- 1000 online participants,
- 2000 onsite participants
1. Media reach

Web3bridge has a large community and social media presence around

- 5000+ Twitter followers
- 4500+ telegram followers
1. Web3 bridge has partnered with a local advertising agency that has over ten mega digital billboards at strategic locations in Lagos.
- Ads are shown on digital billboard
- Minimum of 500k viewers daily
- Ads are played about 500 times daily

Livepeer will be provided an exhibition booth and a platform where she can discuss the Livepeeer product, its mission and its vision.

Web3bridge also provides opportunities for projects to discuss their products and solutions among tech and web3 enthusiasts, developers, and students during their quarterly organized cohorts ( a boot camp for developers) ensuring a firm root in the Nigerian local territory long after the conference is over.

**Deliverables**

- Discuss Livepeer Manifesto and product suite
- Distribute Livepeer merch
-  Provide Qr code for people to sign up

**Funding Information**.

_We request 5000USDC for the **gold** package sponsorship and 2350USD for 3 (three) Ambassadors participating in the Web3 Lagos conference for 3 (three) days. We are open to being reimbursed for expenses like costs of travel, hotel, etc after the conference._ 

These funds are estimated to be used for;
Gold package- $5000
Logistics(Banner, sound, merch, refreshments) - $1000
Accomodation (3 days)- $800
Transportation- $550
Total- $7350

**Comment by nelsorya** [comment]
Hey @olouwaseun, thanks for reaching out. This sounds like an interesting event. After discussing with the team, I'm afraid this is outside our conference sponsorship budget at the moment, so we won't be able to sponsor this event.
