### ISSUE TITLE
My Global

### ISSUE THREAD

**Issue by Vadik-boom** [livepeer/Grant-Program#87]
Email": myglobalmetaverse@gmail.com
Our mission is to reimagine shopping and inspire people to personal consumption responsibility by giving access to the unique crypto technology of prudent resource usage.
The Product
The vision is to unite a decentralized crypto world with the economy of existing world. The current infrastructure of the existing world will be used as a base layer of the fully decentralized application. Augmented reality stands out as a marketing tool for product tokenization where the main focus is the benefits to the environment. Pokemon-Go like gameplay stands as a base tool of player interaction with Augmented Reality around him.
Team:"https://www.linkedin.com/in/anatolii-shehrin-806296223/
https://www.linkedin.com/in/igor-kolos-a412a377/
https://www.linkedin.com/in/vladyslav-kruzhkov-89a7b5230/
https://www.linkedin.com/in/margaret-kolosiuk-1a8b1416a/

Anatolii Shehrin CEO
5+ years Crypto Evangelist, FinTech Project Execution, GameFI.
Vladyslav Kruzhkov
5+ years Blockchain & Crypto Entrepreneur, Experienced BDM. 10+ years Experienced Merchant Fleet Deep Sea Navigator, Second Officer.
Igor Kolosiuk
International executive, Innovator. 10+ years deep Crypto tech R&D, CBDC development. Deployed national wide mobile-wallet projects, GlobalMoney. Achieved total turnover of $1 billion (Central Bank of Ukraine reports).
Marharyta Kolosiuk
5+ years Experienced Global Marketing Executive, Global Brands Support."
[Preview :](https://drive.google.com/file/d/13S1g-x6LllqKunwnNRoadVI4_zsGn0qm/view)

**Comment by nelsorya** [comment]
Hey @Vadik-boom, thanks for putting this together. After looking your proposal, I'm afraid we do not feel Livepeer Grants can fund this as we see this more as an application than a public good that can make it easier for developers to build on Livepeer.
