### ISSUE TITLE
Kasti - Bringing entertainers and fans closer through unique live experiences

### ISSUE THREAD

**Issue by nandod1707** [livepeer/Grant-Program#88]
**Give a 3 sentence description about this proposal.**
Kasti is a live streaming platform that allows artists and entertainers to give their fans access to their streams in exchange for a fee by selling “tickets” to it. This makes Kasti similar to how live pay-per-view events work. 

The main difference, however, is that all tickets on Kasti are NFTs which, once purchased, can give the user who holds them access to additional perks, or even be resold to pass access on to other users.

**Describe the problem you are solving.** 
We know that existing platforms such as Twitch and YouTube take a large cut of their content creators' earnings, which makes starting a project and making an earning on them an uphill battle, so a more fair alternative needs to be found. However, simply creating a decentralized alternative leaves new apps at a disadvantage in terms of resources and features, and for users not used to working with dapps, dealing with wallets and tokens becomes an entry barrier.

**Describe the solution you are proposing.** 
With Kasti we want to give artists and entertainers a way to fund and support their work by connecting with fans in a way that they feel is a valuable and unique experience. We are building a live streaming platform that mixes centralized and decentralized features to offer users a familiar experience, while giving them the benefits of web3. 

Ultimately, we want Kasti to be positioned as the one platform that certifies true fandom.

**Describe the scope of the project including a rough timeline and milestones** 
We have received support from the NEAR foundation in the form of a grant of $15k, out of which $5k have already been disbursed. We are submitting our first milestone for approval this week.

| Task | Date | Status |
|--|--|--|
| MVP Design is complete | ([see Figma here](https://www.figma.com/file/RssZ4nEpB47v0DMliruWmC/Product-Design---KASTI?node-id=2:34)) |Done|
|MVP development|**Now - Oct 15th**|In progress|
|Closed Beta|**Oct 17th - Oct 21st**|Pending|
|Launch event|**Nov 14th**|Pending|
|Multi-tier token support|**Q4 2022**|Pending|
|In-browser broadcasting|**Q1 2023**|Pending|
|Mobile app|**Q2 2023**|Pending|
|Moonpay integration|**Q2 2023**|Pending|

We are currently integrating with [api.video](https://api.video/) and recommending broadcasting through OBS. However, one of our goals is to make our app compatible with EVMs, and progressively decentralize features when beneficial, always keeping UX a priority. With this in mind we think integrating with livepeer is an excellent opportunity.

As for the launch event, we are producing a live concert on November 14th, for which the location and most vendors have already been booked.

**Please estimate hours spent on project based on the above** 

We estimate 12-16 weeks to complete these features with both founders and one contractor actively developing the app, and one Product Owner handling project management and user research.

**Funds requested**: $25,000

**Comment by nelsorya** [comment]
Hey @nandod1707, thanks for putting this together. This sounds like a very interesting use case. After looking your proposal, I'm afraid we have decided we do not feel Livepeer Grants can fund this as we see this more as an application than a public good that can make it easier for developers to build on Livepeer.
