### ISSUE TITLE
Quidli - P2P crypto reward tool | Grant Proposal

### ISSUE THREAD

**Issue by Lukerio** [livepeer/Grant-Program#90]
**Give a 3 sentence description about this proposal.**
This initial proposal to the Livepeer is to build a light integration of the Livepeer blockchain as well as the LPT token to the Quidli API and app environment. 
This will enable us to offer LPT to our user base of 600+ organizations (notable users include ETHDenver, OrangeDAO, Xooglers, SOSV, dlab) as an option to distribute as micro-incentives across browsers, email, Slack and or Discord via Quidli’s hosted sharing wallet application.

**Describe the problem you are solving.** 
- Having an engaged & motivated community is a must for any crypto project
- The power of a community isn’t in its size, it’s in its members’ engagement
- Proactive communities can be your strongest advocates on social media & beyond

**Describe the solution you are proposing.** 
- Build a strong and loyal community by rewarding your top contributors (you already have an amazing community of +9.7k members on your discord, let's boost it!)
- Create a culture of recognition amongst the Livepeer community through Discord 
- Promote & Awareness of the LPT token amongst new holders (quidli users)

**Describe the scope of the project including a rough timeline and milestones** 
1.	Within 2-3 weeks
- Initial light integration of Livepeer blockchain (wallet) & LPT token to Quidli environment
- Implement LPT for users to transact across Quidli web app, Slack and Discord.

2.	Within 1-2 months
Integrate DeFi protocol(s) on Livepeer to offer users yield options on LPT, etc.

3. Within 9 months (potential)
Decentralization of core Quidli features to on-chain infrastructure:
- Open-sourced smart contracts for core features (tipping, streaming, programmatic, etc.)
- Self-custodial wallets to enable full control & visibility
- Core protocol token issuance

******Please estimate hours spent on project based on the above****** 
Request: $2,000 in LPT to implement the first two steps of the outlined roadmap
●	1,000$ to cover dev costs & general hosting/maintenance
●	1,000$ to deploy as incentives to reward our user base at the Quidli level

**Comment by nelsorya** [comment]
Hey @Lukerio, thanks for putting this together. After looking over your proposal, while the Livepeer team would certainly be open to Quidli integrating $LPT into their platform, I'm afraid we don't feel this is something Livepeer Grants can fund.

**Comment by Lukerio** [comment]
Hi Nelsorya,

Thank you for your reply and sorry for the delay! I have discussed this internally with our team.
I am making a counter-proposal, please tell me what you think:
We can integrate the livepeer token freely on quidli and you can use our bot discord for free.
We propose the following pricing model after the integration:
- Quidli is free for orgs up to 99 members. 
- Otherwise, we proposed a $10 / 100 users, monthly fees.

If you are still interested and quidli can bring value to you, don't hesitate to get back to me,

Best,
