### ISSUE TITLE
Project Themistoklis

### ISSUE THREAD

**Issue by alextitonis** [livepeer/Grant-Program#91]
**Give a 3 sentence description about this proposal.**
Themistoklis project aims to make it easy to capture real-world data with drones and offer off-the-shelf models to derive insights from the captured data. It also supports generating 3D models of the real world, which can be used in VR game development.
 
 
**Describe the problem you are solving.** 
Climate change is perhaps the biggest threat facing humanity today. Climate change creates a drier and hotter climate, leading to wildfires that could further accelerate climate change. This forms a perfect positive feedback loop that could shrink our time to address the looming climate crisis. An early fire detection system aimed at detecting fire in the most inaccessible areas or during the night time, when and where the conditions don’t help their early detection, could be an important tool in this battle against climate change. 
 
**Describe the solution you are proposing.** 
Project Themistoklis aims to make it easy for anyone to map the real world using drones. That could form the basis for many climate solutions. The NLP model can generate navigation plans for the drones and send them movement commands.We aim to use drones to capture the real world using cameras and other sensors. The captured data can be used to detect wildfire, survey biodiversity, monitor forest health, and provide valuable information that was once inaccessible. This drone2data tech stack we are developing will be as important in addressing food security when deployed at farms as it will be in addressing climate change.
 
**Describe the scope of the project including a rough timeline and milestones** 
| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Core Graphics Engine    | $15.000             | Done           |
| 2             | Client Interface and functions | $8.000      | 4 weeks      |
| 3             | Drone Connectors     | $10.000            | 4 weeks             |
| 4             | Dryad (Prototype Drone)  | $20.000      | 11 weeks             |
| 5             | Text Reader     | $2.000      | 1 week             |
| 6             | World Building    | $60.000      | 18 weeks             |
| 7             | Client Upgrade    | $10.000      | 4 weeks             |
| 8             | Audio Support   | $20.000      | 10 weeks        |
| 9             | Radio Connection  | $8.000      | 4 weeks            |
| 10           | Automatation Tools   | $6.000      | 2 weeks           |
| 11           | App Info  | $2.500      | 1 week         |
| 12           | Real World Map 2D    | $8.000      | 2 weeks            |
## Total Budget Requested
 
154.500 $
 
**Please estimate hours spent on project based on the above** 
##Total estimated weeks/hours:
61 weeks , which is equal to 2928 hours.

**Comment by nelsorya** [comment]
Hey @alextitonis, thanks for putting this together. Would this project use Livepeer? And how would you see it helping Livepeer developer community? Also to set expectations, I'm afraid the ask for this grant is far beyond the scope of Livepeer Grants.

**Comment by alextitonis** [comment]
Hey, yeah we are planning to use it, we want to make option for users to record videos through their drones (when detecting a fire) and share it with other users, to be able to show the current state of the fire when detected.

**Comment by nelsorya** [comment]
Hey @alextitonis, given Livepeer Grants focus is on driving developer adoption to the Livepeer Network, we wouldn't be able to fund this entire grant to build out all of Themistoklis and the scale of the grant is beyond the scope of Livepeer Grants. With that said, we would be happy to discuss a smaller grant to discuss how you could integrate Livepeer once the network is built

**Comment by alextitonis** [comment]
hey, i'll adjust the milestones and send them here, thank you

**Comment by alextitonis** [comment]
| Milestone No. | Milestone Summary & Staffing | Funding | Estimated Timeframe |
| ------------- | --------------------- | ------- | ------------------- |
| 1             | Client Upgrade - Upgrade the Android/iOS client using Xamarin, integrate the Tello drone connector driectly    | $5.000             | 3-4 Weeks |
| 2             | Wild-fire and video data - Receive the video stream to the server, detect fires, if so create a video for 5-10 seconds after fire detection and store it with current time & long/lat | $8.000      | 4 weeks      |
| 3             | Livepeer Integration - Upload the detected wild-fires videos to Livepeer and share it | $6.000 | 4 weeks             |

## Total Budget Requested
 
19.000 $

**Comment by alextitonis** [comment]
The drone network will be uploading daily or almost daily incidents to Livepeer from what happened and other users will be watching these, leading to increase of the daily usage of the Livepeer network
