### ISSUE TITLE
VOYA is looking for funding to support our independent media production

### ISSUE THREAD

**Issue by thisisvoya** [livepeer/Grant-Program#93]
**Give a 3 sentence description for your proposal.**
VOYA is a web3 media brand focused on explanatory content and visual storytelling to onboard the next generation of web3 users. In our own show we sit down with the most energetic minds of Web3 (LENS, Delphi Digital, Animoca, and many more). We would like to give Livepeer the opportunity to be one of our sponsor partners for a 3-month period starting in December. As the infrastructure for the Web3 creator economy, the Livepeer brand is close to our heart and we would proudly carry out the Livepeer brand as a partner of the show.

**Describe the problem you are solving.** 
We believe Web3 will redefine how we interact, transact, and connect in the future. Yet the barrier to entry for those that are curious is still too high. With our content we seek to onboard the next generation of Web3 users.

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
While responsibly onboarding of next generation of web3 users benefits the ecosystem as a whole, we would be excited to carry out the Livepeer brand in the following ways:
- Shown as supporter of the show and add slot in each episode (pre-scripted) for a period of 3 months. 
- Option for Livepeer to come on as a guest on our show.

In addition, Livepeer functions as the infrastructure for all our content on Lenstube. VOYA is regarded as one of the prime brands within the Lenstube ecosystem.

**Describe why you are the right team with the capability to build this.**
We have already started and have all the necessary skills in-house to keep going. One image says more than a thousand words. You can view our content here: https://lenstube.xyz/thisisvoya.lens (or all channels here https://link3.to/voya)

**Describe the scope of the project including a 3 month timeline and milestones.**
Sponsor partnership Livepeer X VOYA
Milestones:
- One show per week (with minimum of 10 shows over 3-month period considering
holiday season).
- Add slot (c.15-20 seconds) for Livepeer in each episode (pre-scripted).
- One episode with Livepeer as a guest on our show.

**Please estimate hours spent on project based on the above and how much funding you will need.** 
Majority of the funds would go towards editing/animation work (c. 150 hours per week divided over team of three). Yes, this is not a typo, editing and animation work is quite time consuming. The work isn’t done after the shooting, it starts after the shooting. This does not include shooting, research, or any other operational responsibilities. 

Ask: USD 15,000 over a period of 3 months.

**Comment by shann7** [comment]
Hey Voya team this sounds great! Are you available for a call next week?

**Comment by thisisvoya** [comment]
Hey Shann,

Thanks for reaching out. Yes, we are flexible this week. Could you please
share your availability with us ***@***.***) and we will happily set
up a call.
