### ISSUE TITLE
Talent Musica

### ISSUE THREAD

**Issue by holyaustin** [livepeer/Grant-Program#97]
**Give a 3 sentence description for your proposal.**
Talent Musica is an on-chain music Dapp where young music talents can upload their music creation and mint it to the marketplace as Video NFTs. If Muisc Mangers or promoters like the music, such artists can be contacted on their Twitter or other social media handles. The second feature is the streaming of Live music performances, Upcoming artist can stream their hit songs live with the use of Livepeer Studio. Videos are minted and optimized for playback using Livepeer Studio in the talent marketplace.

**Describe the problem you are solving.** 
There are lots of talents in the music industry but how can music directors, talent mangers find them? Talents Musica solves this problem by creating a platform where talents can showcase themselves and possibly get contacted by music directors or talent managers. 

**Describe the solution you are proposing and how it will have a positive impact on the Livepeer developer ecosystem.** 
We are proposing a web3 platform where it will be easy for young and/or upcoming talents to showcase themselves and possibly get hired or sign deals with music labels. Using Livepeer Protocol to stream live performance removes the barrier of centralization.  Talent Musica provides the enabling platform for both artists and managers to hunt down promising talents and take them to the next level. This will be possible due to the power of Livepeeer studio which allows storage of videos as NFTs that will be listed on the Talent Marketplace and the live streaming that is also minted as NFTs.

**Describe why you are the right team with the capability to build this.**
I am an IT professional with more than 10 years of experience as a software programmer and student tutor. With over 3+ experience in Blockchain technology. Skilled at operating in a wide range of platforms. Excellent written and oral communication skills; capable of explaining complex software issues in easy-to-understand terms. I have worked on a couple of hacks and projects and decentralized Library happens to be one am currently working on. My team is well knowledgeable about web3 video streaming.
LinkedIn profile: https://www.linkedin.com/in/holyaustin/
Twitter Handle: https://twitter.com/holyaustin

**Describe the scope of the project including a 3-month timeline and milestones.** 
The scope of this projects is not limited to the Music community alone, but to the entire human populace at large. When this talents are discovered and nurtured, they produce songs that are soul lifting and helps us relax better. We are focused to make the platform accessible to all both professional talents and new talents.  The creators of stream will control their live streaming experience and mint those streams as NFTs.

Phase 1. Frontend / Smart contact development / testing:  ($10,000)
1. Unlock Stream with Unlock
2. Ability to choose stream platform front-page (either from OBS or from Browser).
3. Live stream to audience from Talent Musica live stream page.
4. Smart contract development and integration
5. Store live streams to IPFS and mint it as NFT.

Phase 2. Streaming Dashboard, Profile and Testing: ($5,000)
The streaming profile is social landing page for the creator.
1. Display the playback URL from Livepeer on profile
2. Display current live stream
3. Product Launch 

Milestones for Phase 1  ($10,000)
Milestone #1 (Estimated Deadline (~1 week) Start of November 2022)
Create a user profile and registration for streaming with Unlock or Unstoppable Domain

Milestone #2 (Estimated Deadline (~1 weeks) November 2022)
Develop the front-end for users to choose which way to stream (from OBS/Browser)

Milestone #3 (Estimated Deadline (~3 weeks ) November / December 2022)
Integrate to Livepeer network for live streaming
Implement smart contract for minting streams as NFT
Collaborate with Livepeer team for smooth implementation

Milestone #4 (Estimated Deadline (~1 week) December 2022)
Create a decentralized storage for livestream storage

Milestone #5 (Estimated Deadline (~1 week) December 2022)
Create a links to view minted NFTs on Rarible and OpenSea

Milestones for Phase 2  ($5,000)
Milestone #1 (Estimated Deadline (~1 week) Jan 2023)
Implement the playback url from Livepeer on profile for creators

Milestone #2 (Estimated Deadline (~1 weeks) Jan 2023)
Develop to display live-stream stream

Milestone #3 (Estimated Deadline (~2 weeks ) Jan 2022)
Finish alpha version development
Onboard small group of testers to provide application feedback

Milestone #4 (Estimated Launch ~Early Febrarury, 2022)
Launch of Dapp

Requested funds - $15,000 USDC or LPT

**Please estimate hours spent on the project based on the above and how much funding you will need.** 
Please estimated hours spent on the project based on the above
Livepeer network for live streaming: 100-200 hours total (Might increase in course of development)

**Comment by shann7** [comment]
Thanks for this proposal! We are reviewing and will get back to you asap

**Comment by hansy** [comment]
Hi @holyaustin. Apologies for the delay; we've been overhauling our grants process. If you're still interested in pursuing this grant, happy to jump on a quick scoping call with you. I'm hansy#9576 on Discord. Would love to know what traction you've made since you submitted your application.

**Comment by holyaustin** [comment]
Hi, Hans,
I will ve available for a call on Monday? What time would be suitable for you? My Timezone is GMT+1. My discord handle is holyaustin#3735

Thanks.

Augustine



    On Friday, January 27, 2023 at 09:55:36 PM GMT+1, Hans Yadav ***@***.***> wrote:  
 
 


Hi @holyaustin. Apologies for the delay; we've been overhauling our grants process. If you're still interested in pursuing this grant, happy to jump on a quick scoping call with you. I'm hansy#9576 on Discord. Would love to know what traction you've made since you submitted your application.
